### ISSUE TITLE
Different results between Memories and Photos app

### ISSUE THREAD

**Issue by SidM01** [nextcloud/recognize#1000]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.1.2

### Which Operating system do you have installed?

Unraid

### Which database are you running Nextcloud on?

MariaDB 11.1.2

### Which Docker container are you using to run Nextcloud? (if applicable)

kilrah/nextcloud-ffmpeg

### How much RAM does your server have?

64

### What processor Architecture does your CPU have?

x86

### Describe the Bug

The recognition of people works so far, but far fewer people are shown to me in Memories than in the photos.
I have already reset the tags for the classified files and also ran a rescan. Unfortunately unsuccessful.

I have almost 200 recognized people in the Photos app and only 130 people in Memories. Overall, there are more pictures of the people in the Photos app.
I also noticed that I have different photos in Memories than in Photos and vice versa.

### Expected Behavior

The same recognized people and images in both apps or preferably in Memories

### To Reproduce

Enable facial recognition in Recognize

**Comment by pulsejet** [comment]
This is expected. Photos shows all files the user has, Memories filters only the files in the timeline root.
