### ISSUE TITLE
Problem clustering faces twins

### ISSUE THREAD

**Issue by petrium** [nextcloud/recognize#1005]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.1.2

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

MariaDB 10.3

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I have 2 daughters - twins. The faces are very similar, but not identical.
Uploaded and processed about 50,000 photos with Recognize. Recognizes other faces satisfactorily.
But among the photos with daughters, Recognize cluster face finds only one face in the photo.
For example, in photos where there are only 2 faces daughters, there are 2 records in table oc_recognize_face_detections - in the first record cluster_id>0, and in the second record cluster_id=-1.
Moreover, cluster_id>0 is almost always for the youngest daughter, and cluster_id=-1 for the eldest.
Google photo did not immediately, but coped with the separation of daughters.

What parameters can I try to configure in FaceClusterAnalyzer.php (Recognize 5.0.3) to try to separate my daughters' faces into 2 clusters:
	public const MIN_DATASET_SIZE = 120;
	public const MIN_DETECTION_SIZE = 0.03;
	public const MIN_CLUSTER_SEPARATION = 0.35;
	public const MAX_CLUSTER_EDGE_LENGTH = 0.5;
	public const DIMENSIONS = 128;
	public const MAX_OVERLAP_NEW_CLUSTER = 0.1;
	public const MIN_OVERLAP_EXISTING_CLUSTER = 0.5;
Or does this not make sense?

### Expected Behavior

Separate my daughters' faces into 2 clusters.

### To Reproduce

Upload 50000 photos.

**Comment by marcelklehr** [comment]
Mmmh. I actually removed the code that constrained recognize to have the same face only once per file, so I'm a bit confused why this would still be happening. Do you have photos of only the elder daughter? Does her face get added to any clusters there?

**Comment by petrium** [comment]
It's difficult to say what exactly is happening. So far I have manually distributed the faces into clusters. My daughters have 3000 photos each. There will be new photos and personal time, then I’ll try to track how exactly my daughters’ faces are recognized.
