### ISSUE TITLE
Memories - Unassigned faces - Move to person - fails with out of memory error

### ISSUE THREAD

**Issue by Daddy-ohh** [nextcloud/recognize#1006]
### Which version of recognize are you using?

5.03

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.1.2

### Which Operating system do you have installed?

Debian GNU/Linux 11 (bullseye)

### Which database are you running Nextcloud on?

MariaDB 10.5.21

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

ARM64 - Raspberry Pi 4

### Describe the Bug

While using "Memories->People->Unassigned faces->Move to person", getting the following error on the screen:

Failed to move 20231021_192411.jpg from face.

Error logging shows this:

Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes) at /var/www/nextcloud/lib/public/AppFramework/Db/Entity.php#130

### Expected Behavior

The unassigned face photo should be moved to the person selected.

### To Reproduce

"Memories->People->Unassigned faces->Move to person"

Select photo to move and person to move to.

### Debug log

Error | PHP | Allowed  memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes)  at /var/www/nextcloud/lib/public/AppFramework/Db/Entity.php#130

**Comment by marcelklehr** [comment]
You may need to up your php memory limit slightly, perhaps try 1024MB

**Comment by Daddy-ohh** [comment]
Thank you - that did it.

**Comment by UserX404** [comment]
With recognize 11.0.1 there is no option to assign faces to a persion which are shown under "unassigned faces" (memories->Discover -> Peoples-> show all -> top right, contact icon with question mark)

**Comment by marcelklehr** [comment]
Hello @UserX404 
This issue was closed *three years* ago. The codebase has significantly changed since then. Additionally, the issue your are bringing up seem like an issue with the memories app, not with recognize. ;)
