### ISSUE TITLE
Person names containing '?' do not display matching images

### ISSUE THREAD

**Issue by linuxrrze** [nextcloud/recognize#1010]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.1.2

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

Postgres 14

### How much RAM does your server have?

64GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

While tagging people I couldn't recall some people's last name, so I named them "`<firstname> ?`".

This looks ok when looking at the face overview at
`     /index.php/apps/photos/faces/`
however, when clicking one of those persons it forwards to
`    /index.php/apps/photos/faces/<firstname>`
(missing the "` ?`" part)

### Expected Behavior

It should redirect to here instead:
`    /index.php/apps/photos/faces/<firstname>%20%3F`

### To Reproduce

Just name one the persons grouped by recognize app "Firstname ?"

**Comment by marcelklehr** [comment]
This should be fixed in the next nextcloud version (v28), I believe.
