### ISSUE TITLE
Cannot move photo to another person - getting error message that "Mark person in preview" must be enabled, but not such setting exists

### ISSUE THREAD

**Issue by dinosmm** [nextcloud/recognize#1012]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.1.2

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

PostgreSQL

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I click on a cluster of faces that is currently unnamed, but it is a duplicate (there is another cluster with many more faces of that same person). I select one or more of the unnamed faces from the duplicate cluster. I click 'move to person'.
And I get this error message:

You must enable "Mark person in preview" to use this feature

However, I cannot find such a setting anywhere to enable.

### Expected Behavior

Either allow me to move the selected photo to another person, or have this "Mark person in preview" setting in the UI.

### To Reproduce

As per description above.

### Debug log

Nothing relevant in debug log.

**Comment by dinosmm** [comment]
Closed as this was a Memories UI issue that has been resolved, not a Recognize issue.

**Comment by deddc23efb** [comment]
I'm seeing the same issue, google isn't helping.  Do you mind sharing what the Memories UI issue happened to be?

**Comment by dinosmm** [comment]
There should be a "Mark person in preview" tickbox in the menu where you choose to move photos to another person. I couldn't see this tickbox on my browser (Firefox), but accidentally realised I could see it on the mobile browser version, so I could tick it, then the photos could be transferred to another person without issue.
