### ISSUE TITLE
Image scan is running but consistent tensorflow errors in the log

### ISSUE THREAD

**Issue by zzyzx-dc** [nextcloud/recognize#1015]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

Nextcloud Hub 6 (27.1.3)

### Which Operating system do you have installed?

Ubuntu Server 20.02

### Which database are you running Nextcloud on?

Mariadb

### Which Docker container are you using to run Nextcloud? (if applicable)

Linuxserver.io SWAG with Nextcloud

### How much RAM does your server have?

32GiB

### What processor Architecture does your CPU have?

x86_64 Intel Core i7-4770 CPU

### Describe the Bug

Initial face scans did not run at all and there were no results in the Memories or Photos app. This went on for a few days until I realized it was not running any background jobs. (It said the last background scan was several days ago.)

I ran:
```
occ recognize:reset-faces
occ recognize:clear-background-jobs
occ recognize:classify
```
(I elected to run _recognize:classify_ rather than _recognize:recrawl_ so I could watch the scan as it proceeded, per the Terminal commands at the bottom of the Recognize settings page)

This scan is working, and faces are being resulted in the Memories app. However, I am seeing the below error repeatedly. 

Is it due to my CPU not supporting tensorflow? It appears to support AVX instructions, per Intel docs.

Is it because I do not have **libtensorflow** installed somewhere that my Nextcloud instance can see it?

Error:
```
Classifier process output: Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:72:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Classifier process output: Trying js-only mode
```

Additionally, in the Recognize settings, I see these warnings:

Tensorflow WASM  mode
_Could not check whether your machine supports native TensorFlow operation. Make sure your OS has GNU lib C, your CPU supports AVX instructions and you are running on x86. If one of these things is not the case, you will need to run in WASM mode._ 

Enable WASM mode is **OFF**

Tensorflow GPU mode - Enable GPU mode is **OFF** (this machine does not have a GPU)

Node.js
 _Node.js v14.18.2 binary was installed successfully. 
 Could not load libtensorflow in Node.js. You can try to manually install libtensorflow or run in WASM mode._ 

### Expected Behavior

Recognize would tie in with tensorflow to scan faces/objects on a Haswell CPU.

### To Reproduce

Run: 
```
docker exec -it nextcloud occ recognize:classify
```

**Comment by zzyzx-dc** [comment]
Responding to myself after doing some more searching:

The Linuxserver.io container which I am using for Nextcloud evidently uses musl, not glibc, so it's using an version of C incompatible with tensorflow?

See: 
https://github.com/nextcloud/recognize/issues/453#issuecomment-1303972673
https://github.com/nextcloud/recognize/issues/838#issuecomment-1576548021

There appears to be a project porting tensorflow to musl:

https://github.com/deliveroo/libtensorflow-musl

but that's beyond my ability to know how to integrate it with recognize.

**Comment by zzyzx-dc** [comment]
Closing issue since upon further reading of the docs it appears that new features/compatibilities are unlikely to be added

**Comment by zzyzx-dc** [comment]
Closing issue since upon further reading of the docs it appears that new features/compatibilities are unlikely to be added

**Comment by marcelklehr** [comment]
Hello @zzyzx-dc 
Sorry for the delay. Your conclusion is correct. When used in a musl environment recognize cannot make use of your CPUs AVX and will only run in WASM mode. It was working before enabling WASM mode because it automatically falls back.
