### ISSUE TITLE
Missing many faces from result (files skipped?)

### ISSUE THREAD

**Issue by geez0x1** [nextcloud/recognize#1016]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.1.3

### Which Operating system do you have installed?

Debian 12

### Which database are you running Nextcloud on?

MariaDB docker latest (currently 11.1.2)

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud:apache

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

Ryzen 1000 series

### Describe the Bug

I am unable to get all faces from my pictures to show up in the results (Photos -> People).

I have tried:
- Fixing #992 (for jpg, jpeg, png, webp, bmp)
- Running `recognise:classify` on CLI multiple times. This runs for a while and ends with multiple messages "no more files/faces to classify"
- Reinstalling the app
- Running `reset-faces` and `reset-clusters` and starting again with `recognise:recrawl` from CLI
- Having it run its automatic background processes instead of CLI commands

### Expected Behavior

- (Nearly) all faces from my pictures show up
- Instead I seemingly get faces from the same pictures consistently, while other files seem to be ignored

### To Reproduce

Unclear.

**Comment by marcelklehr** [comment]
Hello,

could you post a screenshot of your recognize admin panel?

**Comment by geez0x1** [comment]
Hi Marcel, absolutely:
![Screenshot from 2023-11-05 11-14-06](https://github.com/nextcloud/recognize/assets/7889615/6eb16664-27d5-4f67-8222-721bca3251e2)

If there's any other useful information I can provide please let me know. I was also thinking; does it make sense to run a `classify` and grep for certain messages/errors?

**Comment by marcelklehr** [comment]
> does it make sense to run a classify and grep for certain messages/errors?

Yes, that could produce some useful information.

before you do that, you can check the recognize_face_detections table in the database, though. If you have a file that is missing in the people section in photos, you can check whether the file id is in the detections table in the database. This may be because the face wasn't detected, or is too small or the probability of it being a true detections is too slim. It is not entirely unexpected for some faces not to be recognized, sadly, but it should be only around 5-10% usually.

**Comment by geez0x1** [comment]
> Yes, that could produce some useful information.
Okay, any suggestions what to grep for?

I've quickly set up phpmyadmin and checked the detections for a few recent pictures I took.

Picture 1: Person certainly exists more than once in the existing pictures but I have not found that person anywhere under People. This latest picture has a certain `file_id` in `oc_filecache`; I have looked up this same `file_id` in `oc_recognize_face_detections`, and found two entries (this is because it is part of a shared folder between two users). This got me two identical rows:
```
id	user_id	file_id	x	y	height	width	vector	cluster_id	threshold
91376	user1	2329385	0.41598725318909	0.20478518307209	0.1441545933485	0.12280853589376	[cut...]	-1	0
91375	user2	2329385	0.41598725318909	0.20478518307209	0.1441545933485	0.12280853589376	[cut...]	-1	0
```
where I have obviously obfuscated usernames and vectors. I'm not sure whether `cluster_id=-1` means that there are no similar faces, or something else.

**Comment by marcelklehr** [comment]
clusterId=-1 means the face couldn't be assigned to a cluster.

You could try installing the memories app which is slightly ahead of the built-in photos app in terms of features. It should allow assigning previously unassigned faces to existing clusters in the UI. The photos app will get the same feature with nextcloud 28. Let me know if that helps.

**Comment by geez0x1** [comment]
To add to the above; selecting for my user in the  `oc_recognize_face_clusters` yields 70 clusters; whereas 63 are displayed in the People view. Not sure under which conditions these are not displayed. Also strangely, I only have one person with one picture. Are faces that are not clustered not shown possibly?

Simultaneously, the People list contains a bunch of people of which I have only 3-4 pictures in my files (some group pictures in the same folder, but no pictures of these people otherwise). This makes me think that these were easy to cluster, and hence these people show up consistently?

With regards to Memories; I'd rather not clutter my NC install too much, it has quite a few additional dependencies and binaries it pulls in which I'd rather not have. Sorry for not testing this.

Hope this helps in some way, let me know if there's anything else I could test or extract from my database. Thanks for your help, great initiative :)

**Comment by marcelklehr** [comment]
> Are faces that are not clustered not shown possibly?

Yes, as noted above, faces that couldn't be clustered are not shown in the photos app prior to the upcoming Nextcloud 28.

> oc_recognize_face_clusters yields 70 clusters; whereas 63 are displayed in the People view

Strange.

> With regards to Memories; I'd rather not clutter my NC install too much

Fair. :)

You can also try accessing recognize's data by pointing a webdav client (e.g. your OS file explorer) at `<your-nextcloud-domain>/remote.php/dav/<user>/recognize/`. It should have a folder with all unclustered faces and you can check if it lists 70 or 63 people.

**Comment by geez0x1** [comment]
> oc_recognize_face_clusters yields 70 clusters; whereas 63 are displayed in the People view
Tried this; via webDAV I got 63 clusters as well. Could this be because I moved all pictures from certain clusters to another cluster? (either by merge or selectively per picture, leaving no picture). Perhaps the old clusters do not pruned?
For the record, the right webDAV address is `davs://<domain>/remote.php/dav/recognize/<user>/`.

> Yes, as noted above, faces that couldn't be clustered are not shown in the photos app prior to the upcoming Nextcloud 28.
Ah sorry, misunderstood you earlier. That's clear. That might explain the missing people, if the pictures are not clustered.. I checked `unassigned-faces`, which gave me 1573 results (potentially hundreds of people). I suppose I should wait for NC28 and re-evaluate this.

With regards to pictures missing for the person with 775 pictures by the way; I did not see that for other people with fewer instances of their face. Not sure what is going on there, perhaps the view in NC with that many pictures. Being connected through webDAV I checked it there, and got the expected 775 results for that cluster ID. I.e., there is likely no problem with that.

**Comment by marcelklehr** [comment]
> Could this be because I moved all pictures from certain clusters to another cluster? 

Ah, yes. If a cluster has no pictures anymore it's not listed. So, that mystery is solved.

> I checked unassigned-faces, which gave me 1573 results (potentially hundreds of people). 

Cool. You can technically also just move the pictures to the right cluster in this mounted DAV share, it should work already. The NC28 update only brings the UI in the photos app for the same functionality ;)

> With regards to pictures missing for the person with 775 pictures by the way; I did not see that for other people with fewer instances of their face. Not sure what is going on there, perhaps the view in NC with that many pictures. Being connected through webDAV I checked it there, and got the expected 775 results for that cluster ID. I.e., there is likely no problem with that.

So, you're saying, in the NC photos UI you don't see all the pictures for a person that you see in the webDAV mount? That's strange.

**Comment by geez0x1** [comment]
> > Could this be because I moved all pictures from certain clusters to another cluster?
> 
> Ah, yes. If a cluster has no pictures anymore it's not listed. So, that mystery is solved.
:+1: 
> 
> > I checked unassigned-faces, which gave me 1573 results (potentially hundreds of people).
> 
> Cool. You can technically also just move the pictures to the right cluster in this mounted DAV share, it should work already. The NC28 update only brings the UI in the photos app for the same functionality ;)
Considering the number of pictures that's a bit tedious, but as soon as NC28 releases I'll retest and come back to this :)
> 
> > With regards to pictures missing for the person with 775 pictures by the way; I did not see that for other people with fewer instances of their face. Not sure what is going on there, perhaps the view in NC with that many pictures. Being connected through webDAV I checked it there, and got the expected 775 results for that cluster ID. I.e., there is likely no problem with that.
> 
> So, you're saying, in the NC photos UI you don't see all the pictures for a person that you see in the webDAV mount? That's strange.
Yes, but I've only observed this for this person, for which I have most pictures. I was counting through Firefox's DOM Inspect tool, searching for `div.file-container`. I suspect it is either in that tool or a NC UI thing, with some lazy loading or such going on. After some more testing, I have seen instances where there were 774 such `div`s. I suspect there is no real problem there (but hard to check exactly with this number of pictures).

**Comment by geez0x1** [comment]
I have a quick update to this, after upgrading to NC 28. Two observations:
- No new people seem to have been added (e.g. those with 1 instance).
- The web GUI now has an icon for unassigned faces, but this one claims "0 unassigned photos".
- Loading the 'unassigned-faces' folder through DAV directly, I get a "HTTP Error: Internal Server Error."

Suggestions what to test next are welcome, would like to help push this functionality forward :)

**Comment by marcelklehr** [comment]
Are you on recognize v6.x ?

**Comment by geez0x1** [comment]
Yes, 6.0.1 to be precise :)
