### ISSUE TITLE
Recognise not processing clusters due to there not being enough PHP RAM available, despite there being plenty or RAM

### ISSUE THREAD

**Issue by chrissuarez** [nextcloud/recognize#1019]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

Nextcloud 27.1.3

### Which Operating system do you have installed?

TrueNAS-SCALE-23.10.0.1

### Which database are you running Nextcloud on?

postgres:13.1

### How much RAM does your server have?

64GB

### What processor Architecture does your CPU have?

Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz

### Describe the Bug

Recognise has I have imported a few thousand images, and recognise has been able to process faces and cluster a reasonable number of them. Right now there are 15,604 faces left to cluster and the last clustering ran 3 days ago.

Im not sure why the processing has stopped as it has previously processed many faces before. I have tried increasing the amount of PHP ram via the app setting in Trunas scale, and have provisioned 1024 mega bytes, but it seems like recognise is not using the available ram.

### Expected Behavior

I expect the number of faces to be clustered to decrease in value and for faces to be added to the "people" section

### To Reproduce

1. Upload lots of images - Some images were added by transferring folders to a folder that was being monitored by Nextcloud, some were added by transferring using WinSCP directly to the relevant user folder then running the occ command so they were imported into Nextcloud
3. Enable face recognition
4. Wait

### Debug log

Here is the raw log from the legging section:

{"reqId":"4UhIOeEYDLKuliV7kG1M","level":3,"time":"2023-11-06T05:31:06+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 163840 bytes) at /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php#449","userAgent":"--","version":"27.1.3.2","data":{"app":"PHP"},"id":"6549224b4dfa8"}

{"reqId":"fsYgnwgB89WT10DyQrlb","level":3,"time":"2023-11-05T18:48:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 163840 bytes) at /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php#449","userAgent":"--","version":"27.1.3.2","data":{"app":"PHP"},"id":"6549224b4dfbf"}

{"reqId":"a8ljaXjmiLp6gkDM1QcL","level":3,"time":"2023-11-05T18:44:10+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 327680 bytes) at /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php#449","userAgent":"--","version":"27.1.3.2","data":{"app":"PHP"},"id":"6549224b4dfd1"}

I have also added a screenshot where the memory limit was set in Trunas scale and the memory limit as reported in Nextcloud.
![Nextcloud - php memory limit](https://github.com/nextcloud/recognize/assets/10571531/43c559fd-4a6b-4dba-bbaa-2ac86fee5167)
![Trunas - php memory limit](https://github.com/nextcloud/recognize/assets/10571531/ab4744f6-72de-4d56-8cd7-6c46b1737a3c)

**Comment by marcelklehr** [comment]
> 536870912

This is not 1024MB. You're attempt to change the PHP memory limit seems to have been unsuccessful.

**Comment by xsiviso** [comment]
I have the same problem. With the same error in Nextcloud Log. I executed occ recognize:classify but then my the RAM and Swap filled up and I had to do a hard reset. Because 16GB/16GB were used.

**Comment by chrissuarez** [comment]
I have added further info in the "steps to reproduce"  and two screenshots where the memory limit was set in Trunas and how it's reported in Nextcloud

**Comment by marcelklehr** [comment]
Recognize's clustering runs in a background job. Make sure that the php command line memory limit is also large enough.

**Comment by marcelklehr** [comment]
@xsiviso this is *not* the same problem.

**Comment by chrissuarez** [comment]
> Recognize's clustering runs in a background job. Make sure that the php command line memory limit is also large enough.

As this was deployed via Trunas scale I am not able to locate php.ini file to double check the memory limit. This is easier to find when deployed manually.

**Comment by xsiviso** [comment]
> @xsiviso this is _not_ the same problem.

I’m sorry, didn't explained it right.
In the Log it says: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 327680 bytes) at /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php#449

That happened when I’m running it normally, the same way @chrissuarez explained above. 

After that I tried the occ command and the server crashed because of RAM overload.

**Comment by marcelklehr** [comment]
@xsiviso You can set the batch size for the cluster-faces command, so it won't use all your ram.
