### ISSUE TITLE
Recognize runs out of memory when clustering faces

### ISSUE THREAD

**Issue by deddc23efb** [nextcloud/recognize#1033]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.1.3

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

maria db

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Recognize eventually consumes all memory when running occ cluster-faces from the cli with large sets of photo collections.
In my particular case, I have approx 37,000 faces identified.  The clustering stage always fails and PHP is killed due to out of memory.
The issue is the tensorflow library being used.  I don't know how the API to that works, but Recognize won't work on large photo sets with many many faces.  The solution is not to throw memory at the problem.  Recognize should be architected to handle libraries like this and not simply allow memory usage to grow unbounded.  

### Expected Behavior

I expect a recommended tool like Recognize to be stable and well behaved against a wide variety of libraries. If the tool cannot handle a large photo set then it shouldn't be advertised as the facial recognition application for Nextcloud.

### To Reproduce

Run Recognize against a large dataset of faces.  

### Debug log

The only debug that shows what is happening  is the "Killed" message when the php occ process is killed and messages in syslog showing that php has been killed due to oom.
$ grep Killed /var/log/syslog
Nov 17 05:37:10 cloud kernel: [455477.743345] Out of memory: Killed process 83279 (php) total-vm:7361252kB, anon-rss:2855060kB, file-rss:3060kB, shmem-rss:0kB, UID:33 pgtables:14068kB oom_score_adj:0
Nov 17 06:06:27 cloud kernel: [457235.666042] Out of memory: Killed process 83583 (php) total-vm:7514852kB, anon-rss:3070040kB, file-rss:3604kB, shmem-rss:0kB, UID:33 pgtables:14384kB oom_score_adj:0
Nov 17 14:28:35 cloud kernel: [ 2075.671577] Out of memory: Killed process 1534 (php) total-vm:12587752kB, anon-rss:6328024kB, file-rss:2528kB, shmem-rss:0kB, UID:33 pgtables:24308kB oom_score_adj:0
Nov 17 18:17:15 cloud kernel: [15794.989675] Out of memory: Killed process 3104 (php) total-vm:12861156kB, anon-rss:6557152kB, file-rss:3256kB, shmem-rss:0kB, UID:33 pgtables:24800kB oom_score_adj:0

**Comment by marcelklehr** [comment]
Have you tried using the batch size parameter for the cluster-faces command?

**Comment by deddc23efb** [comment]
No - I didn't see that documented.  Currently seeing clustering on 38000 recognized faces failing on 24GB of RAM.  Will try batch parameter and report back.

**Comment by marcelklehr** [comment]
Thank you. Closing this for now :)
