### ISSUE TITLE
Add option to only scan untagged files for recrawl

### ISSUE THREAD

**Issue by phirestalker** [nextcloud/recognize#1041]
### Describe the feature you'd like to request

I would like a way to skip files that were already tagged when using recrawl.

### Describe the solution you'd like

Either an option in the configuration or a command line option, that causes the recrawl option to skip files that were already tagged.

### Describe alternatives you've considered

Changing the background job options to try to unstick a background job that seems to be going nowhere.

**Comment by ruedigerkupper** [comment]
Duplictate of #1137 ?

**Comment by marcelklehr** [comment]
Yes, this is a duplicate of #1137

Thank you for your feedback, nonetheless.
