### ISSUE TITLE
Background jobs stuck for many hours after database goes down

### ISSUE THREAD

**Issue by phirestalker** [nextcloud/recognize#1042]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.1.4

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

MariaDB 10.5

### Which Docker container are you using to run Nextcloud? (if applicable)

27.1.4

### How much RAM does your server have?

32GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I take down all my containers with a script so that I can do a nightly backup. I just use a list of strings and I want the databases to come up first, because of this, the database gets taken down before Nextcloud. It seems like after the database gets taken down that recognize doesn't try again for many hours after initially retrying 3 times within a few minutes.

This is odd since Nextcloud should have some kind of initialization when it starts that would kick recognize back into gear.
<img width="1133" alt="Screenshot 2023-11-29 at 8 20 20 AM" src="https://github.com/nextcloud/recognize/assets/7477095/fb6bbf51-fe3b-4039-8d95-f83c1d6e66c8">
<img width="1601" alt="Screenshot 2023-11-29 at 8 23 05 AM" src="https://github.com/nextcloud/recognize/assets/7477095/7254dd03-bbf3-440f-bd16-ffdb1f951515">

### Expected Behavior

Recognize should check every 5 minutes for database access after a long failure.

### To Reproduce

Start your database container.
Start Nextcloud.
Start a reindex and wait for background jobs to be scheduled.
Take down the database.
Wait for and hour.
Start the database again.

### Debug log

```

Warning | recognize | OC\DB\Exceptions\DbalException: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known |   | 10 hours ago
-- | -- | -- | -- | --
Warning | recognize | OC\DB\Exceptions\DbalException: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for db failed: Name or service not known |   | 10 hours ago
Warning | recognize | OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away |   | 10 hours ago

```

**Comment by marcelklehr** [comment]
Hello @phirestalker 

This is a known issue. The background is that Nextcloud's core background job management defers jobs for 12h if they fail. There is currently nothing we can do in recognize to rectify that.

There is a discussion about this over here already: https://github.com/nextcloud/recognize/discussions/821
