### ISSUE TITLE
Moving faces fails with NC28 RC2

### ISSUE THREAD

**Issue by pstumpe** [nextcloud/recognize#1043]
### Which version of recognize are you using?

6.0.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

Nextcloud 28.0.0 RC2

### Which Operating system do you have installed?

OmniOS r151046

### Which database are you running Nextcloud on?

PostgreSQL 15.3

### How much RAM does your server have?

12GB

### What processor Architecture does your CPU have?

amd64 i386

### Describe the Bug

When selecting images from the "unassigned faces" page in Memories and selecting a target person the system throws an error message like 'Failed to move IMG_XYZ.jpg from face.'

### Expected Behavior

The face would be assigned to the selected person.

### To Reproduce

Just try to assign an unrecognized face to a person.

### Debug log

```
[webdav] Fehler: OCA\Recognize\Dav\Faces\FacesHome::__construct(): Argument #6 ($previewManager) must be of type OCP\IPreview, null given, called in /opt/local/share/httpd/htdocs/nextcloud/apps/recognize/lib/Dav/RecognizeHome.php on line 63
	MOVE /nextcloud/remote.php/dav/recognize/user123/unassigned-faces/63470-IMG_ABC.jpg
```

**Comment by marcelklehr** [comment]
Nice catch! Thank you for testing this! Will fix asap

**Comment by marcelklehr** [comment]
Yay! Thank you for re-testing!

**Comment by trojette** [comment]
Hello, I have the same bug in recognize: 10.0.7. Please could you reopen the issue?

Environment

Recognize: 10.0.7
Nextcloud: 32 (Docker image nextcloud:32-fpm)
Memories: 7.8.2
MariaDB: 10.11
Container OS: Debian GNU/Linux 13 (trixie)

Bug description

Error: "Failed to move [filename] to [person name]"
Reproducible on 100% of attempts to move faces from "Unassigned faces" to a named person
Fails both from Memories and from Nextcloud Photos
No detailed error message shown in the UI

What has been verified

oc_recognize_face_detections contains 4166 entries for user
oc_recognize_face_clusters contains valid named clusters
recognize:cluster-faces runs without error
recognize:reset-face-clusters + recognize:cluster-faces performed — issue persists

**Comment by marcelklehr** [comment]
Hi @trojette 
this is unlikely to be the same problem. Please open a new issue 💙
