### ISSUE TITLE
Shared files have to be clustered for each user

### ISSUE THREAD

**Issue by alec-jensen** [nextcloud/recognize#1050]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.1.4

### Which Operating system do you have installed?

Debian 12

### Which database are you running Nextcloud on?

MariaDB 10.5

### Which Docker container are you using to run Nextcloud? (if applicable)

27.1.4?

### How much RAM does your server have?

16gb, 8gb is allocated to the container

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When pictures are shared between users, they are clustered individually for each user. 

### Expected Behavior

Clustering isn't user-dependent

### To Reproduce

Share images between 2 users and cluster them

**Comment by marcelklehr** [comment]
Hello @alec-jensen 

This is by design

**Comment by marcelklehr** [comment]
The initial auto-response applies.
