### ISSUE TITLE
Documation update: Incompatibility with app "suspicious_login"

### ISSUE THREAD

**Issue by Ra72xx** [nextcloud/recognize#1051]
### Describe the feature you'd like to request

There seem to be incompatibilities with the app "suspicious_login", at least there are several github issues which are solved by disabling this app. For me, face recognition failed because of this without even giving a hint in the UI.
Unfortunately, these bug reports are all closed and there seems to be currently no technical solution but disabling the "suspicious_login" app.

### Describe the solution you'd like

Until there is a technical solution, I propose including a hint to this in the documentation. 

### Describe alternatives you've considered

I don't know if it is possible to take care of this during the installation process by means of some dependency management of Nextcloud?!

**Comment by marcelklehr** [comment]
I've been trying to fix this incompatibility. If you are interested you can test the beta release of this effort: [v6.1.0-beta.1 (release)](https://github.com/nextcloud/recognize/releases/tag/v6.1.0-beta.1)

You can install it by switching your nextcloud release mode to "beta" and then updating the recognize app to v6.1.0-beta.1. After that, you can switch back to the release mode you were on before.

If you encounter problems, feel free to open a new issue.
