### ISSUE TITLE
Differentiate between info/notices and warnings in admin panel

### ISSUE THREAD

**Issue by farhills** [nextcloud/recognize#1059]
### Describe the feature you'd like to request

The job status windows in the admin settings are misleading when presented with the 'warning' exclamation and orange background.

Example: these are not errors, but look like a problem:
![image](https://github.com/nextcloud/recognize/assets/83388006/2a571257-187b-4dcf-87cb-dbc6ed764579)

### Describe the solution you'd like

Show non-error status information with blue background and (i) image.
![image](https://github.com/nextcloud/recognize/assets/83388006/55b33bdd-9c08-4b34-bb65-f098f1e49c39)

### Describe alternatives you've considered

none

**Comment by marcelklehr** [comment]
Great idea! Back when I implemented those [there was only green, yellow and red](https://stable7--nextcloud-vue-components.netlify.app/#/Components/NcNoteCard), so I went with yellow :D 

Nowadays there is a neutral one, though :+1:
