### ISSUE TITLE
Support running recognize in a separate container (with GPU support)

### ISSUE THREAD

**Issue by SilleBille** [nextcloud/recognize#1061]
### Describe the feature you'd like to request

With the `nextcloud/all-in-one` container that spawns multiple containers, I'd like to run `recognize` app in a separate container, that can be used by the `nextcloud-aio-nextcloud` container. This will let the user provide GPU capabilities to the docker without having to provide that functionality to the whole NC eco-system. It also provides more portability and isolation.

### Describe the solution you'd like

A docker container that is exposed through a specific port so that the main `nextcloud-aio-nextcloud` container can interact with it through the same network `nextcloud-aio` bridge network.

### Describe alternatives you've considered

A docker container that shares all the existing volume and mounts used by `nextcloud-aio-nextcloud` container in `ro` format. Completely trying to build a container with CUDA + cuDNN and implement this solution. (I'll keep this issue updated based on the results)

**Comment by marcelklehr** [comment]
Hi @SilleBille 

Nextcloud GmbH is planning to make this happen soon-ish :)

**Comment by oliverhu** [comment]
+1 upvote to this... especially the integration with aio.

**Comment by Passaita** [comment]
That wold be a good way to improve nextcloud ecosystem and allow users to install containers that are required.

**Comment by danieloppenlander** [comment]
Any updates on this? Would be great to have the video tagging and performance benefits. If it's a dev time issue, I could help if I was onboarded.

**Comment by bugsyb** [comment]
If you're in instant need, there's this mod I've done:
https://github.com/bugsyb/recognize_docker/

The way I have it set up is very close if not exactly that what requestor raised - in my case it runs on completely separate system, uses FS via NFS to access files and stores all data in shared Postgres DB.

Use the nvidia-tensor-based if you're fine with some mappings being done there.

**Comment by marcelklehr** [comment]
> Nextcloud GmbH is planning to make this happen soon-ish

Sorry to say, the plans have been scrapped due to lack of engineering time so far. It's still on our list of things that would be nice to have, but it's not scheduled any time soon for now :/

**Comment by rowanmoul** [comment]
> the plans have been scrapped due to lack of engineering time
Are you open to community contributions on this one? If so, it would helpful to have an outline of how you intended to implement it, if one exists.
I'm not sure I will personally have the time, but perhaps someone else does.

**Comment by marcelklehr** [comment]
I'd be open to community contributions on this.

my rough plan would be not to deviate too much from how the models are run right now. Instead of the [Classifier class executing node.js directly](https://github.com/nextcloud/recognize/blob/main/lib/Classifiers/Classifier.php#L165), there would be an option in the settings to call out to the recognize External App instead, or perhaps the external app could be auto-detected. The external app would do the same thing as the Classifier class, execute node.js and return the json line results, so they can be processed in the original recognize app. These are the current docs on how App API / External Apps work: https://cloud-py-api.github.io/app_api/index.html

**Comment by marcelklehr** [comment]
I'm closing this in favor of #73 which is basically the same thing. Upvote there, to make it more likely I get to work on this :)
