### ISSUE TITLE
Incompatible with  nextcloud maps?

### ISSUE THREAD

**Issue by alfwro13** [nextcloud/recognize#1064]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.1.5

### Which Operating system do you have installed?

Debian 12

### Which database are you running Nextcloud on?

MySQL 15.1

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I have downloaded enabled the Recognizer app, downloaded the models and then occ recognize:recrawl 

### Expected Behavior

Face recognition.

### To Reproduce

download and enable the app, download models and occ recognize:recrawl 

### Debug log

`{"reqId":"7xi2lzulaE24YjNUJVnt","level":3,"time":"2023-12-27T10:31:39+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 70\n    [rootId] => 17635450\n)\n)","userAgent":"--","version":"27.1.5.1","exception":{"Exception":"ParseError","Message":"syntax error, unexpected token \")\"","Code":0,"Trace":[{"file":"/home/clients_ssl/domain.net/www/nc/lib/composer/composer/ClassLoader.php","line":427,"function":"Composer\\Autoload\\{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"/home/clients_ssl/domain.net/www/nc/apps/recognize/lib/Classifiers/Classifier.php","line":153,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php","line":84,"function":"classifyFiles","class":"OCA\\Recognize\\Classifiers\\Classifier","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":41,"function":"classify","class":"OCA\\Recognize\\Classifiers\\Images\\ClusteringFaceClassifier","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/apps/recognize/lib/BackgroundJobs/ClassifierJob.php","line":73,"function":"classify","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":33,"function":"runClassifier","class":"OCA\\Recognize\\BackgroundJobs\\ClassifierJob","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/home/clients_ssl/domain.net/www/nc/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/home/clients_ssl/domain.net/www/nc/apps/maps/vendor/symfony/process/Process.php","Line":311,"message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 70\n    [rootId] => 17635450\n)\n)","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 70\n    [rootId] => 17635450\n)\n)"}}
`

**Comment by alfwro13** [comment]
OK, found a temporary solution to this problem - I have disabled nextcloud maps app and everything started working.

**Comment by marcelklehr** [comment]
Ah, damnit. Another incompatibilty :/

**Comment by marcelklehr** [comment]
> /home/clients_ssl/domain.net/www/nc/apps/maps/vendor/symfony/process/Process.php

AH, not an incompatibility. The maps app shouldn't ship symfony/process

**Comment by alfwro13** [comment]
So what is the fix here?

**Comment by marcelklehr** [comment]
The maps app should not ship simfony/process. I cannot do anything about this. You may open an issue on their repo and link to this one here.
