### ISSUE TITLE
An unhandled exception has been thrown during face clustering

### ISSUE THREAD

**Issue by alfwro13** [nextcloud/recognize#1067]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Files App

### Which Nextcloud version do you have installed?

27.1.5

### Which Operating system do you have installed?

Debian 12

### Which database are you running Nextcloud on?

MySQL 15.1

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When attempting to run occ recognize:cluster-faces it throws error

### Expected Behavior

Face Clustering should occur

### To Reproduce

run occ recognize:cluster-faces

### Debug log

Clustering face detections for user [USERNAME]
ClusterDebug: Retrieving face detections for user [USERNAME]
ClusterDebug: Found 17422 fresh detections. Adding 0 old detections and 0 sampled detections from already existing clusters. Calculating clusters on 17422 detections.
An unhandled exception has been thrown:
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features() in /www/nextcloud/apps/recognize/lib/Clustering/DualTreeBall.php:107
Stack trace:
#0 /www/nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php(632): OCA\Recognize\Clustering\DualTreeBall::split()
#1 /www/nextcloud/apps/recognize/lib/Clustering/MstSolver.php(22): OCA\Recognize\Clustering\MrdBallTree->grow()
#2 /www/nextcloud/apps/recognize/lib/Clustering/HDBSCAN.php(89): OCA\Recognize\Clustering\MstSolver->__construct()
#3 /www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php(91): OCA\Recognize\Clustering\HDBSCAN->__construct()
#4 //www/nextcloud/apps/recognize/lib/Command/ClusterFaces.php(67): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters()
#5 /www/nextcloud/3rdparty/symfony/console/Command/Command.php(298): OCA\Recognize\Command\ClusterFaces->execute()
#6 /www/nextcloud/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /www/nextcloud/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /www/nextcloud/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#10 /www/nextcloud/console.php(100): OC\Console\Application->run()
#11 /www/nextcloud/occ(11): require_once('/home/clients_s...')
#12 {main}

**Comment by marcelklehr** [comment]
Hi! Thank you for taking the time to report this error. It likely stems from an incompatibility with the suspicious_login app. For now the only solution is to disable that app if you want to use face recognition in recognize.

**Comment by alfwro13** [comment]
I am not using any login apps. Would you be able to clarify what exactly you are referring to by saying suspicious_login app?
Thanks

**Comment by marcelklehr** [comment]
The suspicious_login app detects suspicious logins. It may be installed by default on your instance. See https://github.com/nextcloud/recognize/issues/676

I've been trying to fix this incompatibility. If you are interested you can test the beta release of this effort: https://github.com/nextcloud/recognize/releases/tag/v6.1.0-beta.1

You can install it by switching your nextcloud release mode to "beta" and then updating the recognize app to v6.1.0-beta.1. After that, you can switch back to the release mode you were on before.
