### ISSUE TITLE
Failed to generate preview of 3434 with dimension 1024 with nextcloud preview manager: No provider successfully handled the preview generation

### ISSUE THREAD

**Issue by BoBBer446** [nextcloud/recognize#1098]
### Which version of recognize are you using?

6.0.1

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

28.0.2

### Which Operating system do you have installed?

Ubuntu Server 22.04

### Which database are you running Nextcloud on?

postgres:latest

### Which Docker container are you using to run Nextcloud? (if applicable)

25.0.1

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

![image](https://github.com/nextcloud/recognize/assets/10163536/94053b51-a589-40a8-8d7c-b83e796e6f06)

Roh-Protokoll Eintrag
```
{
  "reqId": "WQ09RCNS23F5kjqVIpfB",
  "level": 2,
  "time": "2024-02-07T12:10:12+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "recognize",
  "method": "",
  "url": "--",
  "message": "Failed to generate preview of 3434 with dimension 1024 with nextcloud preview manager: No provider successfully handled the preview generation",
  "userAgent": "--",
  "version": "28.0.2.5",
  "data": {
    "app": "recognize"
  },
  "id": "65c37d5229988"
}

```

### Expected Behavior

i think i error is an Expected Behavior

### To Reproduce

Just use the app, i change nothing

**Comment by nordscan** [comment]
in my case it was a 200MB png file that contained a collage of photos underneath, deleting it helped :))

**Comment by BoBBer446** [comment]
Thousend of files ?

**Comment by marcelklehr** [comment]
This is a problem with your nextcloud preview provider setup, I cannot do anything about this, sadly.

**Comment by emitclever** [comment]
I just add this. Same here. All the photos are  stored in the files section not in the Photo sections.

Failed to generate preview of 7766 with dimension 1024 with gdlib: Could not load image for preview with gdlib 

Operating System: Linux 6.1.0-31-amd64 x86_64
CPU: QEMU Virtual CPU version 2.5+ (4 threads)
Memory: 9.56 GB
Everything else run smoothly

![Image](https://github.com/user-attachments/assets/e7ecd0ed-7eb5-464a-b0ee-c27aa704baf9)

**Comment by JanMehl** [comment]
> in my case it was a 200MB png file that contained a collage of photos underneath, deleting it helped :))

How did you identify the file? I have the same issue with multiple files but the filename or folder is not included in the error protocoll.

**Comment by robertoschwald** [comment]
> How did you identify the file? I have the same issue with multiple files but the filename or folder is not included in the error protocoll.

Look into the db. In oc_filecache, there is a fileid column. Find the one with your id. e.g.

`SELECT * FROM `oc_filecache` WHERE `fileid` = '<your_id_in_the_errror_message';`

**Comment by JanMehl** [comment]
> > in my case it was a 200MB png file that contained a collage of photos underneath, deleting it helped :))
> 
> How did you identify the file? I have the same issue with multiple files but the filename or folder is not included in the error protocoll.

I used something I found somewhere else. I just opened the file in the browser throu this URL:

<yourNextcloudURLorIP>/f/<fileID>

This opens the "Files"-App and shows the folder and filename. Since I did not need these files, I simply deleted them.
The fileID was shown in the error message and was a 7 digit number.
