### ISSUE TITLE
Check for Tensorflow requirements failing wrongly?

### ISSUE THREAD

**Issue by solracsf** [nextcloud/recognize#1100]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.1.6

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

MariaDB 10.11

### How much RAM does your server have?

16GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Tensorflow admin settings doesn't recognize system support. But:

1. CPU supports AVX an is x86
2. GlibC is installed
3. Not using containers

![image](https://github.com/nextcloud/recognize/assets/12234510/0c04a971-43ca-40a3-a898-0e90ed23b0dd)

So i've runned the test on CLI:

`# ./apps/recognize/bin/node /apps/recognize/src/test_libtensorflow.js`

It outputs:

>I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with one          API Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

This is [not an error](https://stackoverflow.com/questions/65298241/what-does-this-tensorflow-message-mean-any-side-effect-was-the-installation-su), but could the app wrongly detect it as so?

https://github.com/nextcloud/recognize/blob/4a18d64fe1117db26077cdfc389c5198fe42fff1/lib/Controller/AdminController.php#L231-L243

Maybe `\Throwable` will catch it?

https://stackoverflow.com/questions/35911252/disable-tensorflow-debugging-information/42121886#42121886

### Expected Behavior

Detect Tensorflow settings.

_Also (hint), having an occ recognize:system-checks command would be a great addition to performa and debug all checks manually._

### To Reproduce

See steps above.

**Comment by solracsf** [comment]
When i execute the functions manually, all conditions are met:

```
avx => true,
platform => 'x86_64',
musl => false
```
So this should be met:

https://github.com/nextcloud/recognize/blob/4a18d64fe1117db26077cdfc389c5198fe42fff1/src/components/ViewAdmin.vue#L240-L242

```
AVX:
object(JSONResponse)#2 (1) {
  ["data":"JSONResponse":private]=>
  array(1) {
    ["avx"]=>
    bool(true)
  }
}

Platform:
object(JSONResponse)#2 (1) {
  ["data":"JSONResponse":private]=>
  array(1) {
    ["platform"]=>
    string(6) "x86_64"
  }
}

Musl:
object(JSONResponse)#2 (1) {
  ["data":"JSONResponse":private]=>
  array(1) {
    ["musl"]=>
    bool(false)
  }
}
```

**Comment by mr-bryn** [comment]
I have a very similar issue running under NC snap - could be related? #1120
