### ISSUE TITLE
Cannot upgrade to 6.1.1

### ISSUE THREAD

**Issue by tellustheguru** [nextcloud/recognize#1105]
### Which version of recognize are you using?

6.1.0

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

WASM mode

### Downstream App

Files App

### Which Nextcloud version do you have installed?

28.0.3

### Which Operating system do you have installed?

Debian 11

### Which database are you running Nextcloud on?

mysql  8.0.36

### How much RAM does your server have?

19.39 GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Cannot upgrade, get error message:

Exception App with id recognize has invalid signature

### Expected Behavior

To be upgraded.

### To Reproduce

Klick on the upgrade-button.

**Comment by marcelklehr** [comment]
Thanks for reporting! Should be fixed now
