### ISSUE TITLE
An error occurred during the request. Unable to proceed. Could not update app. 6.1.1

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/recognize#1106]
### Which version of recognize are you using?

6.1.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Files App

### Which Nextcloud version do you have installed?

28.0.3

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

MariaDB

### How much RAM does your server have?

24GB

### What processor Architecture does your CPU have?

x64

### Describe the Bug

Unable to update to 6.1.1 error 

### Expected Behavior

Should upgrade

### To Reproduce

Upgrade from 6.1.0 to 6.1.1

### Debug log

{"reqId":"MGTGc9ERgNhenf7DVzuL","level":3,"time":"2024-02-29T12:07:07-06:00","remoteAddr":"1.2.3.2","user":"admin","app":"no app in context","method":"GET","url":"/settings/apps/update/recognize","message":"App with id recognize has invalid signature","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36","version":"28.0.3.2","exception":{"Exception":"Exception","Message":"App with id recognize has invalid signature","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Installer.php","line":195,"function":"downloadApp","class":"OC\\Installer","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":538,"function":"updateAppstoreApp","class":"OC\\Installer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"updateApp","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Installer.php","Line":380,"message":"App with id recognize has invalid signature","exception":[],"CustomMessage":"App with id recognize has invalid signature"},"id":"65e0c7cbcce43"}

**Comment by marcelklehr** [comment]
Thanks for reporting! Should be fixed now

**Comment by AndyXheli** [comment]
Thank you for getting it fixed so fast.

**Comment by AndyXheli** [comment]
Fixed! Thank you!
