### ISSUE TITLE
Error loading models

### ISSUE THREAD

**Issue by DustyBadger** [nextcloud/recognize#1107]
### Which version of recognize are you using?

6.1.1

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

28.0.3

### Which Operating system do you have installed?

Debian 12

### Which database are you running Nextcloud on?

10.11.6

### How much RAM does your server have?

8

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

After upgrading to version 6.1.1 and updating Next cloud to 28.0.3, I receive a message in the admin panel about the need to download models (they were downloaded earlier and everything worked fine). When trying to run in /var/www/next cloud "sudo -u www-data php c recognize:download-models" I get the following message "PHP Fatal error: Declaration of Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand::mergeApplicationDefinition($mergeArgs = true) must be compatible with Symfony\Component\Console\Command\Command::mergeApplicationDefinition(bool $mergeArgs = true): void in /var/www/nextcloud/3rdparty/stecman/symfony-console-completion/src/CompletionCommand.php on line 57"

### Expected Behavior

I was waiting, as before, for the models to load

### To Reproduce

I'm not sure, but apart from updating the application and the next cloud itself, no other changes have been made.

**Comment by marcelklehr** [comment]
mmh, this seems like it's not related to recognize. Seems like stecman/symfony-console-completion is not compatible with symfony/console anymore. Can you report this in nextcloud/server ?

**Comment by DustyBadger** [comment]
It's a strange story. No actions were performed with the server and software (there were not even reboots), but today, when I went to the settings, I found the inscription "Machine learning modeoes have been successfully loaded"
