### ISSUE TITLE
Cannot view pictures, stuck with waiting screen

### ISSUE THREAD

**Issue by andypmuc** [nextcloud/recognize#1109]
### Which version of recognize are you using?

6.1.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

28.0.3

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

Maria DB?

### How much RAM does your server have?

12 GB

### What processor Architecture does your CPU have?

x86_64 

### Describe the Bug

I cannot view the fotos in people part of photos app. It works fine in all other view, like album, usual photos view, but not with faces in the people part. It stucks with the black waiting screen, while trying to load the picture in large view.

I made some changes in Config.php, I do not know, whether this matters.

  'preview_max_x' => 1024,
  'preview_max_y' => 1024,
  'preview_max_scale_factor' => 1,
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\Movie',
    2 => 'OC\\Preview\\TXT',
  ),

I think it worked before that, but I am not sure.

Important point is from my view, that when I copy the link of the picture and paste it in a new tab, it works. Link looks like:

https://mydomain.de/index.php/apps/photos/api/v1/preview/4306074?etag=659d51801049d&x=512&y=512

Don't know, how to discribe this further, write, if there are more questions.

### Expected Behavior

Work like the other part of the photos app

### To Reproduce

Don't know, maybe configure the preview, like I have.

**Comment by andypmuc** [comment]
Here is the error log:

`Viewer.vue:639 Could not open file /smb_drive/path to file with spaces/file with spaces.jpg TypeError: Cannot destructure property 'filename' of 'e' as it is undefined.
    at G (fileUtils.ts:88:23)
    at new K (file.js:35:12)
    at o.openFileInfo (Viewer.vue:725:1)
    at o.openFile (Viewer.vue:632:1)
openFile @ Viewer.vue:639
await in openFile (async)
file @ Viewer.vue:466
un @ vue.runtime.esm.js:3033
e.run @ vue.runtime.esm.js:3550
er @ vue.runtime.esm.js:4141
(anonymous) @ vue.runtime.esm.js:3159
mn @ vue.runtime.esm.js:3081
Promise.then (async)
pn @ vue.runtime.esm.js:3106
Fn @ vue.runtime.esm.js:3171
tr @ vue.runtime.esm.js:4227
e.update @ vue.runtime.esm.js:3529
e.notify @ vue.runtime.esm.js:732
set @ vue.runtime.esm.js:976
open @ Viewer.js:302
openViewer @ FaceContent.vue:315
cn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
cn @ vue.runtime.esm.js:3033
e.$emit @ vue.runtime.esm.js:3732
emitClick @ File.vue:183
click @ File.vue:1
cn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
La.i._wrapper @ vue.runtime.esm.js:7500
Show 18 more frames
Show less
`

**Comment by lildadou** [comment]
I have the same problem but my logs are different.
```
Could not open file /Albums/2018/Nxxx/IMG_20181125_221459.jpg TypeError: e is undefined
    G fileUtils.ts:88
    K file.js:35
    openFileInfo Viewer.vue:725
    openFile Viewer.vue:632
    file Viewer.vue:466
    VueJS 11
    open Viewer.js:301
    openViewer FaceContent.vue:315
    VueJS 4
    emitClick File.vue:183
    click File.vue:1
    VueJS 16
Viewer.vue:639
    openFile Viewer.vue:639
    file Viewer.vue:466
    VueJS 11
    open Viewer.js:301
    openViewer FaceContent.vue:315
    VueJS 4
    emitClick File.vue:183
    click File.vue:1
    VueJS 16
```

I also notice that I can't open photos in other tabs like "Shared with you" or "Folders" (no problem with the "Photos" tab though). Do you also have these problems or are they confined to "Persons"?

**Comment by zerodogg** [comment]
I've also got this issue, might possibly also be related to #1102.

When clicking on a photo:
```
TypeError: this.files[t] is undefined
    list FaceContent.vue:320
    openViewer FaceContent.vue:318
    VueJS 4
    emitClick File.vue:183
    click File.vue:1
    VueJS 44
    resizeObserver TiledLayout.vue:87
    mounted TiledLayout.vue:84
    VueJS 18
    addFaces faces.js:55
    _ vuex.esm.js:844
    commit vuex.esm.js:466
    commit vuex.esm.js:465
    _withCommit vuex.esm.js:624
    commit vuex.esm.js:464
    commit vuex.esm.js:409
    addFaces faces.js:151
    _ vuex.esm.js:851
    dispatch vuex.esm.js:516
vue.runtime.esm.js:3065:16
```

Randomly when loading more photos/scrolling:
```
TypeError: e is undefined
    VueJS 22
    _onScrollHandle VirtualScrolling.vue:346
    updateScrollPosition VirtualScrolling.vue:344
    mounted VirtualScrolling.vue:330
    VueJS 18
    addFaces faces.js:55
    _ vuex.esm.js:844
    commit vuex.esm.js:466
    commit vuex.esm.js:465
    _withCommit vuex.esm.js:624
    commit vuex.esm.js:464
    commit vuex.esm.js:409
    addFaces faces.js:151
    _ vuex.esm.js:851
    dispatch vuex.esm.js:516
vue.runtime.esm.js:3065:16
```

**Comment by JimboJoe** [comment]
Same issue here (in Firefox or Chrome browser):

```
Could not open file /path_to_the_photo.jpg TypeError: e is undefined
    z fileUtils.ts:88
    X file.js:35
    openFileInfo Viewer.vue:728
    openFile Viewer.vue:635
    file Viewer.vue:468
    VueJS 5
        un
        run
        tr
        bn
        mn
Viewer.vue:642
    openFile Viewer.vue:642
    file Viewer.vue:468
    VueJS 5
```

**Comment by marcelklehr** [comment]
Will be fixed in the next photos releases
