### ISSUE TITLE
Support External Storage

### ISSUE THREAD

**Issue by FlattusBlastus** [nextcloud/recognize#1117]
### Describe the feature you'd like to request

Supporting External Storage. Its critical as many users don't store their precious photos in NC databases. Having access to one's photos if the photo app goes does is an absolute requirement!

### Describe the solution you'd like

Support External Storage so that photos can be recognized

### Describe alternatives you've considered

Immich

**Comment by marcelklehr** [comment]
Hello @FlattusBlastus 
What makes you think external storage is not supported? It should work in the latest version.

**Comment by FlattusBlastus** [comment]
I can try it again. If it doesn't, I'll send you some screenshots.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Eis-T** [comment]
Same problem here, only the direct uploads from my phone are scanned. There's no place to select which folders to include/exclude from Recognize. Tried the "rescan all files" button but it seems recognize has its own ideas of what "all files" are.

**Comment by marcelklehr** [comment]
After adding files to your external storage did you run occ files:scan ?
