### ISSUE TITLE
Recognize does not obey ignore files for external storage

### ISSUE THREAD

**Issue by LRomandine** [nextcloud/recognize#1119]
### Which version of recognize are you using?

6.1.1

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

28.0.4

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

postgresql (from Nextcloud AIO)

### Which Docker container are you using to run Nextcloud? (if applicable)

latest AIO

### How much RAM does your server have?

128 GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When using external storage the recognize app ignores [.nomedia and similar ignore files](https://github.com/nextcloud/recognize?tab=readme-ov-file#ignoring-directories), causing it to scan every single file in the external storage.

### Expected Behavior

Recognize observes and obeys the .nomedia and similar files regardless of storage being external or not.

### To Reproduce

1. Add external storage to Nextcloud (I am using SMB/CIFS)
2. Create .nomedia file anywhere on the external storage (I put it in the root)
3. Manually run a classify job
4. Observe the log processing files it should be ignoring

In my case, I had `/admin/files/Storage/.nomedia` but Recognize was scanning `/admin/files/Storage/Books/...`

**Comment by LRomandine** [comment]
Possibly related bugs
#653

**Comment by marcelklehr** [comment]
mmmmh, I believed to have fixed this ages ago. Can you try putting the ignore file one level deeper instead of in the root of the storage?

**Comment by LRomandine** [comment]
I found the issue. The `.nomedia` files MUST be added via Nextcloud, not from another source. I suggest updating readme to include that.

**Comment by marcelklehr** [comment]
Aha. We're getting closer. Did you run a scan after adding the file on the storage source directly (not through nextcloud)? That should make recognize recognize it (heh).

**Comment by LRomandine** [comment]
When I initially opened the bug I
1. Created the `.nomedia` via `touch /Storage/.nomedia`
2. Ran a manual scan via `docker exec --user www-data -it nextcloud-aio-nextcloud php occ recognize:classify` and it started scanning the Books directory mounted in NextCloud at `/admin/files/Storage/Books/`
3. Created another `.nomedia` file via `touch /Storage/Books/.nomedia` 
4. Ran another manual scan and it scanned the Books directory again
5. Opened bug

After your comment I saw [this comment](https://github.com/nextcloud/recognize/issues/653#issuecomment-1673276498) and decided to test if ignore files would also be ignored if not created inside NextCloud.
1. I deleted both the `.nomedia` files 
2. Used the NextCloud GUI to upload a new `.nomedia` file to each of my subdirectories under my external storage except the one I want scanned
3. Ran another manual scan
4. This time it obeyed the ignore files and only scanned the one subdirectory I wanted it to.
