### ISSUE TITLE
Adjust "Platform" check for native TensorFlow support on Nextcloud Snap

### ISSUE THREAD

**Issue by mr-bryn** [nextcloud/recognize#1120]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode, WASM mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

Nextcloud 27.1.7

### Which Operating system do you have installed?

Debian 11

### Which database are you running Nextcloud on?

MySQL 8

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Request to "index.php/apps/recognize/admin/platform" incorrectly returns a null value, despite running on a supported x86_64 platform.

The platform() checking function on line 157 of recognize/lib/Controller/AdminController.php receives a non-0 return code when attempting to execute "lscpu --json".

The command instead returns "sh: 1: lscpu: Permission denied".

Executing the platform() function outside of the snap environment, on the same system, successfully returns the correct platform value "x86_64"

### Expected Behavior

The platform() function correctly returns the platform when operating within the snap envrionment

### To Reproduce

Install the Nextcloud snap package (build 40887) from the latest/stable channel.

Install recognize.

Turn on dev tools and go to the recognize admin page.

Observe the request to /index.php/apps/recognize/admin/platform contains the response "platform: null".

By altering line 165 of AdminController.php to `return new JSONResponse(['platform' => $output]);` the true command return value can be observed.

**Comment by mr-bryn** [comment]
A possible solution is to use php's in-built function [php_uname()](https://www.php.net/manual/en/function.php-uname.php)

`return new JSONResponse(['platform' +. php_uname('m')]);` returns the correct value under the snap package for me

**Comment by marcelklehr** [comment]
> A possible solution is to use php's in-built function [php_uname()](https://www.php.net/manual/en/function.php-uname.php)

Cool! Would you be amenable to make a PR that adds this as a fallback?
