### ISSUE TITLE
JVM background processes cause server crashes 

### ISSUE THREAD

**Issue by SaschaMuehl** [nextcloud/recognize#1121]
### Which version of recognize are you using?

6.1.1.

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

Nextcloud Hub 7 (28.0.3)

### Which Operating system do you have installed?

Ubuntu 20.04.6 LTS 

### Which database are you running Nextcloud on?

10.6.15-MariaDB

### How much RAM does your server have?

47GIB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Server crashes due to JS background processes (Node.js v18.19.1 ): 
![HTOP](https://github.com/nextcloud/recognize/assets/62723171/dc5a496f-bb31-4d60-a60f-82a7414c263d)

The node.js process overkill my RAM and virtual memory. 

### Expected Behavior

As I understand right recognize open a background process for a stack of pictures (in my case 20 per process). Shouldn't close the process #1 after finishing to open a background process #2...? (self closing background processes)

### To Reproduce

starting the recognize process in Nextcloud

### Debug log

{"reqId":"W4EisjY225bdEMTc5WrN","level":2,"time":"2024-04-07T14:12:04+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"**Movinet does not support WASM mode**","userAgent":"--","version":"28.0.3.2","exception":{"Exception":"OCA\\Recognize\\Exception\\Exception","Message":"Movinet does not support WASM mode","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/recognize/lib/Command/Classify.php","line":134,"function":"classify","class":"OCA\\Recognize\\Classifiers\\Video\\MovinetClassifier","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":298,"function":"execute","class":"OCA\\Recognize\\Command\\Classify","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":1040,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":301,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":171,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/Console/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud/occ","line":11,"args":["/var/www/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/recognize/lib/Classifiers/Video/MovinetClassifier.php","Line":37,"message":"Movinet does not support WASM mode","exception":[],"CustomMessage":"Movinet does not support WASM mode"},"id":"66128de2d40fc"}

**Comment by marcelklehr** [comment]
Recognize doesn't use Java or the JVM. Node.js uses JavaScript which is distinct from Java and the JVM. It seems likely that something else is crashing your server.
