### ISSUE TITLE
Stuck at "Checking libtensorflow" in WASM mode

### ISSUE THREAD

**Issue by JartanFTW** [nextcloud/recognize#1123]
### Which version of recognize are you using?

6.1.1

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

28.0.3

### Which Operating system do you have installed?

Ubuntu 20.04.6 LTS

### Which database are you running Nextcloud on?

PostgreSQL 15.6

### Which Docker container are you using to run Nextcloud? (if applicable)

Nextcloud AIO 28.0.3

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

1. "Checking libtensorflow" never completes. 
2. I get the message "Could not check whether your machine supports native TensorFlow operation. Make sure your OS has GNU lib C, your CPU supports AVX instructions and you are running on x86. If one of these things is not the case, you will need to run in WASM mode." I have manually verified that my server meets each of these conditions.
3. Human action recognition is greyed out and cannot be enabled, I presume because of the libtensorflow check hanging.

The other checks appear to be functional. "Node.js v14.18.2 binary was installed successfully." and the Nice binary check doesn't say anything.

### Expected Behavior

1. "Checking libtensorflow" should finish.
2. The system should recognize my server's ability to support native TensorFlow operation.
3. The Human Action Recognition feature should be toggleable.

### To Reproduce

N/A, but here's some extra info:
I'm using NextCloud AIO. I installed recognize after the initial AIO setup. Face, Object, Audio, and Landmark recognition are all working properly.

### Debug log

I cannot find "debug" anywhere in config.php to enable. Please let me know what I need to do to provide any necessary logs for this.

**Comment by marcelklehr** [comment]
Hi @JartanFTW 

> 1. "Checking libtensorflow" should finish.

This is odd indeed.

> 2. The system should recognize my server's ability to support native TensorFlow operation.

This just doesn't work sometimes, but shouldn't prevent you from doing anything. You can disable WASM mode manually anyway.

> 3. The Human Action Recognition feature should be toggleable.

If you disable WASM mode this should be toggleable again. The checks are just informative in nature, they do not enforce anythig.

**Comment by JartanFTW** [comment]
@marcelklehr 
> This just doesn't work sometimes, but shouldn't prevent you from doing anything. You can disable WASM mode manually anyway.  

Ok, fair. I can disable WASM mode manually, and everything already working continues to work with WASM disabled.

> If you disable WASM mode this should be toggleable again. The checks are just informative in nature, they do not enforce anythig.

Unfortunately, this is not what I am experiencing. Upon disabling WASM mode, the Human Action Recognition feature does not become toggleable.

Please let me know how to proceed.

**Comment by ShapeShifter499** [comment]
I tried disabling "WASM Mode" as my CPU supports AVX but I'm not sure if that means I can run the "Human Action Recognition feature", it stays grayed out regardless of if GPU mode is enabled or not. Does that feature require a GPU with CUDA cores?

**Comment by marcelklehr** [comment]
Ah, it seems that x86_64 is required for Human action recognition as well. You said you have x86_64 though. Can you check in the network tab of the web inspector for the recognize settings page for a network request to "platform" and paste the response of that network request here?

**Comment by marcelklehr** [comment]
This will probably be fixed by the next release of which will be v7
