### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by warlordattack** [nextcloud/recognize#1129]
### Which version of recognize are you using?

6.1.1

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

28.0.5

### Which Operating system do you have installed?

Ubuntu 22.04.4 LTS

### Which database are you running Nextcloud on?

default installed by AIO

### Which Docker container are you using to run Nextcloud? (if applicable)

latest

### How much RAM does your server have?

16gb

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When i run this command : 
sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ recognize:classify

I have this error : 
```
)
Running array (
  0 => '/bin/nice',
  1 => '-0',
  2 => '/var/www/html/custom_apps/recognize/bin/node',
  3 => '/var/www/html/custom_apps/recognize/src/classifier_imagenet.js',
  4 => '-',
)
sh: taskset: not found
Classifier process output: Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/lib/napi-v8/../../deps/lib/libtensorflow.so.2)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/dist/index.js:72:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Classifier process output: Trying js-only mode
```

### Expected Behavior

no error expected

### To Reproduce

Run new Ubuntu VM in proxmox with NVIDIA GPU passthrough, 
install nvidia drivers in Ubuntu,
install Nextcloud AIO,
install Recognize,
enable GPU mode,
run : 
sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ recognize:classify
see the error described above.

My Proxmox VM config : 
```
root@pxa:~# cat /etc/pve/local/qemu-server/109.conf
agent: 1,fstrim_cloned_disks=1
balloon: 0
boot: order=scsi0;net0
cores: 4
cpu: x86-64-v2-AES
hostpci0: 0000:01:00,pcie=1,x-vga=1
machine: q35
memory: 16384
meta: creation-qemu=8.1.5,ctime=1712774289
name: px-ubuntu
net0: virtio=BC:24:11:F2:8F:EC,bridge=vmbr0,firewall=1,mtu=9000
numa: 0
ostype: l26
parent: plex-gpu-ok
scsi0: rog:109/vm-109-disk-0.qcow2,cache=writeback,discard=on,iothread=1,size=64G,ssd=1
scsi1: rog:109/vm-109-disk-1.qcow2,cache=writeback,discard=on,iothread=1,size=500G,ssd=1
scsihw: virtio-scsi-single
smbios1: uuid=f38847f9-3306-4faa-8b15-303ff02dee1a
sockets: 1
tags: docker;nextcloud;plex;ubuntu
vga: std
vmgenid: aaaaabaf-2b2e-483b-838d-48f6a4cc7766

```

### Debug log

How can i get a log ?

### Note
I managed to run gpu acceleration with go-vod and Nextcloud, so probably Nvidia driver and Tensorflow is installed in the system and works. But i don't know how to make GPU acceleration work with recognize :)
![WhatsApp Image 2024-05-03 à 15 41 24_ffe9e762](https://github.com/nextcloud/recognize/assets/3226486/31cf9bda-97eb-4c6f-a13e-3aad7fb3e944)

**Comment by marcelklehr** [comment]
Both native mode and GPU mode are not support on AIO
