### ISSUE TITLE
recrawl / classify - only not tagged files

### ISSUE THREAD

**Issue by bugsyb** [nextcloud/recognize#1137]
### Describe the feature you'd like to request

Currently both commands `recognize:classify` and `recognize:recrawl` will go through all files, regardless if these are tagged already or not.

Files tagged already have specific tag added already which could be used to verify if were tagged with current version of recognize/models.

Additionally, there are situations, where i.e. recognize process get stopped and it has been noticed that recognize doesn't pick up these items and recognize them. These files are left and never touched again.

Therefore a mechanism and manual command to catch-up on not tagged items would be great.

It could be a bandage solution where something didn't work and thousands and thousands of files are tagged already, where only some hundreds are missed/skipped. 
Currently it requires to go and re-tag all - which is quite a bit of waste of resources.

Additionally, if these commands could have user and folder option, as for i.e. files scan, that would be amazing as would give control over what needs to be re-scanned/re-classified if needed.

Having this would help in situations like:
https://github.com/nextcloud/recognize/issues/1030

It is also related to:
https://github.com/nextcloud/recognize/issues/905

**Comment by marcelklehr** [comment]
Hi @bugsyb 
This is a great idea! Would you be willing to implement this, with my guidance if needed?

**Comment by marcelklehr** [comment]
I think the classify command could have a --only-missing flag for example which would do what you suggest.

**Comment by bugsyb** [comment]
No promises, as I've avoided PHP as much as possible so far.
With that said, if you could give me some points where to look at, how tag is constructed, etc. to get me kick started, I might just do it too (no timelime promised). It shouldn't be too much of an effort either though. Trickiest will be to learn how NC works, data structure and logic.

**Comment by bugsyb** [comment]
It would be probably down to modifying around this, by first checking if tag is not on it already.

https://github.com/nextcloud/recognize/blob/f963a15c6f7ca15ea489de8c78c044bb8b5973ef/lib/Command/Classify.php#L80

If you could point me to any code which does anything similar - reading tag, that would be good help already.

**Comment by bugsyb** [comment]
Another feeling is that this could be useful or is the name misleading? (findMissedClassifications)
https://github.com/nextcloud/recognize/blob/f963a15c6f7ca15ea489de8c78c044bb8b5973ef/lib/Service/TagManager.php#L102

**Comment by marcelklehr** [comment]
> It would be good if I could be pointed to any RTFM around how to setup test instance for NC app code and debug it or run calls manually. What sort of IDE do you guys use?

We have some tutorials: https://nextcloud.com/developer/
I personally use PHPStorm by JetBrains, but VSCode is also used

Here's the entire Servers-side API of Nextcloud: https://nextcloud-server.netlify.app/

this is the API for checking and assigning tags: https://nextcloud-server.netlify.app/classes/ocp-systemtag-isystemtagobjectmapper ObjectType is always 'files' in this case.

I would imagine you can check if a file is tagged already at this line here: https://github.com/nextcloud/recognize/blob/f963a15c6f7ca15ea489de8c78c044bb8b5973ef/lib/Command/Classify.php#L102

**Comment by marcelklehr** [comment]
This is the tag name that's used to mark files as processed: https://github.com/nextcloud/recognize/blob/f963a15c6f7ca15ea489de8c78c044bb8b5973ef/lib/Service/TagManager.php#L15

**Comment by luxzg** [comment]
> (as a crude hack i for now manually check for **_max(fileid) from recognize_face_detections_**, and monkeypatched some skipcode if $queuefile->getfileid() < max(fileid) to make it skip pictures which are probably scanned already, not sure this is a good place at all, but it seem to work for me)

Hey there, could you share more details about this workaround? I've been using recognize for like 2 years, and from time to time it would get stuck for this reason or another. But as the library grew running it manually every time and waiting to go through all the photos of which 90% had already been scanned and rescanned dozen times started to be ... less than optimal.

I'd love to have a way, even if through a manual workaround in PHP code (as yours sounds), to be able to only scan if:

- date added is newer than dd/mm/yyyy
- id of file is larger than xxxx
- folder of file is inside xxxxx (could put all new files temporarily in folder "to scan" then only run classification on that)

Weird thing is that classification of objects usually doesn't have issues, many photos get correctly tagged by object tags, but never show up in people folders.

I got here after looking at multiple places today, but all workarounds and patches are only WiP and aren't suitable even for a hackish workarounds.

**Comment by marcelklehr** [comment]
Hi @luxzg 
There is a feature in the pipeline that will allow you to continue where classify left off.

**Comment by marcelklehr** [comment]
Oh, I'll add it to the release notes, then. Sorry :)

**Comment by firswaycomputers** [comment]
Hi, thanks ever so much for working on this feature. I think it will save a lot of time!
I cannot seem to find it however. Changelog states available from 8.1.0 and according to my NC I'm on 8.1.1.
sudo -u www-data php occ recognize:classify --retry returns "the --retry option doesn't exist."
Am I missing something? NC version is 30.0.2 running on Ubuntu 24.04.1 (non Docker).. Thanks!

**Comment by marcelklehr** [comment]
Ah, I think I know what's wrong. The mast branch is already prepared for Nextcloud 31, while the latest release is built from the stable8 branch, which doesn't have the change, yet.

**Comment by marcelklehr** [comment]
I'll do a backport and release, so you can use it already on nc 30 :)
