### ISSUE TITLE
Allowed memory size of xxx bytes exhausted (tried to allocate yyy bytes) at MrdBallTree.php on line 449

### ISSUE THREAD

**Issue by JBtje** [nextcloud/recognize#1139]
### Which version of recognize are you using?

6.1.1

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

28.0.2

### Which Operating system do you have installed?

Truenas Scale App

### Which database are you running Nextcloud on?

PostgreSQL 16.0

### Which Docker container are you using to run Nextcloud? (if applicable)

Chart 28.3.3

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

This "bug" has been reported a couple of times, and the solution is to run the below command in the terminal:

`occ recognize:cluster-faces --batch-size=3000`
(you may vary the batch-size depending on the RAM available)

----
Every 10 minutes, the cluster-face command (i assume) runs via cronjob. Every 10 minutes I get a log with the error
```
Allowed memory size of 536870912 bytes exhausted (tried to allocate 163840 bytes) at /var/www/html/apps/recognize/lib/Clustering/MrdBallTree.php#449
```

However, when I run `occ recognize:cluster-faces` (**without a batch-size specified**) in the terminal, it runs fine and the Recognize admin page shows a lower number (below 100) for the amount of `Face clustering: XX faces left to cluster`.

- So, why does it give an error when it runs via cron, but not an error when it runs via command line?

Additional information:
`/settings/admin/serverinfo` page specifies for **PHP**:
- Version 8.2.15
- Memory limit: 4GB

When I run `php -i | grep memory` it also shows `memory_limit => 4G => 4G`, so both php-cli as php-fpm(?) run using 4GB.

And some questions:
- It's not possible to configure the batch-size value in the web interface, right?
- It's also not possible to run a command for `Face recognition: 0 Queued files, Last classification: 1 hour ago, Scheduled background jobs: 0,` in the console, right? Except for `occ recognize:classify` which runs everything.... not just the ones lest in queue.

### Expected Behavior

I expect no memory error, since the command runs fine in the console.

### To Reproduce

Just upload 200k photo's to a new system

### Debug log

Below copied from the console, which ran without problems. But there are error logs up until the moment I ran this in console.
```
$ occ recognize:cluster-faces
Clustering face detections for user xxxxxx
ClusterDebug: Retrieving face detections for user 4413005b-d388-3913-b86a-65cf186c5f1a
ClusterDebug: Found 4366 fresh detections. Adding 1091 old detections and 2369 sampled detections from already existing clusters. Calculating clusters on 7826 detections.
ClusterDebug: Clustering complete. Total num of clustered detections: 3065
```

**Comment by marcelklehr** [comment]
Hi @JBtje 

The difference between the cron job and the command is that the cron job is always run with a batch size of 10000. If you run the command without a batch size the clusterer will set the memory limit to -1. If you run the command with a batch size of 100000 you will get the same error as the cron job. Solution is to increase your memory limit.

**Comment by marcelklehr** [comment]
> It's not possible to configure the batch-size value in the web interface, right?

Yes, that's not possible right now. I was not expecting people to run into memory issues with a limit of 10000, tbh

> It's also not possible to run a command for Face recognition: 0 Queued files, Last classification: 1 hour ago, Scheduled background jobs: 0, in the console, right? Except for occ recognize:classify which runs everything.... not just the ones lest in queue.

Mh, you can run background jobs manually if you know their ID. starting in  Nextcloud 30 you can even do this in a loop.
