### ISSUE TITLE
can't set image area used for temporary files

### ISSUE THREAD

**Issue by krodelabestiole** [nextcloud/recognize#1146]
### Which version of recognize are you using?

7.0.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

29.0.1

### Which Operating system do you have installed?

docker

### Which database are you running Nextcloud on?

MariaDB 10.6

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud:29-fpm

### How much RAM does your server have?

16G

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I've followed the documentation for docker compose :
```
volumes:
      - type: tmpfs
        target: /tmp:exec
```
recognize won't process any image and I can't set image area on the admin panel.
the slider shows NaNxNaN (4x3) instead of a value.

I have `/tmp:exec` as a directory in my container and I think it's looks weird. I wonder if the doc about this docker-compose file is correct :

```
root@c2e1ab4c5374:/var/www/html# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         204G  189G  4.0G  98% /
tmpfs            64M     0   64M   0% /dev
shm              64M     0   64M   0% /dev/shm
tmpfs           7.8G     0  7.8G   0% /tmp:exec
/dev/sda1        15T   13T  1.1T  93% /fatcap
/dev/md0        204G  189G  4.0G  98% /etc/hosts
tmpfs           7.8G     0  7.8G   0% /proc/asound
tmpfs           7.8G     0  7.8G   0% /proc/acpi
tmpfs           7.8G     0  7.8G   0% /sys/firmware
tmpfs           7.8G     0  7.8G   0% /sys/devices/virtual/powercap
```

I will have a look about the `:exec` bit in docker doc.

you can find a description of an exact same bug there : https://www.reddit.com/r/NextCloud/comments/yqd74e/nextcloud_face_recognition_cant_set_image_area/

### Expected Behavior

recognize should processing images

### To Reproduce

Try this docker-compose setup I guess ?

`Docker version 26.1.4, build 5650f9b`

**Comment by krodelabestiole** [comment]
I was wondering if it would be related with some execution permission, but still no luck with :
```
services:
  nextcloud:
    ...
    volumes:
     ...
      - tmp:/tmp
 
volumes:
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpfs
      tmpfs-mode: 1777
```

**Comment by krodelabestiole** [comment]
I wonder if face recognition would not try to get memory_limit settings in a weird way...
according to this documentation e.g. :
https://github.com/matiasdelellis/facerecognition/wiki/PHP-memory_limit

using docker I don't have any "loaded configuration file" :
```
root@f57cfce659d1:/var/www/html# php --ini                                   
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/docker-fpm.ini,
```
Still, memory_limit is defined by an env var in /usr/local/etc/php/nextcloud.ini  :
```
root@f57cfce659d1:/usr/local/etc/php/conf.d# cat nextcloud.ini 
memory_limit=${PHP_MEMORY_LIMIT}
upload_max_filesize=${PHP_UPLOAD_LIMIT}
post_max_size=${PHP_UPLOAD_LIMIT}
```
```
root@f57cfce659d1:/usr/local/etc/php/conf.d# php -i | grep memory_limit
memory_limit => 1G => 1G
```
Sorry right now I don't have the time to check the code in this app I don't know though...

**Comment by marcelklehr** [comment]
Perhaps @thgoebel knows more as they are the one who changed this.

**Comment by marcelklehr** [comment]
> I wonder if face recognition would not try to get memory_limit settings in a weird way...

This seems not related to recognize? Face_recognition and recognize are two separate apps.
