### ISSUE TITLE
SQL Error while running landmark recognition

### ISSUE THREAD

**Issue by nielstron** [nextcloud/recognize#1153]
### Which version of recognize are you using?

7.0.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

29.0.3

### Which Operating system do you have installed?

Ubuntu 24.04 LTS

### Which database are you running Nextcloud on?

mysql  Ver 8.0.37-0ubuntu0.24.04.1 for Linux on x86_64 ((Ubuntu))

### How much RAM does your server have?

8 GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Landmark recognition stopped, reporting that there is an error in the logs (see log)

### Expected Behavior

No error during landmark recognition

### To Reproduce

Not sure why this is happening.

### Debug log

 DriverException An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE0' for column 'name' at row 1
Error while running background job OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob (id: 1210, arguments: {"storageId":3,"rootId":264})

**Comment by marcelklehr** [comment]
It seems that a landmark was recognized that uses exotic Unicode characters in its name. do you have utf8_mb4 enabled in your db?

**Comment by nielstron** [comment]
The error has since not reappeared, I did not do any changes to the database.
