### ISSUE TITLE
Uploaded file not added to queues (Exception postInsert)

### ISSUE THREAD

**Issue by andreaskoelsch** [nextcloud/recognize#1154]
### Which version of recognize are you using?

7.0.2

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Files App

### Which Nextcloud version do you have installed?

29.0.3

### Which Operating system do you have installed?

Debian 12

### Which database are you running Nextcloud on?

MariaDB 10.11.6

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I just upgraded to recognize 7.0.2. After re-downloading the ML models, I uploaded a photo using the Nextcloud Android app. The photo is not added to the classification queues. Tried upload via browser, too. Same result

### Expected Behavior

Uploaded photo is classified.

### To Reproduce

Uploaded a photo. Check queues

### Debug log

Exception postInsert
Error in recognize file listener

**Comment by marcelklehr** [comment]
Ah, well. I should not ignore CI tests :see_no_evil:
