### ISSUE TITLE
NC 30 Support

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/recognize#1158]
### Describe the feature you'd like to request

Support the upcoming release NC 30

### Describe the solution you'd like

^

### Describe alternatives you've considered

^

**Comment by AndyXheli** [comment]
[v7.1.0](https://github.com/nextcloud/recognize/releases/tag/v7.1.0) [Latest](https://github.com/nextcloud/recognize/releases/latest)
New
Support for Nextcloud 30

**Comment by marcelklehr** [comment]
Yep, but v7.1.0 doesn't work yet, sadly, there were some breaking changes in nextcloud. So, I'm on releasing v8 at the moment :)

**Comment by AndyXheli** [comment]
Hi @marcelklehr Thank you for the update. I'll reopen this back once we know the new version works i'll close it :) you okay with that ?

**Comment by marcelklehr** [comment]
v8 is out now
