### ISSUE TITLE
NextCloud error: Data too long for column 'version' at row 1

### ISSUE THREAD

**Issue by kgroot** [nextcloud/recognize#1159]
### Which version of recognize are you using?

7.1.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

other, please specify below

### Which Nextcloud version do you have installed?

Nextcloud Hub 8 (29.0.4)

### Which Operating system do you have installed?

Synology DS920+, DSM 7.2.1-69057 Update 5

### Which database are you running Nextcloud on?

MariaDB 10 (10.11.6-1369)

### How much RAM does your server have?

20GiB (9% used)

### What processor Architecture does your CPU have?

x86_64 (INTEL Celeron J4125)

### Describe the Bug

During installation or activation of Recognize, I get the error:

An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'version' at row 1
could not enable apps 

It stops there. Re-installation fails because the tables are already present in the database:
An error occurred during the request. Unable to proceed.
The column "threshold" on table "nc_recognize_face_detections" already exists.

### Expected Behavior

Recognize gets installed

### To Reproduce

Remove all tables named *recognize*.
Install recognize plugin on Nextcloud on Synology DS920

**Comment by marcelklehr** [comment]
Hi @kgroot 
You will need to remove the relevant entries in the oc_migrations table as well before attempting a reinstall.

**Comment by kgroot** [comment]
Marcel,

Wow, that helped. I did install, but ended up with a few errors and an Recognize that was not enabled. I tried to enable and waited for the next error, but there was no error. It looks as if it is installed and enabled. 

The errors were access problems, probably not from recognize, but from something else.

Up to using recognize.

Thanks.

Klaas groot
