### ISSUE TITLE
Photos not loading due to missing preview

### ISSUE THREAD

**Issue by andypmuc** [nextcloud/recognize#1202]
### Which version of recognize are you using?

7.1.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

29.0.7

### Which Operating system do you have installed?

Ubuntu 24 LTS

### Which database are you running Nextcloud on?

Maria DB latest

### Which Docker container are you using to run Nextcloud? (if applicable)

n/a

### How much RAM does your server have?

12

### What processor Architecture does your CPU have?

x86_64 

### Describe the Bug

I had a lot a problems loading the images in the people app when clicking on faces. I checked the error messages and recognized that some mime types like TIFF HEIF HEIC are not in the preview. After adding them, the pages load very quickly.

Suggest you handle that error, that missing mime types do not lead to the page showing the people with recognized faces is not loading.

Regards

### Expected Behavior

Correct error handling

### To Reproduce

Add pictures like TIFF HEIC or HEIF and activate Preview and do not add them to preview providers

### Debug log

None available, says in Chrome dev tools, that mime type is missing.

**Comment by marcelklehr** [comment]
> some mime types like TIFF HEIF HEIC are not in the preview

What does this mean? I think this issue should go to the photos app

**Comment by andypmuc** [comment]
After adding the mime type in the config.php, everything is fine. See
https://help.nextcloud.com/t/photoshop-psd-psb-tiff-large-files-previews/156862

**Comment by marcelklehr** [comment]
If the issue is with the config.php file then it does not belong in this repository. Sorry.
