### ISSUE TITLE
Option to run model externally

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/recognize#1220]
### Describe the feature you'd like to request

I'm planning to move my Nextcloud instance from my does-it-all old x86-64 homeserver to a dedicated ARMHF platform.

The ML runs are very expensive with regards to memory and when running the main NC server on an ARM device, it might be beneficial to be able to run the model in a container on a different device, which could e.g. be another ARMHF device with a Rockchip SoC with integrated NPU. In the home user space that would mean, the main NC could run e.g. on an RPi5 and if the user wants ML features, they could buy e.g. said Rockchip SBC and can run recognize without the main NC SBC exploding.

I believe, that would also have advantages in SMB or Enterprise infrastructures, where the model could then run on a different machine with accelerator or GPU-compute cards or in some cloud ML service. Servers with lots of drives often don't have additional space for GPUs.

Additionally, there would be all the advantages of not "having all eggs in one basket", e.g. no NC downtime when the ML box needs maintenance, etc.

I'm thinking, as the model anyways needs to be downloaded, how about a config option "Use external ML" which would then require network address configuration and tells recognize to use that external ML instance instead of looking for a downloaded model. So the user can choose to do it the current way or use external ML.

### Describe the solution you'd like

The solution would be to separate the ML from the recognize app logically and optionally run the ML in a separate container.

### Describe alternatives you've considered

The alternative is to leave things as they are with the advantage of simplicity but losing the advantages mentioned above.

**Comment by marcelklehr** [comment]
Hello @sgofferj 
This is already being considered as part of #73 
It will take some time until I can get to this as part of my job at Nextcloud GmbH, however.
