### ISSUE TITLE
Save us from the gory, ugly command line

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/recognize#184]
Any chance on helping to simplify our lives just "that much more" by adding simple buttons we can click to manually do these things? (buttons where the pink are). :-p

![image](https://user-images.githubusercontent.com/39491297/160920597-1d64d0c3-1eb0-4916-8afa-b4a6fe8580b0.png)

Save us from the gory, ugly command line. Copying and pasting commands, etc. lol

---

Originally submitted by @YouveGotMeowxy

**Comment by bonswouar** [comment]
@marcelklehr What would be the recommended way to do this? Doing an exec call in ajax, or still use the CRON (using some user's flags)?

**Comment by marcelklehr** [comment]
@bonswouar I think the classify commands are not suitable to run from the browser, because they take forever, potentially. Reset tags exists already as a button. As such, only clean up tags is missing, which would indeed be nice to have a button for.

**Comment by bonswouar** [comment]
That's what I thought, although cleaning tags is only a small part of the original request :smile:

**Comment by YouveGotMeowxy** [comment]
I'm not a coder so I'm just thinking out load, but for the classify commands, a button that just immediately places it into cron so that cron picks it up on the next run, would be fine with me. :)

**Comment by marcelklehr** [comment]
But even cron is not supposed to run for hours, which is why the current cron job classifies a batch of images every 5-10 minutes by default. If you want it faster, you'll need the command line, there's no way around it.
