### ISSUE TITLE
High load of CPU even if all images are already classified

### ISSUE THREAD

**Issue by galandilias** [nextcloud/recognize#235]
**Describe the bug**
On my installation I have roughly 30k images - all of them are reported by Recognize as already classified - despite that every 30 min Recognize is fully loading 1 core of CPU for 10 mins - same goes with memory. Would it be possible to do a pre-check if there is anything new to classify before launching heavy processing?

**To Reproduce**
1. Just sit and observe ;)

**Expected behavior**
Recognize should first check if anything new to classify has been uploaded and only then start heavy processing.

**Recognize (please complete the following information):**
 - Enabled modes: object detection, landmark detection, location tagging

**Server (please complete the following information):**
 - Nextcloud: 24.0.2
 - OS: gentoo linux
 - RAM: 32GB
 - Processor Architecture x86-64

**Additional context**

![obraz](https://user-images.githubusercontent.com/41627139/175868204-ce9295cc-c82c-4449-bb2f-1ccacf8b4112.png)

**Comment by marcelklehr** [comment]
Thanks for reporting this. This is due to the current file discovery architecture. I will redesign this part soon to avoid scanning the whole file system regularly.
