### ISSUE TITLE
Optimise background crawling and classification performance

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/recognize#252]
Currently the app is running a background job that processes each user and starts a batch classification of the next files that match the criteria of not being processed yet. The batch is currently generated by iterating over all user files in one go and filtering out non-matching mime types or already recognised files depending if they have a specific system tag set.

With #238 new tables are introduced to track the processing status per classifier, which leads to the problem that there are tables growing with the number of files being added to the system.

In order to resolve this and also make the background job being more distributed among users and their file backlog, @marcelklehr and I discussed the following approach today.

The background processing is split into 3 different jobs:

- UserSchedulerJob
  - Iterates over all users and makes sure that a CrawlJob is added to the job list for each user
  - Can be a time-insensitive job on larger instances (only nightly) and new user jobs could be added through UserCreatedEvent directly
- CrawlJob
  - Assumption: Each file only gets processed once
    - For updated files a crawl job could be added during the update event 
  - Prepares the next batch of files that need to get classified and adds a corresponding ClassifyJob to the job list
  - It stores the last used file id per user, so we can batch-iterate the files of a user with the OCP file search
    - The query could look like this and would be using indexes: `select fileid from oc_filecache where storage = 1 and fileid > 0 limit 100;` This could be done issuing the OCP files search API
      - It could even be narrowed down with a mime type filter as we have the fs_storage_mimetype  
    - On the next job run the stored last fileid would be used as the offset
    - Possible problem: oc_jobs arguments have a limit of varchar(4000), so we may need to temporary store the list of file ids to process separately, depending on the batch size
    - A file may occur in multiple ClassifyJobs (e.g. ClassifyImageJob, ClassifyVideoJob), depending on the setting and mime type
  - This only handles files in the users home storage, other storage types like groupfolders or external storage can be implemented in a similar way. This separation also helps to avoid that files with a shared ownership are only processed once.
    - Face recognition on files with shared ownership should probably not match with existing users face clusters anyways
- ClassifyJob
  - Will run the classifier on the batch of files

@marcelklehr Maybe you can double check that, so I haven't missed anything.

**Comment by juliushaertl** [comment]
@PVince81 @CarlSchwan @icewind1991 Would be great to get some sanity check on this especially in regards to the file iteration parts.

**Comment by CarlSchwan** [comment]
The issue with the CrawlJob is that this won't handle file updates

An idea of how to handle this would be:

- Use a listener to detect when updated
- Let the listener create a ClassifyJob for these updated files

**Comment by marcelklehr** [comment]
We've come up with the following architecture now. Feedback welcome :)

![Untitled Diagram drawio](https://user-images.githubusercontent.com/986878/180219397-4e831068-d408-4b46-a187-9a103d4e6baf.png)

**Comment by marcelklehr** [comment]
An open question is how to handle users that are added to a group folder. :thinking:

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/recognize/pull/261
