### ISSUE TITLE
Fatal Errors if working with md and html files

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/recognize#278]
**Describe the bug**
If uploading .md files for pico cms or htmls, the recognize functionality triggers fatal server errors (see logs below).
This happens from time to time and leads to an Error 500 at NC.

**To Reproduce**
1. Activate Recognize and Pico CMS
2. Create Pico Project and Activate Picture, Music and Video recognition at recognize
4. upload htmls and .mds to the pico-cms projectfolder
5. See error

**Expected behavior**
No Errors

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: ALL

**Server (please complete the following information):**
 - Nextcloud: 24.0.4
 - OS: Ubuntu 64 bit LTS
 - RAM: 32 GB
 - Processor x64 Xenon

**Additional context**
Error Messages
--------------

[webdav] Fatal: TypeError: OC\EventDispatcher\ServiceEventListener::__invoke(): Argument #1 ($event) must be of type OCP\EventDispatcher\Event, OC\EventDispatcher\GenericEventWrapper given, called in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264 at <<closure>>

 0. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 264
    OC\EventDispatcher\ServiceEventListener->__invoke()
 1. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 239
    Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
 2. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 3. /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php line 122
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
 4. /var/www/nextcloud/lib/private/Files/Node/Node.php line 118
    OC\EventDispatcher\SymfonyAdapter->dispatch()
 5. /var/www/nextcloud/lib/private/Files/Node/Folder.php line 390
    OC\Files\Node\Node->sendHooks()
 6. /var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php line 67
    OC\Files\Node\Folder->delete()
 7. /var/www/nextcloud/lib/private/Preview/Watcher.php line 65
    OC\Files\SimpleFS\SimpleFolder->delete()
 8. /var/www/nextcloud/lib/private/Preview/Watcher.php line 54
    OC\Preview\Watcher->deleteNode()
 9. /var/www/nextcloud/lib/private/Preview/WatcherConnector.php line 63
    OC\Preview\Watcher->postWrite()
10. <<closure>>
    OC\Preview\WatcherConnector->OC\Preview\{closure}("*** sensitive parameters replaced ***")
11. /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php line 106
    call_user_func_array()
12. /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php line 40
    OC\Hooks\BasicEmitter->emit()
13. /var/www/nextcloud/lib/private/Files/Node/Root.php line 143
    OC\Hooks\PublicEmitter->emit()
14. <<closure>>
    OC\Files\Node\Root->emit()
15. /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php line 72
    call_user_func_array()
16. /var/www/nextcloud/lib/private/Files/Node/LazyFolder.php line 100
    OC\Files\Node\LazyFolder->__call()
17. /var/www/nextcloud/lib/private/Files/Node/HookConnector.php line 114
    OC\Files\Node\LazyFolder->emit()
18. /var/www/nextcloud/lib/private/legacy/OC_Hook.php line 106
    OC\Files\Node\HookConnector->postWrite()
19. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 472
    OC_Hook::emit()
20. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 399
    OCA\DAV\Connector\Sabre\File->emitPostHooks()
21. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1137
    OCA\DAV\Connector\Sabre\File->put()
22. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 492
    Sabre\DAV\Server->updateFile("*** sensitive parameters replaced ***")
23. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut()
24. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
25. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
26. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
27. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 87
    Sabre\DAV\Server->exec()
28. /var/www/nextcloud/remote.php line 166
    require_once("/var/www/nextcl ... ")

PUT /nextcloud/remote.php/webdav/gvlacademy/content/index.md
from 192.84.221.33 by user at 2022-08-12T09:41:50+00:00

**Comment by Ellpeck** [comment]
For my instance, this error also happens, but in various places and seemingly randomly:
- It has occured in the admin settings panel at least once so far, causing an error 500.
- Occasionally, a Nextcloud client file upload will fail with an unexpected error 500, which causes the Nextcloud log to throw this same error.

I do not have Pico CMS installed, and this issue stops occuring entirely if I uninstall or disable Recognize.

**Comment by marcelklehr** [comment]
Fixed by 074bb66c24d10c38f767dc5d
