### ISSUE TITLE
[Feat]: Face Recognition Tab Improvment

### ISSUE THREAD

**Issue by Emporea** [nextcloud/recognize#281]
First of all thanks for all the work put into this.
I enjoy the 2.2.0 update.
It could be useful to add some things in the new "Face recognition" section.

1. Sort recognized faces by amount of occurrences (say you have a face that occurs 200 times it should be on top, in comparison to a face only occurring 2 times)
1.1 As a small detail one could also display the number of occurrences in the header of each Person, since apparently not every associated picture is shown there
3. Some people get recognized multiple times
2.1 Group same person tag
2.2 It might be even possible to have a drop down menu where you can select the person tag so you choose the right tag (maybe even get name suggestions from contact names)
4. Option to hide already tagged recognized persons in the Face Recognition Tab to have a better overview about untagged people / faces
5. Sometimes crap ( a wall, a clock, ~what ever you can think of~ ) gets recognized as a face, so being able to permanently ignore those "people" sections would be useful

I know its a lot, and if I had the technical know how i would like to help.
But thanks again for this work @marcelklehr + others.

**Comment by marcelklehr** [comment]
Thank you @Emporea for your valuable feedback. All of this is planned for the next iteration, which will add a people section to the photos app to replace recognize's face recognition settings. You can keep tabs on the development over here: https://github.com/nextcloud/photos/pull/1155
