### ISSUE TITLE
Privacy Considerations

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/recognize#293]
By using collaborative tags, recognize can leak information about the data found in media to all other users of the Nextcloud Instance.
It should, at the very least, be made very clear to users in the Recognize Settings, that "giving names" to detected persons will create NC wide tags that are visible to everyone (thus potentially leaking full names - probably the most sensitive information that could be contained in recognize's tags).

I think, it would be great to have non-collaborative tags as an alternative - but that's probably more suited for an upstream feature request.

[Here](https://github.com/nextcloud/server/issues/4699#issuecomment-669603540) are a few examples of users who share the same concern and a few scenarios, where this behavior might be problematic.

**Comment by marcelklehr** [comment]
Thank you for your input @theCalcaholic !

In the upcoming version of recognize that we're currently working on, the names will no longer be created as tags.
