### ISSUE TITLE
Failed to save name ( The ability to name clusters requires admin)

### ISSUE THREAD

**Issue by gmeks** [nextcloud/recognize#296]
**Describe the bug**
When trying to name a cluster i get a error (Failed to save name)

**To Reproduce**
1. Profile
2. Settings
3. Recognize
4. Name a clsuter

**Expected behavior**
I should be able to name the cluster

**Recognize (please complete the following information):**
 - JS-only mode: yes
 - Enabled modes: face recognition]

**Server (please complete the following information):**
 - Nextcloud:24.0.4
 - Recognize: 2.2.1
 - OS: Offical docker
 - RAM: 24GB
 - Processor Architecture x86

**Additional context**
There are multiple TB of pictures if that mathers.

I cannot find anything in the logs?

**Comment by gmeks** [comment]
I did some more checking... Like i should have done before hand ( Sorry).
I can see the browser is sending a HTTP Post, but its getting back a 403, with the messsage "Logged in user must be an admin" .

Most users on my installation is not a admin ( And it does not seem like the admin user can see the clusters, and name them).

Im not sure if the intended feature is that the admin Names clusters on behalf of all users ( This can get very annoying, but a shared detection of faces offcourse has value).

**Comment by marcelklehr** [comment]
> but its getting back a 403, with the messsage "Logged in user must be an admin" .

Ah, I see. That's a bug in the API implementation then. The user settings approach has been scrapped and moved to the photos app, so I'm not sure it's worth fixing this.

**Comment by gmeks** [comment]
Ok, 

I cannot see a editing API inside photo app, so i cannot evaluate that. Its 200gb of pictures, so might take a while for it to be ready.

But in general i would say either fix or remove it?

**Comment by marcelklehr** [comment]
Yep, it's been removed in v3
