### ISSUE TITLE
Limit high cpu usage ( clustering faces )

### ISSUE THREAD

**Issue by Emporea** [nextcloud/recognize#303]
Recognize clusters every recognized faces every 30 minutes, even when no new images had been classified.
This takes about 5 minutes each for me ( around 6000 images ).

To me this represents unnecessary computing power, or am I missing something?

![image](https://user-images.githubusercontent.com/21969523/187023006-25d2967b-7e78-46be-9478-4dd4664eead0.png)

- Is it possible to add only new classified images to already computed clusters?
- Or is it atleast possible to only cluster all recognized faces if a new photo has been analyzed since the last clustering?

**Comment by marcelklehr** [comment]
Yes, that's fixed in the upcoming version already :) We're just dotting the i's and crossing the t's before we get out the new version :)
