### ISSUE TITLE
Run at specified times

### ISSUE THREAD

**Issue by marian-code** [nextcloud/recognize#316]
Since this is a rather resource intesive app it would be advantageous to be able to specify allowed run times. For instance my Raspberry Pi is able to run recognize OK, but when some users log into nextcloud at the same time the resposivity of the cloud drops damatically. It would be nice to be albe to specify that this can run for instace between 2 - 4 am when nobody is usually logged in.

**Comment by ralfi** [comment]
Yes, this is really useful...

**Comment by marcelklehr** [comment]
In #347 we're adding support for the server background job config that lets you specify a 4h window each day to run background jobs such as recognize's.

**Comment by ralfi** [comment]
Thanks a lot!
