### ISSUE TITLE
disable face recognition does not disable face recognition

### ISSUE THREAD

**Issue by StarSmasher44** [nextcloud/recognize#324]
**Describe the bug**
I haven't ticked the 'Enable face recognition (based on contact pictures in the Contacts app)' box assuming this was meant to disable the face recognition piece of this app, unfortunately it doesn't and I have not yet found a way to disable the face recognition part of your app. Is this possible somehow or could this be added? I already use the face recognition app, so having this double system is a bit of a hassle, and could do with not being there. As I originally downloaded this app for the other features.

**Expected behavior**
Disables face recognition and removes that portion from the user options.

Hope this is enough explanation

**Comment by marcelklehr** [comment]
This should be fixed in v3 which is currently in beta.
