### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by apg1980** [nextcloud/recognize#328]
**Describe the bug**

Running sudo -u www-data php occ recognize:classify-images -vvv runs a long time then it breaks with:

 `No unclassified photos found by userxxx
Clustering faces in photos by user xxx
Found 360 face clusters
Failed to classify images
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
`
no furhter log entrys, no mysql errors in the logs.
Nextcloud is running well all the time, no mysql connection drop seen.

**Expected behavior**

**Recognize (please complete the following information):**
 - JS-only mode: [e.g. Yes/No]
 - Enabled modes: [e.g. object detection, face recognition]

**Server (please complete the following information):**
 - Nextcloud: [e.g. 21.0.4] 24.0.5
 - OS: [e.g. iOS] ubuntu 22.04
 - RAM: [e.g. 16GB] 10gb
 - Processor Architecture [e.g. x86, ARM64, etc. ] x86
 - mariadb
 - php8.1
 - nginx

**Additional context**

**Comment by apg1980** [comment]
i have increased the the wait_timeout of mariadb to 4800 the action is working longer as before, but after some hours
`Clustering faces in photos by user patrick
Found 830 face clusters
Failed to classify images
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
`

**Comment by marcelklehr** [comment]
Recognize v2 is no longer maintained. I recommend to deactivate it until you are able to upgrade to v3 (which only supports Nextcloud v25). Thank you for your contributions!
