### ISSUE TITLE
Classification fails: Storage with mount id 1 is not available

### ISSUE THREAD

**Issue by dondochaka** [nextcloud/recognize#338]
Recognize appears to be failing when attempting to access mounted storage.

```
root@ffd3a97725d2:/# occ recognize:classify-images
Collecting photos of user admin
Searching files
...
Found /admin/files/Photos/Toucan.jpg
...
Not a supported format: /admin/files/Templates/Business model canvas.odg
...
Searching
Failed to classify images
Storage with mount id 1 is not available
```

My external storage creates a `/home` path for each user.

![image](https://user-images.githubusercontent.com/101915388/193149240-0240893e-6d2c-4734-8c6a-b13b3120c4fe.png)

Is it possible to mount this storage or configure recognize in such a way that it can be accessed?

**Server:**
 - Nextcloud: 24.0.4
 - OS: Linux 5.15.69-0-virt x86_64 (Alpine VM)
 - RAM: 12GB
 - Processor Architecture: x86

**Comment by marcelklehr** [comment]
This should be fixed in v3 which is currently in beta, you may try updating to it
