### ISSUE TITLE
Recrawl not working for existing images

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#362]
**Describe the bug**
Recrawl doesn't seem to start classifying existing images on external storage (smb share on nas, mounted via proxmox into container, permissions seem ok). Object and Face detection etc seem to work fine on newly added photos uploaded from my phone to the same external storage. No errors in the log. I built recognize from source to see if the problem persists, didn't help. currently on master, commit 7ea0def, tried emptying the recognize tables in the db as well

**To Reproduce**
1. press recrawl button / run occ recognize:recrawl
2. wait
3. Nothing happens

**Expected behavior**
It should classify all the existing 400k+ photos

**Recognize (please complete the following information):**
 - JS-only mode: Nope
 - Enabled modes: Everything enabled

**Server (please complete the following information):**
 - Nextcloud:  25.0.0 RC3
 - OS: Ubuntu 22.04.1
 - RAM: 16
 - Processor Architecture x86, 8 cores in container, has MMX etc

**Comment by marcelklehr** [comment]
> press recrawl button / run occ recognize:recrawl

the recrawl command and button only triggers a recrawl. The actual crawling and classification are done in a background job. Since new files are processed for you that doesn't seem to be the problem, though.

**Comment by illnesse** [comment]
I'll try to add some debug logging to StorageCrawlJob to see what's up when i get around to it

**Comment by illnesse** [comment]
https://github.com/nextcloud/recognize/blob/f5d90acfe6e7834712b5506a40af68e09c7a0b06/lib/BackgroundJobs/StorageCrawlJob.php#L98

getting a rowCount() of 0 here

```	$qb = new CacheQueryBuilder($this->db, $this->systemConfig, $this->logger);
	$files = $qb->selectFileCache()
		->whereStorageId($storageId)
		->andWhere($qb->expr()->like('path', $qb->createNamedParameter($root['path'] . '/%')))
		->andWhere($qb->expr()->eq('storage', $qb->createNamedParameter($storageId)))
		->andWhere($qb->expr()->in('mimetype', $qb->createNamedParameter($mimeTypes, IQueryBuilder::PARAM_INT_ARRAY)))
		->andWhere($qb->expr()->gt('filecache.fileid', $qb->createNamedParameter($lastFileId)))
		->orderBy('filecache.fileid', 'ASC')
		->setMaxResults(100)
		->executeQuery();```

**Comment by marcelklehr** [comment]
Maybe your files don't match the necessary mime types? Can you check that? Were you ever able to complete a successful classification run with those files?

**Comment by illnesse** [comment]
> Were you ever able to complete a successful classification run with those files?
nope

MIME types are the same as new uploads from the phone (which get classified correctly), regular jpeg and png

storageid is ok too

if i go deep into the directory structure that gets omitted by recrawl and then copy one of the files in place, into the same dir, they get picked up and classified too. 

maybe it's related to lastFileId? what is it for?
`->andWhere($qb->expr()->gt('filecache.fileid', $qb->createNamedParameter($lastFileId)))`

**Comment by marcelklehr** [comment]
It's used for batching up the job. It's using a greater than comparison, starting with greater than 0, then using the last found file as the lastFileId value in the next job.

**Comment by marcelklehr** [comment]
Is it the path then maybe? `'path', $qb->createNamedParameter($root['path'] . '/%'` the extra slash causing issues?
