### ISSUE TITLE
Installation Error: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted

### ISSUE THREAD

**Issue by LokeYourLord** [nextcloud/recognize#369]
**Describe the bug**
When I try to enable the addon, it just doesn't let itself be enabled due to the following issue:

**To Reproduce**
1: Click Install/Enable
2: Profit? (of it not working)

**Expected behavior**
I... bro these bug reports sometimes... I expect it to get enabled/installed?

**Server:**
 - Nextcloud: 24.0.6
 - OS: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1018-oracle aarch64)
 - RAM: 24GB (assigned 8192MB for PHP to use, more than enough)
 - Processor Architecture ARM64

**Additional context**
Log files:
https://hastebin.skyra.pw/sajuqeliwu.css
https://hastebin.skyra.pw/cerorawomi.css
https://hastebin.skyra.pw/cokebunazo.bash

**Comment by marcelklehr** [comment]
Should be fixed in the latest version. Can you confirm?

**Comment by LokeYourLord** [comment]
> Should be fixed in the latest version. Can you confirm?

I will check later today 😄

**Comment by LokeYourLord** [comment]
@marcelklehr It has not been fixed. Trying to "Download and Install" returns the same errors. I'll send you some pastebin logs soon.
