### ISSUE TITLE
3.0.1: Endless loading of CPU

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/recognize#373]
After updating this never stops:

![image](https://user-images.githubusercontent.com/24530680/195399784-4d1a558b-2f50-4a18-934d-94d08ff0ed23.png)

Console:
![image](https://user-images.githubusercontent.com/24530680/195399999-d4b2c49d-9b8c-4b2f-b380-639a2bb14d30.png)

**Comment by marcelklehr** [comment]
Ctrl + F5 ?

**Comment by jakobroehrl** [comment]
Does not help, sorry. Tested a different browser, too.
Additionally on every change I get this:
![image](https://user-images.githubusercontent.com/24530680/195539102-9c42e6a3-9d1c-47a1-b7bb-2686a2c64485.png)

**Comment by jakobroehrl** [comment]
same as  #375

**Comment by marcelklehr** [comment]
What do the nextcloud logs say? Any errors?

**Comment by marcelklehr** [comment]
> Additionally on every change I get this: Failed to save settings

This would indicate a server issue. Maybe the app wasn't updated properly or the update failed mid-way through?

**Comment by marcelklehr** [comment]
>  Maybe this is a VM problem on netcup, I can spinup a machine on linode for testing, if that helps.

Mh, maybe. But I doubt it.

> Then I remove the app complete and do a fresh install, right?
> Do I have to delete the oc_recognize* Tables, too?

yes, that would be good:

```
DROP TABLE oc_recognize_face_detections; DROP TABLE oc_recognize_face_clusters; DROP TABLE oc_recognize_queue_imagenet; DROP TABLE oc_recognize_queue_landmarks; DROP TABLE oc_recognize_queue_faces; DROP TABLE oc_recognize_queue_movinet; DROP TABLE oc_recognize_queue_musicnn; DELETE from oc_migrations where app = 'recognize';
```

**Comment by jakobroehrl** [comment]
Solved by a fresh install
