### ISSUE TITLE
Stuck "Checking CPU"

### ISSUE THREAD

**Issue by drosenberg-gh** [nextcloud/recognize#375]
**Describe the bug**
After updating to version 3 the app is stuck "Checking CPU"

![image](https://user-images.githubusercontent.com/69093391/195482096-d8c6ceb0-4462-4658-9fee-fdf1d54bf790.png)

**To Reproduce**
The status is always "Checking CPU" when the recognize settings pane is opened 

**Expected behavior**
My processor has AVX (and AVX2) so check should be succesful 

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: 25
 - OS: Linux/Ubuntu
 - RAM: 4GB
 - Processor Architecture: x86
 - VM running in Virtualbox 

**Additional context**
Nexcloud is installed as a Snap

**Comment by marcelklehr** [comment]
Are there any errors in the nextcloud logs?

**Comment by jakobroehrl** [comment]
I could solve it, by removing and reinstalling the app:
https://github.com/nextcloud/recognize/issues/373
