### ISSUE TITLE
Recognize app does not work : "Could not resolve logger! Class "logger" does not exist" Nexcloud docker

### ISSUE THREAD

**Issue by QuaiGoner** [nextcloud/recognize#385]
**Describe the bug**
After installing the app from WebUI and adding 1 contact with photo to find that person and checking box "Enable face recognition (based on contact pictures in the Contacts app)" ive got an error in the logs and no photos were processed.

**To Reproduce**
1. Install Recognize App
2. App a contact with picture
3. Checkbox "Enable face recognition (based on contact pictures in the Contacts app"
4. See error and no images processed

**Expected behavior**
Recognize app recognizes a photos with that person

**Recognize (please complete the following information):**
 - JS-only mode: Not sure
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: latest docker image 24.0.6
 - OS: Ubuntu 22.04 Docker
 - RAM: 4GB
 - Processor Architecture x86

**Comment by QuaiGoner** [comment]
Manually running occ recognize:classify-images
actually works

**Comment by gmeks** [comment]
Version 3.0.x only works with nextcloud 25 and above. See https://github.com/nextcloud/recognize/issues/371

**Comment by QuaiGoner** [comment]
I am not using ver 3.0.x.
I am using the latest available on 24.0.6

**Comment by marcelklehr** [comment]
Recognize v2 is no longer maintained. I recommend to deactivate it until you are able to upgrade to v3 (which only supports Nextcloud v25). Thank you for your contributions!
