### ISSUE TITLE
Classifier process output: Aborted()

### ISSUE THREAD

**Issue by bdevy** [nextcloud/recognize#396]
**Describe the bug**
Recognize throws consistent errors after running for a week and no longer properly tags files or recognizes faces.

**To Reproduce**
1. Not sure, but it's consistently in a broken state.

**Expected behavior**
I expect Recognize to continue to scan and recognize faces without this error.

**Recognize (please complete the following information):**
 - JS-only mode: Yes - using WASM mode
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: 24.0.6
 - OS: Ubuntu 20.04.3 LTS
 - RAM: [e.g. 32GB]
 - Processor Architecture: x86

**Additional context**
I have tens of thousands of images and Recognize has been plugging away at them just fine. After about a week or so, I noticed new images were not being processed correctly; pictures were no longer being tagged with names, no new faces being detected, etc. I discovered the following errors in the nextcloud.log file. They occur during each run every 30 minutes. However, Activity indicates Recognize is still processing images and adding the default tag of "System tag Tagged by recognize v2.2.0 (invisible)."

{"reqId":"SALi6BuPvwRS6xfU9Tx4","level":2,"time":"2022-10-17T21:02:16-05:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: Aborted()\n/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6596\n                    throw ex;\n                    ^\n\nRuntimeError: Aborted(). Build with -s ASSERTIONS=1 for more info.\n    at abort (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6792:135)\n    at _abort (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6867:33)\n    at <anonymous>:wasm-function[11]:0x1095\n    at ResizeBilinear (<anonymous>:wasm-function[134]:0xc3ee)\n    at Module._ResizeBilinear (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6976:124)\n    at Object.resizeBilinear [as kernelFunc] (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:3956:5)\n    at kernelFunc (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4590:32)\n    at /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4650:27\n    at Engine.scopedRun (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4455:23)\n    at Engine.runKernelFunc (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4646:14)\n","userAgent":"--","version":"24.0.6.1","data":{"app":"recognize"},"id":"634e0b316918f"}

{"reqId":"SALi6BuPvwRS6xfU9Tx4","level":2,"time":"2022-10-17T21:02:16-05:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process errored","userAgent":"--","version":"24.0.6.1","data":{"app":"recognize"},"id":"634e0b3169131"}

{"reqId":"SALi6BuPvwRS6xfU9Tx4","level":2,"time":"2022-10-17T21:02:16-05:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process error","userAgent":"--","version":"24.0.6.1","data":{"app":"recognize"},"id":"634e0b3169119"}

**Comment by jakobroehrl** [comment]
Same as https://github.com/nextcloud/recognize/issues/370

**Comment by marcelklehr** [comment]
Recognize v2 is no longer maintained. I recommend to deactivate it until you are able to upgrade to v3 (which only supports Nextcloud v25). Thank you for your contributions!
