### ISSUE TITLE
Different results between WASM and native mode

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/recognize#399]
Is it expected to get different results between WASM and native mode?

Test protocol:
* only enable object recognition
* occ recognize:reset-tags
* occ recognize:recrawl
* php -f cron.php (repeated until there is no more entry in `oc_recognize_queue_imagenet`)

With WASM:
![image](https://user-images.githubusercontent.com/11291457/196748026-f34de4e5-d84a-4a7e-a848-8e3f267f812f.png)
With native:
![image](https://user-images.githubusercontent.com/11291457/196748108-e467d207-398c-43b1-879c-acd0f1d05bea.png)

**Comment by marcelklehr** [comment]
> Is it expected to get different results between WASM and native mode?

Yes, that's expected as WASM mode needs to use a smaller model to work nicely, so it will recognize fewer stuff.
