### ISSUE TITLE
Faces get removed from cluster during recrawl

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#404]
On master currently, still crawling images. 

I just noticed that during the same recrawl session, faces i previously merged into one, named, correct cluster of a person get removed from said cluster and split off into a new one. This has been happening prior to  v3.1.0 as well ( see https://github.com/nextcloud/recognize/issues/391#issuecomment-1282657428 ). Going to keep an eye on and keep you posted!

**Comment by marcelklehr** [comment]
This is kind of intended as the recrawl is supposed to be a reset mechanism. I'll think about this.

**Comment by illnesse** [comment]
Might probably be better if we had a reset faces button like reset tags and any crawling will just detect faces and add them to clusters, if they are not in a cluster yet

**Comment by illnesse** [comment]
I was also hoping that classification would be more precise on the next recrawl, since i cleaned clusters manually and the centroid should be closer to the actual person.  

On recrawl all I expected to happen was new face detecions and that faces w/o cluster would be moved to clusters (more or less acccurate obv) Faces already in clusters should be left alone. 

Whats your opinion on this?

**Comment by RedKage** [comment]
Sorry I want to bump this, as I was expecting exactly the same thing to happen:

> Awesome 👍🏻 I was also hoping that classification would be more precise on the next recrawl, since i cleaned clusters manually and the centroid should be closer to the actual person.
> 
> On recrawl all I expected to happen was new face detecions and that faces w/o cluster would be moved to the closest existing cluster or create new clusters (more or less acccurate obv) Faces already in clusters should be left alone.
> 
> Whats your opinion on this?

I am expecting that all my time wasted merging faces is leveraged for the next classifications so the model "gets better" at detecting subsequent faces already merged.
... but that's not the case?
Merging doesn't improve detection, it's maybe only a UI thing which has no effect on face detection?

**Comment by marcelklehr** [comment]
This issue is now tracked at #484
