### ISSUE TITLE
Cannot get ClassifyFacesJob to run any more

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#405]
i'm on master, classifying faces is enabled and it keeps queueing more and more files but ClassifyFacesJob doesn't run any more, any clues?

![image](https://user-images.githubusercontent.com/40355982/196977245-62c82181-4f15-44d1-8bc3-454e785ff5ce.png)

i tried emptying oc_recognize_queue_faces, reboot, triggering cron.php manually, disabling/enabling face recognition etc..
imagenet classifier seems to work, but no faces

**Comment by illnesse** [comment]
Apparently started again, many hours later. Would be nice to have some more control over it when it runs (like run NOW, and the intervals with amount of files too, or some people might even like to specify times when it should run etc)

![image](https://user-images.githubusercontent.com/40355982/197144620-7c6ed58e-e754-4497-b383-560644a978dd.png)

**Comment by marcelklehr** [comment]
By default it runs every 15 minutes but it also respects the background job window set in the Nextcloud config, where you can specify a 4h window when to run expensive background jobs.

**Comment by illnesse** [comment]
`maintenance_window_start` is disabled here so it should by default run every 15mins, i even set the interval lower and triggered cron.php manually but the job still won't run
