### ISSUE TITLE
Give two people the same name and strange things happen

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/recognize#408]
**Describe the bug**
When I have two people recognized and give them the same name the system will only ever show one person. The other person is nver to be seen again.

**To Reproduce**
1. Give a person name 'John Doe'
2. Give another person the name 'John Doe'

**Expected behavior**
Ideally I'd like the system to *notify* me about the conflict and suggest a merge. The merge suggestion should be approvable or dismissible letting me pick a different name.

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: 25.0.0
 - OS: Docker
 - RAM: 32 GB
 - Processor Architecture x86_64

**Additional context**
Great app. Thanks for all the hard work. This was the only thing still missing in NC for me.

**Comment by mhzawadi** [comment]
I have had this issue, you get a MySQL error back `Did not expect more than one result when executing: query \"SELECT `id`, `title`, `user_id` FROM `*PREFIX*recognize_face_clusters` WHERE (`user_id` = ?) AND (`title` = ?)\"`

Need to make title a uniq

**Comment by marcelklehr** [comment]
Should be fixed with v3.1.1

**Comment by marcelklehr** [comment]
Damnit. I can reproduce. It seems the DAV server simply always removes the destination of a MOVE if it exists :(
