### ISSUE TITLE
Nextcloud cron job fails after enabling recognize

### ISSUE THREAD

**Issue by anym001** [nextcloud/recognize#409]
**Describe the bug**
After i enabled recognize in the admin area, the nextcloud cron routine cannot be completed due to an error.

DivisionByZeroError: Division by zero in /var/www/html/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php:190
Stack trace:
#0 [internal function]: OCA\Recognize\Service\FaceClusterAnalyzer::OCA\Recognize\Service\{closure}(0)
#1 /var/www/html/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php(189): array_map(Object(Closure), Array)
#2 /var/www/html/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php(90): OCA\Recognize\Service\FaceClusterAnalyzer::calculateCentroidOfDetections(Array)
#3 /var/www/html/custom_apps/recognize/lib/BackgroundJobs/ClusterFacesJob.php(28): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters('nicole')
#4 /var/www/html/lib/public/BackgroundJob/Job.php(78): OCA\Recognize\BackgroundJobs\ClusterFacesJob->run(Array)
#5 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(58): OCP\BackgroundJob\Job->start(Object(OC\BackgroundJob\JobList))
#6 /var/www/html/lib/public/BackgroundJob/QueuedJob.php(48): OCP\BackgroundJob\QueuedJob->start(Object(OC\BackgroundJob\JobList))
#7 /var/www/html/cron.php(152): OCP\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#8 {main}

**To Reproduce**
1. Go to admin area of recognize
2. Activate Image tagging for faces and objects
3. Execute"docker exec -i -u 99 Nextcloud php -f /var/www/html/cron.php"

**Expected behavior**
Nextcloud cron routine should run without problems

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: object detection and face recognition

**Server (please complete the following information):**
 - Nextcloud: [e.g. 25.0.0]
 - OS: [e.g. Unraid 6.11.1]
 - RAM: [e.g. 32GB]
 - Processor Architecture [e.g. x86_64 (i3 9350K)]

**Additional context**
-

**Comment by illnesse** [comment]
#397 
should be fixed

**Comment by martadinata666** [comment]
Is there a log of recognize of what happend? The cron itself waiting recognize to finish infinitely. Did it restart from beginning if the cron killed? there is `recrawl` trigger, well it just silent. Thanks.

**Comment by stavros-k** [comment]
> #397 should be fixed

Can you push a release? Latest seems to be 3.1.0, which has this error.

**Comment by sirdrakeistda** [comment]
I got this error today with the latest version after recognizing 20000 images (still arouns 10000 in the queue).

**Comment by diyoyo** [comment]
Same here:
Error: Division by zero at /var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php#190

**Comment by marcelklehr** [comment]
v3.1.1 is out now
