### ISSUE TITLE
Background processing stops very often

### ISSUE THREAD

**Issue by Demian98** [nextcloud/recognize#412]
**Describe the issue**
I installed Recognize with NC 25 at the 19.10, and it's working on my images since this time. In the CPU usage from my nextcloud VM, it shows that the background process only works for some minutes and stops then:
![grafik](https://user-images.githubusercontent.com/77210091/197175011-569c843f-f0a6-441c-b5b1-d509149d06dc.png)

In the settings of Recognize it displays the same:
![grafik](https://user-images.githubusercontent.com/77210091/197175379-c92d2171-b7df-419d-b8e3-c44e30524f76.png)

It always just processes a small amount of images, and then it stops for a while.
My cron jobs are running every 15 mins, it looks like image processing also starts with every cron job and then runs for some minutes.

Currently, there are 11k images in the queue, and it is still increasing. This process would take multiple week to finish if it continues like this.

**Expected behavior**
I would expect the image recognition to run the whole time in the background, without stopping that often.

**Recognize (please complete the following information):**
 - JS-only mode: Yes (WASM is not enabled)
 - Enabled modes: Only face recognition (for now)

**Server (please complete the following information):**
 - Nextcloud: 25.0.0
 - OS: Ubuntu
 - RAM: 4GB
 - Processor Architecture: x64 (3.40GHz (8 cores))

**Comment by dhzl84** [comment]
Same here, and if I issue `occ recognize:recrawl` I get this in return:
```
DivisionByZeroError: Division by zero in /var/www/nextcloud/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php:190
Stack trace:
#0 [internal function]: OCA\Recognize\Service\FaceClusterAnalyzer::OCA\Recognize\Service\{closure}()
#1 /var/www/nextcloud/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php(189): array_map()
#2 /var/www/nextcloud/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php(90): OCA\Recognize\Service\FaceClusterAnalyzer::calculateCentroidOfDetections()
#3 /var/www/nextcloud/custom_apps/recognize/lib/BackgroundJobs/ClusterFacesJob.php(28): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters()
#4 /var/www/nextcloud/lib/public/BackgroundJob/Job.php(78): OCA\Recognize\BackgroundJobs\ClusterFacesJob->run()
#5 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(58): OCP\BackgroundJob\Job->start()
#6 /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php(48): OCP\BackgroundJob\QueuedJob->start()
#7 /var/www/nextcloud/cron.php(152): OCP\BackgroundJob\QueuedJob->execute()
#8 {main}
```

**Comment by illnesse** [comment]
Same, would be nice if i could actually use those 16 cores dedicated to this container to speed things up

**Comment by euro2** [comment]
same. 6 cores set, but i get 30% cpu util. in intervals

**Comment by tkiesel** [comment]
same here with 4 cores and 8 GiB RAM. ~30% utilization for 2-5 min in 10min intervals.

**Comment by ollioddi** [comment]
I am also having issues. There are sometimes half to whole hours between classifications and i have a queue of 52360 faces.

**Comment by SuperSandro2000** [comment]
Try manually updating to 3.1.1. Immediately after the update my server constantly used one core to classify files.

**Comment by derekakelly** [comment]
I too am having this issue.

Face recognition: 198618 Queued files, Last classification: 5 minutes ago

[cron] Error: DivisionByZeroError: Division by zero at <<closure>>

0. <<closure>>
   OCA\Recognize\Service\FaceClusterAnalyzer::OCA\Recognize\Service\{closure}("*** sensitive parameters replaced ***")
1. /var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php line 189
   array_map()
2. /var/www/nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php line 90
   OCA\Recognize\Service\FaceClusterAnalyzer::calculateCentroidOfDetections()
3. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClusterFacesJob.php line 28
   OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters()
4. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
   OCA\Recognize\BackgroundJobs\ClusterFacesJob->run()
5. /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php line 58
   OCP\BackgroundJob\Job->start()
6. /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php line 48
   OCP\BackgroundJob\QueuedJob->start()
7. /var/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\QueuedJob->execute()

at 2022-11-03T06:25:03+00:00

**Comment by marcelklehr** [comment]
v3.1.2 should fix all of this. Let me know if it does. :pray:

**Comment by ollioddi** [comment]
Seems to have improved from hours but I still experience minutes (noticed up to 20) between identifications
________________________________

**Comment by derekakelly** [comment]
Doesn't seem to have fixed it for me. However, there is no more divide by zero error.

I updated everything a few hours ago, and this is what I'm seeing now 

![image](https://user-images.githubusercontent.com/5824837/199822119-0911deae-bd0c-4594-b993-f648dd78232d.png)

![image](https://user-images.githubusercontent.com/5824837/199821961-c273bf26-3376-459a-84e4-c86c5dd3e60b.png)

**Comment by marcelklehr** [comment]
I guess a setting is in order here, to allow everyone to tweak it to their liking.

**Comment by ollioddi** [comment]
@marcelklehr is the interval hard-coded? I understand why, but when the queue is so huge, I'd rather have it use more resources and finish early.

The pattern @derekakelly has looks very similar to what I experience.

Docker stats show an idle of around 5% usage spiking towarda 600-700%? when identifying.

**Comment by tanpro260196** [comment]
In my case, the app seems to take 5mins break very 10 or so items.
I have about 15k pics, 4k songs, and ~1.5k vid. I may die of old age at the current processing rate.

**Comment by derekakelly** [comment]
The Number of CPU cores setting didn't have anything set at first, so I set it to 0 hoping that would help, but no luck. This setting implies to me it's going to push as hard as it can 24/7. There shouldn't be any hard code interval in my opinion. The cpu cores option is enough.

![image](https://user-images.githubusercontent.com/5824837/199949249-f3930d1e-d484-409e-93d1-03833788f12e.png)

**Comment by marcelklehr** [comment]
> There shouldn't be any hard code interval in my opinion. The cpu cores option is enough.

The cpu cores option is only applicable for a single job, though, and we don't want a single job doing all the work because this needs to scale to huge instances as well, with multiple worker nodes. It's not entirely trivial to make something scale up and down seamlessly, but we're trying to accomodate everyone :)

**Comment by marcelklehr** [comment]
Another issue that influenced this bug was that recognize would always assume people were using WASM mode, and scaled down the batch size accordingly, but erroneously, which causes a lot of pauses on fast machines.

**Comment by ollioddi** [comment]
@marcelklehr would it assume WASM mode even when toggled in the UI? This could perhaps explain my experience.

I am running on an i5 11400 with 12 threads so it would categorize it as a "faster" machine

**Comment by marcelklehr** [comment]
Yes, even when WASM mode is off the latest release uses a smaller batch size currently.

**Comment by leegarrett** [comment]
> v3.2.0 is out now which should fix the always-assume-WASM bug and allows setting custom batch sizes for all classifiers. Let me know about your experience with the latest version :)

Hi, thanks for the update. How are you supposed to change the batch size? If I type a different number in the field in the settings menu, it will fall back to the old value after reloading the page. There doesn't seem to be a button to save/apply the changes.

**Comment by Cebrain** [comment]
> v3.2.0 is out now which should fix the always-assume-WASM bug and allows setting custom batch sizes for all classifiers. Let me know about your experience with the latest version :)

Sadly i get now an error in recognize and in the logs.
Have 3.2 on latest docker nextcloud version installed


Recognize:
`An error occurred during face recognition, please check the Nextcloud logs. `

`[PHP] Error: Error: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /var/www/html/lib/private/Files/Cache/Scanner.php#508 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(8192, "strpos(): Passi ... d", "/var/www/html/l ... p", 508)
 1. /var/www/html/lib/private/Files/Cache/Scanner.php line 508
    strpos(null, ".part/")
 2. /var/www/html/lib/private/Files/View.php line 1384
    OC\Files\Cache\Scanner::isPartialFile(null)
 3. /var/www/html/lib/private/Files/Node/HookConnector.php line 227
    OC\Files\View->getFileInfo(null)
 4. /var/www/html/lib/private/Files/Node/HookConnector.php line 113
    OC\Files\Node\HookConnector->getNodeForPath(null)
 5. /var/www/html/lib/private/legacy/OC_Hook.php line 106
    OC\Files\Node\HookConnector->postWrite([null])
 6. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 471
    OC_Hook::emit("OC_Filesystem", "post_write", [null])
 7. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 398
    OCA\DAV\Connector\Sabre\File->emitPostHooks(false)
 8. /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php line 151
    OCA\DAV\Connector\Sabre\File->put(null)
 9. /var/www/html/apps/dav/lib/Upload/UploadFolder.php line 45
    OCA\DAV\Connector\Sabre\Directory->createFile("0000000000000000-0000000004310956", null)
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1098
    OCA\DAV\Upload\UploadFolder->createFile("0000000000000000-0000000004310956", null)
11. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 504
    Sabre\DAV\Server->createFile("uploads/hidden/ ... 6", null, null)
12. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
13. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
14. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
16. /var/www/html/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
17. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
18. /var/www/html/remote.php line 171
    require_once("/var/www/html/a ... p")

PUT /remote.php/dav/uploads/hidden/55b42946b1ec3e0c8be692fc61ac9d54/0000000000000000-0000000004310956
`

`[PHP] Error: Error: pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /var/www/html/lib/private/Files/Cache/Scanner.php#505 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(8192, "pathinfo(): Pas ... d", "/var/www/html/l ... p", 505)
 1. /var/www/html/lib/private/Files/Cache/Scanner.php line 505
    pathinfo(null, 4)
 2. /var/www/html/lib/private/Files/View.php line 1384
    OC\Files\Cache\Scanner::isPartialFile(null)
 3. /var/www/html/lib/private/Files/Node/HookConnector.php line 227
    OC\Files\View->getFileInfo(null)
 4. /var/www/html/lib/private/Files/Node/HookConnector.php line 113
    OC\Files\Node\HookConnector->getNodeForPath(null)
 5. /var/www/html/lib/private/legacy/OC_Hook.php line 106
    OC\Files\Node\HookConnector->postWrite([null])
 6. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 471
    OC_Hook::emit("OC_Filesystem", "post_write", [null])
 7. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 398
    OCA\DAV\Connector\Sabre\File->emitPostHooks(false)
 8. /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php line 151
    OCA\DAV\Connector\Sabre\File->put(null)
 9. /var/www/html/apps/dav/lib/Upload/UploadFolder.php line 45
    OCA\DAV\Connector\Sabre\Directory->createFile("0000000000000000-0000000004310956", null)
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1098
    OCA\DAV\Upload\UploadFolder->createFile("0000000000000000-0000000004310956", null)
11. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 504
    Sabre\DAV\Server->createFile("uploads/hidden/ ... 6", null, null)
12. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
13. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
14. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
16. /var/www/html/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
17. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
18. /var/www/html/remote.php line 171
    require_once("/var/www/html/a ... p")

PUT /remote.php/dav/uploads/hidden/55b42946b1ec3e0c8be692fc61ac9d54/0000000000000000-0000000004310956
`

**Comment by marcelklehr** [comment]
The error stacks you posted are unrelated to recognize I'm afraid.

**Comment by marcelklehr** [comment]
> How are you supposed to change the batch size? If I type a different number in the field in the settings menu, it will fall back to the old value after reloading the page. There doesn't seem to be a button to save/apply the changes.

That would be a bug :/ v3.2.1 should fix this. Thanks for the feedback!

**Comment by rhatguy** [comment]
Is recognize supposed to use more than 1 core?  I have a "fast" 28 core unraid server with 576GB of ram.  Looking at top inside the Nextcloud container I only see one process usually at 100% CPU (one cores worth) even though I've tried setting cores to 0 or 16 inside the recognize settings panel.  Is this expected behavior or should recognize be using multiple cores?

**Comment by marcelklehr** [comment]
> Is recognize supposed to use more than 1 core?

In WASM mode it can only use one core. Otherwise it should be able to use all cores.

**Comment by rhatguy** [comment]
I get the "Your machine supports native TensorFlow operation, you do not need WASM mode. " on the recognize settings panel and the "enable wasm mode" is turned off.  I've run "cat /proc/cpuinfo" inside the nextcloud container and it shows 56 cores (28 real cores and 28 hyperthreads).  How does recognize detect the presence of multiple cores?  Perhaps its not seeing the available cored due to running under docker under unraid?

**Comment by marcelklehr** [comment]
Which version of recognize do you have installed?

**Comment by rhatguy** [comment]
3.2.2

**Comment by marcelklehr** [comment]
It might help to flick the WASM switch on and off once to make sure it has the correct value.

**Comment by rhatguy** [comment]
I tried flipping the WASM switch on and off and it doesn't seem to have changed anything.  Still have 1 process running using all of 1 core.
