### ISSUE TITLE
Classification error in the log

### ISSUE THREAD

**Issue by Demian98** [nextcloud/recognize#416]
**Describe the bug**
The following error appears often in the log since Recognize is installed and processing images:
![20221022_104839](https://user-images.githubusercontent.com/77210091/197330484-9f50d539-dcfd-49e9-ba1c-855928ac73f4.jpg)
Please let me know if more details are required!

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: face

**Server (please complete the following information):**
- Nextcloud: 25.0.0
- OS: Ubuntu
- RAM: 4GB
- Processor Architecture: x64 (3.40GHz (8 cores))

**Comment by jakobroehrl** [comment]
Same as https://github.com/nextcloud/recognize/issues/370
