### ISSUE TITLE
[Enhancement] Add option to show only recognized face and not whole image

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/recognize#429]
When sorting images, it is sometimes very hard to sort them correctly. On images with multiple persons it happens sometimes, that the wrong face is marked as person1, but person1 is somewhere else on the image. If you see only the person in the image view of the person (and not in the person list), it is not possible to tell wether the correct person was recognized.

Solition:
Add option to only show the faces and not the whole image in the person image list.

**Comment by sirdrakeistda** [comment]
Duplicate

**Comment by sirdrakeistda** [comment]
This is missing in the Nextcloud photo app.

**Comment by marcelklehr** [comment]
This is indeed an issue in the photos app, if you want to have it there
