### ISSUE TITLE
Translations from l10n are not applied

### ISSUE THREAD

**Issue by sandzhaj** [nextcloud/recognize#430]
**Describe the bug**
All tags are in english while nextcloud system uses russian

**Expected behavior**
Translated tags.

**Server (please complete the following information):**
 - Nextcloud: 25
 - OS: docker
 - RAM: 16GB
 - Processor Architecture x86

Is it still on development, or I've configured something wrong?

**Comment by marcelklehr** [comment]
That was a bug. It should be fixed in the next patch release: https://github.com/nextcloud/photos/pull/1407

**Comment by sandzhaj** [comment]
Actually, no progress

**Comment by marcelklehr** [comment]
Which Nextcloud version do you have? Which recognize version? Which language is set as your user language?

**Comment by sandzhaj** [comment]
Version 26.0.0 based on nextcloud:latest docker image (updated today)
Recognize: 3.7.0

language - Russian.

I recreated all tags, it still tagged all in English and search works only with English words

**Comment by marcelklehr** [comment]
Translations are only applied in the photos app

**Comment by sandzhaj** [comment]
Oh, I see. Thank you for explaining 
So It’s not useful for searching, while users have to translate their thoughts into English to find a photo. Maybe we can make a feature request to expand a functionality of translated tags to make it more comfortable?

**Comment by marcelklehr** [comment]
> So It’s not useful for searching, while users have to translate their thoughts into English to find a photo. Maybe we can make a feature request to expand a functionality of translated tags to make it more comfortable?

Yes, search is a problem in this case, I agree. Can you file an issue on the photos repository?
