### ISSUE TITLE
Please bring back the occ recognize commands, specially "index"

### ISSUE THREAD

**Issue by pulsejet** [nextcloud/recognize#432]
I work on the integration with [memories](https://github.com/pulsejet/memories), and testing recognize is a nightmare. I need to run the background jobs repeatedly while resetting the job checked params. Please bring back the occ command to index everything at once. This should also be useful for those who want to run an initial scan sycnhronously (I bet a lot of people installing recognize for the first time).

**Comment by marcelklehr** [comment]
Yes, that's a good point. I'll look into that.

**Comment by marcelklehr** [comment]
The next release is again going to have a recognize:classify command :)

**Comment by pulsejet** [comment]
Thank you!

**Comment by bugsyb** [comment]
Thank you @marcelklehr !
