### ISSUE TITLE
Could not find storage root

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#433]
I keep getting this now, my storage setup hasn't changed

```
{
   "reqId":"wlMtO9vvvqlMk8Q4n3nv",
   "level":3,
   "time":"2022-10-28T21:58:29+00:00",
   "remoteAddr":"",
   "user":"--",
   "app":"recognize",
   "method":"",
   "url":"--",
   "message":"Could not find storage root",
   "userAgent":"--",
   "version":"25.0.1.0",
   "data":{
      "app":"recognize"
   }
}
```

**Comment by tullsta2** [comment]
Hello illnesse,

am/was facing the same issue
=> what is filled into the "Node.js path"-field un der the "administrative settings"=> "recognize" (last setting in the page)?
In my case default setting was "none". Deeting this seems to get me one step further.

**Comment by marcelklehr** [comment]
Yes, this is unrelated to the node.js path. This may be due to the mount having been removed, e.g. when a shared file was unshared. Can you find out which job (ie. which arguments) is causing this and investigate what happened to the storage and root directory?

**Comment by tullsta2** [comment]
Hello Marcel,

same here: I got the message twice but currently cannot reproduce this "storage root" error.
Happy to dig further if needed.

Thanks and kind regards - tullsta

PS: However, I get a recognize-warning "Classifier process output: sh: 1: exec: : Permission denied" followed by a core-error "RuntimeException: Classifier process error"in return... :)

**Comment by marcelklehr** [comment]
@tullsta2 Please open a new issue :)
