### ISSUE TITLE
Audio and video tagging not working

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/recognize#434]
**Describe the bug**
Only image tagging is working for me and audio and video is failing with:

```
Classifier process output: Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node. Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module. If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue. at Object.<anonymous> (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Module.require (internal/modules/cjs/loader.js:974:19) at require (internal/modules/cjs/helpers.js:101:18) at Object.<anonymous> (/var/lib/nextcloud/store-apps/recognize/src/classifier_movinet.js:17:9) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) Trying js-only mode Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node. Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module. If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue. at Object.<anonymous> (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:49:11) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Module.require (internal/modules/cjs/loader.js:974:19) at require (internal/modules/cjs/helpers.js:101:18) at Object.<anonymous> (/var/lib/nextcloud/store-apps/recognize/src/movinet/MovinetModel.js:12:9) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) Trying js-only mode Error: Backend name 'tensorflow' not found in registry at Engine.<anonymous> (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4255:35) at step (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:125:27) at Object.next (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:74:53) at /var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:67:71 at new Promise (<anonymous>) at __awaiter (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:53:12) at Engine.setBackend (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4249:16) at Object.setBackend (/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9006:19) at Object.<anonymous> (/var/lib/nextcloud/store-apps/recognize/src/classifier_movinet.js:106:4) at Module._compile (internal/modules/cjs/loader.js:1085:14) 
```

**To Reproduce**
1. Enable all scanning
2. override nodejs path to a node v14.20.1

**Expected behavior**
It should work like image tagging

**Recognize (please complete the following information):**
 - JS-only mode: no
 - Enabled modes: all

**Server (please complete the following information):**
 - Nextcloud: 25.0.0
 - OS: NixOS
 - RAM: 32GB
 - Processor Architecture x86_64

**Additional context**

**Comment by marcelklehr** [comment]
Why did you need to override nodejs path to a node v14.20.1?

**Comment by SuperSandro2000** [comment]
NixOS has no standard FHS layout, so the precompiled nodejs binary is not working because it can't find its shared objects. I have pointed it to the nodejs 14.X from NixOS.

**Comment by marcelklehr** [comment]
Does your system come with gnu libc? libtensorflow depends on that

**Comment by SuperSandro2000** [comment]
> Does your system come with gnu libc?

Technically yes but it is most likely in a none standard location so the shared object cannot find it. Where is that file located in the download? I can't find anything with .so in its name or similar.
According to the logs there should be some file at ``/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node`` but the lib directory ``/var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node/lib/`` is already empty.

I rebuild the native extensions via the following commands. Shouldn't this be done by the extension before distribution?

````
nix shell nixpkgs#nodePackages.node-pre-gyp nixpkgs#nodejs-14_x
cd /var/lib/nextcloud/store-apps/recognize/node_modules/@tensorflow/tfjs-node
node scripts/install.js
````

also after that I noticed in the crontab that the taskset program is missing which I also added to the environment.

**Comment by marcelklehr** [comment]
> Shouldn't this be done by the extension before distribution?

The app should do that upon installation to save on download size, which likely failed because node doesn't work in your environment.

**Comment by SuperSandro2000** [comment]
Shouldn't this be reported as an error when running ``nextcloud-occ recognize:download-models``? The command shows currently no output even when run with ``-vvv``, so I couldn't really know if it worked or not and why.

**Comment by marcelklehr** [comment]
Technically, the models can be downloaded even when the installation didn't succeed entirely, because the command doesn't rely on node.

**Comment by marcelklehr** [comment]
It may be a good idea to add a check to the admin settings whether node installation is functional and libtensorflow works.

**Comment by SuperSandro2000** [comment]
Good to know that the compilation happens at install time and indeed, a check on the admin settings would be good to have.
