### ISSUE TITLE
[FR]: Use default thumbnail backend for converting/downscaling

### ISSUE THREAD

**Issue by Leptopoda** [nextcloud/recognize#437]
**Describe the request**
Currently this app relies on `Imagick` to convert pictures to jpeg and optionally scale them down. Many people recommend not using this php extension and that's why the docker image isn't using it [see](https://github.com/nextcloud/docker/issues/1414).
Since nextcloud 24 there is the possibility to [setup imaginary](https://docs.nextcloud.com/server/24/admin_manual/installation/server_tuning.html#previews) as a thumbnail backend. This can help with performance.
Also some people might only use imaginary and not have Imagick setup also hurting the performance and putting further stress on the main php node.

I stumbled across this while going through the commits and seeing https://github.com/nextcloud/recognize/commit/928160eb4cab2e09633e15bfa072b1fadf7c409a

As the [preview_generator](https://github.com/nextcloud/previewgenerator/) is already making use of it there should be some public functions around this. Although I'm not sure the raw imagic connection is exposed or rather only the limited generatePreview command. I'd have to further investigate this.

**Comment by marcelklehr** [comment]
Since v3.2 we now use the official preview generation mechanism :) Thanks for the suggestion!
