### ISSUE TITLE
OK for other apps to create empty clusters / organize faces?

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#443]
I was suggesting the ability to move selected faces from a cluster to a NEW cluster over at memories: https://github.com/pulsejet/memories/issues/117

What's your opinion on this, do you think it would be safe for other apps to add rows to oc_recognize_face_clusters and assign their id to faces, or are there plans for recognize's internal data structure that might collide with the idea?

**Comment by marcelklehr** [comment]
I don't recommend directly altering db entries of this app. Ideally, the DAV API should be used to interface with the clusters.

**Comment by sotornien** [comment]
Hi,
moving Faces to a new Cluster is kinda possible via the DAV API. I recommend opening the browser console when moving faces to a new Cluster to see whats happening. Basically you can use curl with a MOVE request to move Faces between Clusters. The request also needs a "Destination :" Header. After all faces are moved you see also a delete request at the end for removing the empty Cluster. URL looks like this: https://fqdn.de/remote.php/dav/recognize/username/faces/$clusterId. If the Cluster has allready a name you need to use the name: I.e. Destination: https://fqdn.de/remote.php/dav/recognize/username/faces/Andi/image-20.jpg
