### ISSUE TITLE
Detected face position sometimes inaccurate

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#444]
Memories has a feature that displays a rectangle around recognize's face data, see https://github.com/pulsejet/memories/issues/79

I noticed that the rectangle was off sometimes so i filed this https://github.com/pulsejet/memories/issues/93 But it seems like the wrong position is actually coming from recognize. 

It doesn't happen often but when it does, 
- it always happens to the same files (after a reset/recrawl)
- it very often happens in a row, like many pictures from the same day, a whole photo session etc. (it's always the same resolution/camera/mimetype etc)
- the file is often still correlated to the right person (in the correct cluster)
- sometimes many of those "bad" detections are clustered together
- its dimensions seem more or less correct (compared to the actual face in the image), just the position is off
- there's nothing else in the picture that could be confused with a human face 

I can happily supply test data/files if needed!

Some more examples:
![image](https://user-images.githubusercontent.com/40355982/198979920-b54402fa-f2a4-4d74-b124-adf873852d8d.png)
![image](https://user-images.githubusercontent.com/40355982/198979974-708a35cc-665f-43b9-b03c-abe33ce4a30b.png)
![image](https://user-images.githubusercontent.com/40355982/198980040-f6849e9b-85d4-4b26-bcbb-dc5961fa85be.png)
![image](https://user-images.githubusercontent.com/40355982/198980093-83a692df-ab97-43d9-b249-bd54cedd7d7b.png)

**Comment by reox** [comment]
My first guess was that this might happen if the image has a rotation stored in EXIF data and thus the position of the bbox is measured in the "original image space" while the image is then correctly rotated on preview but the bbox is not... But then there are images where also with a rotation it does not fit.
However, I still think that exif orientation is at least one of the problems here...
