### ISSUE TITLE
Nextcloud store version not updated

### ISSUE THREAD

**Issue by martadinata666** [nextcloud/recognize#446]
**Describe the bug**
recognize version at [nextcloud apps](https://apps.nextcloud.com/apps/recognize) still on 3.1.0, the package url itself at 3.1.1 `https://github.com/nextcloud/recognize/releases/download/v3.1.1/recognize-3.1.1.tar.gz`

As pre existing user can't update recognize as it already got 3.1.0 installed, for new user install it called `3.1.0` but the true version was `3.1.1`

**Comment by serverless83** [comment]
Maybe it's related to the appinfo.xml still having the 3.1.0 tag

**Comment by marcelklehr** [comment]
Yes, I'll push a new release shortly
