### ISSUE TITLE
App "recognize" cannot be installed because appinfo file cannot be read.

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/recognize#452]
**Describe the bug**
After updating to app version 3.1.2 and NC 25.0.1 I can't activate the app anymore. This happens in the Web frontend and also when trying to activate by occ command.

**To Reproduce**
1. update to recognize 3.1.2
2. update NC 25.0.0 -> NC25.0.1 
3. Error: App "recognize" cannot be installed because appinfo file cannot be read.

**Expected behavior**
App should work after update

**Recognize (please complete the following information):**
 - Enabled modes: object detection, face recognition

**Server (please complete the following information):**
 - Nextcloud: 25.0.1
 - OS: Debian
 - RAM: 8GB
 - Device: Raspberry Pi 4

**Comment by sirdrakeistda** [comment]
Let's hope it's a timout issue.

**Comment by marcelklehr** [comment]
Did it resolve itself?

**Comment by sirdrakeistda** [comment]
No it did not. It's still remaining. I tried to install other apps without problem.

**Comment by sirdrakeistda** [comment]
What confuses me, is the fact that the app was never uninstalled or disabled. It might be disabled by the update process, but not by me. And the error occurs faster then 10 seconds (the timout). This sounds for me not like the original issue.

**Comment by karpiq24** [comment]
I had the same issue, I fixed it by removing recognize, manually deleting recognize directory in nextcloud/apps dir and reinstalling recognize.

**Comment by sirdrakeistda** [comment]
@karpiq24 What caused the issue for you? Was it the app update, the NC update or both. I think this would be very interesting. Deleting the app data would be the last thing I want to do. This would mean permanent data loss and rerecognize all images.

**Comment by karpiq24** [comment]
> @karpiq24 What caused the issue for you? Was it the app update, the NC update or both. I think this would be very interesting. Deleting the app data would be the last thing I want to do. This would mean permanent data loss and rerecognize all images.

During Nextcloud update, recognize was trying to update automatically but failed and the app was disabled by the updater.

**Comment by sirdrakeistda** [comment]
Making backup and reinstall app is a good idea. I will try it later. I will leave this issue open, because there is still an issue in the updater.

**Comment by sirdrakeistda** [comment]
I reinstalled recognize and compared the files in the app folder. The folder included after the update only the models folder and recognize.tar.gz. After App update, there where much more files and folders. Could unpack the .tar.gz file fail? It would explain very much.

**Comment by meichthys** [comment]
Removing and reinstalling worked for me as well 👍
