### ISSUE TITLE
Recognize does not detect my CPU (AMD Ryzen 5 PRO 4650G) eventhough it's detected by nextcloud

### ISSUE THREAD

**Issue by Lelo5657** [nextcloud/recognize#453]
**Describe the bug**

Recognize Version: 	3.1.2

**To Reproduce**
1. Go to 'Recognize Settings'
2.  Scroll down to 'Tensorflow plain mode'
4. See error: "Could not check whether your machine supports native TensorFlow operation."

On my Unraid Dashboard I also can see that only one core is been used

**Expected behavior**
As much cores as are addressed (in my case all) should be used by recognize and the CPU should be detected

**Recognize (please complete the following information):**
 - JS-only mode: 
"Node.js path
If the shipped Node.js binary doesn't work on your system for some reason you can set the path to a custom node.js binary. Currently supported is Node v14.17 and newer v14 releases."
/config/www/nextcloud/apps/recognize/bin//node
 - WASM Mode enabled

 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: 25.0.1
 - OS:  Unraid 6.11.1
 - RAM: 32 GB
 - Processor Architecture x86-64 - AMD Ryzen 5 PRO 4650G with Radeon Graphics

**Additional context**
![Unraid Dashboard](https://user-images.githubusercontent.com/73521872/199938410-1f0a5b15-feaf-4792-9fd2-afc84e9d5514.PNG)
![Status Recognize](https://user-images.githubusercontent.com/73521872/199938413-88275ecc-74f9-49e5-a59f-83ea847ee878.PNG)
![Error](https://user-images.githubusercontent.com/73521872/199938417-3b213f3a-79d6-4c72-82f4-9a3905219722.PNG)
![Nextcloud System Dashboard](https://user-images.githubusercontent.com/73521872/199938600-08a8448d-01b6-4c32-85b5-b6be5633fb7f.PNG)

Also i can see in my nextcloud docker log following line:
"sh: taskset: not found"
CPU is detected by Nextcloud Docker - Unraid CPU pinning: all cores to nextcloud 

```
text  error  warn  system  array  login  

s6-rc: info: service init-mods successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser
cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/40-config
cont-init: info: /etc/cont-init.d/40-config exited 0
cont-init: info: running /etc/cont-init.d/50-install
cont-init: info: /etc/cont-init.d/50-install exited 0
cont-init: info: running /etc/cont-init.d/60-memcache
cont-init: info: /etc/cont-init.d/60-memcache exited 0
cont-init: info: running /etc/cont-init.d/70-aliases
cont-init: info: /etc/cont-init.d/70-aliases exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.`
```

>

**Comment by marcelklehr** [comment]
On some systems the php script doesn't get access to the cpu info to detect whether your machine can run libtensorflow. You can try disabling WASM mode manually using the switch in the settings and see if it works, if you get errors, you're stuck with one core.

**Comment by Lelo5657** [comment]
disabled it - no errors but still only one core ... do you have any ideas?

**Comment by Lelo5657** [comment]
otherwise face recognition will take ages: 
101690 Queued files

**Comment by marcelklehr** [comment]
It might take a little time for the setting to take effect as the files are processed in batches

**Comment by Lelo5657** [comment]
ok thx - so i will wait - i did only find a similar issue on a synology nas - thats why I opend this issue for AMD with Unraid and a nextcloud Docker. Is there somewhere a manual or troubleshoot for this kind of problems?

**Comment by marcelklehr** [comment]
> Is there somewhere a manual or troubleshoot for this kind of problems?

Not currently.

If it still doesn't use all cores after half an hour, the classifier process probably falls back to WASM mode, in case your CPU doesn't support AVX instructions (You may want to check if that's the case anyway)

**Comment by Lelo5657** [comment]
sorry for asking this question - never had to deal with avx before - but what kind of AVX do i need? AVX or AVX-512? I'll have to check if it is possible to (de)activate it in the bios ... 
Description of the CPU confirms:
"Hardware virtualization is available on the Ryzen 5 PRO 4650G, which greatly improves virtual machine performance. Programs using Advanced Vector Extensions (AVX) will run on this processor, boosting performance for calculation-heavy applications. Besides AVX, AMD is including the newer AVX2 standard, too, but not AVX-512."

**Comment by marcelklehr** [comment]
Oh! You're on Unraid using the linuxserver docker container? Then you're out of luck, it's running with musl which also isn't supported by libtensorflow.

**Comment by Lelo5657** [comment]
Yes thats the setup ... suddenly now two cores are now in use:
![image](https://user-images.githubusercontent.com/73521872/200187958-9a018758-b701-4521-a88d-f8c356ae6d92.png)

**Comment by Archmonger** [comment]
I'm in a similar situation with Ryzen 3600X on LSIO container.

Would switching containers improve things?

**Comment by zzyzx-dc** [comment]
> I'm in a similar situation with Ryzen 3600X on LSIO container.
> 
> Would switching containers improve things?

Did you ever end up switching?

**Comment by Archmonger** [comment]
I honestly don't remember, but I gave up on it.

**Comment by marcelklehr** [comment]
> Would switching containers improve things?

Yes. Switch to a debain based container for example
