### ISSUE TITLE
Throttle CPU consumption of Classifiers

### ISSUE THREAD

**Issue by phil-lipp** [nextcloud/recognize#455]
On my RaspberryPi 4 8GB the classification is taking up large amounts of resources (even tho I limited it to max 2 CPU cores already), making my Nextcloud Webinterface basically unusable as it runs into gateway timeout frequently. With roughly 60.000 pictures to be classiefied this would clog up my Nextcloud for weeks.
I found myself a workaround by using the cpulimit program on debian to limit the CPU consumption of node to 50% during my active hours (7am till midnight) and 'unlocking' it for when I'm sleeping.
For anyone interested this is my cpulimit command:
`sudo cpulimit -P /var/www/nextcloud/apps/recognize/bin/node -l 50 -v -m`

I think there are many use-cases (like mine) for a feature to throttle the cpu consumption of the Classifiers during certain time. What do you think?

**Comment by marcelklehr** [comment]
You can set a time window of 4h for processing heavy background jobs in Nextcloud: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html
