### ISSUE TITLE
Classifier switches to smaller batchsize even if purejs is disabled

### ISSUE THREAD

**Issue by reox** [nextcloud/recognize#459]
**Describe the bug**
The face classifier only processed 25 files at once and exited, even though WASM was disabled.

**To Reproduce**
1. install recognize
2. Enable Faces
3. wait
4. only 25 images are processed

**Expected behavior**
More files should be processed

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: Faces

**Server (please complete the following information):**
 - Nextcloud: 25.0.1
 - OS: Debian
 - RAM: 6GB
 - Processor Architecture x86_64
 - 
**Additional context**
I checked the config and saw that `tensorflow.purejs` was set to `"null"`:
```
php ./occ config:list | grep recognize -A 10
        "recognize": {
[...]
            "tensorflow.purejs": "null",
```

I flicked the switch for WASM twice, now the value is `false` and now it processes 100 files per batch run:
```
 php ./occ config:list | grep recognize -A 10
        "recognize": {
[...]
            "tensorflow.purejs": "false",
```

Is it possible that the config setting is not set correctly initially?

**Comment by marcelklehr** [comment]
Oh, that would explain a lot. Nice catch!

**Comment by marcelklehr** [comment]
Very nice catch! I can reproduce and have a fix
