### ISSUE TITLE
Recognize spamming Nextclouds cron.php

### ISSUE THREAD

**Issue by derritter88** [nextcloud/recognize#466]
**Describe the bug**
After migrating to NC25 I recognized that the server load is getting higher and higher after some time.
My cron.php runs every 5 minutes and at each cron run it starts to recognize faces.
From my point of view it looks like cronjob is waiting for a "finish-signal" from recognize-app but as it keeps running the cronjob also keeps running.
After 5 minutes another cronjob will start and so on. At the end the server load is too high and I need to either forcefully kill Apache2/PHP-FPM or reboot the server.

The only current solution is to disable the recognize app.

**To Reproduce**
1. Wait

**Expected behavior**
Cron.php should be aware that recognize is still running from the previous job and will skip it.

**Recognize (please complete the following information):**
 - JS-only mode: ? Not sure, WASM mode is not enabled and I am using Node.js which is being shipped with the app.
 - Enabled modes: faces, objects & landmarks (no audio or video tagging enabled)
 - Additional info: I have limitied recognize to only use 4 CPU cores.

**Server (please complete the following information):**
 - Nextcloud: 25.0.1
 - OS: Ubuntu 22.04.1
 - RAM: 32 GB
 - Processor Architecture x86_64

**Comment by marcosvfc** [comment]
I'am facing the same problem in every cron job. Nextcloud 25.0.1, Debian 11. Recognize is running for the past one week! Seeing spikes of CPU utilization in Netdata at every cron job. At this moment I have 20k queued files and growing... My machine supports native TensorFlow, so WASM was disabled.

**Comment by martadinata666** [comment]
In my case, i think it going OOM after 6hrs or so running, i assume that it create new batch run every triggered cron?

**Comment by shilin-da** [comment]
It looks like the https://github.com/nextcloud/recognize/issues/413 is the reason

**Comment by iamklaus** [comment]
I face the same problem. To get rid of the CPU load and tons of running jobs I restarted my docker. No I get this message. Any idea how I could trigger the job to continue without starting all over?

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/17814062/200920810-a402a468-d552-4e2f-9725-3feb7573b9c8.png">

**Comment by marcelklehr** [comment]
Thank you for your feedback. It will soon be possible to tweak the batch sizes for the classifier jobs to avoid overloading the CPU.

**Comment by marcelklehr** [comment]
v3.2.0 is out now where you can dial down the batch size for your classifier jobs

**Comment by martadinata666** [comment]
updated, and please clarify the function. I tried run the cron manually to test it behavior, assuming the classify finished, the cron should be report success? in my test it still stuck without doing anything.

I monitor with `docker top container_name`, so I know that classifying running success but the cron just stuck there.

**Comment by marcelklehr** [comment]
@martadinata666 So, what's the status for you exactly? cron.php is running? Does the Queue size decrease or change at all? Do you still see Recognize jobs in the oc_jobs table in the database?

**Comment by martadinata666** [comment]
So here what i found, the queue size is change, so the classifier is working fine, but the cron weirdly stuck like waiting recognize to finish `but the recognize is finished`, and i tried disabling and re-enabling the cron now reporting success after recognize finish classifying instead stuck. 🤦🏼 

Sorry for the noise.
