### ISSUE TITLE
Q: is there a minimum number of images required in the queue to start classifying?

### ISSUE THREAD

**Issue by reox** [nextcloud/recognize#467]
It took some time to run all images that were in the queue and finally it approached zero. Now 7 new images were uploaded via the Android nextcloud app and I can see that these get put into the queue. But the face detection job seems to not start:
![image](https://user-images.githubusercontent.com/431045/200194265-b750f4b5-377f-4c4b-9170-c4bf4e8d745c.png)

Is there some minimal number of images required in the queue before a new classification job is started, or is this related to #412 or did I even broke something by cleaning up the queue, as I wrote here: https://github.com/nextcloud/recognize/issues/413#issuecomment-1303080590

NC 25.0.1 / recognize 3.1.2

**Comment by marcelklehr** [comment]
> Q: is there a minimum number of images required in the queue to start classifying?

There is not. I recently found a bug that would not remove since-removed files from the queue so that the queue would be clogged with non-existent files, though. This will be patched in the next release
