### ISSUE TITLE
OOM kill, 8GB RAM

### ISSUE THREAD

**Issue by AbelLykens** [nextcloud/recognize#469]
**Describe the bug**
I believe you advice 4GB of ram. I have 8 in my nextcloud server. Node goes up to 10GB though:

`kernel: Out of memory: Killed process 54522 (node) total-vm:10267192kB, anon-rss:7026448kB, file-rss:0kB, shmem-rss:0kB, UID:33 pgtables:16976kB oom_score_adj:0`

10 267 192 kB is 10GB.

**To Reproduce**
1. Enable recognize, queue is >200k files
2. Wait for cron job
3. See OOM killed process

**Expected behavior**
Would hope the process stays within limits (and does not get killed)

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: Face + Object

**Server (please complete the following information):**
 - Nextcloud: 25.0.3
 - OS: Debian GNU/Linux 11 (bullseye)
 - RAM: 8GB
 - Processor Architecture: x86 (fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap xsaveopt xsavec xgetbv1 arat)

**Additional context**
None :)

**Comment by marcelklehr** [comment]
see https://github.com/nextcloud/recognize/issues/370

**Comment by AbelLykens** [comment]
Seems like this is indeed fixed by v3.2.1, cheers @marcelklehr !
