### ISSUE TITLE
sh: 1: exec: : Permission denied

### ISSUE THREAD

**Issue by tullsta2** [nextcloud/recognize#470]
Hi,

running NC25.0.1 with recognize 3.1.2 under openmediavault.
When enabling face recognition I get the following "permission denied"-warning:
```
{
	"reqId":"sg0AiUNtOpuBzo24eiGz",
	"level":2,
	"time":"2022-12-24T20:00:00+00:00",
	"remoteAddr":"",
	"user":"--",
	"app":"recognize",
	"method":"",
	"url":"--",
	"message":"Classifier process output: sh: 1: exec: : Permission denied\n",
	"userAgent":"--",
	"version":"25.0.1.1",
	"data":{
		"app":"recognize"
	}
}
```

this is then followed by a "Runtime-exception"-error:

```
{
   "reqId":"sg0AiUNtOpuBzo24eiGz",
   "level":3,
   "time":"2022-12-24T20:00:00+00:00",
   "remoteAddr":"",
   "user":"--",
   "app":"core",
   "method":"",
   "url":"--",
   "message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 320\n)\n)",
   "userAgent":"--",
   "version":"25.0.1.1",
   "exception":{
      "Exception":"RuntimeException",
      "Message":"Classifier process error",
      "Code":0,
      "Trace":[
         {
            "file":"/var/www/html/custom_apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php",
            "line":77,
            "function":"classifyFiles",
            "class":"OCA\\Recognize\\Classifiers\\Classifier",
            "type":"->",
            "args":[
               "faces",
               [
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":10
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":11
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":12
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":13
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":14
                  },
                  "And 95 more entries, set log level to debug to see all entries"
               ],
               120
            ]
         },
         {
            "file":"/var/www/html/custom_apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php",
            "line":39,
            "function":"classify",
            "class":"OCA\\Recognize\\Classifiers\\Images\\ClusteringFaceClassifier",
            "type":"->",
            "args":[
               [
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":10
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":11
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":12
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":13
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":14
                  },
                  "And 95 more entries, set log level to debug to see all entries"
               ]
            ]
         },
         {
            "file":"/var/www/html/custom_apps/recognize/lib/BackgroundJobs/ClassifierJob.php",
            "line":67,
            "function":"classify",
            "class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob",
            "type":"->",
            "args":[
               [
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":10
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":11
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":12
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":13
                  },
                  {
                     "__class__":"OCA\\Recognize\\Db\\QueueFile",
                     "id":14
                  },
                  "And 95 more entries, set log level to debug to see all entries"
               ]
            ]
         },
         {
            "file":"/var/www/html/custom_apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php",
            "line":31,
            "function":"runClassifier",
            "class":"OCA\\Recognize\\BackgroundJobs\\ClassifierJob",
            "type":"->",
            "args":[
               "faces",
               [
                  3,
                  320
               ]
            ]
         },
         {
            "file":"/var/www/html/lib/public/BackgroundJob/Job.php",
            "line":78,
            "function":"run",
            "class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob",
            "type":"->",
            "args":[
               [
                  3,
                  320
               ]
            ]
         },
         {
            "file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php",
            "line":103,
            "function":"start",
            "class":"OCP\\BackgroundJob\\Job",
            "type":"->",
            "args":[
               {
                  "__class__":"OC\\BackgroundJob\\JobList"
               }
            ]
         },
         {
            "file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php",
            "line":93,
            "function":"start",
            "class":"OCP\\BackgroundJob\\TimedJob",
            "type":"->",
            "args":[
               {
                  "__class__":"OC\\BackgroundJob\\JobList"
               }
            ]
         },
         {
            "file":"/var/www/html/cron.php",
            "line":152,
            "function":"execute",
            "class":"OCP\\BackgroundJob\\TimedJob",
            "type":"->",
            "args":[
               {
                  "__class__":"OC\\BackgroundJob\\JobList"
               },
               {
                  "__class__":"OC\\Log"
               }
            ]
         }
      ],
      "File":"/var/www/html/custom_apps/recognize/lib/Classifiers/Classifier.php",
      "Line":139,
      "message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 320\n)\n)",
      "exception":{
         
      },
      "CustomMessage":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 320\n)\n)"
   }
}
```

Any idea/suggestion how to proceed here welcome.

**Comment by tullsta2** [comment]
Hi - thanks for coming back on this!

Here the details of the machine:

Intel Celeron J4105 (4 cores, Gemini Lake) 32 GB RAM
Openmediavault 5.6.26 Linux Kernel 5.10 (amd64)
docker 5:20.10.21~3-0~debian-buster
Running NC25.0.1 official docker latest image
WASM mode was activated automatically 
- machine does not support native TensorFlow operation
- server does not support AVX instructions

ldd --version
 => ldd (Debian GLIBC 2.28-10+deb10u2) 2.28

Hope that provides all details. I checked whether there is a specific bin for this architecture available (read about this here I think), but could not find anything for this arch.

Thanks and kind regards - tullsta

**Comment by marcelklehr** [comment]
Can you update to v3.2.0 as soon as it's available and check in the admin settings whether node.js works correctly?

**Comment by tullsta2** [comment]
Hello Marcel,

I have upgraded to 3,2,1 and also manually enabled WASM mode and I indeed get Node.js warning:
`Could not execute the Node.js binary. You may need to set the path to a working binary manually. `
and consequently I also get an error:
` An error occurred during face recognition, please check the Nextcloud logs. `
followed by another warning:
` Face recognition: 13822 Queued files, Last classification: 1.1.1970 `
=> although no classifiction had happened yet.

I'll dig into how to install a running Node.js later.

Thanks for your effort plus a nice evening,

tullsta

**Comment by tullsta2** [comment]
Hello Marcel,

after reading through some older posts (https://github.com/nextcloud/recognize/issues/65) I ended up trying
`root@serv:~# sudo docker exec -i -u www-data nextcloud /var/www/html/custom_apps/recognize/bin/node --version`

which resulted in 

`OCI runtime exec failed: exec failed: unable to start container process: exec /var/www/html/custom_apps/recognize/bin/node: permission denied: unknown`

if I understand one of your previous answers , this should point to an install issue?

Thanks and kind regards - tullsta

**Comment by marcelklehr** [comment]
> OCI runtime exec failed: exec failed: unable to start container process: exec /var/www/html/custom_apps/recognize/bin/node: permission denied: unknown
What happens if you run ldd inside the docker container?

**Comment by tullsta2** [comment]
running
`ldd --version `
as root reveals
```ldd (Debian GLIBC 2.31-13+deb11u5) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.```

**Comment by marcelklehr** [comment]
Mh, not sure what's up with that. You can try installing node.js v14 manually inside the container and pointing recognize to the node binary manually in the admin settings. Hopefully that'll work.

**Comment by tullsta2** [comment]
Hi - after some break at least a small step forward
I copied node binary downloaded from "nodejs.org/download/release/v14.21.1/" to an executable path and set the node.js path to point to this binary.
As a result I got all green lights in the admin settings page.
also "node --version" worked => v14.21.1

Nevertheless, I was then set back with an error:

`Warning	recognize	Classifier process output: /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6452 throw ex; ^ RuntimeError: memory access out of bounds at <anonymous>:wasm-function[483]:0x3cfb8 at <anonymous>:wasm-function[482]:0x3cd98 at malloc (<anonymous>:wasm-function[484]:0x3d0a0) at BackendWasm.move (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6940:38) at BackendWasm.write (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6914:14) at BackendWasm.makeOutput (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7031:27) at Object.resizeBilinear [as kernelFunc] (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:3976:23) at kernelFunc (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4623:32) at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4683:27 at Engine.scopedRun (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4488:23)
`
If anyone has an idea how to proceed... any suggestion welcome :)

Thanks and kind regards - tullsta

**Comment by phil-lipp** [comment]
I am getting the same error as @tullsta2 since updating to 3.2.3

**Comment by marcelklehr** [comment]
> memory access out of bounds at <anonymous>:wasm-function

That's a known bug that I'm still investigating #508
