### ISSUE TITLE
stuck at recognizing objects, can I review a log to find the problematic file

### ISSUE THREAD

**Issue by htc1977** [nextcloud/recognize#474]
**Describe the bug**
After recognizing about 2500+ files, the process tries to recognize the same file over and over again, without moving forward.
There are still 2500+ faces and 100 videos left for classification, but every cron job running I do see a spike in CPU usage and the "last classification" time for object recognition gets set correctly and that's it ...
I'd like to see, which file it tries to classify so I can decide whether to "repair" or delete this picture.

**To Reproduce**
1. start a cron-job via console
2. see the cpu usage via top and verify the classifier_imagenet.js is running
3. see that afterwards the classifier_landmarks.js is running
4. wait for the process to end
5. check the queded files count
6. nothing except the last classification time changed

**Expected behavior**
Skipping the file and move forward or print an error message with the filename and full path for further examination.

**Recognize (please complete the following information):**
 - JS-only mode: YES
 - Enabled modes: object detection, face recognition, landmark recognition, music genre recognition, video human action recognition

**Server (please complete the following information):**
 - Nextcloud: [e.g. 25.0.1]
 - OS: docker on Synology
 - RAM: 32 GB on Synology - 8 GB max for this docker
 - Processor Architecture AMD Ryzen V1500B

**Additional context**
After deactivating the landmark recognition, the queded files counter went to zero, but all other queues don't get processed.
Are there any logs and where can I activate and find them?

_**Update 2022-11-10 08:23 UTC**_
I pressed the recrawl button and after about 20 hours of work, it's stuck again.
3869 faces, 336 objects, 70 music genres and 145 videos left.
Last classification on objects some seconds ago, gets updated every 10 minutes (when cron is running), a short high CPU usage and that's it ... the files in the queue are not getting any smaller.

**Comment by htc1977** [comment]
It would be enough for me to have a log file to see which picture is being classified atm.
An enhanced stats counter page could then be "the crowning glory". :smile:

**Comment by marcelklehr** [comment]
> It would be enough for me to have a log file to see which picture is being classified atm.

Great idea!

**Comment by htc1977** [comment]
Now, it doesn't move forward and doesn't even update the last classification time anymore.
Cron is running every 10 minutes and I don't see any new recognize entries in the nextcloud.log (loglevel 0) anymore.
![image](https://user-images.githubusercontent.com/6369358/201337086-12fe8700-5850-4bb2-a93d-c183757055a6.png)
