### ISSUE TITLE
Reprocessed all removed persons after updating app

### ISSUE THREAD

**Issue by adrianog91** [nextcloud/recognize#484]
**Describe the bug**
After the first update made of the app to version 3.2.1. All the photos were also reprocessed of the people I had removed for two days and I found them all again.

**To Reproduce**
1. Update app to next version (3.2.1)

**Expected behavior**
In my opinion reprocessing should not reprocess the photos of the people removed as well. Especially following an update. At the most through a precise functionality

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud: 25.0.1
 - OS: Rasbian
 - RAM: 4GB
 - Processor Architecture: ARM64,

**Additional context**
After the first update made of the app to version 3.2.1. All the photos were also reprocessed of the people I had removed for two days and I found them all again. In my opinion reprocessing should not reprocess the photos of the people removed as well. Especially following an update. At the most through a precise functionality

**Comment by htc1977** [comment]
Same here ... :point_left:

**Comment by gmeks** [comment]
I used the Remove person to make it reproccess it. Because it had grouped like 15 people in bad person. So if this feature is intented to permanly hide a person then perhaps the feature should have a different name.

**Comment by marcelklehr** [comment]
> All the photos were also reprocessed

Thank you for reporting this and for your patience. The next release will not reprocess on update.
