### ISSUE TITLE
Batch size settings don't save and apply

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#485]
![image](https://user-images.githubusercontent.com/40355982/201470701-4deb5882-d0f9-4e6b-b55f-e138be0b2941.png)

Batch size numbers don't save on unfocus or enter and reset on page reload (i think it only saves if you toggle the classifier check) 

They also don't seem to get applied to running jobs (not the currently running job of course, but the entire schedule. I guess it will only apply on recrawl)

Not 100% on those as i didn't have much time to test, so if someone has more details and wants to chime in, please go ahead

**Comment by marcelklehr** [comment]
v3.2.1 should fix this
