### ISSUE TITLE
[FR] Paginate faces page

### ISSUE THREAD

**Issue by AbelLykens** [nextcloud/recognize#486]
Cool app! On my instance, there are thousands of recognized faces. Would be nice if the `/apps/photos/faces` were paginated. Loading thousands of thumbnails takes a while ;)

**Comment by marcelklehr** [comment]
Yep, that's been implemented and is waiting for the next release :)

**Comment by AbelLykens** [comment]
Are you sure @marcelklehr ? I'm on 3.2.3 now, don't see pagination :wink:

**Comment by marcelklehr** [comment]
Sorry, I wasn't clear. The photos app is the app you need to wait for :)
