### ISSUE TITLE
Warnings loop: OCP\Files\NotFoundException

### ISSUE THREAD

**Issue by ChiragSukhala** [nextcloud/recognize#488]
Logs are filled with Recognize warnings, and Last classification was 19 hours ago.
A Log:
`
[recognize] Warning: OCP\Files\NotFoundException:  at <<closure>>

 0. /var/www/nextcloud/lib/private/Preview/Generator.php line 162
    OC\Preview\Generator->getMaxPreview()
 1. /var/www/nextcloud/lib/private/Preview/Generator.php line 114
    OC\Preview\Generator->generatePreviews()
 2. /var/www/nextcloud/lib/private/PreviewManager.php line 185
    OC\Preview\Generator->getPreview()
 3. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 196
    OC\PreviewManager->getPreview()
 4. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 65
    OCA\Recognize\Classifiers\Classifier->getConvertedFilePath()
 5. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php line 78
    OCA\Recognize\Classifiers\Classifier->classifyFiles()
 6. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php line 37
    OCA\Recognize\Classifiers\Images\ClusteringFaceClassifier->classify()
 7. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 64
    OCA\Recognize\BackgroundJobs\ClassifyFacesJob->classify()
 8. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php line 29
    OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
 9. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
    OCA\Recognize\BackgroundJobs\ClassifyFacesJob->run()
10. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
11. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
12. /var/www/nextcloud/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

at 2022-11-12T18:05:04+00:00
`

**Suspects**
Preview Generator is breaking for:
- panorama pictures (known [bug](https://github.com/nextcloud/previewgenerator/issues/128))
- high resolution pictures ~>20MB 	9248 x 6944

I suspect same files are breaking recognize.

**Expected behavior**
atleast it should not end up in a loop, and just move on in queue.

**Recognize: 3.2.1**
 - JS-only mode: No
 - Enabled modes: face recognition

**Server:**
 - Nextcloud: 25.0.1
 - OS: Linux / LXC container on Proxmox
 - RAM: 4GB
 - Processor Architecture: x86

**Comment by marcelklehr** [comment]
> panorama pictures (known https://github.com/nextcloud/previewgenerator/issues/128)

Well, that sucks :/

**Comment by matthewparkes** [comment]
I am seeing this in the logs after updating to recognize: 3.2.1
I did get a could not create folder message in the logs.

**Comment by Cebrain** [comment]
I have the same problem. Is this really only related to the panorama pictures?
The problem startet with 3.2.1

**Comment by ChiragSukhala** [comment]
I guess it more than panorama pictures, I have disabled recognize: 3.2.1 tasks. 
Waiting for next patch version.

**Comment by Cebrain** [comment]
@marcelklehr could we reopen this?

**Comment by matthewparkes** [comment]
Please reopen, I'm not sure how to see which images are causing the problem.

**Comment by reox** [comment]
Not sure if this is related, but I see several of these errors before I see the Warning with NotFound:
```
[PHP] Fehler: Error: getimagesize(): corrupt JPEG data: 13 extraneous bytes before marker at /var/www/nextcloud/lib/private/legacy/OC_Image.php#598 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /var/www/nextcloud/lib/private/legacy/OC_Image.php line 598
    getimagesize()
 2. /var/www/nextcloud/lib/private/legacy/OC_Image.php line 665
    OC_Image->checkImageSize()
 3. /var/www/nextcloud/lib/private/Preview/Image.php line 52
    OC_Image->loadFromFile()
 4. /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php line 65
    OC\Preview\Image->getThumbnail()
 5. /var/www/nextcloud/lib/private/Preview/Generator.php line 343
    OC\Preview\GeneratorHelper->getThumbnail()
 6. /var/www/nextcloud/lib/private/Preview/Generator.php line 162
    OC\Preview\Generator->getMaxPreview()
 7. /var/www/nextcloud/lib/private/Preview/Generator.php line 114
    OC\Preview\Generator->generatePreviews()
 8. /var/www/nextcloud/lib/private/PreviewManager.php line 185
    OC\Preview\Generator->getPreview()
 9. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 196
    OC\PreviewManager->getPreview()
10. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 65
    OCA\Recognize\Classifiers\Classifier->getConvertedFilePath()
11. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php line 78
    OCA\Recognize\Classifiers\Classifier->classifyFiles()
12. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php line 37
    OCA\Recognize\Classifiers\Images\ClusteringFaceClassifier->classify()
13. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 64
    OCA\Recognize\BackgroundJobs\ClassifyFacesJob->classify()
14. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php line 29
    OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
15. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
    OCA\Recognize\BackgroundJobs\ClassifyFacesJob->run()
16. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
17. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
18. /var/www/nextcloud/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

at 2022-11-16T06:25:05+00:00
```

I know that there are several corrupted jpegs on my nextcloud - I have already checked with `jpeginfo -c`. But there are also panoramic pictures that already have issues with the preview-generator.

NC 25.0.1 / recognize 3.2.1

**Comment by reox** [comment]
Yep, for me too. I saw the jpeg error only once for all the corrupt images after the update and the images were removed from the queue.

**Comment by Cebrain** [comment]
Is it possible to find this broken images?

**Comment by reox** [comment]
> Is it possible to find this broken images?

I used
```
find /var/www/nextcloud/data/$username -iname \*.jpg -o -iname \*.jpeg -exec jpeginfo -c {} + | grep '[ERROR]'
```
