### ISSUE TITLE
NOT tagging local storage photos

### ISSUE THREAD

**Issue by ollioddi** [nextcloud/recognize#494]
**Describe the bug**
I see that there is a couple of issues regarding external storage, but it is unclear to me what the conclusion is, and if this is a bug or a "feature".

I have mounted a local folder containing Photos within Nextcloud as "Local storage".
![image](https://user-images.githubusercontent.com/7466744/201713163-1be7962f-2547-49a3-b186-60c0559267b0.png)

This works as expected and i can browse any photo.

 I noticed that recent fixes to batch size and processing (Thank you Marcel) made huge improvements to recognition, but that progress has been stuck for a while now.
![image](https://user-images.githubusercontent.com/7466744/201713025-73a6d38b-058d-4ca1-a578-9d8d54f9e09f.png)

I took a look at the tagged photos, and noticed that the only pictures which were tagged, were located within Nextcloud itself - No external Photos were tagged, resulting in the large queue of non processed images.

**To Reproduce**
1. Enable recognize
2. Use "local external storage"
3. Check tags of local local files and external local files

**Expected behavior**
External files are tagged and processed.

**Recognize (please complete the following information):**
 - JS-only mode: No
 - Enabled modes: All

**Server (please complete the following information):**
 - Nextcloud: Nextcloud Hub 3 (25.0.1)
 - Recognize: 3.2.1
 - OS: [Unraid Docker]
 - RAM: [32 GB]
 - Processor Architecture x86

**Comment by GuiPoM** [comment]
> I cannot reproduce this. When I mount an external storage recognize tags the photos correctly in my tests.

Hello @marcelklehr ,

I am also having no photo tagged, and I also use local External Storage. Is there any check I can make on my side to add more information to that issue and try to figure out why none of my photos are tagged ? 

Nextcloud: Nextcloud 25.0.1
Recognize: 3.2.1
OS: openmediavault docker Linux 6.0.0-0.deb11.2-amd64 x86_64
CPU : Intel(R) Pentium(R) Gold G6400 CPU @ 4.00GHz (4 cores)
Mémoire : 16 GB

**Comment by marcelklehr** [comment]
Versions before v3.2.3 likely had a bug involving storage IDs, it could be that updating to the latest version and starting from scratch fixes this for you

**Comment by GuiPoM** [comment]
I just updated to 25.0.2 and latest version of photos and recognize. It seems to now scan the directory as I can see people in the list. I now face another issue when I try to merge entries, but this is another story. So I guess that it is solved on my side !
