### ISSUE TITLE
Newly added files are not classified

### ISSUE THREAD

**Issue by fa0311** [nextcloud/recognize#495]
**Describe the bug**
Files added after the StorageCrawlJob has finished are not added to the queue.

**To Reproduce**

**Expected behavior**

**Recognize (please complete the following information):**

**Server (please complete the following information):**

**Additional context**
The result of the `SELECT COUNT(*) FROM oc_jobs WHERE class LIKE '%Recognize%';` run is 0.
Is there a way to automatically add them to the queue without running `occ recognize:recrawl`?

**Comment by marcelklehr** [comment]
There is a file listener that should add them to the queue: https://github.com/nextcloud/recognize/blob/master/lib/Hooks/FileListener.php#L97

**Comment by fa0311** [comment]
This is a server bug and is therefore closed.
https://github.com/nextcloud/server/issues/34958

**Comment by fa0311** [comment]
> https://github.com/nextcloud/recognize/blob/master/lib/Hooks/FileListener.php#L97

Not directly related to this Issues, but does this respect `.nomedia`?

**Comment by marcelklehr** [comment]
> Not directly related to this Issues, but does this exclude .nomedia?

Good point! It does not currently.

**Comment by marcelklehr** [comment]
see https://github.com/nextcloud/recognize/pull/497
