### ISSUE TITLE
3.2.2 - nodejs installation incompleted

### ISSUE THREAD

**Issue by markuman** [nextcloud/recognize#502]
**Describe the bug**  
With version 3.2.2 the nodejs version is incompleted

```
m@atom:/var/www/nextcloud$ sudo ls -l /var/www/nextcloud/apps/recognize/bin//node
ls: cannot access '/var/www/nextcloud/apps/recognize/bin//node': No such file or directory
m@atom:/var/www/nextcloud$ sudo ls -l /var/www/nextcloud/apps/recognize/bin/
total 25092
-rw-rw---- 1 www-data www-data 25688731 Nov 17 20:10 x64.tar.gz
```
![Bildschirmfoto vom 2022-11-17 21-13-56](https://user-images.githubusercontent.com/3920157/202549895-a4d7b8b0-79be-477e-97ae-77ab7c4d06e2.png)

**To Reproduce**
1. install
```
sudo -u www-data php occ app:install recognize -vvv
recognize 3.2.2 installed
recognize enabled
```

2. Goto admin menu an see the error
3. verify

```
sudo file /var/www/nextcloud/apps/recognize/bin/node
/var/www/nextcloud/apps/recognize/bin/node: cannot open `/var/www/nextcloud/apps/recognize/bin/node' (No such file or directory)
```

**Expected behavior**

**Recognize (please complete the following information):**
 - Installed app version: 3.2.2
 - WASM mode: Yes
 - Enabled modes: object detection

**Server (please complete the following information):**
 - Nextcloud version: 25.0.1
 - OS: Ubuntu 22.04
 - Docker container (if applicable): no
 - RAM: 8 GB
 - Processor Architecture: x64_64 (_Intel(R) Atom(TM) x5-Z8350_), no AVX

**Additional context**

**Comment by markuman** [comment]
> m@atom:/var/www/nextcloud$ sudo ls -l /var/www/nextcloud/apps/recognize/bin/
> total 25092
> -rw-rw---- 1 www-data www-data 25688731 Nov 17 20:10 x64.tar.gz

as seen here https://github.com/nextcloud/recognize/compare/v3.2.1...v3.2.2#diff-1084cd25e518e495532cb5c908f7b09e7747b83e7e9e6bfec0dbcf33d112af0aR156  
the file is downloaded successfully, but not extracted anymore

So something is wrong here https://github.com/nextcloud/recognize/compare/v3.2.1...v3.2.2#diff-1084cd25e518e495532cb5c908f7b09e7747b83e7e9e6bfec0dbcf33d112af0aR164

**Comment by markuman** [comment]
Unfortunately, there is no error while installing ...

**Comment by markuman** [comment]
yes, the installation is successfull here too. No error message. but anyway, the nodejs setup is incompletet.

**Comment by markuman** [comment]
hmmm after removing again, and also drop all recognize tables this time, the reinstall of 3.2.2 was successfull. No idea what's going wrong.

**Comment by davekopecek** [comment]
I'm having what appears to be a similar issue with a new install of 3.3.2.  `node` is present in `..apps/recognize/bin` but is not recognized:


admin@nextcloud /var/www/nextcloud/apps/recognize/bin
└─ # ls -al
total 108882
drwxr-xr-x  2 www-data www-data        4 Nov 24 15:38 .
drwxr-xr-x 12 www-data www-data       18 Nov 24 15:52 ..
-rwxr-xr-x  1 www-data www-data 76346528 Nov 24 15:38 node
-rw-r--r--  1 www-data www-data 34958062 Nov 24 15:38 x64.tar.gz


The following was in my nextcloud log:


Error	PHP	Error: chmod(): No such file or directory at /var/www/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#119		32 minutes ago
Error	PHP	Error: chmod(): No such file or directory at /var/www/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#119		32 minutes ago
Error	PHP	Error: chmod(): No such file or directory at /var/www/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#119		32 minutes ago
Error	index	OCP\Files\NotPermittedException: Could not create folder		35 minutes ago
