### ISSUE TITLE
An error occurred during object recognition, please check the Nextcloud logs.

### ISSUE THREAD

**Issue by markuman** [nextcloud/recognize#503]
**Describe the bug**

On a fresh recognize installation on nextcloud 25.0.1, base on intel atom cpu (wasm, no avx), recognize just mentioned in the admin menu

> An error occurred during object recognition, please check the Nextcloud logs.

Items are queued, but not classified.  
And there is no `recognize` in the nextcloud log.

```
m@atom:/var/www/nextcloud$ sudo grep -i recognize data/nextcloud.log 
m@atom:/var/www/nextcloud$ 

```

Nodejs is working fine

```
m@atom:/var/www/nextcloud$ sudo -u www-data apps/recognize/bin/node 
Welcome to Node.js v14.18.2.
Type ".help" for more information.
> 
```

Manuell trigger of the classification does not exist anymore in recognize 3.x  
It's unclear how to debug this.

**To Reproduce**

**Expected behavior**

**Recognize (please complete the following information):**
 - Installed app version:3.2.2
 - WASM mode: yes
 - Enabled modes:  object detection

**Server (please complete the following information):**
 - Nextcloud version: 25.0.1
 - OS: Ubuntu 22.04
 - Docker container (if applicable):
 - RAM: 8GB
 - Processor Architecture: x86_64 intel atom

**Additional context**

**Comment by JohnXLivingston** [comment]
I have a similar issue.
I can see these error logs:

```log
  | OC\Encryption\Exceptions\DecryptionFailedException: Cannot decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.
```

I have enable the backend encryption.
I assume this application can't work when encryption is activated?

Perhaps you have the same issue.

**Comment by markuman** [comment]
When I rollback to 2.2.2, everything works as expected ...

**Comment by marcelklehr** [comment]
> It's unclear how to debug this.

I recommend setting nextcloud log level to debug and looking for recognize messages

**Comment by marcelklehr** [comment]
You can also check the oc_jobs table for recognize classifier jobs.

**Comment by diyoyo** [comment]
Well, I don't know if we have the same problem, but while waiting for more information, I'd like to share this error log:

`Classifier process output: /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6452 throw ex; ^ RuntimeError: memory access out of bounds at <anonymous>:wasm-function[481]:0x3caca at <anonymous>:wasm-function[482]:0x3cecf at malloc (<anonymous>:wasm-function[484]:0x3d0a0) at BackendWasm.move (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6940:38) at BackendWasm.write (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6914:14) at BackendWasm.makeOutput (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7031:27) at Object.concat [as kernelFunc] (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:1670:23) at kernelFunc (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4623:32) at /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4683:27 at Engine.scopedRun (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4488:23)`

I rebooted my host and made sure there was enough memory, but recognize keeps generating the error!
Is there a way to clear some kind of cache or something.
There were about 20k pictures and it went down to 780 without problem. Now it's stuck on this error.

**Comment by marcelklehr** [comment]
@diyoyo You are likely experiencing #508
