### ISSUE TITLE
[FR] "CPU doesnt support AVX" rather than "Could not load libtensorflow in Node.js." ?

### ISSUE THREAD

**Issue by potagerGit** [nextcloud/recognize#506]
This is a Feature Request, maybe not a bug.

Hello, I have this message in the config panel : " Could not load libtensorflow in Node.js. You can try to manually install libtensorflow or run in WASM mode", then I tried to install manually TensorFlow (using "npm ci" in the www/nextcloud/apps/recognize directory).

But after some efforts, I realized that it is probably useless because my CPU ( Intel Celeron N3050) seems not to support AVX.
It should be better to tell "your CPU doesn't support AVX mode, only WASM is possible".

Note : after npm ci , I have been told of 4 high severity vulnerabilities.  Should I worry or uninstall something ?
![image](https://user-images.githubusercontent.com/115888982/202871775-aa7cd0b5-ef7f-44f3-b5fd-eba08bf88c03.png)

**Comment by marcelklehr** [comment]
> Should I worry or uninstall something ?

You don't need to worry, npm is overzealous.

> It should be better to tell "your CPU doesn't support AVX mode, only WASM is possible".

yeah, that makes sense. good iea
