### ISSUE TITLE
Feature request - intuitive face tagging

### ISSUE THREAD

**Issue by abctaylor** [nextcloud/recognize#507]
It is a slow process to always add contacts for each face, and then add a photo, in order to have facial recognition. It would be great if some UUID could be generated for each distinct face, and then a user can view a "faces" portal and give a name in place of a UUID for faces they've tagged.

Eg I might have a bunch of UUIDs for people in a crowd with my girlfriend in it and her friends. My GF is picked up as she already exists, the friends are too and get random UUIDs because we haven't classified them before, and the random dudes in the background might get some UUID as well. I don't care about these latter ones, so don't specify a name.

Great effort, this is a fantastic app in Nextcloud!

**Comment by marcelklehr** [comment]
> It would be great if some UUID could be generated for each distinct face, and then a user can view a "faces" portal and give a name in place of a UUID for faces they've tagged.

This is exactly what happens in Nextcloud 25 :)
