### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by hypervtechnics** [nextcloud/recognize#508]
**Describe the bug**
Face recognition is not running successfully.

**To Reproduce**
1. Activate face recognition
2. Wait...

**Expected behavior**
Green check marks everywhere ;)

**Recognize (please complete the following information):**
 - Installed app version: 3.2.2
 - WASM mode: Yes
 - Enabled modes: object detection, face recognition

**Server (please complete the following information):**
 - Nextcloud version: 25.0.1
 - OS: ubuntu
 - RAM: 8 GB
 - Processor Architecture: AMD64

**Additional context**

The only log entry I could find hinting towards an error:
```
 Debug    recognize          Classifier process output:                                     2022-11-19T23:46:25+00:00
                              /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6452

                                                  throw ex;
                                                  ^

                              RuntimeError: memory access out of bounds
                                  at <anonymous>:wasm-function[481]:0x3caca
                                  at <anonymous>:wasm-function[482]:0x3cecf
                                  at malloc (<anonymous>:wasm-function[484]:0x3d0a0)
                                  at BackendWasm.move
                              (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6940:38)

                                  at BackendWasm.write
                              (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6914:14)

                                  at BackendWasm.makeOutput
                              (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7031:27)

                                  at Object.concat [as kernelFunc]
                              (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:1670:23)

                                  at kernelFunc
                              (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4623:32)
                                  at
                              /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4683:27
                                  at Engine.scopedRun
                              (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4488:23)
```

![grafik](https://user-images.githubusercontent.com/10027956/202876101-0d2123e1-666a-403d-b3f8-502ec989d45b.png)

**Comment by hypervtechnics** [comment]
Can I provide any info or logs? Although the above entry was pretty hard to find.

What I tried in the mean time: Reduce the batch size from 50 to 20 for the face recognition. Did not help :(

**Comment by elr3m** [comment]
I have the same issue on 2 Nextcloud environments.
Everytime the facial recognition runs in the backgound, I get the "Memory out of bounds" error as well as the following:
`{"reqId":"REQID","level":3,"time":"2022-11-20T22:46:48+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"{\"Exception\":\"RuntimeException\",\"Message\":\"Classifier process error\",\"Code\":0,\"Trace\":[{\"file\":\"WHEREMYNCWEBFOLDERIS/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php\",\"line\":78,\"function\":\"classifyFiles\",\"class\":\"OCA\\\\Recognize\\\\Classifiers\\\\Classifier\",\"type\":\"->\"},{\"file\":\"WHEREMYNCWEBFOLDERIS/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php\",\"line\":37,\"function\":\"classify\",\"class\":\"OCA\\\\Recognize\\\\Classifiers\\\\Images\\\\ClusteringFaceClassifier\",\"type\":\"->\"},{\"file\":\"WHEREMYNCWEBFOLDERIS/apps/recognize/lib/BackgroundJobs/ClassifierJob.php\",\"line\":64,\"function\":\"classify\",\"class\":\"OCA\\\\Recognize\\\\BackgroundJobs\\\\ClassifyFacesJob\",\"type\":\"->\"},{\"file\":\"WHEREMYNCWEBFOLDERIS/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php\",\"line\":29,\"function\":\"runClassifier\",\"class\":\"OCA\\\\Recognize\\\\BackgroundJobs\\\\ClassifierJob\",\"type\":\"->\"},{\"file\":\"WHEREMYNCWEBFOLDERIS/lib/public/BackgroundJob/Job.php\",\"line\":78,\"function\":\"run\",\"class\":\"OCA\\\\Recognize\\\\BackgroundJobs\\\\ClassifyFacesJob\",\"type\":\"->\"},{\"file\":\"WHEREMYNCWEBFOLDERIS/lib/public/BackgroundJob/TimedJob.php\",\"line\":103,\"function\":\"start\",\"class\":\"OCP\\\\BackgroundJob\\\\Job\",\"type\":\"->\"},{\"file\":\"WHEREMYNCWEBFOLDERIS/lib/public/BackgroundJob/TimedJob.php\",\"line\":93,\"function\":\"start\",\"class\":\"OCP\\\\BackgroundJob\\\\TimedJob\",\"type\":\"->\"},{\"file\":\"WHEREMYNCWEBFOLDERIS/cron.php\",\"line\":152,\"function\":\"execute\",\"class\":\"OCP\\\\BackgroundJob\\\\TimedJob\",\"type\":\"->\"}],\"File\":\"WHEREMYNCWEBFOLDERIS/apps/recognize/lib/Classifiers/Classifier.php\",\"Line\":166,\"message\":\"Error while running background job (class: OCA\\\\Recognize\\\\BackgroundJobs\\\\ClassifyFacesJob, arguments: Array\\n(\\n    [storageId] => 274\\n    [rootId] => 5920278\\n)\\n)\",\"exception\":{},\"CustomMessage\":\"Error while running background job (class: OCA\\\\Recognize\\\\BackgroundJobs\\\\ClassifyFacesJob, arguments: Array\\n(\\n    [storageId] => 274\\n    [rootId] => 5920278\\n)\\n)\"}","userAgent":"--","version":"25.0.1.1"}`

Not sure if pasted line is related, but it shows up after every Memory out of bounds entry.
Looks like Background Job related?

**Comment by elr3m** [comment]
I installed TensorFlow on Staging env, and it now works (recent facial recongition according to NC/settings/admin/recognize.

Hope this helps if you can install Tensorflow

Gonna see if more faces shows.

**Comment by marcelklehr** [comment]
@hypervtechnics Could be related to ARM, although I see no reason why that WASM code should not work on ARM, that's why WASM exists after all.

**Comment by hypervtechnics** [comment]
The recognition itself works (some faces have been added) but does not continue now. Maybe it encountered a bad/corrupted file?

I corrected the architecture btw to be AMD64 instead of ARM. Was too tired at time of writing, sorry.

**Comment by marcelklehr** [comment]
> I corrected the architecture btw to be AMD64 instead of ARM. Was too tired at time of writing, sorry.

Ah, ok then :D 

This could be due to a memory leak in the tensorflow code. I'll see if I can update the face recognition library to possibly fix that.

**Comment by marcelklehr** [comment]
As a quickfix you might get farther by decreasing the batch size of the face recognition. (What do you have it set to currently?) Also, since it doesn't seem to continue classifying, can you check oc_jobs whether ClassifyFacesJob is still in there?

**Comment by hypervtechnics** [comment]
Thanks for your response 😄 . I reduced the batch size from 50 (default) to 20 and now to 10. Lets see if that helps.

Yes the job is still listed there:

```
| id    | class                                                           | argument                                                                                                                           | last_run   | last_checked | reserved_at | execution_duration | argument_hash                    | time_sensitive |
+-------+-----------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+------------+--------------+-------------+--------------------+----------------------------------+----------------+
| 31198 | OCA\Recognize\BackgroundJobs\ClassifyFacesJob                   | {"storageId":2,"rootId":5}                                                                                                         | 1669057202 |   1669057501 |           0 |                176 | REDACTED                         |              0 |
| 31221 | OCA\Recognize\BackgroundJobs\ClassifyImagenetJob                | {"storageId":2,"rootId":5}                                                                                                         | 1669057220 |   1669057502 |           0 |                 77 | REDACTED                         |              0 |
```

I redacted the argument_hash. Don't know if that is actually needed tho 😆. The last_run timestamp shows the last time the background jobs were triggered. Just give me a short ping if you need more information 😄

**Comment by vanantwerp** [comment]
I also believe I am encountering this issue, happy to provide any info I can to help.

Recognize:
    Installed app version: 3.2.3
    WASM mode: Yes
    Enabled modes: face recognition

Server:
    Nextcloud version: 25.0.1
    OS: Docker / Alpine

**Comment by MrRusch** [comment]
I am getting this error as well.

Recognize:
Installed app version: 3.2.3
WASM mode: Yes
Enabled modes: face recognition

Server:
Nextcloud version: 25.0.1
OS: FreeBSD 12.3-RELEASE-p5

I tried tuning it down to 20 files per 5 min job start. It processes some 5000 files and then stops completely with the above reported error in log.

**Comment by tullsta2** [comment]
Hi,

upgraded to NC 25.0.2 plus recognize 3.3.0 and reduced the number of files per job to 1.
Regarding node: I copied the node-binary (v14.17.6) to a place in the path but still get  a 
RuntimeError: memory access out of bounds at <anonymous>:wasm-function[486]...

Pls. let me knwo if t here is anything I could/should look at / debug.

kind regards - tullsta

**Comment by Regardo** [comment]
I am getting this error as well.

Recognize:
Installed app version: 3.3.1
WASM mode: Yes
Enabled modes: face recognition

Server:
Nextcloud version: 25.0.2
OS: Alpine 3.15

How I bypass it:

1. From the database, I got the ID of the first file from the queue for face recognition.

    `SELECT * From oc_recognize_queue_faces`

![image](https://user-images.githubusercontent.com/65348387/206904936-68298fe2-2edc-4ff3-8dbe-03b489d672c4.png)

2. We are looking for a file with the first file_id:

    `SELECT * FROM oc_filecache WHERE fileid = 30530`

![image](https://user-images.githubusercontent.com/65348387/206905170-94726e4b-a255-465a-ba96-0200cb902a0c.png)
This file turned out to be a panorama with a resolution of 10778x3315

3. I moved this file to another folder with `.nomedia` and delete the entry with the id of this file from the table of the recognition queue (`oc_recognize_queue_faces`)

Recognition continued again (I think until the next panorama)

Suggestion for a workaround for this issue:
   - Before recognition, check the aspect ratio of the photo. If more let's say 2 then photo will not be sent to face recognition
   - use a different face recognition model that supports working with panoramas

**Comment by nonofr91** [comment]
Hello,
I also get error messages in my logs. I deleted the panaramic photo (which does not display a thumbnail for info). I reset the tags. And now no more messages.

{"reqId":"T7ZSQoqwd7fnEfTGCBqt","level":3,"time":"2022-12-11T13:40:10+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 118\n)\n)","userAgent":"--","version":"25.0.2.3","exception":{"Exception":"RuntimeException","Message":"Classifier process error","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php","line":79,"function":"classifyFiles","class":"OCA\\Recognize\\Classifiers\\Classifier","type":"->"},{"file":"/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":41,"function":"classify","class":"OCA\\Recognize\\Classifiers\\Images\\ClusteringFaceClassifier","type":"->"},{"file":"/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php","line":70,"function":"classify","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":33,"function":"runClassifier","class":"OCA\\Recognize\\BackgroundJobs\\ClassifierJob","type":"->"},{"file":"/config/www/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/config/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/config/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php","Line":169,"message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 118\n)\n)","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 118\n)\n)"}}

**Comment by marcelklehr** [comment]
Mh. How large are these panorama image files in MB?

**Comment by tullsta2** [comment]
Hello, Panorama files I gave are around 15 MB (11450x3628).Kind regards - tullstaAm 11.12.22 um 17:09 schrieb Marcel Klehr
                
            
            
                
                    Von: "Marcel Klehr" ***@***.***>Datum: 11. Dezember 2022An: "nextcloud/recognize" ***@***.***>Cc: "tullsta2" ***@***.***>,"Comment" ***@***.***>Betreff: Re: [nextcloud/recognize] RuntimeError: memory access out of bounds (Issue #508)
                
                
Mh. How large are these panorama image files in MB?

**Comment by marcelklehr** [comment]
Recognize should resize all images to at max 1024x1024 pixels and should not run images through the classifier that are larger than 8MiB.

**Comment by Regardo** [comment]
I had problems because of this file
[Panorama3.zip](https://github.com/nextcloud/recognize/files/10202649/Panorama3.zip)

**Comment by hypervtechnics** [comment]
As an addition: Can't the engine also be refined to not abort and continue with the next item in the queue after a detection did not work successfully?

**Comment by marcelklehr** [comment]
When an error occurs it is IMHO safer to abort the classifier process. It could be restarted of course. I'll think about it

**Comment by marcelklehr** [comment]
I've added a constraint to avoid images that are larger than 1024x1024

**Comment by hypervtechnics** [comment]
Thank you! 😄

**Comment by tullsta2** [comment]
yep - thanks a lot Marcel and Regardo!

**Comment by phil-lipp** [comment]
> I've added a constraint to avoid images that are larger than 1024x1024

I'm still getting the Memory out of Bounds error after updating Nextcloud to 25.0.2 and Recognize to 3.3.3. From what I can gather it's only the face recognition failing, the object recognition (imagenet) is working fine. On a side note: I noticed that my admin interface for recognize seems kinda buggy as well recently. The number of files to be classified for imagenet doesnt reduce even tho the job is running and I can see (within the activity section of nextcloud) that files are being tagged.



Here's a snippet of my nextcloud.log:

`(
    [storageId] => 3
    [rootId] => 170
)
)","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array
(
    [storageId] => 3
    [rootId] => 170
)
)"}}
{"reqId":"TWyQvsADeSXk0JQqprrE","level":2,"time":"2022-12-15T10:20:26+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6492
                    throw ex;
                    ^

RuntimeError: memory access out of bounds
    at <anonymous>:wasm-function[486]:0x3d25d
    at <anonymous>:wasm-function[485]:0x3d09b
    at malloc (<anonymous>:wasm-function[487]:0x3d3a3)
    at BackendWasm.move (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6982:38)
    at BackendWasm.write (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:6956:14)
    at BackendWasm.makeOutput (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:7073:27)
    at Object.resizeBilinear [as kernelFunc] (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:4012:23)
    at kernelFunc (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4623:32)
    at /var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4683:27
    at Engine.scopedRun (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4488:23)
","userAgent":"--","version":"25.0.2.3","data":{"app":"recognize"}}
{"reqId":"TWyQvsADeSXk0JQqprrE","level":3,"time":"2022-12-15T10:20:26+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array
(
    [storageId] => 3
    [rootId] => 170
)
)","userAgent":"--","version":"25.0.2.3","exception":{"Exception":"RuntimeException","Message":"Classifier process error","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php","line":79,"function":"classifyFiles","class":"OCA\\Recognize\\Classifiers\\Classifier","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":41,"function":"classify","class":"OCA\\Recognize\\Classifiers\\Images\\ClusteringFaceClassifier","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php","line":70,"function":"classify","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":33,"function":"runClassifier","class":"OCA\\Recognize\\BackgroundJobs\\ClassifierJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php","Line":169,"message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array
(
    [storageId] => 3
    [rootId] => 170
)
)","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array
(
    [storageId] => 3
    [rootId] => 170
)
)"}}`

**Comment by marcelklehr** [comment]
It seems this may be a problem with tensorflow.js https://github.com/tensorflow/tfjs/issues/6439

**Comment by vanantwerp** [comment]
@marcelklehr to confirm - that means any fix is blocked by the tensorflow.js dependency? is there anything we can do to support this upstream?

**Comment by marcelklehr** [comment]
> is there anything we can do to support this upstream?

I doubt it :/

**Comment by teewhey** [comment]
I'm getting this error in Nextcloud log and Recognize doesn't seem to be functioning at the moment.

Classifier process output: Initialization of backend wasm failed RuntimeError: memory access out of bounds at __wasm_call_ctors (<anonymous>:wasm-function[7]:0x103e) at callRuntimeCallbacks (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8803:34) at initRuntime (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8726:38) at doRun (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:9035:25) at run (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:9041:17) at runCaller (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:9027:17) at removeRunDependency (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8748:21) at receiveInstance (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8786:393) at receiveInstantiationResult (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8786:484) Error: The highest priority backend 'wasm' has not yet been initialized. Make sure to await tf.ready() or await tf.setBackend() before calling other methods at Engine.get (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4314:27) at Engine.makeTensor (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4845:35) at makeTensor (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5734:19) at tensor (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5925:12) at decodeWeights (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:6354:29) at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:25476:55 at Array.forEach (<anonymous>) at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:25474:44 at Array.forEach (<anonymous>) at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:25470:45) Initialization of backend wasm failed RuntimeError: memory access out of bounds at __wasm_call_ctors (<anonymous>:wasm-function[7]:0x103e) at callRuntimeCallbacks (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8803:34) at initRuntime (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8726:38) at doRun (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:9035:25) at run (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:9041:17) at runCaller (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:9027:17) at removeRunDependency (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8748:21) at receiveInstance (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8786:393) at receiveInstantiationResult (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.node.js:8786:484) 

Any idea if this still has dependency with TF upstream?

**Comment by 4bgt** [comment]
I am running into exactl the same error.
