### ISSUE TITLE
Files are not added to the Queue, no images are classified

### ISSUE THREAD

**Issue by p-atr** [nextcloud/recognize#510]
**Describe the bug**
The app just does nothing at all. There are many images on this instance, but none of them get added to the queue. Reinstalling the app does not fix the issue. Initially, about 30 Photos were classified, then it just stopped doing anything. Running all the available occ recognize commands also does not help.

**To Reproduce**
1. Install Recognize
2. Wait for Pictures to be added to the queue
3. nothing happens

**Expected behavior**
Images get recognized

**Recognize (please complete the following information):**
 - Installed app version: v3.2.2
 - WASM mode: No
 - Enabled modes: face recognition

**Server (please complete the following information):**
 - Nextcloud version: 25.0.1
 - OS: Ubuntu 22.04
 - RAM: 16GB
 - Processor Architecture: x86_64

**Additional context**
App config:
`"recognize": {
            "enabled": "yes",
            "faces.batchSize": "5",
            "faces.enabled": "true",
            "faces.lastFile": "1668711743",
            "faces.status": "true",
            "imagenet.batchSize": "100",
            "imagenet.enabled": "false",
            "installed_version": "3.2.2",
            "landmarks.batchSize": "100",
            "landmarks.enabled": "false",
            "movinet.batchSize": "5",
            "movinet.enabled": "false",
            "movinet.lastFile": "1668720710",
            "movinet.status": "true",
            "musicnn.batchSize": "100",
            "musicnn.enabled": "false",
            "node_binary": "\/var\/www\/nextcloud\/apps\/recognize\/bin\/node",
            "tensorflow.cores": "0",
            "tensorflow.gpu": "false",
            "tensorflow.purejs": "false",
            "types": "filesystem,dav"
        }`

The tables `[oc_recognize_face_clusters, oc_recognize_face_detections, oc_recognize_queue_faces, oc_recognize_queue_imagenet, oc_recognize_queue_landmarks, oc_recognize_queue_movinet, oc_recognize_queue_musicnn]` are all empty.

**Comment by marcelklehr** [comment]
Are you running cron jobs on your system?

**Comment by shoaib42** [comment]
@p-atr Hit the same issue, and the issue was not running [cron](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html) . After you enable cron (first set to use cron from administration > Basic settings > Background jobs section), it is set to use AJAX by default. And after you have the cron entry for the `www-data` user. Next you'll have to deselect all the options you had in recognize (faces, landmarks etc), and switch them back again. This worked for me.

@marcelklehr Would be nice if this was documented, that cron is needed.

**Comment by marcelklehr** [comment]
@shoaib42 Good point! I'll draw up a PR for that :)

**Comment by p-atr** [comment]
I am actually already running cron, and I just noticed around 20 "hanging?" cronjobs from Nextcloud and a pretty high load average. Should I just keep them running for now and wait?  Or will they just run forever? There are still zero images in the queue, and no images got classified.

**Comment by shoaib42** [comment]
I don't see an issue on my end, things are progressing slowly, yes I do see high load, hope there was a way to really use the tensor cores that I've on the test environment, nividia-smi shows no load :/ . Its being processed by node only

**Comment by p-atr** [comment]
Just for clarification, this issue is not about speed at all. There are no node instances running on my system. The load seems to be caused by mariadb?, while the cron jobs are running. When I disable Recognize, and kill the currently running cronjobs, the load is gone.

fyi: the number of concurrently running cron.php decreased to 5, so they seem to exit at some point...

**Comment by marcelklehr** [comment]
@p-atr you are likely experiencing this issue: #505

**Comment by shoaib42** [comment]
@p-atr Did you confirm that the load is from mariadb? Can you check what top or nmon say on your system. If you can confirm that the load is from mariadb (chugging CPU), next step will be to enable slow query log and see what query is taking its sweet time, and why. Maybe you can try `mysqlcheck --analyze --databases nextcloud` hoping that an analyze will refresh stats.

**Comment by p-atr** [comment]
According to htop, the load came from mariadb. I could not stop the mariadb service either, I had to use SIGKILL. Running mysqlcheck only reported OK for all tables, not sure if it did anything else.

After restarting mariadb and manually running a StorageCrawlJob via occ, it classified about 2000 images. Now it's stuck again (several running cron.php, but no noticeable load on the database), with about 300 images in the queue, and the last classification was hours ago. I've created some xdebug performance profiles of some of the still running cron.php (I hope it's not a bad idea to share them publicly, otherwise please let me know...), maybe you can get more information from these files.
[https://www.dropbox.com/sh/ii7164wfmxr6ui0/AAAlQfkWx06AEn3QramdpnlDa](https://www.dropbox.com/sh/ii7164wfmxr6ui0/AAAlQfkWx06AEn3QramdpnlDa)

I restarted mariadb again (forcibly), which caused the cron.php processes to disappear.

This issue does indeed sound similar to #505, but I am not familiar enough with Nextcloud to determine this. If you would prefer to close this issue and follow up on the error in #505, that's fine with me.

**Comment by marcelklehr** [comment]
> I've created some xdebug performance profiles of some of the still running cron.php (I hope it's not a bad idea to share them publicly, otherwise please let me know...), maybe you can get more information from these files.

Thank you! These are most helpful!
