### ISSUE TITLE
Classifier process output: sh: exec: line 1: recognize/bin/node: not found

### ISSUE THREAD

**Issue by Venkman42** [nextcloud/recognize#511]
**Describe the bug**
Recognize isn't classifying files.
Files are in queue, but it wont classify anything.

Error in Log:
Recognize: 

> Classifier process output: sh: exec: line 1: /config/www/nextcloud/apps/recognize/bin/node: not found

Core:

> RuntimeException: Classifier process error/config/www/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php - line 78:OCA\Recognize\Classifiers\Classifier->classifyFiles()/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php - line 37:OCA\Recognize\Classifiers\Images\ClusteringFaceClassifier->classify()/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php - line 64:OCA\Recognize\BackgroundJobs\ClassifyFacesJob-

> classify()/config/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php - line 29:OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()/config/www/nextcloud/lib/public/BackgroundJob/Job.php - line 78:OCA\Recognize\BackgroundJobs\ClassifyFacesJob->run()/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 103:OCP\BackgroundJob\Job->start()/config/www/nextcloud/lib/public/BackgroundJob/TimedJob.php - line 93:OCP\BackgroundJob\TimedJob->start()/config/www/nextcloud/cron.php - line 152:OCP\BackgroundJob\TimedJob->execute()

--

**To Reproduce**
1. Install linuxserver\nextcloud on docker on raspberry pi
2. activate recognize
3. download models
4. activate face and object-recognition
5. activate wasm mode
6. set node.js binary to path /config/www/nextcloud/apps/recognize/bin/node (specific to linuxserver/nextcloud

**Expected behavior**
nextcloud starts classifying files

**Recognize (please complete the following information):**
 - Installed app version: 3.2.2
 - WASM mode: Yes
 - Enabled modes: object detection, face recognition, landmark recognition

**Server (please complete the following information):**
 - Nextcloud version: 25.0.1
 - OS: docker on raspberrypi OS
 - Docker container (if applicable): linuxserver/nextcloud
 - RAM: 2GB
 - Processor Architecture ARM64

**Additional context**
I also tried the official nextcloud container, but it didnt work either and I also had problems with cron. 
Thats why I used linuxserver/nextcloud.

THe path to node js I got from looking around inside the container, so it exists and is correct

**Comment by marcelklehr** [comment]
Does the admin settings page tell you anything about whether node.js is installed correctly (on the bottom)? for linuxserver/nextcloud your node.js executable needs to be built with musl instead of glibc. This is likely the problem.

**Comment by Venkman42** [comment]
> Does the admin settings page tell you anything about whether node.js is installed correctly (on the bottom)? for linuxserver/nextcloud your node.js executable needs to be built with musl instead of glibc. This is likely the problem. If you can, install node.js inside the container and point recognize to its location.

Yes, it says:
Could not execute the Node.js binary. You may need to set the path to a working binary manually.

Isn't there a way without installing it manually?
I mean I can see the path to ..../bin/node
Then I would also have to update it manually, right?

**Comment by marcelklehr** [comment]
By defult recognize tries to download the right node binary for you. Sometimes it may not be able to detect that you need a special one and gives you the default instead which then doesn't work. You can try using ldd ..../bin/node to check if you have a node that works with musl. Also try running it manually by with docker exec for example and it probably won't work. (Alternatively, it may be missing +x file attribute, but I doubt it.)

**Comment by Haplo164** [comment]
@marcelklehr this helped me a bunch, I don't know how the installed node stopped working but I swapped it out with a working install and bingo. I didn't have any mention of recognize in my logs so I just started clearing out databases thinking that was the problem. Oh well, at least I know how more of nextcloud works now. I would suggest adding the app's node install to a repair step so that `occ maintenance:repair` reinstalls it.

**Comment by jalin2** [comment]
I'm using linuxserver's nextcloud image and I believe I have this exact problem.  May I ask where to download the node.js binary that was built with musl?

**Comment by Haplo164** [comment]
@jalin2 I now believe there was no problem with the included binary, try changing the path to something else, then back to the included one and see if that gets it going.

**Comment by marcelklehr** [comment]
> The node is installed directly in /usr/bin. That means either I have to make the whole directory a persistend volume, or I have to execute this command every time i recreate the container. Any ideas?

```
cp /usr/bin/node apps/recognize/bin/
```

Might do the trick

**Comment by Venkman42** [comment]
@marcelklehr great idea, but doesnt work unfortnately after a rebuild of the container

**Comment by jalin2** [comment]
> @jalin2 I now believe there was no problem with the included binary, try changing the path to something else, then back to the included one and see if that gets it going.

Thanks.  I'm a bit confused since I don't see this error in the nextcloud logs anymore.  However, when I check the recognize settings, under node.js section I see see the warning "Could not load libtensorflow in Node.js. You can try to manually install libtensorflow or run in WASM mode. "

I ran "lld /config/www/nextcloud/apps/recognize/bin/node" in my nextcloud container and got the following output:
        /lib/ld-musl-x86_64.so.1 (0x7f1ee2a6e000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f1ede800000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f1ede7e6000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f1ee2a6e000)

I assume this means I have the correct binary since the linuxserver nextcloud is running alpine?

When I check the file properties "ls -alsh /config/www/nextcloud/apps/recognize/bin/node" I get the following:
73M -rwxrwxr-x 1 abc users 73M Nov 19 09:41 /config/www/nextcloud/apps/recognize/bin/node

So it looks like has the executable property already.  Perhaps I don't have this problem anymore?
