### ISSUE TITLE
Why it can't process large images ?

### ISSUE THREAD

**Issue by ereynier** [nextcloud/recognize#513]
I saw in Changelog a "bug fix" that remove the ability to process files over 8MiB. Why ? And is it possible to process larger files ?

**Comment by marcelklehr** [comment]
If an image is too large it will cause Out of Memory errors during classification. However, we use the preview generator to scale down large images to 1000x1000px, so they can still be processed.

**Comment by ereynier** [comment]
Oh yes I didn't notice my photos was tagged. My question is just for face recognition so. Only my old photos (light weight) was processed

**Comment by marcelklehr** [comment]
Maybe the newer photos are still in the queue? Or the preview generator didn't work for them, i don't know.

**Comment by ereynier** [comment]
How can I see the queue ? I checked in *settings/admin/recognize* it says "The app is installed and will automatically classify files in background processes." (maybe I don't know where to search 😕)

**Comment by marcelklehr** [comment]
if you have enabled any classifiers, you should get information about their work.

**Comment by ereynier** [comment]
In "Image tagging" section I have "Face recognition is working." and "Object recognition is working." with checkmark. That's it ? Because I don't see any work information or number of file processed...

**Comment by marcelklehr** [comment]
Which version do you have installed?

**Comment by ereynier** [comment]
3.2.2

**Comment by ereynier** [comment]
Thanks you for the quick update. I have a bug with the face recognition timer. Queued files passed from 27615 to 24622 in 4h30 but it still show "last classification 5 days ago".
The Object recognition seems to work properly updated about 5 to 10 min.

**Comment by marcelklehr** [comment]
> it still show "last classification 5 days ago".

Sorry for the delay, has this changed by now?

**Comment by ereynier** [comment]
That's good all photos are processed and the timer is updated but all the new photos I import  are not showing in "peoples" tab

**Comment by marcelklehr** [comment]
Mmh, do you import them into an external storage or directly into your home directory?

**Comment by ereynier** [comment]
Directly to home directory. Next to the photos which display properly

**Comment by marcelklehr** [comment]
Are they all the same file type?

**Comment by ereynier** [comment]
Same file type, same camera.
It was at "0 files in queue" then I stopped the "recognize face" and restart it after a day. Now it's "30000 files in queue"

**Comment by marcelklehr** [comment]
Which version of recognize do you have installed?

**Comment by ereynier** [comment]
3.2.3

**Comment by ereynier** [comment]
I have some "Face results for 38726 are in", "Remove file with existing faces from queue 38700", generating preview and moving to tmp. it's seems to work. I'll wait until the files are processed and see if there are displayed to "people" tab
