### ISSUE TITLE
Recognize does not find fils?

### ISSUE THREAD

**Issue by big1tasty** [nextcloud/recognize#518]
I just downloaded Recognize via App store because i run nextcloud on docker (apache)
When i want to use this feature i get this warning and nothing seem to work:
![image](https://user-images.githubusercontent.com/64231135/204306613-4b6bc60b-7b94-4e48-b02f-608bba07ee28.png)
![image](https://user-images.githubusercontent.com/64231135/204306684-45e6f494-b0d4-40ee-b87c-0c701484bac9.png)

**Comment by marcelklehr** [comment]
Are you executing Background jobs using cron? Have you checked the Nextcloud logs?

**Comment by big1tasty** [comment]
i have set that to cron but i am missing something, maby permissions issue for "www-data"?
which i am not sure how to set (i'm relatively new to docker)
![image](https://user-images.githubusercontent.com/64231135/204473380-bc842e7c-b13d-4759-8b1f-c236c7390b2e.png)

Here are the logs:
`{"reqId":"Q0ThHK9H34uoerofkH7g","level":3,"time":"2022-11-28T20:36:55+00:00","remoteAddr":"141.101.96.195","user":"admin","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/admin/77c6d1603c70677f47ac422a00477632/0000000000000000-0000000002691190","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /var/www/html/lib/private/Files/Cache/Scanner.php#508","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.22.3","version":"25.0.1.1","exception":{"Exception":"Error","Message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /var/www/html/lib/private/Files/Cache/Scanner.php#508","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8192,"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated","/var/www/html/lib/private/Files/Cache/Scanner.php",508]},{"file":"/var/www/html/lib/private/Files/Cache/Scanner.php","line":508,"function":"strpos","args":[null,".part/"]},{"file":"/var/www/html/lib/private/Files/View.php","line":1384,"function":"isPartialFile","class":"OC\\Files\\Cache\\Scanner","type":"::","args":[null]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":227,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":[null]},{"file":"/var/www/html/lib/private/Files/Node/HookConnector.php","line":113,"function":"getNodeForPath","class":"OC\\Files\\Node\\HookConnector","type":"->","args":[null]},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":106,"function":"postWrite","class":"OC\\Files\\Node\\HookConnector","type":"->","args":[[null]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":471,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","post_write",[null]]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","line":398,"function":"emitPostHooks","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[false]},{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":151,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/html/apps/dav/lib/Upload/UploadFolder.php","line":45,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["0000000000000000-0000000002691190",null]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["0000000000000000-0000000002691190",null]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/admin/77c6d1603c70677f47ac422a00477632/0000000000000000-0000000002691190",null,null]},{"file":"/var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":171,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6385bdef3c2fe"}`

**Comment by marcelklehr** [comment]
If cron is not running that's not an issue with recognize. Sorry.
