### ISSUE TITLE
Capitalised and un-capitalised tag duplication

### ISSUE THREAD

**Issue by pjroutledge** [nextcloud/recognize#520]
**Describe the bug**
Tags appear twice, once with a leading capital letter and once without. Eg photos with animals are tagged with 'Animal' and 'animal'.

**To Reproduce**
Download and enable Recognize. Let it run.

**Expected behavior**
Tags should be either capitalised or not, but not both.

**Recognize (please complete the following information):**
 - Installed app version: 3.2.3
 - WASM mode: Don't know
 - Enabled modes: N/A (I've temporarily removed the app due to the duplicate tag problem. From memory I had all available modes enabled.)

**Server (please complete the following information):**
 - Nextcloud version: 25.0.1
 - OS: Debian 11
 - Docker container (if applicable): N/A
 - RAM: 8GB
 - Processor Architecture Intel i5 

**Additional context**
![Screenshot 2022-11-29 174358](https://user-images.githubusercontent.com/3173767/204457868-1ef44205-237d-4f67-849d-49b4bfb4d993.jpg)

**Comment by GrillGuth** [comment]
This is maybe related to #465, as the uncapitalised tags were generated by an older recognize version.

**Comment by marcelklehr** [comment]
Yep

**Comment by pjroutledge** [comment]
Thank you!
