### ISSUE TITLE
Photos from post 2010 not in peoples tab

### ISSUE THREAD

**Issue by ereynier** [nextcloud/recognize#524]
All my photos taken after 2010 are not displayed in the people tab (taken with the exact same camera than the photos before). I don't know how to see if a photos get errors while searching for faces or how to update the people tab to display the new faces. I uploaded new photos from my phone, the queue is updating to 1, then to 0 and no new face.
Btw I have not this problem on tags page.

**Comment by marcelklehr** [comment]
You can check what's going on in the nextcloud.log after setting the log level to debug.

**Comment by ereynier** [comment]
I used the "reset faces for classified files" button, now it's seems to work fine and the "people" tab display my new photos. I wait for all the files to be processed and see if everything still good

**Comment by marcelklehr** [comment]
Great, I'm closing this for now. Let me know if you have further problems
