### ISSUE TITLE
Could not load libtensorflow in Node.js. You can try to manually install libtensorflow or run in WASM mode. 

### ISSUE THREAD

**Issue by fr3ddy-sudo** [nextcloud/recognize#533]
Since the last update i become the Error
Could not load libtensorflow in Node.js. You can try to manually install libtensorflow or run in WASM mode. 

when WASM Activate i become:

Could not load Tensorflow WASM in Node.js. Something is wrong with your setup. 

**Recognize (please complete the following information):**
 - Installed app version: [3.2.3]
 - WASM mode: [Yes and  No]
 - Enabled modes: [object detection, face recognition]

**Server (please complete the following information):**
 - Nextcloud version: [e.g. 25.0.2  RC2]
 - OS: [Gentoo]
 - RAM: [64GB]
 - Processor Architecture [AMD64]

**Comment by marcelklehr** [comment]
Does node.js work?

**Comment by c-schulz-rd13** [comment]
For me yes.
Displayed on the settings Page.
Node.js v14.18.2 binary was installed successfully.

**Comment by Elektronenhirn108** [comment]
Same for me. WASM mode works.
I manually run npm ci, same problem.
I tried the version from the nextcloud App Store and building it on my own. Same error

**Comment by marcelklehr** [comment]
> WASM mode works.

If WASM works, then nothing is wrong. Either your CPU does not support AVX instructions or you don't have glibc or both. This issue is about neither libtensorflow nor WASM mode not working.

**Comment by fr3ddy-sudo** [comment]
Nodejs runs by me
 by the new Version 3.3.1 i become

```
 Node.js
Node.js {Version} Bibliothek wurde erfolgreich installiert.
libtensorflow konnte nicht in Node.js geladen werden. Du kannst versuchen, libtensorflow manuell zu installieren oder im WASM-Modus auszuführen. 
```

**Comment by fr3ddy-sudo** [comment]
Is there any update?
I have the Bug until 2 Weeks and no Help

**Comment by fr3ddy-sudo** [comment]
Error    recognize          Failed to install Tensorflow.js: #                         2022-12-21T02:25:38+00:00 
                              # Fatal error in , line 0                                                            
                              # Check failed: reservation_.SetPermissions(protect_start,                           
                              protect_size, permission).                                                           
                              #                                                                                    
                              #                                                                                    
                              #                                                                                    
                              #FailureMessage Object: 0x7ffeceaee390                                               
                               1: 0xaa6321                                                                         
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               2: 0x1a3b584 V8_Fatal(char const*, ...)                                             
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               3: 0xdd081f                                                                         
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               4: 0xdf6978                                                                         
                              v8::internal::PagedSpace::SetReadAndExecutable()                                     
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               5: 0xd1f4df                                                                         
                              v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*,                           
                              v8::internal::StartupDeserializer*)                                                  
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               6: 0x1130d5b                                                                        
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               7: 0xbe2758 v8::Isolate::Initialize(v8::Isolate*,                                   
                              v8::Isolate::CreateParams const&)                                                    
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               8: 0xa78bb9                                                                         
                              node::NodeMainInstance::NodeMainInstance(v8::Isolate::CreateParams*,                           
                              uv_loop_s*, node::MultiIsolatePlatform*,                                             
                              std::vector<std::string, std::allocator<std::string> >                               
                              const&, std::vector<std::string,                                                     
                              std::allocator<std::string> > const&, std::vector<unsigned                           
                              long, std::allocator<unsigned long> > const*)                                        
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                               9: 0xa0174d node::Start(int, char**)                                                
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]                           
                              10: 0x7f8a9b97334a  [/usr/lib64/libc.so.6]                                           
                              11: 0x7f8a9b9733fc __libc_start_main                                                 
                              [/usr/lib64/libc.so.6]                                                               
                              12: 0x98a4cc                                                                         
                              [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]

**Comment by c-schulz-rd13** [comment]
After the latest update to 3.3.3 and NC 25.0.2 the error was gone for me. everything works now as accepted.

**Comment by marcelklehr** [comment]
@fr3ddy-sudo Can you successfully execute `/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node`? If no, then you need a different node executable. Since installing tensorflow failed you can try installing it manually: https://github.com/nextcloud/recognize/wiki/Manual-install

**Comment by fr3ddy-sudo** [comment]
@marcelklehr  i can run `/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node` without any problem and when i manual install tenserflow i have the same error.

**Comment by ollioddi** [comment]
Also having issues with "Could not load libtensorflow in Node.js. You can try to manually install libtensorflow or run in WASM mode."

It has worked before and im using an i5 11400 so it should be just fine.

What is the steps to manually install libtensorflow?

**Comment by ondrejlohnisky** [comment]
@ollioddi To manually install libtensorflow ou should:
 `cd /var/www/nextcloud/apps/recognize/`
then 
`sudo -u www-data npm i`

and if is still not installed do: 
`sudo -u www-data npm i @tensorflow/tfjs-node`
Hope that helps!

**Comment by SimonBard** [comment]
@ondrejlohnisky 

I get

```
www-data@84d5b936cf50:~/html/apps/recognize$ npm ci
bash: npm: command not found
```

Is the newest nextcloud no more using npm?

I also get the message
`libtensorflow could not be loaded in Node.js. You can try to install libtensorflow manually or run it in WASM mode.`
in the overview page of nextcloud recognize

**Comment by SimonBard** [comment]
I have installed npm in the docker container and then did npm ci, but I still get the message:

`libtensorflow could not be loaded in Node.js. You can try to install libtensorflow manually or run it in WASM mode `

This is the log from the installation:
```
root@84d5b936cf50:/var/www/html/apps/recognize# npm ci
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'recognize@9.0.1',
npm WARN EBADENGINE   required: { node: '20.x', npm: '10.x' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/auth@2.4.0',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/axios@2.5.0',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/router@3.0.1',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/browser-storage@0.4.0',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/browserslist-config@2.3.0',
npm WARN EBADENGINE   required: { node: '^16.0.0', npm: '^7.0.0 || ^8.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/capabilities@1.2.0',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/eslint-config@8.2.1',
npm WARN EBADENGINE   required: { node: '^16.0.0', npm: '^7.0.0 || ^8.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/event-bus@3.3.1',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/initial-state@2.2.0',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/l10n@3.1.0',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/router@3.0.1',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/logger@3.0.2',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/router@2.1.2',
npm WARN EBADENGINE   required: { node: '^16.0.0', npm: '^7.0.0 || ^8.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/sharing@0.2.3',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/stylelint-config@2.3.1',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^9.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/timezones@0.1.1',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/typings@1.9.1',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/vue@8.19.0',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/vue-select@3.25.1',
npm WARN EBADENGINE   required: { node: '^20.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/router@3.0.1',
npm WARN EBADENGINE   required: { node: '^20.0.0', npm: '^10.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@nextcloud/webpack-vue-config@5.5.1',
npm WARN EBADENGINE   required: { node: '^16.0.0', npm: '^7.0.0 || ^8.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.19.0', npm: '9.2.0' }
npm WARN EBADENGINE }
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated text-encoding@0.6.4: no longer maintained
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated vue@2.7.16: Vue 2 has reached EOL and is no longer actively maintained. See https://v2.vuejs.org/eol/ for more details.

added 1499 packages, and audited 1500 packages in 4m

287 packages are looking for funding
  run `npm fund` for details

43 vulnerabilities (10 low, 14 moderate, 16 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
