### ISSUE TITLE
Couldn't get ptxas version string: INTERNAL: Couldn't invoke ptxas --version\n"

### ISSUE THREAD

**Issue by bugsyb** [nextcloud/recognize#537]
### Which version of recognize are you using?

github master (as of 2022.12.09)

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

25

### Which Operating system do you have installed?

Linux

### Which Docker container are you using to run Nextcloud? (if applicable)

v20.10.12

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

amd64

### Describe the Bug

Tensorflow complains about missing ptxas and all what's needed is path to be provided to it.
Key question is how to set paths for Node process?

`Couldn't get ptxas version string: INTERNAL: Couldn't invoke ptxas --version\n"`

Location of ptxas might depend on Cuda-Toolkit version installed as well as on the system, hence the best is to have it set as variable somewhere, i.e. via PATHs offloading it to the system. 

Whilst question is more generic, am not sure how to set it for the involved Nodejs environment.

My install (Docker based) has it:
`/usr/local/cuda-11.8/bin/ptxas`

Thanks!

### Expected Behavior

Should use system level installed via Env variable (PATHs would be the best - least mods to the code required and easy to maintain).

### To Reproduce

Enable GPU with default Cuda install and task run from Cron.

### Debug log

`Couldn't get ptxas version string: INTERNAL: Couldn't invoke ptxas --version\n"`

```
find / -name ptxas
/usr/local/cuda-11.8/bin/ptxas
```

**Comment by marcelklehr** [comment]
You probably need to make sure that the cron job has access to the PATH variable. Maybe wrap the cron call in bash -c

**Comment by bugsyb** [comment]
Found it - missing nvcc. Added it to the second docker build and it is solved now.
Thanks for help!
