### ISSUE TITLE
Shared Galery Rename or Move Only user "xy" can update this person

### ISSUE THREAD

**Issue by apg1980** [nextcloud/recognize#545]
### Which version of recognize are you using?

3.3.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

12gb

### What processor Architecture does your CPU have?

x64

### Describe the Bug

I share my whole image galery with my wife and she is uploading her images in this galery as well.
facerecoginition with my account quits the option for move faces to another cluster or rename the cluster with "Only user "xx" can update this person".
This appears by images uploadet and created from user of my wife in my galery share.
I cannot manage my galery´s faces anymore.
any tips appreciate

best regards

### Expected Behavior

able to move or rename faces

### To Reproduce

try above

**Comment by apg1980** [comment]
to descrive my issue more detailed.
i have on my account an folder names Galery which is shared with my wife (fullpermissions).
i am uploading from nextcloud app images and videos via auto upload and my wife up to this folder as well.
with the latest 2 versions of recognize or i dont know the nextcloud 25.0.2 i cannot move recognized persons to another cluster if my wife shot those images. the error in the topic appears.
if i try to move the images to another cluster from my wifes account i got an error move of image xy failed. no further entrys in the log.
this is an serious issue for me i cannot organize my structure anymore. 
are here any tips?

**Comment by marcelklehr** [comment]
That's a bug in the memories app. Please open an issue there.
