### ISSUE TITLE
CPU 100% - one core exhausted by PHP and rest in idle.

### ISSUE THREAD

**Issue by bugsyb** [nextcloud/recognize#546]
### Which version of recognize are you using?

latest

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

NC 25.0.2

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

v20.10

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

amd64

### Describe the Bug

CPU is for long time used at 100% by PHP as part of running Recognize. More CPU cores are siting at idle.
Worth mentioning it stays like this for long minutes whilst Tensorflow runs very quickly (on GPU) (thanks to @marcelklehr  again for making it possible).

This wasn't the case when Recognize started processing and feels like is related to faces and not other portions of recognition as only faces re-use data, whilst rest just assigns tags.

Feeling is that some logic of faces portion clustering runs in PHP and that is the slow portion - this is long shot into the dark and I might be completely wrong

When the limitation to 100% occurs on the core is exactly when it's PHP process running. Not looking into Recognize code, seems like it is after receiving data from NC db, not pulling any data from filesystem (as in my case it is on different system and I can differentiate when FS via NFS data is pulled and DB data is pulled from where it sits).

Hope it helps in identification from where the limitation comes. Maybe sort of cluster grouping/identification which is run in PHP code or a way to pass data from PHP code to elsewhere?

Interestingly also I've noticed following.
Had running Recognize on one system (GPU based) and counts of movie/music were at 0, constantly for hours of run.
Images and faces were at low level (counts in hundreds where initially it was in ~80k).

The moment I did add additional node (running just recognize), the number of files to process jumped back to ~50-60k$), same as Movies/Music bumped again.

This suggests me that there is potentially a place in the code where it sets some marking points for Reognize and whilst initial thought was this is due to me running it from two systems, and i.e. Recognize is not written with this in mind, it could be related to this CPU issue. Literally 

### Expected Behavior

Multi-core use or potentially offload to GPU if possible.

### To Reproduce

Large database of files to categorize (~80k) and large number of cases cluster as feeling is, this is related to cluster faces.

**Comment by marcelklehr** [comment]
This is likely the clustering algorithm

**Comment by marcelklehr** [comment]
I'm not sure this can be parallelized, but if you have suggestions on how to improve, here's the code: https://github.com/nextcloud/recognize/blob/master/lib/Service/FaceClusterAnalyzer.php

**Comment by bugsyb** [comment]
Thanks and unfortunately am no way close to your abilities in coding. One idea which comes to my mind (though silly) - if this would become a problem later on for larger deployments a compiled Go binary or Python which would get compiled could potentially behave better - it could be called same as Tensorflow is.
Feel free to close it as I can't help and it "works as designed" :)
