### ISSUE TITLE
Documentation suggestion: add preview_max_memory

### ISSUE THREAD

**Issue by bugsyb** [nextcloud/recognize#547]
### Which version of recognize are you using?

latest

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

NC 25.0.2

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

v20.10.12

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

amd64

### Describe the Bug

Suggestion to include it in readme/docs.

Recognize uses Preview generation from NC and as such depends on parameters set for it.

There might be pictures in collections required to be processed which take more memory than default for Preview processing.
Images like photosphere, panorama, etc.
Even if preview size is set to i.e. 2048 as max, it takes to read and process input file which might be much larger.

If not set properly, Preview will fail, also causing Recognize to fail and potentially re-try very same files in next round causing it to be in sort of a loop. The re-try/loop is not confirmed, just a worry hopefully to be rejected after code review.

Long shot for me to avoid issues and as plenty of memory is available has been set to:
`  'preview_max_memory' => 512,`
in `config.php`

### Expected Behavior

Log error and skipping file, proceed to next file.

### To Reproduce

Put file to image file to be Recognized which would take more than usual size of memory, i.e. 13kx13k or so, (photsphere type of image).

**Comment by marcelklehr** [comment]
> potentially re-try very same files in next round causing it to be in sort of a loop

Files that are too large will not be tried again
