### ISSUE TITLE
Multiple clusters for the same person

### ISSUE THREAD

**Issue by afonsofrancof** [nextcloud/recognize#548]
### Which version of recognize are you using?

3.2.3

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu 20.04

### Which Docker container are you using to run Nextcloud? (if applicable)

Not using docker

### How much RAM does your server have?

10GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

There are a lot of clusters for the same person.
For example, I find about 10 clusters for one of my cousins. They haven't changed their look much between all the pictures but it's all still marked as different ones. I have used other services that tag people and all of them correctly had 1 cluster per person, so maybe the AI is too strict on recognize?

### Expected Behavior

Every person has 1 and only 1 cluster

### To Reproduce

Just install recognize on nextcloud . This has happened in several recognize versions with several nextcloud versions.

**Comment by marcelklehr** [comment]
Mh, maybe that's an artifact of wasm mode, but I doubt it. In general recognize is less confident about grouping two clusters together, but once you merge them manually it learns from that.
