### ISSUE TITLE
CUDNN_STATUS_ALLOC_FAILED (on 2GB GPU)

### ISSUE THREAD

**Issue by bugsyb** [nextcloud/recognize#550]
### Which version of recognize are you using?

latest

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

25.0.2.3

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

v20.10.12

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

amd64

### Describe the Bug

Same GPU Docker image used as on the two other systems and on this one CUDNN doesn't want to cooperate - fails to allocate memory by the looks of the message.

Not sure if this is due to model sizes or anything else, i.e. something statically programmed.

This system is different from the other two in terms of having only 2GB on GPU:
- GeForce 940MX (GM108M)

Other than that, I don't have a clue why would this one fail.

The other two have 4GB:
- Quadro M1200 (GM107GLM)
- NVIDIA GeForce GTX 960M (GM107M)

Tests were run down to a single image to be processed.

### Expected Behavior

Hopefully can work for the guys with 2GB GPUs

### To Reproduce

```
{
  "reqId": "pCL5tnuqFpPCvgYzJ5Ok",
  "level": 0,
  "time": "2022-12-12T00:14:05+01:00",
  "remoteAddr": "",
  "user": "--",
  "app": "recognize",
  "method": "",
  "url": "/cron.php",
  "message": "Classifier process output: 2022-12-12 00:14:05.692355: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : NOT_FOUND: No algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 0: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 2: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engine 5: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n",
  "userAgent": "--",
  "version": "25.0.2.3",
  "data": {
    "app": "recognize"
  }
}
(END)
```
```
{
  "reqId": "pCL5tnuqFpPCvgYzJ5Ok",
  "level": 0,
  "time": "2022-12-12T00:14:05+01:00",
  "remoteAddr": "",
  "user": "--",
  "app": "recognize",
  "method": "",
  "url": "/cron.php",
  "message": "Classifier process output: Error: Invalid TF_Status: 5\nMessage: No algorithm worked!  Error messages:\n  Profiling failure on CUDNN engine 1: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED\nin tensorflow/stream_executor/cuda/cuda_dnn.cc(4023): 'cudnnConvolutionForward( cudnn.handle(), alpha, input_nd_.handle(), input_data.opaque(), filter_.handle(), filter_data.opaque(), conv_.handle(), ToConvForwardAlgo(algo), scratch_memory.opaque(), scratch_memory.size(), beta, output_nd_.handle(), output_data.opaque())'\n  Profiling failure on CUDNN engin\n    at NodeJSKernelBackend.executeSingleOutput (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/dist/nodejs_kernel_backend.js:219:43)\n    at conv2dImpl (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/dist/kernels/Conv2D.js:76:20)\n    at Object.kernelFunc (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/dist/kernels/FusedConv2D.js:35:46)\n    at kernelFunc (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4623:32)\n    at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4683:27\n    at Engine.scopedRun (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4488:23)\n    at Engine.runKernelFunc (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4679:14)\n    at Engine.runKernel (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4552:21)\n    at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:23743:30\n    at forwardFunc (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:5123:25)\n",
  "userAgent": "--",
  "version": "25.0.2.3",
  "data": {
    "app": "recognize"
  }
}
```

**Comment by marcelklehr** [comment]
You could try decreasing this value: https://github.com/nextcloud/recognize/blob/master/lib/Classifiers/Classifier.php#L29 to reduce the size of the image tensor.

**Comment by bugsyb** [comment]
Thank you. Will give it a try (need to take care of daily job and a bit of life admin ;) )
One question though - 1024px is not that much. Is it that all files are loaded sequentially, one after another?
This is small already and wondering why would this fail on 2GB GPU memory? Could it be that the model files simply do not fit into the memory?

**Comment by marcelklehr** [comment]
> 1024px is not that much

I believe 1024x1024 is quite a lot for a Neural network. It may not seem much but the models are trained on much smaller images AFAIK

**Comment by bugsyb** [comment]
Yup, understood and fully aware of models being trained on much smaller resolution. Wasn't just aware that it takes that much of a memory to process "relatively" small pics (it comes from my unawareness how data is extrapolated as part of NN layers processing).

Btw. running two parallel processes on 4GB system, got me into the same issue.

**Comment by jakepi84** [comment]
I tried setting "TEMP_FILE_DIMENSION" all the way down to 256 and I am still getting out of memory errors from CUDA. This is on a Quadro P400 2GB. I I use my 1660 6GB card it runs flawlessly.

Below is I think the relevant part of the error:

_t_ensorflow/stream_executor/cuda/cuda_blas.cc:232] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED\n2022-12-22 04:05:06.209646: E tensorflow/stream_executor/cuda/cuda_blas.cc:234] Failure to initialize cublas may be due to OOM (cublas needs some free memory when you initialize it, and your deep-learning framework may have preallocated more than its fair share), or may be because this binary was not built with support for the GPU in your machine.\n2022-12-22 04:05:06.212526: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'cuModuleLoadData(&module, data)' failed with 'CUDA_ERROR_OUT_OF_MEMORY'__

**Comment by marcelklehr** [comment]
@jakepi84 Then you'll have to use the 6Gb card for now, I'm afraid

**Comment by bugsyb** [comment]
Just a thought - could it be due to the way memory is initiated (reserving on the go/fragmentation issue vs grabbing all memory at initialization time? Not sure if there aren't any default parameters which impact that). Whilst initially doing search around the issue I came by some comments around tuning of that parameter(s).
