### ISSUE TITLE
Slow on populating people

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/recognize#551]
### Which version of recognize are you using?

	3.3.1

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu 22.0.4

### Which Docker container are you using to run Nextcloud? (if applicable)

NO

### How much RAM does your server have?

23.47

### What processor Architecture does your CPU have?

X64

### Describe the Bug

Really slow on populating people 

### Expected Behavior

should load them quick

### To Reproduce

Got to photos, click on people, wait.

**Comment by marcelklehr** [comment]
This is a known issue which will be fixed with the next 25 release
