### ISSUE TITLE
Can only merge 1 person, requires refresh of page to merge more 

### ISSUE THREAD

**Issue by Doomsdayrs** [nextcloud/recognize#552]
### Which version of recognize are you using?

3.3.1

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.1

### Which Operating system do you have installed?

Fedora Server 37

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

6

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When handling faces under Photos > People, one can only merge a single person once, before having to refresh the page to merge more.

### Expected Behavior

Can keep on merging back to back

### To Reproduce

1. Go to Photos
2. Go to People
3. Select unnamed person
4. Merge with different person
5. Merge with target
6. Repeat at step 3
7. Notice step 4 does not cause a dialog to appear

**Comment by MayeulC** [comment]
I found that [*Memories*](https://github.com/pulsejet/memories) handled this better, it also enables moving a single picture to another cluster.

**Comment by marcelklehr** [comment]
This is fixed in photos stable25 and will be released with the next v25 release.
