### ISSUE TITLE
Images of person disapear if name is number

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/recognize#555]
### Which version of recognize are you using?

3.3.1

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

no docker

### How much RAM does your server have?

8Gb

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

When renaming a person and choosing a number as name, the number appears as name in the people list. If you open this person, there are no images. All images of the renamed person and of groups with the same number are not there.

### Expected Behavior

Don't allow numbers in name or show images of the person with number as name.

### To Reproduce

- Choose cluster
- rename with number
-

**Comment by marcelklehr** [comment]
Are you using the memories app or the photos app? Do things fix themselves when reloading?

**Comment by sirdrakeistda** [comment]
This happened with the memories App. Reloading does not help, but renaming back to a none number name helps.

**Comment by marcelklehr** [comment]
Can you try the same thing with the photos app?

**Comment by sirdrakeistda** [comment]
Explanation:
- cluster 1 (get the number of this cluster by looking in the url)
- cluster 2 (gets renamed to the number of cluster 1)


Recognize behaves differently in the photo app. Both apps have different problems:
Photo app:
- the cluster 1 gets replaced by the renamed cluster 2. It seems like the first cluster is lost.
- both cluster do not appear in the person view. The second one is only accessible by using the url of the first cluster

Memories App:
- cluster 1 and 2 get merged, but the images do not appear unless the name gets changed to a none number

Both apps seem to have problems with number names and do not work as expected.

**Comment by marcelklehr** [comment]
Thanks for the detailed explanation. I found the bug in the code that prevented renaming a cluster to an existing cluster name in case the cluster name falls back to the cluster ID.
