### ISSUE TITLE
TypeError: stream_copy_to_stream

### ISSUE THREAD

**Issue by markuman** [nextcloud/recognize#559]
### Which version of recognize are you using?

3.3.1

### Enabled Modes

Object recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

no docker, maybe this field must not be required

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I'm running `/var/www/nextcloud$ sudo -u www-data php occ recognize:classify` which ended in

```
...
generating preview of 4903 with dimension 1024
Copying 4903 preview to tempfolder
An unhandled exception has been thrown:
TypeError: stream_copy_to_stream(): Argument #1 ($from) must be of type resource, bool given in /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php:226
Stack trace:
#0 /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php(226): stream_copy_to_stream()
#1 /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php(67): OCA\Recognize\Classifiers\Classifier->getConvertedFilePath()
#2 /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ImagenetClassifier.php(47): OCA\Recognize\Classifiers\Classifier->classifyFiles()
#3 /var/www/nextcloud/apps/recognize/lib/Command/Classify.php(118): OCA\Recognize\Classifiers\Images\ImagenetClassifier->classify()
#4 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Recognize\Command\Classify->execute()
#5 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#6 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#7 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#8 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#9 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#10 /var/www/nextcloud/occ(11): require_once('...')
#11 {main}
```

### Expected Behavior

finish successfully without exception

### To Reproduce

I've no idea. But it repeatedly ended in an exception.

**Comment by marcelklehr** [comment]
Mh, that's a weird one. Something is wrong with preview generation here, it seems. I can make it skip the file if this happens, but I don't know why it happens.

**Comment by marcelklehr** [comment]
should be fixed in the latest release

**Comment by markuman** [comment]
> Mh, that's a weird one. Something is wrong with preview generation here, it seems. I can make it skip the file if this happens, but I don't know why it happens.

can it log the potential broken file somehow?

**Comment by marcelklehr** [comment]
If the original file itself is broken as opposed to the preview generator it will be logged in the debug log

**Comment by marcelklehr** [comment]
@markuman Can you confirm whether the latest version fixes this?

**Comment by markuman** [comment]
Until now, it seems to be working since ~4 hours without an exception (version 3.3.3)

**Comment by markuman** [comment]
It completed without any exception now.
