### ISSUE TITLE
Make user photos smaller

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/recognize#564]
### Describe the feature you'd like to request

I think the photos of the people are too big. It would be nice to be smaller. Please see Synology  photos for references 

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/59488153/207666959-678b6a27-89fe-44cc-b896-60be842d317e.png)

### Describe alternatives you've considered
Nextcloud full screen
![image](https://user-images.githubusercontent.com/59488153/207667311-b4bf4b99-c815-48d6-ba12-394e71c0d272.png)

**Comment by marcelklehr** [comment]
This is an issue for the photos app. Recognize only does the behind the scenes AI stuff

**Comment by andyxheli** [comment]
@marcelklehr can you please transfer it to photos ?
