### ISSUE TITLE
The library pdlib is not available

### ISSUE THREAD

**Issue by nonofr91** [nextcloud/recognize#570]
### Which version of recognize are you using?

3.3.3

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

Nextcloud 25.0.2

### Which Operating system do you have installed?

 Linux 6.0.0-0.deb11.2

### Which Docker container are you using to run Nextcloud? (if applicable)

Nextcloud

### How much RAM does your server have?

16Go

### What processor Architecture does your CPU have?

amd64 x86_64

### Describe the Bug

Hello, I had recognize installed and also updated to version 3.3.3. I disabled it and deleted. and now when i want to reinstall i get an error;
[settings] Erreur: Exception: App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available. at <<closure>>

0. /config/www/nextcloud/lib/private/Installer.php line 140
   OC_App::checkAppDependencies()
1. /config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 451
   OC\Installer->installApp()
2. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Settings\Controller\AppSettingsController->enableApps()
3. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
4. /config/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /config/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
6. /config/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
7. /config/www/nextcloud/index.php line 36
   OC::handleRequest()

POST /settings/apps/enable
from xxx.xx.xxx.xx by yyyy at 2022-12-16T14:04:46+00:00

### Expected Behavior

I imagine that there are still elements of my previous installation. how to clean to install properly?

### To Reproduce

Reboot ESXI
Reboot container Nextcloud/nextclouddb
uninstall recognize

**Comment by SchVinzenz** [comment]
This bug is already closed, but i had the same problem and was looking for a solution for a long time.
Maybe it will help others:
[https://technik.xn--schchner-2za.de/blog/2023/08/08/pdlib-installieren/](https://technik.xn--schchner-2za.de/blog/2023/08/08/pdlib-installieren/)

**Comment by marcelklehr** [comment]
For reference

```
App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available.
```

This is not the Face Recognition repository. This is the recognize repository. Recognize does not use pdlib.

**Comment by SchVinzenz** [comment]
> For reference
> 
> ```
> App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available.
> ```
> 
> This is not the Face Recognition repository. This is the recognize repository. Recognize does not use pdlib.

Your're right, sorry. But I think, the "pdlib" Problem is the same.
