### ISSUE TITLE
Not all pictures scanned by recognize

### ISSUE THREAD

**Issue by lolotiti06** [nextcloud/recognize#571]
### Which version of recognize are you using?

3.3.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu 20.04

### Which Docker container are you using to run Nextcloud? (if applicable)

No Docker

### How much RAM does your server have?

2GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Hello,
While Recognize claims that all pictures have been scanned (no more files in queue), a lot of pictures haven't been recognized.
In addition for the pictures that have been scanned, one person at most has been recognized, even if there are several people on it.

How can I check the number of files that have been scanned ?

Thanks

Laurent.

### Expected Behavior

Scann all pictures and find all relevant person on them.

### To Reproduce

Put pictures in a folder.

### Debug log

No information in NextCloud log

**Comment by gohrner** [comment]
Might be related to https://github.com/nextcloud/recognize/issues/588.

**Comment by marcelklehr** [comment]
Sorry, this could be due to various things. If this is still an issue, drop a note here, and I'll reopen this.
