### ISSUE TITLE
Not scanning

### ISSUE THREAD

**Issue by tio-trom** [nextcloud/recognize#578]
### Which version of recognize are you using?

3.3.3

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

 25.0.2

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

64GB

### What processor Architecture does your CPU have?

AMD64

### Describe the Bug

I think I've setup up everything ok but no files are scanned. I use server side encryption and I suspect that's the cause? 

![2022-12-17_18-10](https://user-images.githubusercontent.com/38043315/208253454-59a9593b-d4ca-4628-9cb7-efd7d2b3da3b.png)

I'd like to know. Thanks!

### Expected Behavior

My cron is working fine, and I see no logs in nextcloud regarding this issue. I suppose it should start working. I waited for hours now. The CPU is barely used.

### To Reproduce

As said above.

**Comment by ohneb** [comment]
Hey @tio-trom,
I'm not the developer but I saw in your screenshot that it say in the very top that you did not yet download the models so the recoginition cannot work at this point. You can download them by running `occ recognize:download-models` on the command line. This will download the models and afterwards it will begin scanning your images.

@marcelklehr Maybe it would be a good idea to the status "The machine learning models still need to be downloaded." as a yellow warning admonition? I was confused by this too when I set up recognize.

Best regards,
Benjamin

**Comment by bugsyb** [comment]
Or potentially to have the models auto-downloaded on the first run? Just a thought, as initially when started with Recognize, that was my impression, gave it a while and then downloaded manually - still unsure if it shouldn't be downloaded automatically.

**Comment by Emporea** [comment]
I seem to have the same problem.
I just setup a new Nextcloud 25 instance yesterday with Preview Generator and recognize installed.
Somehow I can see some recognized faces but there are 0 tags created so far and nothing has been scanned or classified. 
I tried downloading the model manually, run scan all from the admin page or recrawl via occ. Nothing seems to work.

**Comment by Emporea** [comment]
This is part of my config.php. Maybe it has something to do with it?

```
  'enable_previews' => true,
  'preview_max_x' => 1024,
  'preview_max_y' => 1024,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\MarkDown',
    2 => 'OC\\Preview\\PDF',
    4 => 'OC\\Preview\\JPEG',
    5 => 'OC\\Preview\\PNG',
    6 => 'OC\\Preview\\GIF',
    7 => 'OC\\Preview\\BMP',
    8 => 'OC\\Preview\\XBitmap',
    9 => 'OC\\Preview\\MP3',
    10 => 'OC\\Preview\\HEIC',
    11 => 'OC\\Preview\\Movie',
    12 => 'OC\\Preview\\MKV',
    13 => 'OC\\Preview\\MP4',
    14 => 'OC\\Preview\\AVI',
    18 => 'OC\\Preview\\Krita',
    19 => 'OC\\Preview\\TIFF',
  ),
  'filesystem_check_changes' => 1,
```

**Comment by bugsyb** [comment]
What are cron settings? By default it might be that Cron (Ajax) is run on user click/interaction.
Give it a try and use php cron.php run out of cron - maybe at the beginning with relatively small interval and see what happens.

Output of oc_jobs table filtered by Recognize could help diagnosing issue too.

**Comment by marcelklehr** [comment]
Closing due to lack of response.
