### ISSUE TITLE
Same tags différents photos

### ISSUE THREAD

**Issue by ereynier** [nextcloud/recognize#580]
### Which version of recognize are you using?

3.3.3

### Enabled Modes

Object recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Alpine 

### Which Docker container are you using to run Nextcloud? (if applicable)

Idk

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I have multiple tags with and without a capitalize letter but without the same photos in. Like alpine / Alpine, bag / Bag, animal / Animal

### Expected Behavior

Expect to have only one tag or at leats the same photos with the tags

### To Reproduce

I don't know just have different photos.

**Comment by marcelklehr** [comment]
Lowercase tags are from recognize version 2 and can be safely removed using `occ recognize:remove-legacy-tags`
