### ISSUE TITLE
Faces still there after resetting tags

### ISSUE THREAD

**Issue by b3nis** [nextcloud/recognize#581]
### Which version of recognize are you using?

3.3.3

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu Server 20.04

### Which Docker container are you using to run Nextcloud? (if applicable)

Cannot check now

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When resetting tags with occ recognize:reset-tags - faces are still there. Should be removed as well? Let's say that I wanna start over or just remove recognize - I can get rid of tagged pictures but not faces.

### Expected Behavior

The faces to get back to zero.

### To Reproduce

Run occ recognize:reset-tags and note how faces are still there.

**Comment by marcelklehr** [comment]
If you want faces to be resetted, you'll need to use the reset faces command

**Comment by b3nis** [comment]
Whops, I totally missed that option. Sorry!
