### ISSUE TITLE
Talk chat can't edit our own message

### ISSUE THREAD

**Issue by yjjoe-head** [nextcloud/recognize#583]
### Describe the feature you'd like to request

As a user I would like to be able to edit my message after posted

### Describe the solution you'd like

Get a edit button

### Describe alternatives you've considered

any ways to edit our own post

**Comment by phil-lipp** [comment]
I think you're in the wrong git. Recognize (where we are currently) is used for classifying files (music, photos) using Artificial Intelligence. 
You probably wanna ask your question over at: https://github.com/nextcloud/spreed

**Comment by yjjoe-head** [comment]
My bad. Thanks to point me this out!
