### ISSUE TITLE
Use Meme recognition model

### ISSUE THREAD

**Issue by phil-lipp** [nextcloud/recognize#586]
### Describe the feature you'd like to request

My photo files contain a lot of memes that people sent me. These take up a lot of resources, for example when recognize is classifying faces as many memes have faces on them. I thought about how the problem could be approached and saw this research article: https://towardsdatascience.com/meme-vision-framework-e90a9a7a4187 .
Could this model be integrated into recognize and maybe run before the face classification? Then put the meme faces at the end of the queue or something?

### Describe the solution you'd like

Since Memes often contain faces and are a pretty well defined set of images (not every meme has to be caught), excluding memes from face recognition may be a good option to reduce the total amount of classifications for some. 

### Describe alternatives you've considered

Implement a face ignore list that can be viewed in photos/memories and manually edited.

**Comment by marcelklehr** [comment]
Closing as not planned.
