### ISSUE TITLE
Table 'nextcloud.oc_recognize_queue_imagenet' doesn't exist

### ISSUE THREAD

**Issue by markuman** [nextcloud/recognize#587]
### Which version of recognize are you using?

3.3.3

### Enabled Modes

Object recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

none docker installation

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

While everything works as expected, I've notices thousand of error messages in the nextcloud Log

>  Table 'nextcloud.oc_recognize_queue_imagenet' doesn't exist

```
[recognize] Error: OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_queue_imagenet' doesn't exist at <<closure>>

0. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 296
   OC\DB\Exceptions\DbalException::wrap()
1. /var/www/nextcloud/lib/public/AppFramework/Db/QBMapper.php line 336
   OC\DB\QueryBuilder\QueryBuilder->executeQuery()
2. /var/www/nextcloud/apps/recognize/lib/Db/QueueMapper.php line 62
   OCP\AppFramework\Db\QBMapper->findEntities()
3. /var/www/nextcloud/apps/recognize/lib/Service/QueueService.php line 91
   OCA\Recognize\Db\QueueMapper->getFromQueue()
4. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 53
   OCA\Recognize\Service\QueueService->getFromQueue()
5. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 33
   OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
6. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
   OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->run()
7. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
8. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
9. /var/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2022-12-22T16:36:25+00:00
```

### Expected Behavior

no errors and missing tables are self-created

```sql
create table if not exists oc_recognize_queue_imagenet ...
```

### To Reproduce

No idea.

**Comment by marcelklehr** [comment]
This normally only happens if you have tinkered with the tables manually. I recommend

1. Uninstall recognize
2. dropping all recognize tables and
3. then deleting all recognize entries from oc_migrations
4. Finally reinstall recognize

**Comment by ralfi** [comment]
@markuman Do you have a working recognize? At me doesnt work, also with recommend steps from @marcelklehr

**Comment by ralfi** [comment]
latest version 3.6.1 from nextcloud app store

**Comment by markuman** [comment]
Yes, it's working here. But I'm still on 3.5.0 atm

```sql
CREATE TABLE `oc_recognize_queue_imagenet` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `file_id` bigint(20) NOT NULL,
  `storage_id` bigint(20) DEFAULT NULL,
  `root_id` bigint(20) DEFAULT NULL,
  `update` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `recognize_imagenet_file` (`file_id`),
  KEY `recognize_imagenet_storage` (`storage_id`,`root_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13184 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

**Comment by ralfi** [comment]
Second try, now it works. Curious. Seems to me is related to deleting old tags or similar. Deleting everything from terminal and set a classify after a few seconds it works.
