### ISSUE TITLE
RuntimeException: Classifier process timeout

### ISSUE THREAD

**Issue by ernolf** [nextcloud/recognize#601]
### Which version of recognize are you using?

3.3.4

### Enabled Modes

Object recognition, Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2.3

### Which Operating system do you have installed?

Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-200-generic x86_64)

### Which Docker container are you using to run Nextcloud? (if applicable)

No Docker, running on bare machine Linux.

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Sometimes it works fine but after a certain time it only produces this error messag after every job.
When I change the number of files to process per job run, it often returns to work without error messages after a while and it shows green (Audio recognition is working.) in the admin panel.

### Expected Behavior

No timeout-errors

### To Reproduce

I'm pondering, since I don't find no regularities to make it reproducible.
It happens with 1 file to process per job run as well as with 2, 3, 4, 5, 6, or more.
If the number of files is too high, the processing takes so long that (with a 10-minute interval of the cron) up to 3 or 4 jobs are running in parallel, I try to avoid that somehow.

### Debug log

    [core] Error: RuntimeException: Classifier process timeout at <<closure>>
    
    0. /var/www/nextcloud/apps/recognize/lib/Classifiers/Audio/MusicnnClassifier.php line 46
       OCA\Recognize\Classifiers\Classifier->classifyFiles()
    1. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyMusicnnJob.php line 43
       OCA\Recognize\Classifiers\Audio\MusicnnClassifier->classify()
    2. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
       OCA\Recognize\BackgroundJobs\ClassifyMusicnnJob->classify()
    3. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyMusicnnJob.php line 35
       OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
    4. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
       OCA\Recognize\BackgroundJobs\ClassifyMusicnnJob->run()
    5. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
       OCP\BackgroundJob\Job->start()
    6. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
       OCP\BackgroundJob\TimedJob->start()
    7. /var/www/nextcloud/cron.php line 152
       OCP\BackgroundJob\TimedJob->execute()
    
    at 2023-01-01T10:31:50+00:00

**Comment by sirdrakeistda** [comment]
I still get this error for one audio file.
