### ISSUE TITLE
Selecting and then merging photos merges ALL photos

### ISSUE THREAD

**Issue by racheljwood** [nextcloud/recognize#602]
### Which version of recognize are you using?

3.3.4

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Ubuntu 22.04.1

### Which Docker container are you using to run Nextcloud? (if applicable)

Casa V0.4.0 - Docker version 20.10.17, build 100c70180f

### How much RAM does your server have?

4Gb

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

A person (PERSON A) has many pictures of someone else (PERSON B), so whist looking at PERSON A I select all the PERSON B photos. Then I click merge with another person and all of the photos of PERSON A are merged with PERSON B. Person A has in effect disappeared and I left with PERSON B who has all of PERSON A and PERSON B photos.

### Expected Behavior

Only the photos selected should be merged.

### To Reproduce

1) Go to the Photos app in Nextcloud
2) Click on the Menu item People
3) Choose a person (Lets call them PERSON A).
4) Select two or more of "their" photos by clicking on the box in the photo.
5) In the top right corner, click the three dots and select "Merge with different person"
6) A window will appear with all the previously recognised people. Select one of them (PERSON B) by clicking on them.
7) ALL of the photos of PERSON A will now be completely merged with PERSON B and PERSON A will be removed

**Comment by marcelklehr** [comment]
Hello @racheljwood 

Thank you for taking the time to report this. It seems that this issue is due to a misunderstanding. There is currently no feature to assign specific photos to a different cluster. "Merge" will always merge the whole person.

**Comment by racheljwood** [comment]
Hi,  Thank you for your reply but unfortunately that makes the software even less useful unless I have missed something. I scanned thousands of photos and in many cases the softwore identified the wrong person. I simply need to pick one of more people that it thinks is me and say "no, its not me it is person X". The added friústration I see is that Person X may not have been identified in any picture so I want to really say, this photo is a new person called X.

Thanks you for the software but I have ended up with 305 matches for one person when in reality there are 10 different people there and I don't see how to resolve it.

Regards

**Comment by marcelklehr** [comment]
> "no, its not me it is person X"

You are right, this feature doesn't exist at the moment. You can only say "This is not me", currently. I understand that this is frustrating.

> I scanned thousands of photos and in many cases the softwore identified the wrong person.

I see this as the core problem. We're still trying to improve the accuracy of the face clustering, which should reduce the need to do manual bookkeeping.

Which version of recognize do you have installed?

**Comment by racheljwood** [comment]
Hi,  I am running version 3.3.4. I don't see it as a core issue as I would always imagine that there will will be times when mistakes happen. We are both programmers and we know there will always be issues. One example is identical twins, I know a pair, and they dress alike just to confuse people. What whould be much better is the ability to pick one or more ohotos and move them to a new or existing person.

Without this ability, for me, I will stop trying and testing the software and look for, or wait for, another solution. Sorry if I sound negative and I appreciate the effort you have put into the software, but with ability to correct mistakes I cannot use it.

regards

**Comment by bdevy** [comment]
@racheljwood, using the Memories App you can select all the photos you want, click the 3 dots, then click "Move to another person." I think this will achieve your goal. I've been using this quite a bit.

![image](https://user-images.githubusercontent.com/63156715/210282834-2da5242b-cbcc-40ba-8cd2-d2c0300d01d6.png)

Regards,
Brian

**Comment by racheljwood** [comment]
@bdevy  Thank you for suggestion. That does indeed solve by orogonal issue about how to get the right people into the right bucket. Do you also know of a way to get people into a new bucket? For example my danish teacher has been recognised as being me but she hasn't been recognised as being herself. Therefore there is no existing person I can merge her photos with.

Manga tak if you or anyone can help.

**Comment by bdevy** [comment]
Hi @racheljwood, I'm not aware of a current method to creating a new Cluster/Person manually. It would be interesting if this were possible, and we could feed that new Cluster/Person more images for it to "learn" from.
