### ISSUE TITLE
Image tagging not working

### ISSUE THREAD

**Issue by kjlhgfds** [nextcloud/recognize#604]
### Which version of recognize are you using?

3.3.4

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Linux Mint 21.1

### Which Docker container are you using to run Nextcloud? (if applicable)

Nextcloud-AIO v4.0.1

### How much RAM does your server have?

32GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I installed nextcloud, then the Recognize app and turned ON 'face recognition" but nothing happens.

Here is my settings :
![Screenshot from 2023-01-02 19-56-29](https://user-images.githubusercontent.com/43605270/210270430-26b657b8-a98f-4f31-b634-c255c94b62f7.png)
![Screenshot from 2023-01-02 19-56-53](https://user-images.githubusercontent.com/43605270/210270439-250891f5-e448-46d6-8c4b-9c3e491d103a.png)

What can I do please ?

### Expected Behavior

The face recognition to start.

### To Reproduce

Just install Nextcloud_AIO (latest), then the Recognize app with "face recognition" turned ON/

### Debug log

There is no info in the "Logging" tab.

**Comment by marcelklehr** [comment]
I think currently you need to enable WASM mode in AIO. Until https://github.com/nextcloud/all-in-one/pull/1569 is released into production.

**Comment by kjlhgfds** [comment]
Seems to be working, thanks !
