### ISSUE TITLE
stuck at "Checking libtensorflow"

### ISSUE THREAD

**Issue by lukasig** [nextcloud/recognize#609]
### Which version of recognize are you using?

3.3.4

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

ubuntu server 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud-AIO

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

x86_64 ( i3-10110U )

### Describe the Bug

In the Recognize admin settings, under "Tensorflow WASM mode" i get:

> ⚠️ Could not check whether your machine supports native TensorFlow operation.

and at the very bottom o of the page, under "Node.js", i get:

> ✅ Node.js v14.18.2 binary was installed successfully.

but the next line shows that loading animation (rotating circle icon) forever:

> ↻ Checking libtensorflow

### Expected Behavior

face recognition

### To Reproduce

I installed the app and checked if requirements were met.
I wasn't sure if i have glibc installed so I installed it using:
`sudo apt install glibc-source`

I downloaded the learning models manually:
`sudo docker exec -u 33 -it nextcloud-aio-nextcloud php occ recognize:download-models`

after enabling face, object and music genre recognition, nothing is happening.

### Debug log

after several hours, I got this error in the nextcloud logs:

> RuntimeException: Classifier process timeout

which is re-logged every 20min

**Comment by JediBrooker** [comment]
me too. same issue where under the Node.js section where it says "Checking libtensorflow" the circle is in a constant spin. Node.js binary is ticked.

**Comment by bahelit** [comment]
Am also using Nextcloud-AIO and "Checking libtensorflow" was constantly spinning.

Here's an error log, this log message appears multiple times:
`[richdocuments] Error: GuzzleHttp\Exception\ServerException: Server error: `GET https://<my server>/hosting/capabilities` resulted in a `530 ` response:
<!DOCTYPE html>

<!--[if IE 7]>    <html class (truncated...)
 at <<closure>>

 0. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 69
    GuzzleHttp\Exception\RequestException::create(GuzzleHttp\Psr7\Request {}, "*** sensitive parameters replaced ***", null, [], null)
 1. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 204
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 153
    GuzzleHttp\Promise\Promise::callHandler(1, "*** sensitive parameters replaced ***", null)
 3. /var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 48
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 248
    GuzzleHttp\Promise\TaskQueue->run(true)
 5. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 224
    GuzzleHttp\Promise\Promise->invokeWaitFn()
 6. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 269
    GuzzleHttp\Promise\Promise->waitIfPending()
 7. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 226
    GuzzleHttp\Promise\Promise->invokeWaitList()
 8. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
 9. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Promise\Promise->wait()
10. /var/www/html/lib/private/Http/Client/Client.php line 218
    GuzzleHttp\Client->request("get", "https://<my server> ... s", ["/mnt/ncdata/fi ... e])
11. /var/www/html/custom_apps/richdocuments/lib/Service/CapabilitiesService.php line 132
    OC\Http\Client\Client->get("https://<my server> ... s", [45,[true]])
12. /var/www/html/custom_apps/richdocuments/lib/Service/CapabilitiesService.php line 74
    OCA\Richdocuments\Service\CapabilitiesService->refetch()
13. /var/www/html/custom_apps/richdocuments/lib/AppInfo/Application.php line 80
    OCA\Richdocuments\Service\CapabilitiesService->getCapabilities()
14. /var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 67
    OCA\Richdocuments\AppInfo\Application->OCA\Richdocuments\AppInfo\{closure}("*** sensitive parameters replaced ***")
15. /var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php line 51
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn(Closure {})
16. /var/www/html/custom_apps/richdocuments/lib/AppInfo/Application.php line 135
    OC\AppFramework\Bootstrap\BootContext->injectFn(Closure {})
17. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 190
    OCA\Richdocuments\AppInfo\Application->boot(OC\AppFramework\Bootstrap\BootContext {})
18. /var/www/html/lib/private/legacy/OC_App.php line 208
    OC\AppFramework\Bootstrap\Coordinator->bootApp("richdocuments")
19. /var/www/html/lib/private/legacy/OC_App.php line 141
    OC_App::loadApp("richdocuments")
20. /var/www/html/lib/base.php line 1045
    OC_App::loadApps()
21. /var/www/html/index.php line 36
    OC::handleRequest()

HEAD /
from 127.0.0.1 at 2023-01-06T23:51:26+00:00`

**Comment by gadric** [comment]
Same problem here ...

**Comment by manugch** [comment]
Yeah me too, definitely AIO related.

**Comment by EthicalObligation** [comment]
Any workarounds?

**Comment by szaimen** [comment]
Hi, I doubt that this is an issue only with AIO. I rather suspect an issue with recognize on Alpine in general. I pinged Marcel and he said he will have a look soon.

**Comment by EthicalObligation** [comment]
This does appear to be alpine related some library is not loading in correctly. Just not sure why it isn't throwing an error.

**Comment by EthicalObligation** [comment]
I recommend a chroot or something similar if possible.

**Comment by szaimen** [comment]
gcompat should be installed in AIO by default since v4.0.1 so not sure why it doesnt seem to work still...

**Comment by EthicalObligation** [comment]
sudo apk add debootstrap
 for i in /proc/sys/kernel/grsecurity/chroot_*; do echo 0 | sudo tee $i; done
 mkdir ~/chroot
 sudo debootstrap --arch=i386 wheezy ~/chroot http://http.debian.net/debian/
 for i in /proc/sys/kernel/grsecurity/chroot_*; do echo 1 | sudo tee $i; done
 sudo chroot ~/chroot /bin/bash
https://wiki.alpinelinux.org/wiki/Running_glibc_programs
Might be helpful

**Comment by szaimen** [comment]
What exaclty is this doing? Is this something that could be done by recognize?

**Comment by EthicalObligation** [comment]
It is creating a chroot of debian which may or may not help. Just thinking out loud. I don't have much experience with chroots and it will most likely take a lot of integration.

**Comment by qudiqudi** [comment]
This seems to be still a problem on Nextcloud AIO v4.2.0. Is there any news on this?

**Comment by gigerIT** [comment]
It's in the next release
You can check the progress here:
https://github.com/nextcloud/all-in-one/issues/1829

**Comment by szaimen** [comment]
This is now released with v4.3.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by qudiqudi** [comment]
This is not fixed, Recognize is now actually not working at all.

**Comment by szaimen** [comment]
What was fixed is the `stuck at checking libtensorflow` issue. What you are reporting is a different one. Please open a new issue for this. Thanks!

**Comment by gigerIT** [comment]
> This is not fixed, Recognize is now actually not working at all on AIO.

Not true, it works now since the last update but you have to turn on WASM mode.
(I've already tagged thousands of images with it in my AIO instance)

**Comment by qudiqudi** [comment]
> > This is not fixed, Recognize is now actually not working at all on AIO.
> 
> Not true, it works now since the last update but you have to turn on WASM mode. (I've already tagged thousands of images with it in my AIO instance)

Are you on Nextcloud AIO v4.3.4?

**Comment by szaimen** [comment]
Hi, is anyone here using arm64?

**Comment by szaimen** [comment]
Looks like this https://github.com/nextcloud/recognize/commit/30602dcfa972257f4fae1534fb2419ef319acdb9 should solve the requirement for gcompat on arm64 in a future update.

**Comment by dillfrescott** [comment]
I am having this issue

**Comment by dillfrescott** [comment]
Ive got it to display that it has successfully loaded the `libtensorflow` module twice, with it again reverting to just spinning forever. Ive tried many different things to try to remedy the issue to no avail. I have determined that this is an extremely buggy plugin. :/

**Comment by marcelklehr** [comment]
@dillfrescott Have you enabled WASM mode?
