### ISSUE TITLE
Plugin causes error message upon deleting files

### ISSUE THREAD

**Issue by android606** [nextcloud/recognize#612]
### Which version of recognize are you using?

2.2.2

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

24.0.8

### Which Operating system do you have installed?

Ubuntu 22.04.1 LTS

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

12GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When users attempt to delete a file using the Nextcloud web interface, an error message appears that says 'Error deleting file "filename.txt"'.

### Expected Behavior

Users should be able to delete files without an error message.

### To Reproduce

1. Install Recognize 2.2.2
2. Log into Nextcloud Web UI
3. Click "Files"
4. Create a new file named "New text file.md" with + button (or any other method)
5. Right-click the file and click "Delete file"

Error message 'Error deleting file "New text file.md"' appears, and the file is not removed from the GUI.

- If you look in the user's data folder, the file is deleted as expected.
- If you reload the Web UI in your browser, the file will disappear as expected.

### Debug log

{"reqId":"BKK60CJG2dYAQ5thqYA4","level":3,"time":"2023-01-06T00:57:24+00:00","remoteAddr":"fd00::457:9209:84ff:87ea","user":"admin","app":"PHP","method":"DELETE","url":"/remote.php/dav/files/admin/New%20text%20file2.md","message":"Opis\\Closure\\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) at /big/www-cloud.android606.com/html/3rdparty/opis/closure/src/SerializableClosure.php#18","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","version":"24.0.8.2","exception":{"Exception":"Error","Message":"Opis\\Closure\\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) at /big/www-cloud.android606.com/html/3rdparty/opis/closure/src/SerializableClosure.php#18","Code":0,"Trace":[{"file":"/big/www-cloud.android606.com/html/3rdparty/opis/closure/src/SerializableClosure.php","line":18,"function":"onAll","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/big/www-cloud.android606.com/html/lib/composer/composer/ClassLoader.php","line":571,"args":["/big/www-cloud.android606.com/html/3rdparty/opis/closure/src/SerializableClosure.php"],"function":"include"},{"file":"/big/www-cloud.android606.com/html/lib/composer/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"file":"/big/www-cloud.android606.com/html/3rdparty/opis/closure/functions.php","line":18,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Command/CronBus.php","line":72,"function":"Opis\\Closure\\serialize"},{"file":"/big/www-cloud.android606.com/html/lib/private/Command/CronBus.php","line":45,"function":"serializeCommand","class":"OC\\Command\\CronBus","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Command/AsyncBus.php","line":45,"function":"queueCommand","class":"OC\\Command\\CronBus","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/files_trashbin/lib/Trashbin.php","line":851,"function":"push","class":"OC\\Command\\AsyncBus","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/files_trashbin/lib/Trashbin.php","line":373,"function":"scheduleExpire","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/big/www-cloud.android606.com/html/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php","line":107,"function":"move2trash","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/big/www-cloud.android606.com/html/apps/files_trashbin/lib/Trash/TrashManager.php","line":102,"function":"moveToTrash","class":"OCA\\Files_Trashbin\\Trash\\LegacyTrashBackend","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/files_trashbin/lib/Storage.php","line":202,"function":"moveToTrash","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/files_trashbin/lib/Storage.php","line":102,"function":"doDelete","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":1187,"function":"unlink","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":733,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/lib/Connector/Sabre/File.php","line":523,"function":"unlink","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/lib/Server.php","line":358,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/remote.php","line":170,"args":["/big/www-cloud.android606.com/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/big/www-cloud.android606.com/html/lib/private/Log/ErrorHandler.php","Line":99,"CustomMessage":"--"}}

{"reqId":"BKK60CJG2dYAQ5thqYA4","level":4,"time":"2023-01-06T00:57:24+00:00","remoteAddr":"fd00::457:9209:84ff:87ea","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/admin/New%20text%20file2.md","message":"Call to undefined method OCP\\Files\\Events\\Node\\NodeDeletedEvent::getSubject()","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","version":"24.0.8.2","exception":{"Exception":"Error","Message":"Call to undefined method OCP\\Files\\Events\\Node\\NodeDeletedEvent::getSubject()","Code":0,"Trace":[{"file":"/big/www-cloud.android606.com/html/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Recognize\\Hooks\\FileListener","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/Node/HookConnector.php","line":156,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/legacy/OC_Hook.php","line":106,"function":"postDelete","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":1300,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":1228,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":733,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/lib/Connector/Sabre/File.php","line":523,"function":"unlink","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/lib/Server.php","line":358,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/remote.php","line":170,"args":["/big/www-cloud.android606.com/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/big/www-cloud.android606.com/html/apps/recognize/lib/Hooks/FileListener.php","Line":22,"CustomMessage":"--"}}

{"reqId":"BKK60CJG2dYAQ5thqYA4","level":4,"time":"2023-01-06T00:57:24+00:00","remoteAddr":"fd00::457:9209:84ff:87ea","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/admin/New%20text%20file2.md","message":"Call to undefined method OCP\\Files\\Events\\Node\\NodeDeletedEvent::getSubject()","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36","version":"24.0.8.2","exception":{"Exception":"Error","Message":"Call to undefined method OCP\\Files\\Events\\Node\\NodeDeletedEvent::getSubject()","Code":0,"Trace":[{"file":"/big/www-cloud.android606.com/html/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Recognize\\Hooks\\FileListener","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/Node/HookConnector.php","line":156,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/legacy/OC_Hook.php","line":106,"function":"postDelete","class":"OC\\Files\\Node\\HookConnector","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":1300,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":1228,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/lib/private/Files/View.php","line":733,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/lib/Connector/Sabre/File.php","line":523,"function":"unlink","class":"OC\\Files\\View","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/lib/Server.php","line":358,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/big/www-cloud.android606.com/html/remote.php","line":170,"args":["/big/www-cloud.android606.com/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/big/www-cloud.android606.com/html/apps/recognize/lib/Hooks/FileListener.php","Line":22,"CustomMessage":"--"}}

**Comment by marcelklehr** [comment]
The v2 branch is no longer maintened sadly due to time constraints. I recommend updating to Nextcloud 25 so you can run recognize v3.
