### ISSUE TITLE
/tmp fills up and is not being cleared during classification

### ISSUE THREAD

**Issue by swestersund** [nextcloud/recognize#629]
### Which version of recognize are you using?

3.3.4

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

OpenSUSE Tumbleweed (release-20230110)

### Which Docker container are you using to run Nextcloud? (if applicable)

25-apache

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I run Nextcloud in a Podman container. When running the `occ recognize:classify` command, preview files are generated into `/tmp`. For performance reasons, I use a `tmpfs` mount on `/tmp` (instead of letting it go into the overlayfs, i.e. my SSD), but I limit it to 1024MiB in order not to let Nextcloud use all of my RAM (`podman run` with parameter: `--mount type=tmpfs,tmpfs-size=1024M,destination=/tmp`). I notice that the Recognize app doesn't do any clean-up inside `/tmp`, after a while (45-60 minutes in my case) the `/tmp` file system was full. The amount of `oc_tmp_*.jpg` files kept increasing over time.

To its credit, Recognize seems to be able to keep going after `/tmp` is full. However, this might be problematic for other apps inside the container. Generally, it's bad to have 100% full file systems.

As a workaround, I set up a loop which removes the jpg files that are at least 15 minutes old:
```sh
podman exec -it nc bash -c 'while true; do date; df -h /tmp; echo "cleaning up..."; find /tmp -maxdepth 1 -type f -name "oc_tmp_*.jpg" -mmin +15 -delete ; df -h /tmp ; echo "sleeping 120s..." ; sleep 120 ; echo; done'
```
Might this be harmful for the classification performance? I.e., does Recognize ever reuse tempfiles that have presumably already been processed? Let me know. Thanks in advance!

### Expected Behavior

I would like Recognize to do some cleaning up of temporary files that it has already processed and does not need anymore. Without knowing the code, I would expect that the amount of tmp files would be in the neighborhood of the batch size that I set in the Settings > Recognize admin controls of Nextcloud (500 by default).

### To Reproduce

1. Have a Nextcloud account with a decent amount of unclassified photos.
1. Run Nextcloud in Podman (probably reproduces without containers too), and limit `/tmp` to a fixed size, small `tmpfs` file system, e.g.:
    ```sh
    podman run --name=nc ${volume_mounts_et_cetera:?} --mount type=tmpfs,tmpfs-size=1024M,destination=/tmp --detach=True docker.io/nextcloud:25-apache
    ```
1. Start a classification process: `occ recognize:classify`
2. Monitor the contents and usage of `/tmp` and watch it fill up until 100%.
    ```sh
    # See the file system usage
    df -h /tmp
    # Count the amount of temp files generated by Recognize
    find /tmp -maxdepth 1 -type f -name "oc_tmp*.jpg" -print | wc -l
    ```

**Comment by ernolf** [comment]
I can't answer your question, but I also mount /tmp with tmpfs for the same (performance) reason.
Since many Nextcloud apps are downright wasteful with temporary files, it might be good to know that there is a variable 'tempdirectory' in /config/config.php where you can specify a directory with more space. The recognize app makes use of that temp folder.
For me it looks like this:

    'tempdirectory' => '/tmp_nc',

The directory must of course have 777 rights or belong to the www user.

**Comment by swestersund** [comment]
Thanks @ernolf for the tip! Separating the Nextcloud tempdirectory from the rest of the applications is useful.

I gathered some numbers to amend my original post. On my system, the `/tmp` usage goes up like this without any workarounds applied:

| Time | Tmpfs Usage | Amount of `oc_tmp*.jpg` files |
| ------ | ------------------ | ---------------- |
| 0 min | 72MiB | 498 |
| 6 min | 126 MiB | 1110 |
| 10 min | 302 MiB | 2782 |
| 15 min | 535 MiB | 3914 |
| 20 min | 764 MiB | 5449 |

**Comment by marcelklehr** [comment]
Ah, that's a nice catch. Thank you for reporting!
