### ISSUE TITLE
Fresh install v3.3.6 do not work after deleting previous versions

### ISSUE THREAD

**Issue by ralfi** [nextcloud/recognize#643]
### Which version of recognize are you using?

3.3.6

### Enabled Modes

Object recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

v20.10.22+dfsg-1

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

After removing v3.3.5 and check the app directory is complete empty a fresh new install from app.nextcloud.com failed to start.

### Expected Behavior

Start object recognation 

### To Reproduce

Remove v3.3.5
Install v3.3.6

### Debug log

`{"reqId":"uvFahRJ9LNx1T9HlZfAn","level":3,"time":"2023-01-18T12:04:34+00:00","remoteAddr":"10.0.0.2","user":"admin","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"chmod():No such file or directory at /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php#146","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36","version":"25.0.3.2","exception":{"Exception":"Error","Message":"chmod(): No such file or directory at /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php#146","Code":0,"Trace":[{"function":"onError","class":"OC\Log\ErrorHandler","type":"::","args":[2,"chmod(): No such file or directory","/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php",146]},{"file":"/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php","line":146,"function":"chmod","args":["/var/www/html/custom_apps/recognize/bin/node",493]},{"file":"/var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php","line":78,"function":"testBinary","class":"OCA\Recognize\Migration\InstallDeps","type":"->","args":["/var/www/html/custom_apps/recognize/bin/node"]},{"file":"/var/www/html/lib/private/Repair.php","line":127,"function":"run","class":"OCA\Recognize\Migration\InstallDeps","type":"->","args":[{"class":"OC\Repair"}]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":1064,"function":"run","class":"OC\Repair","type":"->","args":[]},{"file":"/var/www/html/lib/private/Installer.php","line":156,"function":"executeRepairSteps","class":"OC_App","type":"::","args":["recognize",["OCA\Recognize\Migration\InstallDeps"]]},{"file":"/var/www/html/apps/settings/lib/Controller/AppSettingsController.php","line":451,"function":"installApp","class":"OC\Installer","type":"->","args":["recognize"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"enableApps","class":"OCA\Settings\Controller\AppSettingsController","type":"->","args":[["recognize"],[]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\AppFramework\Http\Dispatcher","type":"->","args":[{"class":"OCA\Settings\Controller\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\AppFramework\Http\Dispatcher","type":"->","args":[{"class":"OCA\Settings\Controller\AppSettingsController"},"enableApps"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\AppFramework\App","type":"::","args":["OCA\Settings\Controller\AppSettingsController","enableApps",{"class":"OC\AppFramework\DependencyInjection\DIContainer"},["settings.AppSettings.enableApps"]]},{"file":"/var/www/html/lib/base.php","line":1047,"function":"match","class":"OC\Route\Router","type":"->","args":["/settings/apps/enable"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}`

**Comment by dzacball** [comment]
exact same error with me as well. I was using 3.3.4, then the upgrade to 3.3.5 presented me the "missing node binary" problem. So I uninstalled the app, and waited for 3.3.6, and now I have the above issue, and in Admin settings/Recognize I have the error "
An error occurred during face recognition, please check the Nextcloud logs."

**Comment by marcelklehr** [comment]
Can you retry with the latest version? @dzacball Can you post the relevant log entries from the nextcloud log?

**Comment by ralfi** [comment]
Hi @marcelklehr with 3.4.0 install node file works again but enable recognize action fails with hint to log file. I try to setup the loglevel and take a deeper look...

**Comment by ralfi** [comment]
sorry there is 3.5.0 now, will try it

**Comment by ralfi** [comment]
i will close this and set a new issue
