### ISSUE TITLE
It won't scan the files!

### ISSUE THREAD

**Issue by carlchen2007** [nextcloud/recognize#648]
### Which version of recognize are you using?

3.3.6

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Ubuntu Server 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

no Docker

### How much RAM does your server have?

8-16GiB

### What processor Architecture does your CPU have?

Intel Xeon idk

### Describe the Bug

It is searching for Faces but and pictures for a scan but it is not scanning them. Any Idea?

### Expected Behavior

It should scan all my pictures and give me results in my photos app.

### To Reproduce

1.Install Recognition
2. Set it up
3. Look up settings
![image](https://user-images.githubusercontent.com/119757558/213931806-ae93a57c-cca1-49b4-a62f-16432f00ae28.png)

**Comment by jcobreros** [comment]
Having a similar problem with Nextcloud running on Unraid (docker). 32GB RAM x64.
I just want to add that when installing the app, I get an error at the end that says: 
`Error: chmod(): No such file or directory at /config/www/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#146`

After this, the app appears as installed but disabled. I enable the app. Everything looks fine. It downloads the models, then doesn't scan any files. No CPU usage. The Recognize settings page says "Face Recognition: 1095 queued files, last classification: 20 minutes ago". The number of queued files never changes.

**Comment by k0stya63** [comment]
Same problem 
![error](https://user-images.githubusercontent.com/70490566/214089703-9d110bd7-3874-4b9a-b170-cdd0df3c50fc.png)

**Comment by renemadeira** [comment]
> Having a similar problem with Nextcloud running on Unraid (docker). 32GB RAM x64. I just want to add that when installing the app, I get an error at the end that says: `Error: chmod(): No such file or directory at /config/www/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#146`
> 
> After this, the app appears as installed but disabled. I enable the app. Everything looks fine. It downloads the models, then doesn't scan any files. No CPU usage. The Recognize settings page says "Face Recognition: 1095 queued files, last classification: 20 minutes ago". The number of queued files never changes.

I have the same exact behaviour running on docker (debian 11 host).

**Comment by jcobreros** [comment]
> > Having a similar problem with Nextcloud running on Unraid (docker). 32GB RAM x64. I just want to add that when installing the app, I get an error at the end that says: `Error: chmod(): No such file or directory at /config/www/nextcloud/apps/recognize/lib/Migration/InstallDeps.php#146`
> > After this, the app appears as installed but disabled. I enable the app. Everything looks fine. It downloads the models, then doesn't scan any files. No CPU usage. The Recognize settings page says "Face Recognition: 1095 queued files, last classification: 20 minutes ago". The number of queued files never changes.
> 
> I have the same exact behaviour running on docker (debian 11 host).

It ended up working. It's just very slow and in my case it only uses one core. I don't know if my error on install has any effect on the performance.

**Comment by renemadeira** [comment]
> It ended up working. It's just very slow and in my case it only uses one core. I don't know if my error on install has any effect on the performance.

Again, happened the same. After a lot of hours it scanned the folders and the queue empty now. However, it missed most of the faces and objects.

**Comment by carlchen2007** [comment]
I now got a new issue. When the App is activated after several hours the server automatically shuts down. Any idea how to fix?

**Comment by marcelklehr** [comment]
> After a lot of hours it scanned the folders and the queue empty now.

That's typical if an error has occured. the job will be picked up again after 12h by nextcloud cron job.

> However, it missed most of the faces and objects.

Not sure why that is. If you it's using only one core despite setting cores to 0 you might be running in WASM mode which has lower accuracy.

> When the App is activated after several hours the server automatically shuts down.

This is likely unrelated to recognize. I think. It would be very weird. Recognize doesn't shut down your machine, AFAIK.

Closing for now. Feel free to open new issues if anything comes up.
