### ISSUE TITLE
Face Album pictures can't be opened: File with name //files could not be located

### ISSUE THREAD

**Issue by hashworks** [nextcloud/recognize#649]
### Which version of recognize are you using?

3.3.6

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Arch Linux

### Which Docker container are you using to run Nextcloud? (if applicable)

None

### How much RAM does your server have?

64GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Pictures in face albums created by recognize can be listed, but not opened directly. The NC log shows an error message.

```json
{
    "reqId": "PsoVy0ZU3gNhPw2Q0HCh",
    "level": 0,
    "time": "2023-01-23T11:52:16+00:00",
    "remoteAddr": "foo",
    "user": "bar",
    "app": "webdav",
    "method": "PROPFIND",
    "url": "/remote.php/dav/files/bar/files/bar/Photos/Messenger/WhatsApp/IMG-20160325-WA0053.jpg",
    "message": "File with name //files could not be located",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0",
    "version": "25.0.3.2"
    ...
}
```
Opening the images in a new tab prompts a working image download.

### Expected Behavior

Images are opened in the same tab as other photos in the "Photos" app.

### To Reproduce

Try to open face pictures with a left mouse click.

**Comment by phil-lipp** [comment]
I think this is a bug in the photos app. I already opened an issue over there: https://github.com/nextcloud/photos/issues/1594
