### ISSUE TITLE
Video tagging not available, it shows in grey and music tagging not working.

### ISSUE THREAD

**Issue by ManuXD32** [nextcloud/recognize#651]
### Which version of recognize are you using?

3.3.6

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

WASM mode, GPU mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Ubuntu server 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

No docker container

### How much RAM does your server have?

4GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I'm using the binary Node.js v14.21.2.

The object and face recognition works fine, but the video one just can't be activated as it shows in grey and the music one throws an error i can't seem to find as it is not in the nextcloud logs.

### Expected Behavior

Video recognition: to be able to be activated
Music recognition: to work properly

### To Reproduce

I installed the app from nextcloud app store but the models didn't download, i tried using the OCC command "occ recognize:download-models" but it threw an error, so did it when i tried running curl or wget on my own. In order to get the models I downloaded the repo, moved the models folder to the recognize app folder and changed the ownership.

### Debug log

There isn't

**Comment by marcelklehr** [comment]
> Video tagging not available

Video tagging is not available in WASM mode because the model is not compatible with WASM mode. With your specs you shouldn't need to enable WASM mode, though, I believe.

I'll check if music recognition works with WASM in a bit, I can't remember off the top of my head.

**Comment by ManuXD32** [comment]
> > Video tagging not available
> 
> Video tagging is not available in WASM mode because the model is not compatible with WASM mode. With your specs you shouldn't need to enable WASM mode, though, I believe.
> 
> I'll check if music recognition works with WASM in a bit, I can't remember off the top of my head.

Unfortunately it says that my system is not compatible with tensorflow so it enables WASM automatically

**Comment by ManuXD32** [comment]
> > Video tagging not available
> 
> Video tagging is not available in WASM mode because the model is not compatible with WASM mode. With your specs you shouldn't need to enable WASM mode, though, I believe.
> 
> I'll check if music recognition works with WASM in a bit, I can't remember off the top of my head.

So, is it available? The situation is different from the video one, as i can actually check the box to start the analysis but an error always appears.

**Comment by marcelklehr** [comment]
> So, is it available?

The model runs on WASM for me. Preprocessing with ffmpeg may be a problem, though

> Unfortunately it says that my system is not compatible with tensorflow so it enables WASM automatically

That may be a false positive. You can still force disable WASM mode.

> i can actually check the box to start the analysis but an error always appears.

What's the error?

**Comment by ManuXD32** [comment]
> > So, is it available?
> 
> The model runs on WASM for me. Preprocessing with ffmpeg may be a problem, though
> 
> > Unfortunately it says that my system is not compatible with tensorflow so it enables WASM automatically
> 
> That may be a false positive. You can still force disable WASM mode.
> 
> > i can actually check the box to start the analysis but an error always appears.
> 
> What's the error?

I've tried forcing it but it still doesn't work as i install tensorflow but the app keeps asking for it to be installed. 

I can't see the error as it asks me to look for it on the register section but it appears empty.

**Comment by ManuXD32** [comment]
So it seems like the music problem has resolved by itself, after days of seeing that error banner it just changed and it's working now. I guess we can close this issue.

Thank you so much.
