### ISSUE TITLE
Does not respect ignore files in external storage

### ISSUE THREAD

**Issue by ernolf** [nextcloud/recognize#653]
### Which version of recognize are you using?

3.3.6

### Enabled Modes

Object recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.3.2

### Which Operating system do you have installed?

Ubuntu 18.04.6 LTS

### Which Docker container are you using to run Nextcloud? (if applicable)

No Docker, running on bare machine Linux.

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

running `./occ recognize:classify` should "Classify all files with the current settings in one go (will likely take a long time)"
In my understanding those files that mark the directories to be excluded are part of the "current settings" and these directories and all of its descendants (including subdirectories), should be left untouched.
In fact, the occ command doesn't respect these exclusion rules.

In addition, the tagging activities are not been recorded as `activity` when classified with this occ-command. It happens entirely clandestine.

### Expected Behavior

- The behavior described in the README.md: path/to/your/folder/* to be excluded.
- Register each assigned tag as an activity in the `oc_activity` table of database as done when classified per cron job, so that in the `Details` view of the files it can be understood what was allocated and when.

### To Reproduce

Make your settings (image- music tagging, etc.) as usual, but set the number of files to be processed per job run to "0". No jobs will be scheduled to the cron-queue this way.

`sudo -u www-data /usr/bin/php -f /var/www/nextcloud/occ recognize:classify`

Since I am connected via ssh and it can take days, (in my case it took a week until i killed the process) I did this from inside a `screen` session with the occ - option `--quiet`.

### Debug log

.

**Comment by marcelklehr** [comment]
Which marker files did you use specifically? .nomedia? or .noimage?

**Comment by ernolf** [comment]
> Which marker files did you use specifically? .nomedia? or .noimage?

I've used both, but I noticed it first in directories marked with .nomedia. I killed the job before it reached directories with .noimage. It was tagging thousands of jpeg files from blender animation projects . It would have taken weeks.

**Comment by marcelklehr** [comment]
mh, that's strange. the mechanism for checking if a file should be ignored is the same. I'll have to write a unit test for this

**Comment by ernolf** [comment]
> Is it possible, the ignore markers were created after the classify command was started?

No. But eventually important: It was on *External storage* where I noticed this.

**Comment by marcelklehr** [comment]
Was it a setup like this?

```
/foobar
    /.nomedia
        / -> external storage
           ...
```

**Comment by ernolf** [comment]
> Was it a setup like this?
> ```
> /foobar
>     /.nomedia
>     / -> external storage
>            ...
> ```

No, like this

```
/foobar
    / -> external storage
        /.nomedia
           ...
```

The .nomedia files *inside* of the external storages

**Comment by daufinsyd** [comment]
Hi there,
I can reproduce the bug with external storage (NFS)

```
/nfs-folder-in-nextcloud
    / -> external storage
        /.nomedia
        /.noimage
           ...
```
Nextcloud 25.0.4
Collaborative tags 1.15.0
Recognize 3.7.0

**Comment by marcelklehr** [comment]
I've investigated this a bit further, it seems that generally files that have been added to the external storage from outside of nextcloud will not trigger recognize's hooks and will just be ignored. Did you all create these ignore files inside the nextcloud UI / via the desktop client or outside of nextcloud on the raw filesystem?

**Comment by PyroniaDE** [comment]
> Did you all create these ignore files inside the nextcloud UI / via the desktop client or outside of nextcloud on the raw filesystem?

Mine were created via filesystem outside of nextcloud. But If you make hidden files visible in nextcloud, you are able to see them via nextcloud browser frontend.

**Comment by daufinsyd** [comment]
Same as @PyroniaDE for me

**Comment by Fran6nd** [comment]
Same here, same issue, same symptoms.

**Comment by victorkp** [comment]
Same setup, same issue, same symptoms.

**Comment by marcelklehr** [comment]
Finally confirmed. The problem only occurs with ignore files in the root of a storage

**Comment by Christophmarczinzik** [comment]
Hello, 
has anyone found a solution yet? My NAS always automatically creates a snapshot folder next to my pictures folder and despite .nomedia, nextcloud always searches the snapshot folder and messes everything up.

**Comment by marcelklehr** [comment]
@Christophmarczinzik Can you please create a new issue if this is a problem that you are having currently? This is supposed to have been resolved a long time ago, so we should investigate if you are hitting this again now
