### ISSUE TITLE
mariadb query runs too long when enabling Face Recognition

### ISSUE THREAD

**Issue by Daddy-ohh** [nextcloud/recognize#671]
### Which version of recognize are you using?

3.4.0

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Rasberry PI 4 Bullseye

### Which Docker container are you using to run Nextcloud? (if applicable)

not applicable

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

Turning on "Enable Face Recognition" causes a long running MariaDB query to start.  I have not seen the query end yet.  I identified the query as:

SELECT `file`.`fileid`, `storage`, `path`, `path_hash`, `file`.`parent`, `file`.
`name`, `mimetype`, `mimepart`, `size`, `mtime`, `storage_mtime`, `encrypted`, `
etag`, `permissions`, `checksum`, `unencrypted_size` FROM `oc_filecache` `file`
LEFT JOIN `oc_vcategory_to_object` `tagmap` ON `file`.`fileid` = `tagmap`.`objid
` LEFT JOIN `oc_systemtag_object_mapping` `systemtagmap` ON (`file`.`fileid` = `
systemtagmap`.`objectid`) AND (`systemtagmap`.`objecttype` = 'files') LEFT JOIN
`oc_vcategory` `tag` ON (`tagmap`.`type` = `tag`.`type`) AND (`tagmap`.`category
id` = `tag`.`id`) AND (`tag`.`type` = 'files') AND (`tag`.`uid` = 'daddyohh') LE
FT JOIN `oc_systemtag` `systemtag` ON (`systemtag`.`id` = `systemtagmap`.`system
tagid`) AND (`systemtag`.`visibility` = '1') WHERE ((`tag`.`category`  COLLATE u
tf8mb4_general_ci LIKE '%recog%') OR (`systemtag`.`name`  COLLATE utf8mb4_genera
l_ci LIKE '%recog%')) AND ((`storage` = 2) AND ((`path` = 'files') OR (`path` LI
KE 'files/%'))) ORDER BY `mtime` + '0' desc LIMIT 5;

### Expected Behavior

Face recognition should complete as designed.

### To Reproduce

Turn on "Enable Face Recognition".

**Comment by marcelklehr** [comment]
mh, the query you posted looks like a search query. Recognize doesn't contain code that searches for `recog` with `LIMIT 5`. Could the problem be a different query?

**Comment by Daddy-ohh** [comment]
@marcelklehr - thanks for checking on that.

I will continue to research the query itself.

Since the query, which seems to run forever (at least an hour), is triggered by enabling face recognition in recognize (this is repeatable), I will try to find a connection between recognize and some other app.

I have already gone through optimizing nextcloud and mariadb per the online docs I could find.  I am going to ANALYZE the query to see if I can find something I may have missed.

Closing as a non-issue in recognize.

**Comment by Daddy-ohh** [comment]
By monitoring the mariadb query log, I found something that indicates I should reopen this issue.

It appears that during every other (at least not every) run of cron.php (scheduled via crontab in my case), the below query (with an incrementing cluster_id) executes forever:

SELECT `id`, `user_id`, `file_id`, `x`, `y`, `height`, `width`, `vector`, `cluster_id`, `threshold` FROM `oc_recognize_face_detections` WHERE `cluster_id` = '1'
.
.
.
SELECT `id`, `user_id`, `file_id`, `x`, `y`, `height`, `width`, `vector`, `cluster_id`, `threshold` FROM `oc_recognize_face_detections` WHERE `cluster_id` = '2162'
.
.
.
(repeat forever)

Let me know if you need help solving this.

**Comment by marcelklehr** [comment]
The query runs forever, or it doesn't stop sending those queries?

**Comment by Daddy-ohh** [comment]
Yes, good point - each query completes quickly and the next one starts.

**Comment by marcelklehr** [comment]
Alright. I guess that's to be expected on larger amounts of pictures. The good news is, we have a new clustering algorithm now that does not do this anymore. So, stay tuned for the next release :)

**Comment by Daddy-ohh** [comment]
Thanks for the heads up!

**Comment by Daddy-ohh** [comment]
Until then, I modified the crontab entry, run every 30 minutes, to kill the task after 15 minutes:

*/30  *  *  *  *  timeout 15m php -f /var/www/nextcloud/cron.php
