### ISSUE TITLE
People: click on thumbnail does not show photo

### ISSUE THREAD

**Issue by gody01** [nextcloud/recognize#672]
### Which version of recognize are you using?

3.4.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

RockyLinux 8

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

8G

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When clickin on thumbnail in People, picture is not displayed.

### Expected Behavior

When clicking on thumnail photo should be displayed. (Start slideshow bar is displayed, but with no photos).

### To Reproduce

Select People
Select one cluster (face)
Click on one of thumbnails
Only rotating icon displayed with no photo. But Start slideshgow bar is displayed.

### Debug log

In browser console log there is wrong URL:

https://nc.gody.si/remote.php/dav/files/gody/files/gody/Slike/AnalogneFotke/Familja-Godeci/1991/05-04-Dan%C4%8Di_18_RD/58209f03-50e4-4aa0-a0e2-0993b83ce204.jpg

Problematic part is duoplicated "root": files/gody/files/gody/

it sohuld be:
https://nc.gody.si/remote.php/dav/files/gody/Slike/AnalogneFotke/Familja-Godeci/1991/05-04-Dan%C4%8Di_18_RD/58209f03-50e4-4aa0-a0e2-0993b83ce204.jpg

[nc.gody.si-1675678960159.log](https://github.com/nextcloud/recognize/files/10661992/nc.gody.si-1675678960159.log)

**Comment by marcelklehr** [comment]
> I think its probably coming with Nextcloud 25.0.4

Correct.
