### ISSUE TITLE
Cores=0 is not using all cores

### ISSUE THREAD

**Issue by Chuckame** [nextcloud/recognize#682]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

UnraidOS

### Which Docker container are you using to run Nextcloud? (if applicable)

apache (question not clear, I give the image)

### How much RAM does your server have?

8gb, php limit 2G

### What processor Architecture does your CPU have?

arm64

### Describe the Bug

During execution of `occ recognize:classify`, there is only 1 cpu core used even if the core limitation is to `0` (default) so it's computing slowly (1 photo every 2-4 seconds) 
![image](https://user-images.githubusercontent.com/16419143/218544370-aed58089-4e27-4f32-92d7-5e64055feb1e.png)

### Expected Behavior

During execution of `occ recognize:classify`, all the cpu cores should burn when the core limitation is to `0` (default)

### To Reproduce

execute as www-data `php occ recognize:classify` in `/var/www/html` folder

### Debug log

No error

**Comment by chrissi5120** [comment]
same behaviour at my side, also running unraid, all relevant software in same version

**Comment by marcelklehr** [comment]
> WASM mode

Some parts of the WASM stack in this app cannot handle multithreading for some reason. So, this is expected. A comment near the setting is probably in order.

**Comment by Chuckame** [comment]
Sorry but if I've written an issue, it's to understand why, and improve Recognize to be better documented on some points 😊
Here a screenshot that shows you (in French) that there is absolutely no information about the multithreading issue with wasm. So this issue should not be closed right?
![IMG_20230219_181932](https://user-images.githubusercontent.com/16419143/219964042-13abd5d3-86ee-47e9-bb08-991e291240b8.jpg)


Also, why we can't do multithreading with wasm?

**Comment by marcelklehr** [comment]
That's a good question. The answer lies here: https://github.com/tensorflow/tfjs/issues/3830
