### ISSUE TITLE
Nothing started to be recognized automatically

### ISSUE THREAD

**Issue by Chuckame** [nextcloud/recognize#683]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

UnraidOS

### Which Docker container are you using to run Nextcloud? (if applicable)

apache (question not clear, I give the image)

### How much RAM does your server have?

8gb, php limit 2G

### What processor Architecture does your CPU have?

arm64

### Describe the Bug

After having the bug of https://github.com/nextcloud/recognize/issues/676, I rebooted and nothing happened. I had to execute `php occ recognize:classify`. the previous check were marked as the year of 1970.

### Expected Behavior

The ML should work without doing manual cli

### To Reproduce

I don't know

### Debug log

Nothing

**Comment by Chuckame** [comment]
Update: the tagging process is executing in background automatically since `php occ recognize:classify` was executed (and canceled after a few minutes). Also works after reboots.

**Comment by marcelklehr** [comment]
Glad it works now.

**Comment by fbievan** [comment]
having this issue, not quite sure how to fix.

**Comment by marcelklehr** [comment]
@fbievan please open a new issue
