### ISSUE TITLE
Path to Node.js is empty in settings

### ISSUE THREAD

**Issue by ErikSteiner** [nextcloud/recognize#686]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Ubuntu 22.10 (GNU/Linux 5.19.0-1013-raspi aarch64)

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud:25.0.3-fpm-alpine

### How much RAM does your server have?

8 GiB

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

I installed Recognize from the App Store. When I had a look into the Administrator Panel and the log files, it showed me the following:
```
[recognize] Fehler: Failed to install Tensorflow.js: sh: /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/scripts/install.js: Permission denied

POST /settings/apps/enable
from XXX.XXX.XXX.XXX by Admin at 2023-02-16T20:27:15+00:00

[no app in context] Fehler: Exception: Failed to install Tensorflow.js: sh: /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/scripts/install.js: Permission denied at <<closure>>

 0. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 90
    OCA\Recognize\Migration\InstallDeps->runTfjsInstall("")
 1. /var/www/html/lib/private/Repair.php line 127
    OCA\Recognize\Migration\InstallDeps->run(OC\Repair {})
 2. /var/www/html/lib/private/legacy/OC_App.php line 1064
    OC\Repair->run()
 3. /var/www/html/lib/private/Installer.php line 164
    OC_App::executeRepairSteps("recognize", ["OCA\\Recognize ... "])
 4. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp("recognize")
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->enableApps(["recognize"], [])
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
 7. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
 8. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, ["settings.AppSettings.enableApps"])
 9. /var/www/html/lib/base.php line 1047
    OC\Route\Router->match("/settings/apps/enable")
10. /var/www/html/index.php line 36
    OC::handleRequest()

POST /settings/apps/enable
from XXX.XXX.XXX.XXX by Admin at 2023-02-16T20:27:15+00:00
```

### Expected Behavior

I do not expect these error messages.

### To Reproduce

I navigated to the App Store of Nextcloud and clicked "Install".
If it helps, I could try to share my docker composer file.
I don't know about `Enabled Mode` and `TensorFlow mode`, but it was required to submit this issue.

**Comment by ErikSteiner** [comment]
I saw, that in the admin settings, related to recognize, the path to the node.js is empty. The node.js is definitely there under `/html/custom_apps/recognize/bin\node`. Unfortunately, I have no idea how to insert the path in the settings. Should I add the path that includes root like `/var/www/html/custom_apps/recognize/bin/` or should I add the path from the custom_apps folder like this `/recognize/bin/`?
Is a slash or a backslash required?

**Comment by marcelklehr** [comment]
`/var/www/html/custom_apps/recognize/bin/` should work. Since tensorflow failed to install, you'll only be able to run in WASM mode like this. Unless you install manually: https://github.com/nextcloud/recognize/wiki/Manual-install
Or you fix your permissions error and reinstall recognize.

**Comment by ErikSteiner** [comment]
It is funny to see, that we both came to the same conclusion at the very same time: 
[Issue 688](https://github.com/nextcloud/recognize/issues/688#issuecomment-1436038918)

If I try to execute node in the container of my Nextcloud image (nextcloud:25.0.3-fpm-alpine), it seems like this node version is not build against arm64 musl.

```
/var/www/html # cd /var/www/html/custom_apps/recognize/bin/
/var/www/html/custom_apps/recognize/bin # ls
arm64.tar.gz  node
/var/www/html/custom_apps/recognize/bin # sh node
node: line 1: ELFPa@8: not found
node: line 2: syntax error: unexpected ")"
```
So I assume, that I do not need to include the specific node version in my image by hand?

**Comment by marcelklehr** [comment]
> sh node

That's not how you execute node, I believe. Try `./node`

**Comment by ErikSteiner** [comment]
From your recent commit, I assume that in 3.5.0 recognize is not shipped with Node.js for ARM64 Musl and so is the output:
```
/var/www/html/custom_apps/recognize/bin # sh ./node --version
./node: line 1: ELFPa@8: not found
./node: line 2: syntax error: unexpected ")"
/var/www/html/custom_apps/recognize/bin # ./node --version
sh: ./node: not found
```

**Comment by marcelklehr** [comment]
Ah, I didn't see you're on alpine. Yep, then it's a known issue. Will be fixed in the next release.

**Comment by ErikSteiner** [comment]
Thank you very much for the support!
