### ISSUE TITLE
PHP Fatal error on recognize:cluster-faces

### ISSUE THREAD

**Issue by ced455** [nextcloud/recognize#687]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

alpine 3.15 

### Which Docker container are you using to run Nextcloud? (if applicable)

linuxserver/nextcloud:25.0.3

### How much RAM does your server have?

32 GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

After running `occ recognize:reset-face-clusters` I tried to run `occ recognize:cluster-faces`

This is the error i get : 
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 163840 bytes) in /config/www/nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php on line 449

I haven't set a limit for my docker and my server have 16gb or ram left.
Did I miss a parameter somewhere ?

### Expected Behavior

Not crash during the cluster face process

### To Reproduce

Run occ recognize:cluster-faces

### Debug log

occ recognize:cluster-faces
Clustering face detections for user XXX1
ClusterDebug: Retrieving face detections for user XXX1
ClusterDebug: Found 44 unclustered detections. Calculating clusters.
ClusterDebug: Clustering complete. Total num of clustered detections: 5
Clustering face detections for user XXX2
ClusterDebug: Retrieving face detections for user XXX2
ClusterDebug: Found 9166 unclustered detections. Calculating clusters.
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 163840 bytes) in /config/www/nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php on line 449

**Comment by avephill** [comment]
I'm getting the exact same error with all the same parameters as @ced455 except my machine runs arch linux and has 16GB RAM

**Comment by iamklaus** [comment]
I had the same problem.

Solution: Increase your PHP memory limit.

My php memory limit was 2G. I creased it to 4G. Afterwards the clustering process finished sucessfully.

**Comment by avephill** [comment]
> Solution: Increase your PHP memory limit.
I was looking into this but couldn’t figure it out for some reason. I couldn’t find a php.ini file and the setting .htaccess wasn’t working it seemed

**Comment by iamklaus** [comment]
> > Solution: Increase your PHP memory limit.
> 
> I was looking into this but couldn’t figure it out for some reason. I couldn’t find a php.ini file and the setting .htaccess wasn’t working it seemed

If you are using a docker container, check the documentation of the docker container you are using. Usually you can pass the PHP memory limit as an environment variable to docker.

**Comment by avephill** [comment]
>  Usually you can pass the PHP memory limit as an environment variable to docker.

for `nextcloud:apache` I was able to pass it in my docker-compose as PHP_MEMORY_LIMIT
Thank you!!!
