### ISSUE TITLE
Recognize stopped finding its Node file

### ISSUE THREAD

**Issue by RikkiBC** [nextcloud/recognize#688]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

Nextcloud 25.0.3

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

Nextcloud AIO

### How much RAM does your server have?

8 GiB

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

Some days ago, Recognize stopped picking faces up from new photos. I just got around to checking the logs and it looks like it's stopped being able to talk to its Node file or something?

This is running on Nextcloud AIO, and I can't see any reason why it was working before and has now stopped working. I've found the node file that it's complaining is missing, and I haven't made any major changes to the system (just installed a new app, Custom Menu, which should be completely unrelated).

### Expected Behavior

Recognize should continue working.

### To Reproduce

Recognize stopped working (I wish there were more details I could provide here, other than the logs attached).

### Debug log

From the Admin Settings --> Logging:

```
Error	core	RuntimeException: Classifier process error	
8 minutes ago
Warning	recognize	Classifier process output: sh: exec: line 0: /var/www/html/custom_apps/recognize/bin/node: not found 	
8 minutes ago
Error	core	RuntimeException: Classifier process error	
8 minutes ago
Warning	recognize	Classifier process output: sh: exec: line 0: /var/www/html/custom_apps/recognize/bin/node: not found 	
8 minutes ago
Error	core	RuntimeException: Classifier process error	
18 minutes ago
Warning	recognize	Classifier process output: sh: exec: line 0: /var/www/html/custom_apps/recognize/bin/node: not found 	
18 minutes ago
Error	core	RuntimeException: Classifier process error	
18 minutes ago
Warning	recognize	Classifier process output: sh: exec: line 0: /var/www/html/custom_apps/recognize/bin/node: not found 	
18 minutes ago
Error	no app in context	Exception: Failed to install Tensorflow.js: sh: /var/www/html/custom_apps/recognize/bin/node: not found	
26 minutes ago
Error	recognize	Failed to install Tensorflow.js: sh: /var/www/html/custom_apps/recognize/bin/node: not found	
26 minutes ago
Error	no app in context	Exception: Failed to install Tensorflow.js: sh: /var/www/html/custom_apps/recognize/bin/node: not found	
26 minutes ago
```

I can confirm that the node file is in fact still where it should be:

![image](https://user-images.githubusercontent.com/57303982/219657274-21067b58-f176-48bd-b130-8f7efe013173.png)

**Comment by szaimen** [comment]
As I said elsewhere, you might need to enable gcompat on arm64 but otherwise no clue. 

However adding gcompat seems to break recognize on x64. This is why we removed it again with the latest version...

**Comment by szaimen** [comment]
Actually, this looks about right after I think about it. So let me add this back but only in case of arm64.

**Comment by qudiqudi** [comment]
> As I said elsewhere, you might need to add gcompat on arm64 by using https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container but otherwise no clue if that doeesnt work.
> 
> However adding gcompat breaks recognize on x64. This is why we removed it again with the latest version...

Well I'm on x64 and it does not work with or without gcompat.

**Comment by szaimen** [comment]
> Well I'm on x64 and it does not work with or without gcompat.

Then I am out of ideaa again. However some other people reported that it works foe them after upgrading AIO to 4.3.4...

**Comment by szaimen** [comment]
Do you have something useful in the logs?

**Comment by qudiqudi** [comment]
> works foe them after upgrading AIO to 4.3.4...

This is what irritates me, I've not changed anything on my config, the mastercontainer updated itself on the nightly sheduled backup task and boom, Recognize stopped working...



> Do you have something useful in the logs?

Only what I've already posted, which is the same as @RikkiBC posted above.
´´´
core	RuntimeException: Classifier process error	
´´´

**Comment by szaimen** [comment]
> core	RuntimeException: Classifier process error

Nothing more? Without more it is useless...

**Comment by qudiqudi** [comment]
This. 
```
[recognize] Warnung: Classifier process output: sh: exec: line 0: /var/www/html/custom_apps/recognize/bin/node: not found


at 2023-02-17T16:48:32+00:00
```
That's it. And the Error ribbon in the Recognize GUI telling me to check the logs.
Really unsatisfying.

**Comment by szaimen** [comment]
Is the node binary still there?

**Comment by qudiqudi** [comment]
Yep.
<img width="478" alt="Bildschirm­foto 2023-02-17 um 17 54 34" src="https://user-images.githubusercontent.com/5947641/219715427-d0d3487f-e51e-4bd2-9030-3e75f5e46453.png">

**Comment by szaimen** [comment]
As I said: out of ideas then. We dont do anything unusual in AIO except using Alpine Linux as base.

**Comment by qudiqudi** [comment]
Ok, thanks anyways for your time.

**Comment by qudiqudi** [comment]
I could resolve this by deleting the app, cleaning all tags and models, cleaning the app folder, re-create (compose force--recreate) the the docker master container and re-install the app and let it do a complete re-scan of my files.
I don't know if any one of these steps or the conjunction did the trick. @szaimen I removed gcompat again, as like you said it breaks the app and is apparently not necessary on x64.

**Comment by szaimen** [comment]
> re-install the app

I suppose this may have done the trick for you. Glad that you've found a fix/workaround!

**Comment by szaimen** [comment]
@RikkiBC can you re-add gcompat by using https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container, reinstall recognize and check if that makes it work for you? I'll try to find out if gcomoat is really required for arm64...

**Comment by marcelklehr** [comment]
> I suppose this may have done the trick for you. Glad that you've found a fix/workaround!

Yes, i guess the reason is that with gcompat enabled recognize downloads the normal x64 executable of node. AIO recently removed gcompat again, but the gnu libc dependent node executable remained. Reinstalling recognize without gcompat installs the alpine-specific node executable.

**Comment by marcelklehr** [comment]
I seem to have not considered ARM64 users may be running Alpine as well: https://github.com/nextcloud/recognize/blob/main/lib/Migration/InstallDeps.php#L100

**Comment by RikkiBC** [comment]
> @RikkiBC can you re-add gcompat by using https://github.com/nextcloud/all-in-one#how-to-add-os-packages-permanently-to-the-nextcloud-container, reinstall recognize and check if that makes it work for you? I'll try to find out if gcomoat is really required for arm64...

@szaimen , apologies for my ignorance but just confirming. Can I just run the docker command with containers running? Containers stopped? Or do I have to completely uninstall everything then run that docker command with the gcompat command to reinstall it?

**Comment by szaimen** [comment]
> Can I just run the docker command with containers running?

yes you can. But you need to restart them from the AIO interface afterwards in order to apply that change.

**Comment by RikkiBC** [comment]
Thanks @szaimen , I went to update the environment variable with:

```
sudo docker run \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 80:80 \
--publish 8080:8080 \
--publish 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
-e NEXTCLOUD_DATADIR="/mnt/sdb/nc-data" \
-e NEXTCLOUD_ADDITIONAL_APKS="imagemagick gcompat" \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest-arm64
```

However I got the following error:

`docker: Error response from daemon: Conflict. The container name "/nextcloud-aio-mastercontainer" is already in use by container "5f61913a0e0e165bc0975983a35dadf25181c01e8859cd53b6d6fa02bf237125". You have to remove (or rename) that container to be able to reuse that name.`

I looked around for how to add or update an environment variable on an already-setup/already-running container, and found mixed recommendations. I don't suppose there's a recommended way for Nextcloud AIO, on how to update the environment vars?

**Comment by szaimen** [comment]
> I don't suppose there's a recommended way for Nextcloud AIO, on how to update the environment vars?

There is: you need to stop the mastercontainer, remove it and recreate it with changed settings
