### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by fr3ddy-sudo** [nextcloud/recognize#689]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26 beta4

### Which Operating system do you have installed?

Gentoo

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

64GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

<html>
<body>

OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_queue_imagenet' doesn't exist/var/www/localhost/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 295:OC\DB\Exceptions\DbalException::wrap()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Db/QueueMapper.php - line 150:OC\DB\QueryBuilder\QueryBuilder->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Service/QueueService.php - line 116:OCA\Recognize\Db\QueueMapper->count()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Controller/AdminController.php - line 74:OCA\Recognize\Service\QueueService->count()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Recognize\Controller\AdminController->countQueued()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest()Verursacht durch Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_queue_imagenet' doesn't exist/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1814:Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1749:Doctrine\DBAL\Connection->handleDriverException()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1055:Doctrine\DBAL\Connection->convertExceptionDuringQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/Connection.php - line 264:Doctrine\DBAL\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php - line 345:OC\DB\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 280:Doctrine\DBAL\Query\QueryBuilder->execute()/var/www/localhost/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 293:OC\DB\QueryBuilder\QueryBuilder->execute()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Db/QueueMapper.php - line 150:OC\DB\QueryBuilder\QueryBuilder->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Service/QueueService.php - line 116:OCA\Recognize\Db\QueueMapper->count()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Controller/AdminController.php - line 74:OCA\Recognize\Service\QueueService->count()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Recognize\Controller\AdminController->countQueued()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest()Verursacht durch Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_queue_imagenet' doesn't exist/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php - line 77:Doctrine\DBAL\Driver\PDO\Exception::new()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1050:Doctrine\DBAL\Driver\PDO\Connection->query()/var/www/localhost/htdocs/nextcloud/lib/private/DB/Connection.php - line 264:Doctrine\DBAL\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php - line 345:OC\DB\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 280:Doctrine\DBAL\Query\QueryBuilder->execute()/var/www/localhost/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 293:OC\DB\QueryBuilder\QueryBuilder->execute()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Db/QueueMapper.php - line 150:OC\DB\QueryBuilder\QueryBuilder->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Service/QueueService.php - line 116:OCA\Recognize\Db\QueueMapper->count()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Controller/AdminController.php - line 74:OCA\Recognize\Service\QueueService->count()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Recognize\Controller\AdminController->countQueued()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest()Verursacht durch PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_queue_imagenet' doesn't exist/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php - line 72:PDO->query()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1050:Doctrine\DBAL\Driver\PDO\Connection->query()/var/www/localhost/htdocs/nextcloud/lib/private/DB/Connection.php - line 264:Doctrine\DBAL\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php - line 345:OC\DB\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 280:Doctrine\DBAL\Query\QueryBuilder->execute()/var/www/localhost/htdocs/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 293:OC\DB\QueryBuilder\QueryBuilder->execute()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Db/QueueMapper.php - line 150:OC\DB\QueryBuilder\QueryBuilder->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Service/QueueService.php - line 116:OCA\Recognize\Db\QueueMapper->count()/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Controller/AdminController.php - line 74:OCA\Recognize\Service\QueueService->count()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Recognize\Controller\AdminController->countQueued()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest()
--

</body>
</html>

### Expected Behavior

How i can repair the database

### To Reproduce

i download it in nextcloud and it just happend

### Debug log

<html>
<body>

OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_face_clusters' doesn't exist/var/www/localhost/htdocs/nextcloud/lib/private/DB/ConnectionAdapter.php - line 68:OC\DB\Exceptions\DbalException::wrap()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryDays.php - line 328:OC\DB\ConnectionAdapter->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryPeopleRecognize.php - line 75:OCA\Memories\Db\TimelineQuery->executeQueryWithCTEs()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Controller/PeopleController.php - line 59:OCA\Memories\Db\TimelineQuery->getPeopleRecognize()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Memories\Controller\PeopleController->recognizePeople()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest()Verursacht durch Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_face_clusters' doesn't exist/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1814:Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1749:Doctrine\DBAL\Connection->handleDriverException()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1055:Doctrine\DBAL\Connection->convertExceptionDuringQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/Connection.php - line 264:Doctrine\DBAL\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/ConnectionAdapter.php - line 65:OC\DB\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryDays.php - line 328:OC\DB\ConnectionAdapter->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryPeopleRecognize.php - line 75:OCA\Memories\Db\TimelineQuery->executeQueryWithCTEs()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Controller/PeopleController.php - line 59:OCA\Memories\Db\TimelineQuery->getPeopleRecognize()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Memories\Controller\PeopleController->recognizePeople()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest()Verursacht durch Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_face_clusters' doesn't exist/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php - line 103:Doctrine\DBAL\Driver\PDO\Exception::new()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1045:Doctrine\DBAL\Driver\PDO\Statement->execute()/var/www/localhost/htdocs/nextcloud/lib/private/DB/Connection.php - line 264:Doctrine\DBAL\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/ConnectionAdapter.php - line 65:OC\DB\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryDays.php - line 328:OC\DB\ConnectionAdapter->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryPeopleRecognize.php - line 75:OCA\Memories\Db\TimelineQuery->executeQueryWithCTEs()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Controller/PeopleController.php - line 59:OCA\Memories\Db\TimelineQuery->getPeopleRecognize()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Memories\Controller\PeopleController->recognizePeople()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest()Verursacht durch PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_recognize_face_clusters' doesn't exist/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php - line 101:PDOStatement->execute()/var/www/localhost/htdocs/nextcloud/3rdparty/doctrine/dbal/src/Connection.php - line 1045:Doctrine\DBAL\Driver\PDO\Statement->execute()/var/www/localhost/htdocs/nextcloud/lib/private/DB/Connection.php - line 264:Doctrine\DBAL\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/lib/private/DB/ConnectionAdapter.php - line 65:OC\DB\Connection->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryDays.php - line 328:OC\DB\ConnectionAdapter->executeQuery()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Db/TimelineQueryPeopleRecognize.php - line 75:OCA\Memories\Db\TimelineQuery->executeQueryWithCTEs()/var/www/localhost/htdocs/nextcloud/apps/memories/lib/Controller/PeopleController.php - line 59:OCA\Memories\Db\TimelineQuery->getPeopleRecognize()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Memories\Controller\PeopleController->recognizePeople()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest() |   | 2023-02-18T01:37:46+0100
-- | -- | --
Fehler | no app in context | Exception: Failed to install Tensorflow.js: # # Fatal error in , line 0 # Check failed: reservation_.SetPermissions(protect_start, protect_size, permission). # # # #FailureMessage Object: 0x7ffdcf397890 1: 0xaa6321 [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 2: 0x1a3b584 V8_Fatal(char const*, ...) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 3: 0xdd081f [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 4: 0xdf6978 v8::internal::PagedSpace::SetReadAndExecutable() [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 5: 0xd1f4df v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*, v8::internal::StartupDeserializer*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 6: 0x1130d5b [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 7: 0xbe2758 v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 8: 0xa78bb9 node::NodeMainInstance::NodeMainInstance(v8::Isolate::CreateParams*, uv_loop_s*, node::MultiIsolatePlatform*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 9: 0xa0174d node::Start(int, char**) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 10: 0x7f227eb7334a [/usr/lib64/libc.so.6] 11: 0x7f227eb733fc __libc_start_main [/usr/lib64/libc.so.6] 12: 0x98a4cc [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]/var/www/localhost/htdocs/nextcloud/apps/recognize/lib/Migration/InstallDeps.php - line 90:OCA\Recognize\Migration\InstallDeps->runTfjsInstall()/var/www/localhost/htdocs/nextcloud/lib/private/Repair.php - line 126:OCA\Recognize\Migration\InstallDeps->run()/var/www/localhost/htdocs/nextcloud/lib/private/legacy/OC_App.php - line 1077:OC\Repair->run()/var/www/localhost/htdocs/nextcloud/lib/private/Installer.php - line 164:OC_App::executeRepairSteps()/var/www/localhost/htdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php - line 451:OC\Installer->installApp()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 230:OCA\Settings\Controller\AppSettingsController->enableApps()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 137:OC\AppFramework\Http\Dispatcher->executeController()/var/www/localhost/htdocs/nextcloud/lib/private/AppFramework/App.php - line 183:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/localhost/htdocs/nextcloud/lib/private/Route/Router.php - line 315:OC\AppFramework\App::main()/var/www/localhost/htdocs/nextcloud/lib/base.php - line 1050:OC\Route\Router->match()/var/www/localhost/htdocs/nextcloud/index.php - line 36:OC::handleRequest() |   | 2023-02-18T01:37:43+0100
Fehler | recognize | Failed to install Tensorflow.js: # # Fatal error in , line 0 # Check failed: reservation_.SetPermissions(protect_start, protect_size, permission). # # # #FailureMessage Object: 0x7ffdcf397890 1: 0xaa6321 [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 2: 0x1a3b584 V8_Fatal(char const*, ...) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 3: 0xdd081f [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 4: 0xdf6978 v8::internal::PagedSpace::SetReadAndExecutable() [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 5: 0xd1f4df v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*, v8::internal::StartupDeserializer*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 6: 0x1130d5b [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 7: 0xbe2758 v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 8: 0xa78bb9 node::NodeMainInstance::NodeMainInstance(v8::Isolate::CreateParams*, uv_loop_s*, node::MultiIsolatePlatform*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 9: 0xa0174d node::Start(int, char**) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 10: 0x7f227eb7334a [/usr/lib64/libc.so.6] 11: 0x7f227eb733fc __libc_start_main [/usr/lib64/libc.so.6] 12: 0x98a4cc [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] |   | 2023-02-18T01:37:43+0100
Fehler | no app in context | Exception: Failed to install Tensorflow.js: # # Fatal error in , line 0 # Check failed: reservation_.SetPermissions(protect_start, protect_size, permission). # # # #FailureMessage Object: 0x7fff460eeed0 1: 0xaa6321 [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 2: 0x1a3b584 V8_Fatal(char const*, ...) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 3: 0xdd081f [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 4: 0xdf6978 v8::internal::PagedSpace::SetReadAndExecutable() [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 5: 0xd1f4df v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*, v8::internal::StartupDeserializer*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 6: 0x1130d5b [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 7: 0xbe2758 v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 8: 0xa78bb9 node::NodeMainInstance::NodeMainInstance(v8::Isolate::CreateParams*, uv_loop_s*, node::MultiIsolatePlatform*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 9: 0xa0174d node::Start(int, char**) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 10: 0x7f1d6877334a [/usr/lib64/libc.so.6] 11: 0x7f1d687733fc __libc_start_main [/usr/lib64/libc.so.6] 12: 0x98a4cc [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] |   | 2023-02-18T01:37:43+0100
Fehler | recognize | Failed to install Tensorflow.js: # # Fatal error in , line 0 # Check failed: reservation_.SetPermissions(protect_start, protect_size, permission). # # # #FailureMessage Object: 0x7fff460eeed0 1: 0xaa6321 [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 2: 0x1a3b584 V8_Fatal(char const*, ...) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 3: 0xdd081f [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 4: 0xdf6978 v8::internal::PagedSpace::SetReadAndExecutable() [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 5: 0xd1f4df v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*, v8::internal::StartupDeserializer*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 6: 0x1130d5b [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 7: 0xbe2758 v8::Isolate::Initialize(v8::Isolate*, v8::Isolate::CreateParams const&) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 8: 0xa78bb9 node::NodeMainInstance::NodeMainInstance(v8::Isolate::CreateParams*, uv_loop_s*, node::MultiIsolatePlatform*, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const*) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 9: 0xa0174d node::Start(int, char**) [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node] 10: 0x7f1d6877334a [/usr/lib64/libc.so.6] 11: 0x7f1d687733fc __libc_start_main [/usr/lib64/libc.so.6] 12: 0x98a4cc [/var/www/localhost/htdocs/nextcloud/apps/recognize/bin/node]

</body>
</html>

**Comment by marcelklehr** [comment]
0. Uninstall recognize
1. Make sure all database tables starting with 'recognize' are removed.
2. Remove all entries related to recognize are removed in oc_migrations database table
3. Install recognize
