### ISSUE TITLE
Could not fetch storage root without details

### ISSUE THREAD

**Issue by a0g83agbc84** [nextcloud/recognize#696]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3.2

### Which Operating system do you have installed?

Debian 4.19.269-1

### Which Docker container are you using to run Nextcloud? (if applicable)

Bare metal

### How much RAM does your server have?

8Gb

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

According to the logs, recognize cannot get the root storage and does not provide a detailed error, so my guess is that it's failing on here: https://github.com/nextcloud/recognize/blob/d8719ff2742ade14e2fe9821da9c2f676871166b/lib/Service/StorageService.php#L118

For some reason, root is `false`.

### Expected Behavior

Recognize properly detect the root storage and scans the images.

### To Reproduce

1. Install app through the store
2. Run `sudo -u www-data php occ recognize:download-models` to download models
3. Enable people recognition
4. Fails

### Debug log

```
{"reqId":"bVTTXRc5TZpSFmfT3Woe","level":3,"time":"2023-02-20T19:10:03+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Could not fetch storage root","userAgent":"--","version":"25.0.3.2","data":{"app":"recognize"},"id":"63f3cd41055f6"}
```

**Comment by marcelklehr** [comment]
I don't know why this would ever happen. Could it be that your nextcloud instance is b0rked somehow?

**Comment by oxomichael** [comment]
I've got the same error

`{"reqId":"WQ1W1ed3AY9aTgwp81pD","level":3,"time":"2023-04-03T19:26:15+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Could not fetch storage root","userAgent":"--","version":"25.0.5.1","data":{"app":"recognize"},"id":"642b2883273ed"}`

What can help ?

**Comment by Lipown** [comment]
I have same issue. I will try to restart docker container.

**Comment by Lipown** [comment]
Still it throws the error. I am running nextcloud by docker-compose. Having the external storage mounted thru NFS from Proxmox to VM, then by local in NC. Not sure if it is connected with the issue. Everything else is working fine.

**Comment by Lipown** [comment]
{"reqId":"pefpQDZ7dzk3MozfMQFz","level":3,"time":"2023-06-16T08:14:37+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Could not fetch storage root","userAgent":"--","version":"27.0.0.8","data":{"app":"recognize"},"id":"648c1a94ea5dd"}

Still throws error and do not go thru all the photos :(

**Comment by AndyXheli** [comment]
@marcelklehr Just got the same error on 4.3.0 

{"reqId":"Ze4CuXPqhcQJ3a1xKlrj","level":3,"time":"2023-07-12T09:40:01-05:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Could not fetch storage root","userAgent":"--","version":"27.0.0.8","data":{"app":"recognize"},"id":"64aebc4ccc39f"}

**Comment by tenhishadow** [comment]
5.0.3 - the same error:
`{"reqId":"HaajzWIwVWbMsANB5JIt","level":3,"time":"2023-10-17T10:05:01+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Could not fetch storage root","userAgent":"--","version":"27.1.2.1","data":{"app":"recognize"},"id":"652e5d7ab9b34"}`

**Comment by dinosmm** [comment]
I have been having this issue since April on NC 26. Now on NC 27.1.2, it persists. Recognize does not scan or detect faces, I have reset it and tried to rescan but no luck. "Could not fetch storage root" is the only error in the logs. My NC has always worked, and is still working 100% fine otherwise.

**Comment by lxklr650** [comment]
Also have been experiencing this issue. Classify works fine from command line, but background jobs always seem to trigger this error. Bare metal box ubuntu 22.04 and the files are not in external storage.

**Comment by beckenc** [comment]
Same here. Running in a docker container via docker-compose. External storage is mounted via CIFS to nextcloud

{"reqId":"CqwM9s1sfMFQVRSTkO6u","level":3,"time":"2023-12-01T06:20:04+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Could not fetch storage root","userAgent":"--","version":"27.1.4.1","data":{"app":"recognize"},"id":"65699620325f1"}

**Comment by marcelklehr** [comment]
This should only ever be temporary, I believe. I have not found a way to reproduce this consistently
