### ISSUE TITLE
include npm in binary

### ISSUE THREAD

**Issue by realies** [nextcloud/recognize#707]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

unRAID 6.11.5

### Which Docker container are you using to run Nextcloud? (if applicable)

kilrah/nextcloud-ffmpeg:latest

### How much RAM does your server have?

64GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

no npm binary

### Expected Behavior

have npm binary

### To Reproduce

install latest recognize app (occ and webui)

**Comment by marcelklehr** [comment]
> no npm binary

This is not a bug.
