### ISSUE TITLE
Error: Cannot find module 'fs/promises' and SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Cathnan** [nextcloud/recognize#709]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Ubuntu 22.04.2 LTS

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

X86_64

### Describe the Bug

Multiple Errors appear in the Nextcloud log and recognition doesn't work. Status in the submenu for recognition says: "Es ist ein Fehler bei der Gesichtserkennung aufgetreten, bitte überprüfe die Nextcloud-Protokolle." and "Es ist ein Fehler bei der Objekterkennung aufgetreten, bitte überprüfe die Nextcloud-Protokolle."

in the log the two following errors appear:
[recognize] Warnung: Classifier process output: /var/www/nextcloud/apps/recognize/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

at 2023-03-03T10:31:11+00:00

and

[recognize] Warnung: Classifier process output: internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /var/www/nextcloud/apps/recognize/src/classifier_faces.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/classifier_faces.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/www/nextcloud/apps/recognize/src/classifier_faces.js' ]
}

at 2023-03-03T10:30:44+00:00

### Expected Behavior

Recognition should work. Complete reinstall of the app from scratch didn't help either.

### To Reproduce

Install the app from nextcloud Appstore and download models as instructed

### Debug log

I'm not sure if these are helpful, but I also have the following log entries the seem to be related:

[PHP] Fehler: Error: imagecreatefromstring(): Data is not in a recognized format at /var/www/nextcloud/lib/private/legacy/OC_Image.php#758 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /var/www/nextcloud/lib/private/legacy/OC_Image.php line 758
    imagecreatefromstring("*** sensitive parameters replaced ***")
 2. /var/www/nextcloud/lib/private/Preview/Image.php line 52
    OC_Image->loadFromFile()
 3. /var/www/nextcloud/lib/private/Preview/GeneratorHelper.php line 65
    OC\Preview\Image->getThumbnail()
 4. /var/www/nextcloud/lib/private/Preview/Generator.php line 343
    OC\Preview\GeneratorHelper->getThumbnail()
 5. /var/www/nextcloud/lib/private/Preview/Generator.php line 162
    OC\Preview\Generator->getMaxPreview()
 6. /var/www/nextcloud/lib/private/Preview/Generator.php line 114
    OC\Preview\Generator->generatePreviews()
 7. /var/www/nextcloud/lib/private/PreviewManager.php line 185
    OC\Preview\Generator->getPreview()
 8. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 252
    OC\PreviewManager->getPreview()
 9. /var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php line 84
    OCA\Recognize\Classifiers\Classifier->getConvertedFilePath()
10. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ImagenetClassifier.php line 47
    OCA\Recognize\Classifiers\Classifier->classifyFiles()
11. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 41
    OCA\Recognize\Classifiers\Images\ImagenetClassifier->classify()
12. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
    OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->classify()
13. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 33
    OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
14. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
    OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->run()
15. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
    OCP\BackgroundJob\Job->start()
16. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
    OCP\BackgroundJob\TimedJob->start()
17. /var/www/nextcloud/cron.php line 152
    OCP\BackgroundJob\TimedJob->execute()

at 2023-03-03T10:40:29+00:00

[core] Fehler: RuntimeException: Classifier process error at <<closure>>

0. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ImagenetClassifier.php line 47
   OCA\Recognize\Classifiers\Classifier->classifyFiles()
1. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 41
   OCA\Recognize\Classifiers\Images\ImagenetClassifier->classify()
2. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
   OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->classify()
3. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 33
   OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
4. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
   OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->run()
5. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
6. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
7. /var/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2023-03-03T10:40:28+00:00

**Comment by marcelklehr** [comment]
What's the status of node.js? Have you set a custom binary?

**Comment by Cathnan** [comment]
Well, that's embarassing for me. I was indeed running a custom nodejs, as the pre-packaged version didn't (and still appears to not) work. I only now noticed the nodejs version on my system was 12.22.9. I don't know how I missed that. But as a suggestion, it may be useful to underly the text stating the version in a different color than green if the version is below the requirement. 
![Screenshot 2023-03-08 143157](https://user-images.githubusercontent.com/87026832/223729070-fde94222-586d-4099-a391-b9b93c03db53.png)

**Comment by marcelklehr** [comment]
> it may be useful to underly the text stating the version in a different color than green if the version is below the requirement

Ah, yes, that's a good idea! :) Glad it works now!
