### ISSUE TITLE
Found 19057 unclustered detections. Calculating clusters. PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 327680 bytes) in /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php on line 449

### ISSUE THREAD

**Issue by gmeks** [nextcloud/recognize#716]
### Which version of recognize are you using?

3.6.1

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

v25.0.4

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

v25.0.4

### How much RAM does your server have?

24

### What processor Architecture does your CPU have?

x86_64 

### Describe the Bug

Run command
php occ recognize:cluster-faces

ClusterDebug: Found 19057 unclustered detections. Calculating clusters.
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 327680 bytes) in /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php on line 449
www-data@6ba56b22b28c:~/html$ 

The user where it fails has around 200gb of picutres.

### Expected Behavior

Not sure if you want the 4gb limit to real, or more dynamic. It might be a option to split clustering into batches?

### To Reproduce

Run command
php occ recognize:cluster-faces

**Comment by marcelklehr** [comment]
> It might be a option to split clustering into batches?

That's already done, but apparently not in a smart enough way. I have a fix in mind :) Thanks for reporting!

**Comment by marcelklehr** [comment]
I tried fixing this in v3.6.3 -- let me know if it works now :)

**Comment by gmeks** [comment]
```
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features() in /var/www/html/custom_apps/recognize/lib/Clustering/DualTreeBall.php:107
Stack trace:
#0 /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php(632): OCA\Recognize\Clustering\DualTreeBall::split(Object(Rubix\ML\Datasets\Labeled), Object(OCA\Recognize\Clustering\SquaredDistance))
#1 /var/www/html/custom_apps/recognize/lib/Clustering/MstSolver.php(22): OCA\Recognize\Clustering\MrdBallTree->grow(Object(Rubix\ML\Datasets\Labeled))
#2 /var/www/html/custom_apps/recognize/lib/Clustering/HDBSCAN.php(90): OCA\Recognize\Clustering\MstSolver->__construct(Object(Rubix\ML\Datasets\Labeled), 20, 4, Object(OCA\Recognize\Clustering\SquaredDistance), Array, true)
#3 /var/www/html/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php(69): OCA\Recognize\Clustering\HDBSCAN->__construct(Object(Rubix\ML\Datasets\Labeled), 5, 4)
#4 /var/www/html/custom_apps/recognize/lib/Command/ClusterFaces.php(62): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters('Tripe3')
#5 /var/www/html/custom_apps/recognize/vendor/symfony/console/Command/Command.php(298): OCA\Recognize\Command\ClusterFaces->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/custom_apps/recognize/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/custom_apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Recognize\Command\ClusterFaces), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/custom_apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(100): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')

I did a  occ app:update --all

So it should have reverted all my changes from the pull req. I did not reset tags and so on
```

**Comment by marcelklehr** [comment]
see https://github.com/nextcloud/recognize/issues/676

**Comment by yoalieh** [comment]
I tested using 3.6.3 (though with only 2gb of ram allowed in php) and it stills consumes all my ram I'll test with 4gb.

**Comment by yoalieh** [comment]
I tried with a memory limit of 5gb and keeps crashing, from an user with 14183 unclustered detections, using version 3.6.3, and it keeps exhausting system memory.

**Comment by gmeks** [comment]
PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 655360 bytes) in /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php on line 449

**Comment by rhatguy** [comment]
I've got a similar error on my install.  Running nextcloud on docker on unraid.  My php memory limit is set to 16GB.  Recognize is 3.6.3.  

ClusterDebug: Found 29684 unclustered detections. Calculating clusters.
PHP Fatal error:  Allowed memory size of 17179869184 bytes exhausted (tried to allocate 1310720 bytes) in /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php on line 449

I wonder if I had run the clustering more frequently rather than letting a classify run for so long before running a cluster if this would be any different.  I'm going to try to reset the DB and run smaller batches of classify/cluster.

**Comment by marcelklehr** [comment]
>  I'm going to try to reset the DB and run smaller batches of classify/cluster.

Do yourself a favor and just wait for this to get fixed. It's not worth the resources. :earth_africa:

**Comment by cliffalbert** [comment]
Still have a problem with recognize:cluster-faces on NextCloud 26.0.1 with recognize 4.0.1:

Even when setting a small batch size with 8G ram allocated to PHP:

$ ./occ recognize:cluster-faces --batch-size=200
Clustering face detections for user cliff
ClusterDebug: Retrieving face detections for user cliff
ClusterDebug: Found 120 unclustered detections. Calculating clusters.
PHP Fatal error:  Allowed memory size of 8589934592 bytes exhausted (tried to allocate 655360 bytes) in /opt/nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php on line 449

When running without batch size it get's killed by OOM. The server has 32GB of ram.

**Comment by marcelklehr** [comment]
@cliffalbert Huh. Can you open a new issue for this? Also please mention in the issue how many people you have already clustered.
