### ISSUE TITLE
3.6.1: Class "voku\helper\Bootup" not found

### ISSUE THREAD

**Issue by flintman** [nextcloud/recognize#719]
### Which version of recognize are you using?

3.6.1

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

UBUNTU 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

not

### How much RAM does your server have?

16gb

### What processor Architecture does your CPU have?

Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 cores)

### Describe the Bug

Error: Class "voku\helper\Bootup" not found.   With the app enabled i get this error and it crashes my nextcloud and can't view files.   

### Expected Behavior

expect my system to work as it should 

### To Reproduce

Install the latest version

**Comment by marcelklehr** [comment]
I can confirm this was an issue with v3.6.0 but I cannot reproduce this anymore with v3.6.1.

**Comment by flintman** [comment]
> I can confirm this was an issue with v3.6.0 but I cannot reproduce this anymore with v3.6.1.

I was at 3.5.0 and moved to 3.6.1 and have this issue.

**Comment by flintman** [comment]
Let me know if you need any more info.   did find this in the log as well  	ArgumentCountError: Too few arguments to function OCA\Recognize\Dav\RootCollection::__construct(), 0 passed in /nextcloud/apps/dav/lib/AppInfo/PluginManager.php on line 259 and exactly 8 expected
/nextcloud/apps/dav/lib/AppInfo/PluginManager.php - line 259:

OCA\Recognize\Dav\RootCollection->__construct()

/nextcloud/apps/dav/lib/AppInfo/PluginManager.php - line 288:

OCA\DAV\AppInfo\PluginManager->createClass()

<<closure>>

OCA\DAV\AppInfo\PluginManager->OCA\DAV\AppInfo\{closure}("*** sensiti ... *")

/nextcloud/apps/dav/lib/AppInfo/PluginManager.php - line 293:

array_map()

/nextcloud/apps/dav/lib/AppInfo/PluginManager.php - line 158:

OCA\DAV\AppInfo\PluginManager->loadSabreCollectionsFromInfoXml()

/nextcloud/apps/dav/lib/AppInfo/PluginManager.php - line 106:

OCA\DAV\AppInfo\PluginManager->populate()

/nextcloud/apps/dav/lib/Server.php - line 343:

OCA\DAV\AppInfo\PluginManager->getAppPlugins()

/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

OCA\DAV\Server->OCA\DAV\{closure}("*** sensiti ... *")

/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 456:

Sabre\DAV\Server->emit()

/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

Sabre\DAV\Server->invokeMethod()

/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

Sabre\DAV\Server->start()

/nextcloud/apps/dav/lib/Server.php - line 360:

Sabre\DAV\Server->exec()

/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/nextcloud/remote.php - line 171:

**Comment by marcelklehr** [comment]
> Error: Class "voku\helper\Bootup" not found. With the app enabled i get this error and it crashes my nextcloud and can't view files.

Could you post the full error stack trace, please?

**Comment by flintman** [comment]
> 

Error: Class "voku\helper\Bootup" not found
/nextcloud/apps/recognize/vendor/composer/autoload_real.php - line 55:

require()

/nextcloud/apps/recognize/vendor/composer/autoload_real.php - line 38:

composerRequireed7f0a1d9dc886564ddbe2945c018806()

/nextcloud/apps/recognize/vendor/autoload.php - line 25:

ComposerAutoloaderInited7f0a1d9dc886564ddbe2945c018806::getLoader()

/nextcloud/apps/recognize/lib/AppInfo/Application.php - line 34:

include_once("/websites/c ... p")

/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 136:

OCA\Recognize\AppInfo\Application->register()

/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php - line 91:

OC\AppFramework\Bootstrap\Coordinator->registerApps()

/nextcloud/lib/base.php - line 671:

OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()

/nextcloud/lib/base.php - line 1144:

OC::init()

/nextcloud/index.php - line 34:

require_once("/websites/c ... p")

**Comment by marcelklehr** [comment]
Thank you.

Could you now please post the contents of the following files:

* recognize/vendor/autoload.php 
* recognize/appinfo/info.xml

**Comment by flintman** [comment]
info.xml <?xml version="1.0"?>
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
	<id>recognize</id>
	<name>Recognize</name>
	<summary>Smart media tagging for Nextcloud</summary>
	<description><![CDATA[
This app goes through your media collection and adds fitting tags, automatically categorizing your photos and music.

* 📷 👪 Recognizes faces from contact photos
* 📷 🏔 Recognizes animals, landscapes, food, vehicles, buildings and other objects
* 📷 🗼 Recognizes landmarks and monuments
* 👂 🎵 Recognizes music genres
* ⚡ Tagging works via Nextcloud's Collaborative Tags, allowing access by any of your apps
  * 👂 listen to your tagged music with the audioplayer app
  * 📷 view your tagged photos with the photos app

After installation, you can enable tagging in the admin settings.

Requirements:
- PHP 7.4 and above
- App "collaborative tags" enabled
- For native speed:
  - Processor: x86 64-bit (with support for AVX instructions)
  - System with glibc (usually the norm on Linux; Alpine linux and FreeBSD are *not* such systems)
- For sub-native speed (using JavaScript mode)
  - Processor: x86 64-bit, arm64, armv7l (no AVX needed)
  - System with glibc or musl (incl. Alpine linux)
- ~4GB of free RAM (if you're cutting it close, make sure you have some swap available)

The app does not send any sensitive data to cloud providers or similar services. All processing is done on your Nextcloud machine, using Tensorflow.js running in Node.js.

]]></description>
	<version>3.6.1</version>
	<licence>agpl</licence>
	<author mail="mklehr@gmx.net">Marcel Klehr</author>
	<types>
		<filesystem/>
		<dav/>
	</types>
	<category>organization</category>
	<category>search</category>
	<category>multimedia</category>
	<website>https://github.com/marcelklehr/recognize</website>
	<bugs>https://github.com/marcelklehr/recognize/issues</bugs>
	<repository type="git">https://github.com/marcelklehr/recognize.git</repository>
	<screenshot>https://raw.githubusercontent.com/marcelklehr/recognize/master/screenshots/recognize.png</screenshot>
	<screenshot>https://raw.githubusercontent.com/marcelklehr/recognize/master/screenshots/imagenet_examples.jpg</screenshot>
	<dependencies>
		<php min-version="7.4" />
		<nextcloud min-version="25" max-version="27" />
	</dependencies>

	<repair-steps>
		<post-migration>
			<step>OCA\Recognize\Migration\InstallDeps</step>
		</post-migration>
		<install>
			<step>OCA\Recognize\Migration\InstallDeps</step>
		</install>
	</repair-steps>

	<commands>
		<command>OCA\Recognize\Command\ResetFaces</command>
		<command>OCA\Recognize\Command\ResetFaceClusters</command>
		<command>OCA\Recognize\Command\ResetTags</command>
		<command>OCA\Recognize\Command\RemoveLegacyTags</command>
		<command>OCA\Recognize\Command\CleanupTags</command>
		<command>OCA\Recognize\Command\Recrawl</command>
		<command>OCA\Recognize\Command\DownloadModels</command>
		<command>OCA\Recognize\Command\Classify</command>
		<command>OCA\Recognize\Command\ClusterFaces</command>
	</commands>

	<settings>
		<admin>OCA\Recognize\Settings\AdminSettings</admin>
		<admin-section>OCA\Recognize\Settings\AdminSection</admin-section>
	</settings>

	<sabre>
		<collections>
			<collection>OCA\Recognize\Dav\RootCollection</collection>
		</collections>
		<plugins>
			<plugin>OCA\Recognize\Dav\Faces\PropFindPlugin</plugin>
		</plugins>
	</sabre>
</info>

**Comment by flintman** [comment]
autoload.php   <?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    trigger_error(
        $err,
        E_USER_ERROR
    );
}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitRecognize::getLoader();

**Comment by eibex** [comment]
Getting this error on 3.6.1 at a rate of ~7 errors per second.

I also couldn't load the home folder in files until I disabled recognize as this error was shown:
`This directory is unavailable, please check the logs or contact the administrator`

**Comment by marcelklehr** [comment]
I'm getting closer to uncovering the problem, I think. Are you all on php < 8?

**Comment by flintman** [comment]
> I'm getting closer to uncovering the problem, I think. Are you all on php < 8?

Yes on 8.1

**Comment by eibex** [comment]
> I'm getting closer to uncovering the problem, I think. Are you all on php < 8?

I'm on 8.1 too

**Comment by marcelklehr** [comment]
huh

**Comment by flintman** [comment]
I see you figured it out.  Do you plan on releasing soon or you going to wait?  Just trying to figure out if I should pull and run a build to get my recognize going on my site or wait for the release.   Thanks again for jumping on this.

**Comment by marcelklehr** [comment]
Building the next release as we speak

**Comment by flintman** [comment]
> Building the next release as we speak

Awesome,  Thanks again.
