### ISSUE TITLE
Classifier process output: Error: Unsupported MIME type: video/mp4

### ISSUE THREAD

**Issue by phil-lipp** [nextcloud/recognize#742]
### Which version of recognize are you using?

3.6.3

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Debain 11

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

Classification throws an error (but keeps on going).

### Expected Behavior

No error or rather no scanning for faces in videos (yet).

### To Reproduce

Run `occ recognize:classify`

### Debug log

```
Classifier process output: Error: Unsupported MIME type: video/mp4
    at Jimp.throwError (/var/www/nextcloud/apps/recognize/node_modules/@jimp/utils/dist/index.js:21:13)
    at Jimp.parseBitmap (/var/www/nextcloud/apps/recognize/node_modules/@jimp/core/dist/utils/image-bitmap.js:159:32) {
  methodName: 'constructor'
}
```

**Comment by marcelklehr** [comment]
Huh. Recognize doesn't do this on its own. For this error to occur when doing face recognition, you must have a file that has a file ending that looks to nextcloud like on of [these](https://github.com/nextcloud/recognize/blob/main/lib/Constants.php#L10).

Avenues forward are

1. Nextcloud server could introduce proper mime type detection
2. You could change that file's ending

The error is thus not a bug, IMO.
