### ISSUE TITLE
on processor not capable of AVX app gives error with misleading message

### ISSUE THREAD

**Issue by chris299** [nextcloud/recognize#743]
### Which version of recognize are you using?

3.6.3

### Enabled Modes

Object recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

although the app properly recognized the missing AVX instruction set and activated WASM by default, the classification was not done with the JS native mode.
the resulting error message does not say anything and is misleading: "Classifier process error"
![image](https://user-images.githubusercontent.com/33319001/225920526-3f03461f-bfdf-487f-8687-01dabf7412af.png)

![image](https://user-images.githubusercontent.com/33319001/225920599-a003d618-abd1-402e-b16c-9132ec24c844.png)

see also my request in the help forum here: 
https://help.nextcloud.com/t/solved-recognize-app-classifier-process-error-bug-how-to-analyse/157973

problem was gone after switching to an core i7 processer, capable of AVX

### Expected Behavior

no error and tensorflow running in JS only mode on a Pentium GT4400T

### To Reproduce

using a Pentium G440T show the problem always

**Comment by marcelklehr** [comment]
> problem was gone after switching to an core i7 processer, capable of AVX

That's surprising. The beauty of WASM mode is that it doesn't need AVX. *head scratch*

Could you try running `recognize/bin/node src/classifier_musicnn.js <path-to-some-music-file-on-your-hdd-here>` on the pentium?

**Comment by chris299** [comment]
Thank you for your commitment and your work here. Unfortunately, I can't reinstall the old processor because it's a "production" environment....

**Comment by chris299** [comment]
the problem may have been caused by me using "npm ci" 
I used this, because it gave other errors on initial one-click install....

**Comment by marcelklehr** [comment]
I think this should be fixed by now in the lastest release. Thank you for reporting this!
