### ISSUE TITLE
An error occurred during face recognition, please check the Nextcloud logs.

### ISSUE THREAD

**Issue by kruthoff** [nextcloud/recognize#760]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Debian 11.6, 5.10.0-21-amd64

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

x86_64 GNU/Linux

### Describe the Bug

Face recognition stopped to work a few days ago, and I don't understand, why? It might be related to upgraded versions, as it was working before.

Image tagging:
An error occurred during face recognition, please check the Nextcloud logs.
Face recognition: 27394 Queued files, Last classification: 3/7/2023
Status: green.
Node.js: green.

The message is shown in the configuration page, as soon as face recognition is enabled. It was working with an older recognize version. The syslog message is suspicious, maybe.

### Expected Behavior

Face recognition.

### To Reproduce

Enable Face recognition.

### Debug log

syslog:
```
Mar 21 21:14:08 delta3 kernel: [1131100.436539] traps: node[284146] trap invalid opcode ip:7f1d67927b40 sp:7ffd0cdb4588 error:0 in libtensorflow_framework.so.2.9.1[7f1d66882000+11ef000]
Mar 21 21:14:08 delta3 kernel: [1131100.437935] traps: node[284160] trap invalid opcode ip:7fd3396e1410 sp:7ffd27e42838 error:0 in libtensorflow_framework.so.2.9.1[7fd338430000+1390000]

```
nextcloud.log:

`{"reqId":"0W2DzQTZ2791fBUdtky4","level":3,"time":"2023-03-21T21:20:02+01:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 10\n    [rootId] => 86906\n)\n)","userAgent":"--","version":"25.0.4.1","exception":{"Exception":"RuntimeException","Message":"Classifier process error","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php","line":83,"function":"classifyFiles","class":"OCA\\Recognize\\Classifiers\\Classifier","type":"->"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":41,"function":"classify","class":"OCA\\Recognize\\Classifiers\\Images\\ClusteringFaceClassifier","type":"->"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php","line":70,"function":"classify","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":33,"function":"runClassifier","class":"OCA\\Recognize\\BackgroundJobs\\ClassifierJob","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/html/nextcloud/apps/recognize/lib/Classifiers/Classifier.php","Line":211,"message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 10\n    [rootId] => 86906\n)\n)","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 10\n    [rootId] => 86906\n)\n)"}}`

**Comment by kruthoff** [comment]
Recognize 3.8.0, Nextcloud Hub 3 (25.0.7) on SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
Same issue. It looks like the error is libtensorflow_framework.so.2.9.1

**Comment by kruthoff** [comment]
First of all, it looked promising. The queued files were getting smaller and smaller over a few days.

But the queue is stuck since yesterday with the following error. Shall I open a new issue?

`{"reqId":"h9xbCUrP87sRSqIJ6MHl","level":3,"time":"2023-06-14T16:34:14+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 120\n)\n)","userAgent":"--","version":"25.0.7.1","exception":{"Exception":"RuntimeException","Message":"Classifier process error","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php","line":83,"function":"classifyFiles","class":"OCA\\Recognize\\Classifiers\\Classifier","type":"->"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":41,"function":"classify","class":"OCA\\Recognize\\Classifiers\\Images\\ClusteringFaceClassifier","type":"->"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php","line":70,"function":"classify","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/var/www/html/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyFacesJob.php","line":33,"function":"runClassifier","class":"OCA\\Recognize\\BackgroundJobs\\ClassifierJob","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/html/nextcloud/apps/recognize/lib/Classifiers/Classifier.php","Line":213,"message":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 120\n)\n)","exception":{},"CustomMessage":"Error while running background job (class: OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob, arguments: Array\n(\n    [storageId] => 3\n    [rootId] => 120\n)\n)"}}
`

**Comment by kruthoff** [comment]
`nextcloud=# select * from oc_recognize_queue_faces limit 10;
   id   | file_id | storage_id | root_id | update 
--------+---------+------------+---------+--------
 117846 | 1179103 |          3 |     120 | f
 117851 | 1179135 |          3 |     120 | f
 117852 | 1179264 |          3 |     120 | f
 117853 | 1179272 |          3 |     120 | f
 117858 | 1179293 |          3 |     120 | f
 117859 | 1179297 |          3 |     120 | f
 117860 | 1179326 |          3 |     120 | f
 117861 | 1179805 |          3 |     120 | f
 117862 | 1179869 |          3 |     120 | f
 117863 | 1179878 |          3 |     120 | f
(10 rows)

nextcloud=#
`

**Comment by marcelklehr** [comment]
Here you go, I think it's this on: #807
