### ISSUE TITLE
error messages in log after one-click update

### ISSUE THREAD

**Issue by chris299** [nextcloud/recognize#764]
### Which version of recognize are you using?

3.70

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

after onclick update from 3.6.3 i see a strange error in the log, but the app looks as updated properly (shows 3.7. in the GUI), but I assume it isn't.
in fact I don't have a directory 'composer' at the expected place. how should that have gotten there?
however, /var/www/nextcloud/apps/recognize/vendor/voku/portable-utf8/bootstrap.php is available

can I restart the procedure to retry/reproduce?
![image](https://user-images.githubusercontent.com/33319001/227179386-f5d57bc2-0b83-459b-93fa-b1d3d6d06a4b.png)

### Expected Behavior

no error on updating the app

### To Reproduce

n/a

**Comment by marcelklehr** [comment]
Please update again. v3.6 was a failed attempt to fix some bugs.
