### ISSUE TITLE
Audio tagging reported as working, but shows no movement

### ISSUE THREAD

**Issue by Daddy-ohh** [nextcloud/recognize#767]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.5

### Which Operating system do you have installed?

Raspberry Pi OS with desktop (bullseye)

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

Even though Audio tagging is enabled, there is no progress shown in the admin page:

![Image1](https://user-images.githubusercontent.com/93015741/227484770-f09f3cd9-ee97-4dce-86e8-99d115d5bed8.gif)

### Expected Behavior

By enabling Audio tagging, I expect to see the number of queued files to drop to zero.

### To Reproduce

Enable Audio tagging, check the number of queued files, see no change.

**Comment by lonelywoolf** [comment]
Same problem here. 
My setup 2x Xeon E5645 (without AVX), 96G RAM, 4x2Tb HDD RAID 10, Debian 11, PHP 8.1, Bare metal. Nextcloud version is 26.0.1, version of recognize is 3.7.0

**Comment by marcelklehr** [comment]
Confirmed and bug identified. The next release should fix this.
