### ISSUE TITLE
Recognize tries to download non-existend nodejs file

### ISSUE THREAD

**Issue by Venkman42** [nextcloud/recognize#775]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Object recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Raspberry Pi OS(64bit)

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud-aio

### How much RAM does your server have?

2GB

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

After installing recognize it says node.js is not installed. In the nextcloud logs i see the following error from recognize:
`[recognize] Fehler: GuzzleHttp\Exception\ClientException: Client error: `GET https://unofficial-builds.nodejs.org/download/release/v14.18.2/node-v14.18.2-linux-arm64-musl.tar.gz` resulted in a `404 Not Found` response:
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr> (truncated...)
 at <<closure>>

 0. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 69
    GuzzleHttp\Exception\RequestException::create(["GuzzleHttp\\Psr7\\Request"], "*** sensitive parameters replaced ***", null, [], null)
 1. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 204
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 2. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 153
    GuzzleHttp\Promise\Promise::callHandler(1, "*** sensitive parameters replaced ***", null)
 3. /var/www/html/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 48
    GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 248
    GuzzleHttp\Promise\TaskQueue->run(true)
 5. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 224
    GuzzleHttp\Promise\Promise->invokeWaitFn()
 6. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 269
    GuzzleHttp\Promise\Promise->waitIfPending()
 7. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 226
    GuzzleHttp\Promise\Promise->invokeWaitList()
 8. /var/www/html/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
 9. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Promise\Promise->wait()
10. /var/www/html/lib/private/Http/Client/Client.php line 218
    GuzzleHttp\Client->request("get", "https://unoffic ... z", ["/mnt/ncdata/fi ... "])
11. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 230
    OC\Http\Client\Client->get("https://unoffic ... z", [1200,"/var/www/ ... "])
12. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 115
    OCA\Recognize\Migration\InstallDeps->downloadNodeBinary("https://unoffic ... /", "v14.18.2", "arm64", "musl")
13. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 83
    OCA\Recognize\Migration\InstallDeps->installNodeBinary(["OC\\Repair"])
14. /var/www/html/lib/private/Repair.php line 127
    OCA\Recognize\Migration\InstallDeps->run(["OC\\Repair"])
15. /var/www/html/lib/private/legacy/OC_App.php line 1068
    OC\Repair->run()
16. /var/www/html/lib/private/Installer.php line 164
    OC_App::executeRepairSteps("recognize", ["OCA\\Recognize ... "])
17. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp("recognize")
18. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->enableApps(["recognize"], [])
19. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Settings\ ... "], "enableApps")
20. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Settings\ ... "], "enableApps")
21. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", ["OC\\AppFramewo ... "], ["settings.AppSettings.enableApps"])
22. /var/www/html/lib/base.php line 1047
    OC\Route\Router->match("/settings/apps/enable")
23. /var/www/html/index.php line 36
    OC::handleRequest()

POST /settings/apps/enable
from 2a02:810d:640:4d1c::fd60 by admin at 2023-03-28T08:27:38+00:00`

The problem is that the file https://unofficial-builds.nodejs.org/download/release/v14.18.2/node-v14.18.2-linux-arm64-musl.tar.gz does not exist. The name is ...linux-arm6l.tar.gz

### Expected Behavior

Install recognize and node.js

### To Reproduce

Install recognize in nextcloud aio on raspberry pi

**Comment by marcelklehr** [comment]
Huh, that would be a bug. Apparently, node.js unofficial builds project does not provide a musl arm64 build :(

As a short-term fix, you can install node.js manually on Alpine and point recognize to the node binary.

**Comment by piyushaswani55** [comment]
@marcelklehr how can i install it manually and where to install it?
@Venkman42 did you fix it for yourself?

**Comment by piyushaswani55** [comment]
It seems like it's searching for node at `GET https://unofficial-builds.nodejs.org/download/release/v14.18.2/node-v14.18.2-linux-arm64-musl.tar.gz` but it's actually at `GET https://unofficial-builds.nodejs.org/download/release/v14.18.2/node-v14.18.2-linux-x64-musl.tar.gz`. 
Either naming convention at node changed or the architecture is wrongly being passed in code and if instead of `arm64` it's sent as `x64` it will work fine.

**Comment by piyushaswani55** [comment]
I did install it and passed the nodejs binary path at the bottom of recognize under administrative setting, but it still didn't work for me. I am sure I would have done something wrong. I will give it another try.
But I have a question @marcelklehr, which is why is unofficial build project is being used, won't official ones be stable and tested, so such issues would minimize?

**Comment by marcelklehr** [comment]
If you find official builds for musl, be my guest

**Comment by piyushaswani55** [comment]
I could finally install it but still can't get `recognize` working for me.
<img width="958" alt="image" src="https://user-images.githubusercontent.com/5944859/229564002-0a70bca2-0757-4ca3-8fe2-48a2ed7baf84.png">

**Comment by piyushaswani55** [comment]
Also for some reason "Video Tagging" is disabled, unable to enable it.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/5944859/229566072-192844ce-ef0d-4988-84dc-3b93c228d87e.png">

**Comment by marcelklehr** [comment]
Video and audio tagging aren't support on musl systems

**Comment by piyushaswani55** [comment]
ohhh okay but what about the other errors @marcelklehr 
Do i need to download the machine learning models manually?
Even after setting up node, i am unable to use Recognize, I think there is still something missing, but nothing is coming up in logs as well.

**Comment by piyushaswani55** [comment]
@marcelklehr This is the latest piece of error I see after downloading the machine learning models. 
<img width="941" alt="image" src="https://user-images.githubusercontent.com/5944859/230556423-a3e18ab7-cb18-46c7-9914-155bec149509.png">

**Comment by marcelklehr** [comment]
Does /usr/bin/node exist inside the container? What happens if you run it yourself?

**Comment by piyushaswani55** [comment]
Tried running the `occ recognize:classify` in the console and got this error. I see that `usr/bin/node` also exists and works. 

<img width="673" alt="image" src="https://user-images.githubusercontent.com/5944859/230734545-ec9e55dc-81d5-4308-9ba6-6ab98726c724.png">

**Comment by piyushaswani55** [comment]
And when I manually removed the lines as per the above fix, I am getting some weird Tensorflow permission issues.
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/5944859/230736018-da6dd078-a9d5-4af8-939a-7b2e04a1802d.png">

**Comment by marcelklehr** [comment]
Oh. I see you entered `"/usr/bin/node"` (*with* quotes). Who told you to put quotes in there?
