### ISSUE TITLE
Installation error on aarch64, missing dependencies

### ISSUE THREAD

**Issue by juriSacchetta** [nextcloud/recognize#784]
### Which version of recognize are you using?

 3.7.0

### Enabled Modes

Object recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.5

### Which Operating system do you have installed?

ubuntu

### Which Docker container are you using to run Nextcloud? (if applicable)

All-in-one

### How much RAM does your server have?

24

### What processor Architecture does your CPU have?

aarch64

### Describe the Bug

I attempted to install the application, but I was unable to start it from the administrative page and there was a banner on some problem with the node path. As a result, I installed node at the system level, and it worked correctly.
However, when I opened a shell inside the Docker container to check what was happening, I found that I was unable to run node. After investigating the issue, I discovered a strange error message that read as follows:
```
bash-5.1# ls
arm64.tar.gz  node
bash-5.1# ./node
bash: ./node: No such file or directory
```
So I started to look for the way and I found missing dependencies:
```
ldd node
	/lib/ld-linux-aarch64.so.1 (0xffff83111000)
	libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0xffff83111000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xffff82f21000)
	libm.so.6 => /lib/ld-linux-aarch64.so.1 (0xffff83111000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffff82efc000)
	libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0xffff83111000)
	libc.so.6 => /lib/ld-linux-aarch64.so.1 (0xffff83111000)
Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by node)
Error relocating node: __register_atfork: symbol not found
Error relocating node: makecontext: symbol not found
Error relocating node: backtrace: symbol not found
Error relocating node: setcontext: symbol not found
Error relocating node: getcontext: symbol not found
Error relocating node: gnu_get_libc_version: symbol not found
Error relocating node: __strdup: symbol not found
Error relocating node: __libc_stack_end: symbol not found
```

### Expected Behavior

I would like to run it

### To Reproduce

Just install it on aarch64

**Comment by marcelklehr** [comment]
For AIO on Arm64 you'll need to install node.js inside the AIO docker container yourself using alpine's package manager.

> So I started to look for the way and I found missing dependencies:

How did you install node?

**Comment by juriSacchetta** [comment]
Yes, I did inside the `nextcloud-aio-nextcloud` container. 
The version is 16.20 and works correctly inside the container, but the already binary in the app directory doesn't.
```
bash-5.1# node -v
v16.20.0
bash-5.1# cd custom_apps/recognize/bin/
bash-5.1# ldd node
	/lib/ld-linux-aarch64.so.1 (0xffff9ae24000)
	libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0xffff9ae24000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xffff9ac34000)
	libm.so.6 => /lib/ld-linux-aarch64.so.1 (0xffff9ae24000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffff9ac0f000)
	libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0xffff9ae24000)
	libc.so.6 => /lib/ld-linux-aarch64.so.1 (0xffff9ae24000)
Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by node)
Error relocating node: __register_atfork: symbol not found
Error relocating node: makecontext: symbol not found
Error relocating node: backtrace: symbol not found
Error relocating node: setcontext: symbol not found
Error relocating node: getcontext: symbol not found
Error relocating node: gnu_get_libc_version: symbol not found
Error relocating node: __strdup: symbol not found
Error relocating node: __libc_stack_end: symbol not found
bash-5.1# ./node 
bash: ./node: No such file or directory
```
Would you happen to have any suggestions?

**Comment by marcelklehr** [comment]
You can change the binary the app uses in the settings of the app.
