### ISSUE TITLE
The number of files to process per job run - setting over 100 does not work

### ISSUE THREAD

**Issue by luxzg** [nextcloud/recognize#787]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

Nextcloud 26.0.0

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86

### Describe the Bug

Background job always picks 100 files.
As NC admin I've gone to settings `index.php/settings/admin/recognize` (Administration Settings - Recognize)
Under "The number of files to process per job run" set "500" later "250"

Job status above that always said `Face recognition: 100 Queued files`, never over 100.
Setting is saved but seems that job is not reflecting that saved number.

### Expected Behavior

If I set batch to 500 because I know I have enough processing resources, it should allow higher number.

I have only enabled face recognition, but I went ahead trying to set 250 for all image recognition settings (enable, set, disable) and leaving just first check enabled... Still didn't help.

![image](https://user-images.githubusercontent.com/9318107/229796280-30551637-ebcc-43d9-98fb-0feb36f8a6cb.png)

CPU cores setting is at 0 (unlimited), WASM and GPU are disabled.

Node.js v14.18.2 binary was installed successfully.
Libtensorflow was loaded successfully into Node.js.

### To Reproduce

Not sure that I did anything out of the ordinary. It's fresh install of NC26 on Ubuntu 22.04 LTS, Apache, MariaDB.
I'm using it in Chrome desktop browser.

My images are now finally all classified so I can't reproduce or debug until I have a next larger batch of photos. Let me know if you want me to setup something special for logging and debugging before I get new photos.

### Debug log

none for now

**Comment by marcelklehr** [comment]
Checking the latest code I can't see anything hardcoded or any bug in the setting storage code.

My recommendation: Try if updating fixes this for you. Otherwise, it might just be that the background job only manages to run through exactly 100 images in 5 minutes.

**Comment by Yatagarasu50469** [comment]
Salutations, encountered the same issue, where only 100 files ever get added to the queue and then classified each job run; have found a likely fix.

The Storage Crawl Job calls getFilesInMount() in /lib/Service/StorageService.php, which imposes a default limit: $maxResults = 100, that does not get overridden. The expected behavior would be that maxResults should be set according to the number of files indicated to process per job run. Instead, the current behavior is that the background job only ever adds a maximum 100 files, per Storage Crawl Job, to the queue. 

Manually changing the default $maxResults in /lib/Service/StorageService.php to match with the number of files indicated for the classifier to process appears to bypass the issue.

**Comment by marcelklehr** [comment]
Hey @Yatagarasu50469,

nice find! Storage crawl job is designed to only add 100 files per run and the settings in the admin panel are for classifier jobs, but when they are activated at the same time, the storage crawl job may indeed limit the number of files available to the classifiers. I guess the craw job should be able to handle more than 100 files.

**Comment by luxzg** [comment]
Thanks for these useful tips and finding the actual bottleneck.

I assume that changing the line in PHP will be required after each NC update/upgrade, correct? Should I then open an issue asking for exposing storage job batch size in NC settings? I don't mind changing it in PHP, but pretty sure I'll keep forgetting it :)

P.S. And I'm glad it wasn't just me imagining stuff 😂

**Comment by Yatagarasu50469** [comment]
Would assume the same regarding updates/upgrades, though probably not an issue for most beyond the initial setup. It also looks like there's another couple defaults for clustering operations that would ideally be exposed in the settings (just started running into them as a consequence of having all images added to the queue at once): a maximum of 10,000 is listed in /lib/BackgroundJobs/ClusterFacesJob.php (imagine this causes some systems with low RAM to crash) and a per-user maximum of 500 appears to be enforced when manually specifying a batch size with cluster-faces...

**Comment by marcelklehr** [comment]
> having the batch size exposed for clustering would probably also become necessary if the storage job batch size is made accessible.

Mh, I don't think so.

> imagine this would cause some systems with insufficient memory to crash or have the routine quietly fail

The number is carefully chosen to avoid memory troubles, but in theory yes.

> Would assume the same regarding updates/upgrades

I've changed the code by now, so the next update should fix this :) New number is 2000 :D
