### ISSUE TITLE
Unable to install on Nextcloud on shared bluehost hosting

### ISSUE THREAD

**Issue by technokul** [nextcloud/recognize#791]
### Which version of recognize are you using?

didnt install

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode, WASM mode, GPU mode

### Which Nextcloud version do you have installed?

26

### Which Operating system do you have installed?

Bluehost

### Which Docker container are you using to run Nextcloud? (if applicable)

NA

### How much RAM does your server have?

NA

### What processor Architecture does your CPU have?

NA

### Describe the Bug

Didnt install on my nextcloud.

Could not extract app recognize: Unable to extract symbolic link {/tmp/oc_tmp_gv28BS-folder/recognize/node_modules/.bin/dbf2json}

### Expected Behavior

Should have installed normally

### To Reproduce

just press download and install

### Debug log

Could not extract app recognize: Unable to extract symbolic link {/tmp/oc_tmp_gv28BS-folder/recognize/node_modules/.bin/dbf2json}

**Comment by marcelklehr** [comment]
Should be fixed in nextcloud server nowadays.
