### ISSUE TITLE
Can not install libtensorflow 

### ISSUE THREAD

**Issue by DenuxPlays** [nextcloud/recognize#797]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.5

### Which Operating system do you have installed?

Fedora 37

### Which Docker container are you using to run Nextcloud? (if applicable)

23.0.3

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I can not install tensorflow with npm ci.
I want to run tensorflow in normal mode and when I try to add the lib it says that all the packages added successfully but in the web interface it still says that their needed to be adddd.
![Screenshot_20230409_012011_Brave](https://user-images.githubusercontent.com/83671398/230746685-29892cef-5000-4eaf-937c-f7c8f3d4a656.jpg)

### Expected Behavior

Running in normal mode.

### To Reproduce

Install nextcloud aio version 4.7.0
Add npm and musl to extra apk and the  install recognize,
Execute the command `sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ app:install recognize` to install recognize.
Use the same command but replacd php.... with bash goto custom_app/recognize and execute npm ci.
Reload your admin settings and you still see the warning.

**Comment by DenuxPlays** [comment]
Info:
The app works but really really really slow.
For 3.600 pictures it needs almost 3 whole days!

**Comment by DenuxPlays** [comment]
This is how it looks atm:
![image](https://user-images.githubusercontent.com/83671398/230954608-9e37fa40-768f-4a2c-b736-5c266d95e6a6.png)

**Comment by Sblop** [comment]
I have the same problem...

**Comment by marcelklehr** [comment]
> The app works but really really really slow.

I assume, you are running in WASM mode? Since you are running in the AIO container, only WASM mode is supported, because libtensorflow doesn't support musl, I believe. :shrug: 

The empty faces in the photos view may be due to this issue: #806
