### ISSUE TITLE
Recognize does not seem to set RECOGNIZE_PUREJS correctly when running node

### ISSUE THREAD

**Issue by GreenCappuccino** [nextcloud/recognize#804]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

26.0.0

### Which Operating system do you have installed?

The host operating system of the container is Rocky Linux 9.1, k3s+istio, SELinux enabled

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud:26.0.0-apache

### How much RAM does your server have?

128 GiB on host, 8192 MiB resource limit per pod

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Recognize encounters a runtime error. Digging deeper into the command it runs (when I first looked into it, the issue was with the JS file for ImageNet, but it may apply to other scripts), it brings up `Illegal Instruction [core dumped]`. Presumably this is because the script is attempting to run AVX2 instructions which do not exist.

This behavior also happens with `occ recognize:classify`. To fix the issue, you need to run `RECOGNIZE_PUREJS=true occ recognize:classify`. The classification job will then run correctly.

### Expected Behavior

Automated job runs correctly. There is no need to specify environment variable on `occ` during manual job runs.

### To Reproduce

Attempt to run Recognize on a system which does not support AVX instructions. cronjobs will fail.

**Comment by marcelklehr** [comment]
Can you execute the following command to check what is set in the app config?

```
php occ config:app:get recognize tensorflow.purejs
```

**Comment by GreenCappuccino** [comment]
```sh
www-data@nextcloud-6f7cd5f779-m2dcj:~/html$ ./occ config:app:get recognize tensorflow.purejs
true
```

**Comment by GreenCappuccino** [comment]
Correction, recognition is now working on my installation. Only notable change I think is that I've upgraded from Nextcloud 26.0.0 to Nextcloud 26.0.1

**Comment by marcelklehr** [comment]
You probably updated to v3.8.0 / v4.0.1 in the process. I've included a fix for this issue, just forgot to close it.
