### ISSUE TITLE
Face Recognition is stuck/not processing at all

### ISSUE THREAD

**Issue by piyushaswani55** [nextcloud/recognize#809]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

26.0.0

### Which Operating system do you have installed?

Alpine in Docker on DietPi OS (bookworm 64bit)

### Which Docker container are you using to run Nextcloud? (if applicable)

linuxserver

### How much RAM does your server have?

8

### What processor Architecture does your CPU have?

arm64

### Describe the Bug

After almost a month of debugging and trial & error, I was finally able to get the app installed but seems like all those efforts are in vain because the app doesn't do it's work properly.
More Context about the previous issues here : https://github.com/nextcloud/recognize/issues/775

But currently the problem is that the Face Recognition is not working at all and is stuck. I see images queued but no face is recognised yet. Even to get it to working I had to manually run the commands on terminal, it wasn't working from the "Administration Setting" at all.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/5944859/233838018-7ee30b90-61cc-4421-b3b9-3ab7c45d897f.png">

I followed another issue thread (https://github.com/nextcloud/recognize/issues/608) and based on that these are the more details about the Recognize jobs from the DB.

```
id	class	argument	last_run	last_checked	reserved_at	execution_duration	argument_hash	time_sensitive
79	OCA\Recognize\BackgroundJobs\ClassifyFacesJob	{"storageId":1,"rootId":1}	0	1682269808	0	0	127f6d3080643c511e99c2b74a5ebfb5	1
80	OCA\Recognize\BackgroundJobs\StorageCrawlJob	{"storage_id":1,"root_id":1,"override_root":2,"last_file_id":46,"models":["faces"]}	0	1682269808	0	0	333815f1b056d4ab50de808546b8e152	1
81	OCA\Recognize\BackgroundJobs\ClassifyFacesJob	{"storageId":3,"rootId":215}	0	1682269808	0	0	c2576587fd207048e1726615cc634efc	1
82	OCA\Recognize\BackgroundJobs\StorageCrawlJob	{"storage_id":3,"root_id":215,"override_root":222,"last_file_id":387,"models":["faces"]}	0	1682269808	0	0	f226fc000c7b022be2c8b648749a7eee	1
```

### Expected Behavior

Recognize app should recognize individual faces and tag them, but queue is just stuck and no faces are found under People tab.

### To Reproduce

Install LinuxServer/Nextcloud docker container on a RaspberryPi 4, and try to use "Recognize" app which won't be easy and help is also very limited.

### Debug log

No debug logs available related to "Recognize".

**Comment by AndyXheli** [comment]
Same issue ruuning NC 26.0.1 App 3.7.0

**Comment by marcelklehr** [comment]
In the jobs table dump you provided, it looks like the jobs are never executed. Can you confirm that your cron setup is working? Also, please make sure that your maintenance window is either not set or set to a reasonable time as the jobs will only run in that window if it set. See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#maintenance-window-start

**Comment by AndyXheli** [comment]
@marcelklehr My cron ran a min ago 
![image](https://user-images.githubusercontent.com/59488153/234614649-354be5fb-0b80-4cce-a834-7148b0730079.png)

Recognition app still show 7 days ago 

![image](https://user-images.githubusercontent.com/59488153/234614834-bfe59caa-e27e-491e-8770-ae10a584607d.png)

**Comment by biguenique** [comment]
Seems like files get unqueued once _processed_, but what if they are _missing_?

I got stuck with 10200 files in queue right after moving external folders around.
They still linger there after a full `occ recognize:classify` job (ssh).

Mine are most likely _missing files_. Is there any way to **flush the queue** ?

_Recognize 3.7.0 (face recognition only, normal mode) NC 25.0.5 YunoHost/Debian 8 Gb RAM x86_64_

**Comment by marcelklehr** [comment]
@biguenique Starting with v3.8.0 you can now clear all queues and remove all scheduled background jobs with occ recognize:clear-background-jobs

**Comment by marcelklehr** [comment]
@AndyXheli Can you also try updating to v3.8.0 to see if that fixes things?

**Comment by AndyXheli** [comment]
@marcelklehr Thanks! i upgraded to 4.0.1 the Queue was still stuck so i cleared the Queue out and reset the face then ran a rescan all files but it only Queued 497 and no more then that now the Queue is 0 but i have alot more files then that do i need to run another occ to scan everything ?

**Comment by piyushaswani55** [comment]
@marcelklehr even with the latest version for some reason face recognition isn't working, only object recognition works. I have tried running the commands as well manually, but doesn't help.
<img width="930" alt="image" src="https://user-images.githubusercontent.com/5944859/235183750-4879cf96-092c-48a1-a100-c9e0a72c6e5c.png">

**Comment by marcelklehr** [comment]
> it only Queued 497

huh.

> do i need to run another occ to scan everything ?

You can run occ recognize:classify on the command line to see better what's happening

**Comment by marcelklehr** [comment]
> Face score too low. continuing with next face error keeps coming, even though the image is pretty clear and has multiple faces in it.

Then there's nothing we can do, for now. It may be due to WASM Mode

**Comment by AndyXheli** [comment]
> > it only Queued 497
> 
> huh.
> 
> > do i need to run another occ to scan everything ?
> 
> You can run occ recognize:classify on the command line to see better what's happening

Thank you! Giving it a try now.

**Comment by AndyXheli** [comment]
@marcelklehr thanks I give it a try and same results it will not run for all the pictures the before it used to scan over 40k worth of photos and quote them now no more then 400 and it stops after that.

**Comment by AndyXheli** [comment]
I also removed the app and reinstalled it and same results scans about 400 files or so the stops and not all faces are detected. Any other suggestions?

**Comment by bendschs** [comment]
same here

**Comment by aortmannm** [comment]
For me it seems like it stopped searching for new files ;/. I uploaded yesterday new pictures and the face recognician run is 4 days ago. I'm not sure if this is since I updated the recognize version to the newest stable. Do I need to retrigger anything? Object recognician seems to be executed -> see screenshot.

any ideas for me?

![image](https://github.com/nextcloud/recognize/assets/3414298/33f3a299-e0f1-4a27-aaf7-a840558b0424)

**Comment by whlsxl** [comment]
version 4.1.0
same error `Face score too low. continuing with next face.`
No face was detected, although the photo is a portrait.

**Comment by piyushaswani55** [comment]
From my experience I have seen that **Recognize** as an app is not that efficient, it doesn't deliver well and not very user friendly, still requires a lot of development. 
I really wished for it to work and had high expectations but I am kind of disappointed. With this working fine I would have had almost all my requirements fulfilled with just Nextcloud and it's apps/extensions. 

But I guess it's not gonna work for me, so while looking at alternatives the best thing I could find out was this another self-hosted service called [Immich](https://github.com/immich-app), it looks very similar to Google Photos and does exactly what you expect from it or it says. They recently added the Face Recognition functionality as well, which works pretty reliably.
So, as long as **Recognize** or **Face Recognition** apps don't start working well and deliver as they claim (which I hope changes soon) I am gonna continue to with Immich.

_The purpose of this comment is not to shame the app and it's developer or praise any other, these are just my opinions from my past experience with this app. As a developer myself I understand that it's not easy as other people may thing._
That being said I have faith in Nextcloud and it's vast community, that this app too will be as great as the **Memories** app and will work flawlessly along side to replace all the Photo Management needs of people who are looking for a privacy friendly and self-hosted alternatives. :)

**Comment by marcelklehr** [comment]
I'm closing this issue as the original issue seems to be resolved.

**Comment by marcelklehr** [comment]
For issues with faces not getting detected, I've created a discussion here #865
