### ISSUE TITLE
Recognize says everything is scanned and classified but nothing shows up.

### ISSUE THREAD

**Issue by carlchen2007** [nextcloud/recognize#813]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

no Docker

### How much RAM does your server have?

15GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

![image](https://user-images.githubusercontent.com/119757558/234402891-4934c978-57d8-45dd-88e8-26d05da7b15d.png)
![SCR-20230425-vu8](https://user-images.githubusercontent.com/119757558/234403020-0a22a187-9d50-44d2-8f9f-6e62d00a50eb.png)
Nothing shows up in the Photos App but it has done something.

### Expected Behavior

Pictures should show up in Persons tab.

### To Reproduce

Normal installation.

**Comment by marcelklehr** [comment]
How many pictures do you have? Below 100-200 pictures the clustering won't start because the results would be bad.

**Comment by carlchen2007** [comment]
about 150 it said. ill upload more to test!

**Comment by kaincenteno** [comment]
I'm experiencing the exact same issue, have more than 200 pictures. Is there a log that for recognize that i can refer to? I had to run `occ recognize:download-models` after enabling the app

![Screenshot from 2023-04-27 15-49-26](https://user-images.githubusercontent.com/26943220/235007215-9c878b82-01dc-43ab-adbc-5d43be647bbf.png)

**Comment by marcelklehr** [comment]
There was a bug introduced by incompatibility of recognize with NC 26.0.1. Recognize v4.x fixes that. Can you try updating?

**Comment by kaincenteno** [comment]
> There was a bug introduced by incompatibility of recognize with NC 26.0.1. Recognize v4.x fixes that. Can you try updating?

Forgot to mention I just installed it two days ago, on version 4.0.1

![Screenshot_2023-04-28-07-49-25-762_com.android.chrome.jpg](https://user-images.githubusercontent.com/26943220/235180580-9e475e9d-b3be-47f1-b23b-1ca8f599e903.jpg)

Let me know if there's somewhere to pull logs =)

**Comment by carlchen2007** [comment]
What does the output of a classification say when it says:
Face results for 5389 are in
preparing face detection for user <username>
Face score too low. continuing with the next face.
face classifier end

**Comment by marcelklehr** [comment]
> Face score too low. continuing with the next face.

That means the detected face is doesn't look enough like a face.

**Comment by marcelklehr** [comment]
> Let me know if there's somewhere to pull logs =)

Nextcloud log. You are using Nextcloud. When you need logs for it, go to the nextcloud log.

**Comment by SKB-CGN** [comment]
I have the same problem.

Log flooding with;

~~Error: Call to undefined method Rubix\ML\Datasets\Labeled::features()~~

**Comment by phil-lipp** [comment]
> I have the same problem.
> 
> Log flooding with;
> 
> `Error: Call to undefined method Rubix\ML\Datasets\Labeled::features()`

see #676

**Comment by SKB-CGN** [comment]
> > I have the same problem.
> > Log flooding with;
> > `Error: Call to undefined method Rubix\ML\Datasets\Labeled::features()`
> 
> see #676

Thanks, will there be again an update of the update for this update?

I love, when apps are updated, but everytime an app of nextcloud updates, it has some other app being disabled casuse of some error.

**Comment by SKB-CGN** [comment]
I have uninstalled the app again and switched over to FaceRecognition. This app is further developed and is working better. Not crashing or blocking different apps!

**Comment by marcelklehr** [comment]
If you feel like you need to vent, this is not the place for it. Go to the forum, to twitter or somewhere else. This is a technical issue tracker, so please make sure to focus on the tech and keep your opinions to yourself.
