### ISSUE TITLE
App update not under app store

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/recognize#814]
New update release not showing under https://apps.nextcloud.com/apps/recognize

**Comment by phil-lipp** [comment]
From my experience it takes some time to become available. I think there's some kind of approval process going on behind the scenes.
You could always download the git release and install it on your own. @marcelklehr has posted a brief explanation on how to do this somewhere in the discussion forum (I dont have the time to look for it now)

**Comment by AndyXheli** [comment]
Thank you!! I'll close for now
