### ISSUE TITLE
Recogniz does not continue after nc restart.

### ISSUE THREAD

**Issue by DenuxPlays** [nextcloud/recognize#816]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Fedora 38 (container: Alpine)

### Which Docker container are you using to run Nextcloud? (if applicable)

Nextcloud AIO v4.9.0

### How much RAM does your server have?

32GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Recognize does not continue after restart.
Every day at 1AM (UTC) my nextcloud does a backup. (Nextcloud AIO integrated borg backup solution) and for this the nc container stops.
Recognize doesn't seem to continue scanning after this.
![image](https://user-images.githubusercontent.com/83671398/235159324-9fb74d4f-9e08-4f4c-87ae-960afeb89976.png)

### Expected Behavior

After nextcloud starts recognize should start scanning all queued images.

### To Reproduce

* set up nextcloud AIO
* install recognize
* schedule an automatic backup

### Debug log

/

**Comment by marcelklehr** [comment]
If you stop the container while the classification job is running, nextcloud will wait some time before it tries running that job again, because it assumes it is faulty as it didn't finish properly. There's nothing I can do about that.

**Comment by DenuxPlays** [comment]
> If you stop the container while the classification job is running, nextcloud will wait some time before it tries running that job again, because it assumes it is faulty as it didn't finish properly. There's nothing I can do about that.

But I dont think that waiting for atleast 12h is expected behavior or?

**Comment by DenuxPlays** [comment]
> > But I dont think that waiting for atleast 12h is expected behavior or?
> 
> 
> 
> Yes that's expected behavior

Okay.
Is there are way to change this?
