### ISSUE TITLE
Unmanagable ghost faces in Photos and Memories

### ISSUE THREAD

**Issue by Andreaux** [nextcloud/recognize#822]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Ubuntu 22.10

### Which Docker container are you using to run Nextcloud? (if applicable)

Image nextcloud:latest on Docker v23.0.5

### How much RAM does your server have?

4GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I have installed Memories to have a neater way to organize photos, set tags, etc. which is not possible with the stock Photos app in NC and Memories integrates Recognize also, like Photos does (and does a way better job at it with options like framing the recognized face in the thumbnails so you really know who was classified on that thumbnail, which I love).
Now when opening People in both the Photos app and Memories, I see different things:
- Several faces in Photos are just blank grey circles with no photo in them. Opening those shows no picture at all, just a blank page.
![image](https://user-images.githubusercontent.com/1387888/235358534-6cd0ef70-9efb-42e5-b36a-fe3fef640c21.png)
(screenshot from Photos showing ghost face)
![image](https://user-images.githubusercontent.com/1387888/235358577-ed4140e3-0069-4cc0-979c-f032556dd3e9.png)
(screenshot from Photos showing ghost face)
- Opening the same ID face in Memories shows photos in there nicely.
- Removing photos from those "ghost" faces in Photos is not possible as no picture is displayed at all
- Trying to remove photos from people in Memories gives an error
![image](https://user-images.githubusercontent.com/1387888/235358792-531f0903-9b0d-43be-8fca-f8fec2f35fdd.png)
(screenshot from Memories trying to remove photo from person)

There is obviously something wrong with the way some of the found faces/people are stored/handled and this error is showing in Photos straight away and not so obviously in Memories (although when you try to remove photos from people in Memories, you run into an error). This doesn't seem to be a Memories or Photos issue as the problem affects both in some way.

I only tried to remove photos from people in Memories, didn't try to transfer photos to another person as I don't want to mess up classification.

There is no error of any kind in the logs.

### Expected Behavior

- People in both Photos and Memories should show images for faces recognized
- Photos should be removable from People in Memories
- There should be no "ghost" people in Photos with no pictures in the face preview or the page once clicked.

### To Reproduce

Install Recognize and Memories
Once you see People show up in Photos or Memories, check if all of them have pictures and the face preview actually contains a picture (ghost faces in Photos can be looked up in Memories as the ID in the URLs will be the same, e.g. https://*yournextcloud*/apps/photos/faces/21 vs  https://*yournextcloud*/apps/memories/recognize/*yourusername*/21

**Comment by Andreaux** [comment]
Moving images to another person also fails, I just found one mismatch to move and tried.

![image](https://user-images.githubusercontent.com/1387888/235361500-3c9b3aa9-4f5c-4c16-af50-e199ada7763d.png)

**Comment by Andreaux** [comment]
A new version of Memories just came out. I re-tested moving images to another person and it seems to have been solved, so that seems to not be an issue anymore. The ghost faces in Photos still remain.

**Comment by Andreaux** [comment]
I just catched an error in the Console (Chrome) when opening a ghost face in Photos/People (I redacted the hostname):

[ERROR] photos: Error fetching face files
SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at https://***hostname***/apps/photos/js/photos-main.js?v=34497e89-2:2:3662409 at Array.forEach (<anonymous>) at h.updateFiles (https://***hostname***/apps/photos/js/photos-main.js?v=34497e89-2:2:3662222) at https://***hostname***/apps/photos/js/photos-main.js?v=34497e89-2:2:2732297 at https://***hostname***/apps/photos/js/photos-main.js?v=34497e89-2:2:2733815 at Array.forEach (<anonymous>) at https://***hostname***/apps/photos/js/photos-main.js?v=34497e89-2:2:2733794 at h._withCommit (https://***hostname***/apps/photos/js/photos-main.js?v=34497e89-2:2:2735624) at h.commit (https://***hostname***/apps/photos/js/photos-main.js?v=34497e89-2:2:2733768)

**Comment by eldertek** [comment]
Same issue : ghost faces...

Nextcloud version : 26.0.1
![image](https://github.com/nextcloud/recognize/assets/118362885/b128bbf0-1962-4fa0-889d-18378f400532)

Get theses error when accesing the face page:
`{"reqId":"LDgV5bbXmP2Gn0XmHo8q","level":3,"time":"2023-05-11T13:04:46+00:00","remoteAddr":"77.143.29.230","user":"user","app":"webdav","method":"PROPFIND","url":"/fichiers/remote.php/dav/recognize/andrelauret/faces/3/","message":"value is not a valid attribute","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35","version":"26.0.0.11","exception":{"Exception":"BadFunctionCallException","Message":"value is not a valid attribute","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/Entity.php","line":169,"function":"getter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/Dav/Faces/FacePhoto.php","line":149,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/Dav/Faces/PropFindPlugin.php","line":57,"function":"getMetadata","class":"OCA\\Recognize\\Dav\\Faces\\FacePhoto","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"OCA\\Recognize\\Dav\\Faces\\{closure}","class":"OCA\\Recognize\\Dav\\Faces\\PropFindPlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/recognize/lib/Dav/Faces/PropFindPlugin.php","line":57,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"OCA\\Recognize\\Dav\\Faces\\PropFindPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":366,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":171,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/public/AppFramework/Db/Entity.php","Line":152,"message":"value is not a valid attribute","exception":[],"CustomMessage":"value is not a valid attribute"},"id":"645ce8040fca1"}`

**Comment by kpaaro** [comment]
> Same issue : ghost faces...
> 
> Nextcloud version : 26.0.1 ![image](https://user-images.githubusercontent.com/118362885/237697026-b128bbf0-1962-4fa0-889d-18378f400532.png)
> 
> Get theses error when accesing the face page: `{"reqId":"LDgV5bbXmP2Gn0XmHo8q","level":3,"time":"2023-05-11T13:04:46+00:00","remoteAddr":"77.143.29.230","user":"user","app":"webdav","method":"PROPFIND","url":"/fichiers/remote.php/dav/recognize/andrelauret/faces/3/","message":"value is not a valid attribute","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35","version":"26.0.0.11","exception":{"Exception":"BadFunctionCallException","Message":"value is not a valid attribute","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/public/AppFramework/Db/Entity.php","line":169,"function":"getter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/Dav/Faces/FacePhoto.php","line":149,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/nextcloud/apps/recognize/lib/Dav/Faces/PropFindPlugin.php","line":57,"function":"getMetadata","class":"OCA\\Recognize\\Dav\\Faces\\FacePhoto","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"OCA\\Recognize\\Dav\\Faces\\{closure}","class":"OCA\\Recognize\\Dav\\Faces\\PropFindPlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/recognize/lib/Dav/Faces/PropFindPlugin.php","line":57,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"OCA\\Recognize\\Dav\\Faces\\PropFindPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":366,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":171,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/public/AppFramework/Db/Entity.php","Line":152,"message":"value is not a valid attribute","exception":[],"CustomMessage":"value is not a valid attribute"},"id":"645ce8040fca1"}`
Same here

**Comment by Andreaux** [comment]
I somehow feel this is more of an issue with Photos than Recognize. I installed [Memories ](https://apps.nextcloud.com/apps/memories) and everything is fine in there, only Photos has issues.

**Comment by kpaaro** [comment]
@Andreaux I see the same thing

**Comment by Andreaux** [comment]
I updated Recognize to 4.1.0 today and can confirm the issue is gone. Yippeee!

**Comment by kpaaro** [comment]
Now I am getting this

``` 
"exception":{"Exception":"BadFunctionCallException","Message":"decodedValue is not a valid attribute","Code":0,"Trace":[{"file":"/config/www/nextcloud/lib/public/AppFramework/Db/Entity.php","line":169,"function":"getter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/config/www/nextcloud/apps/recognize/lib/Dav/Faces/FacePhoto.php","line":149,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/config/www/nextcloud/apps/recognize/lib/Dav/Faces/PropFindPlugin.php","line":57,"function":"getMetadata","class":"OCA\\Recognize\\Dav\\Faces\\FacePhoto","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":95,"function":"OCA\\Recognize\\Dav\\Faces\\{closure}","class":"OCA\\Recognize\\Dav\\Faces\\PropFindPlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/recognize/lib/Dav/Faces/PropFindPlugin.php","line":57,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"propFind","class":"OCA\\Recognize\\Dav\\Faces\\PropFindPlugin","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1662,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1647,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Server.php","line":366,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/remote.php","line":171,"args":["/config/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/public/AppFramework/Db/Entity.php","Line":152,"message":"decodedValue is not a valid attribute","exception":{},"CustomMessage":"decodedValue is not a valid attribute"}}
```

**Comment by marcelklehr** [comment]
@kpaaro Please open a new issue

**Comment by Andreaux** [comment]
I'd like to re-open this issue if possible, but only for Photos. Memories is OK, but the issue came back on Photos. I'm not sure it has anything to do with the 26.0.2 update, but it's definitely back. I have a Person identified who has no thumbnail and no photos and when opened, there's a 404 error in the console. No pictures are shown. This person and their photos show up totally fine in Memories.

**Comment by marcelklehr** [comment]
@Andreaux can you a) test whether this issue persists even if you disable recognize? b) open a new issue if that is the case? If a) is not the case, then it's not an issue with recognize

**Comment by Andreaux** [comment]
Hello,
I am unable to test this if I disable Recognize because the People tab disappears and I don't see faces but it redirects to /settings/apps/installed/recognize

**Comment by Andreaux** [comment]
I have - for the sake of argument - disabled and re-enabled Recognize, nothing changed. I still have that one ghost in there and I know it's a legit one otherwise, because I gave it a name in Memories so I know what I should be seeing there. That person has 51 pictures when seen from Memories and doesn't show up at all seen from Photos.

**Comment by marcelklehr** [comment]
@Andreaux Please open a new issue.
