### ISSUE TITLE
Can't disable video tagging after moving NC from x64 to ARM64

### ISSUE THREAD

**Issue by seventhsite** [nextcloud/recognize#828]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

No docker. NGINX, MariaDB, PHP8.2

### How much RAM does your server have?

8 GB + 4 GB swap

### What processor Architecture does your CPU have?

ARM64, Hetzner Ampere VPS

### Describe the Bug

After using NC on x64 VPS, I moved it to cheaper ARM server (copied DB, data and /var/www/nextcloud folders)
Running in WASM mode can't disable video tagging and have a lot of errors in log. 
Enable human action recognition switch is not active.

> WASM mode was activated automatically, because your machine does not support native TensorFlow operation:
> Your server does not support AVX instructions
> Your server does not have an x86 64-bit CPU

![image](https://user-images.githubusercontent.com/19604503/236501769-bf2c1ff6-c276-49d5-b22b-b793c79b3185.png)

![image](https://user-images.githubusercontent.com/19604503/236502453-30c6d1b2-7413-4b9f-8586-cfbd64b403e1.png)

![image](https://user-images.githubusercontent.com/19604503/236502162-76341644-bec8-4959-b315-6034799662e9.png)

### Expected Behavior

Possibility to disable video tagging.

### To Reproduce

Setup NC on x64 and move it to ARM.

**Comment by marcelklehr** [comment]
Thank you for reporting this :blue_heart:
