### ISSUE TITLE
Setup still too complicated for normal users

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/recognize#838]
### Which version of recognize are you using?

I don't know. It doesn't show the version anywhere on the admin page.

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Ubuntu 20.04

### Which Docker container are you using to run Nextcloud? (if applicable)

LSIO

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

From: https://github.com/nextcloud/recognize/wiki/Manual-install

> The easiest way to install libtensorflow is pointing your terminal at apps/recognize/ and running npm ci, preferably using npm v8.

Result: https://pastebin.com/nrX6Wnu2

### Expected Behavior

No hassle trying to run Recognize :)

Some things that would help users that I've noticed while dealing with this:
- Place the version of Recognize right on the Admin page for Regonize's Settings. Bonus to also add the versions for anything else Recognize depends on, such as the Node.js version detected.
- A tool tip or similar next to things than your average user would have zero idea what the feature does. Such as "WASM Mode", and "GPU Mode". Those are "geeky" sounding things that your average user will scratch their head at when seeing. Also, a description on "Why" a user would want to enable or disable them. Right now it just basically says "Yo, Ya want WASM Mode on or off??"
- It would be really nice if this all was abstracted away from the user. All packages required (Tensorflow, node.js, their proper paths, proper permissions set, et. al.)  just get installed with the main Recognize app, so we don't have to manually hunt error alerts down on google, and manually install and configure packages. Just a hassle-free installation.

### To Reproduce

- Install Recognize from Apps tab in NC
- Notice bunch of issues on Recognize's  Settings page (i.e. Could not check whether your machine supports native TensorFlow operation.)
- Google and come across a bunch of pages, [some of which](https://help.nextcloud.com/t/could-not-execute-the-node-js-binary-you-may-need-to-set-the-path-to-a-working-binary-manually/153720) lead to the Manual Install page linked above
- Take the "easiest" route described on that page
- Get a ton of [failures/errors](https://pastebin.com/nrX6Wnu2) :)

**Comment by marcelklehr** [comment]
> LSIO

If this means linuxserver.io then it doesn't support normal mode. You'll need to run in WASM mode. WASM means WebAssembly.

> [Manual-install](https://github.com/nextcloud/recognize/wiki/Manual-install)
> [...]
> node@10

Node version 10 is too old. You'll need at least v16. This is also written on the admin page.

> It doesn't show the version anywhere on the admin page.

All apps' versions are displayed on the apps page in your nextcloud UI.

> Those are "geeky" sounding things that your average user will scratch their head at when seeing.

I'll try to improve this. Thanks for the suggestions!

> It would be really nice if this all was abstracted away from the user. All packages required just get installed with the main Recognize app.

Yes, that's the idea. It just doesn't work in all cases, e.g. when people use the LSIO docker container.

**Comment by YouveGotMeowxy** [comment]
> Yes, that's the idea. It just doesn't work in all cases, e.g. when people use the LSIO docker container.

Hmm, maybe I'll give the official NC container a try instead then. I looked a t doing so once, but it seemed like a whole lot of extra work in getting it setup compared to the linuxserver container, which was why I went with the LSIO one in the first place. Almost all of their containers follow the same exact logic when setting up, so it's super easy to get a LSIO container running in no time.

**Comment by marcelklehr** [comment]
Mostly fixed by adding more explanations.

**Comment by zzyzx-dc** [comment]
> > Yes, that's the idea. It just doesn't work in all cases, e.g. when people use the LSIO docker container.
> 
> Hmm, maybe I'll give the official NC container a try instead then. I looked a t doing so once, but it seemed like a whole lot of extra work in getting it setup compared to the linuxserver container, which was why I went with the LSIO one in the first place. Almost all of their containers follow the same exact logic when setting up, so it's super easy to get a LSIO container running in no time when you've run many other LSIO containers before it.

Hi - did you get it working with the official Nextcloud container or is it still using WASM?

**Comment by chri2** [comment]
**recognize 3.8.0 on nextcloud 25 on a Synology NAS**

I ended up here, because I searched for the words: "nextcloud recognizeTensorflow WASM mode".

I don't know what `WASM` is and am searching for an explanation about the term and information whether it should be enabled or disabled in my setup.

There are no tooltips and no information shown in my gui:

![Image](https://github.com/user-attachments/assets/39401a02-d53e-4623-b1bc-3e89096cc487)

The installation from the webgui didn't work and installing on the command line produced the same error:

```
# sudo -u http php74 occ app:install -vvv recognize
Error: Could not extract app recognize: Out-of-path file extraction {/volume1/@tmp/oc_tmp_VrLWBP-folder/recognize/node_modules/@mapbox/node-pre-gyp/node_modules/.bin/rimraf --> ../rimraf/bin.js}
```

I had to install manually by downloading and extracting the tar.gz. Then I've been able to enable the App from the command line (didn't try from the gui).

The point @YouveGotMeowxy makes is still IMHO. Please re-open this.

**Comment by chri2** [comment]
Hm, my updater said I couldn't update no more, but you're right: My fault there seem to be newer versions that I probably do not get (yet) because of my older php...

Thanks for the cool project and the quick answer!
