### ISSUE TITLE
include(): Failed opening '/var/www/nextcloud/apps/recognize/vendor/composer

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/recognize#839]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Ubuntu 22.0.4

### Which Docker container are you using to run Nextcloud? (if applicable)

None

### How much RAM does your server have?

26GB

### What processor Architecture does your CPU have?

x64

### Describe the Bug

see logs

### Expected Behavior

See logs

### To Reproduce

Not sure

### Debug log

{"reqId":"nNp1Pwhx2fG97mjmSSv3","level":3,"time":"2023-05-08T08:32:25-05:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"include(/var/www/nextcloud/apps/recognize/vendor/composer/../../lib/BackgroundJobs/ClusterFacesJob.php): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/composer/composer/ClassLoader.php#578","userAgent":"--","version":"26.0.1.1","data":{"app":"PHP"},"id":"645a4ccaa1542"}

{"reqId":"nNp1Pwhx2fG97mjmSSv3","level":3,"time":"2023-05-08T08:32:25-05:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"include(): Failed opening '/var/www/nextcloud/apps/recognize/vendor/composer/../../lib/BackgroundJobs/ClusterFacesJob.php' for inclusion (include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') at /var/www/nextcloud/lib/composer/composer/ClassLoader.php#578","userAgent":"--","version":"26.0.1.1","data":{"app":"PHP"},"id":"645a4ccaa1537"}

**Comment by lckarssen** [comment]
I see the same messages in my logs. I'm not sure of this affects Recognize's behaviour and I can't tell what triggered it.

- OS: Ubuntu 20.04
- Nextcloud: 26.0.1
- Recognize: 4.1.0

**Comment by marcelklehr** [comment]
Can you try updating to Nextcloud v26.0.2?

**Comment by lckarssen** [comment]
A quick update: I no longer see the aforementioned messages in the logs. Maybe the upgrade to Nextcloud 26.0.2 indeed fixed the underlying problem. I upgraded some time ago and forgot to keep an eye on the logs for this issue so I can't say for sure.

**Comment by marcelklehr** [comment]
Cool! Thanks for the update :)
