### ISSUE TITLE
occ recognize:cluster-faces exits on PHP memory exhaustion or gets OOM killed

### ISSUE THREAD

**Issue by cliffalbert** [nextcloud/recognize#843]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Debian 12

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

32

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

When running occ recognize:cluster-faces a PHP memory exhaustion occurs or it get's OOM killed based on batch-size.

Without a batch size it get's OOM killed as php memory limit is set to -1 (see https://github.com/nextcloud/recognize/commit/308f9d4024fbe4f27e261c00a736810ff5047b63). 

Out of memory: Killed process 22092 (php) total-vm:36580832kB, anon-rss:31636976kB, file-rss:1708kB, shmem-rss:204kB, UID:33 pgtables:68532kB oom_score_adj:0

With a batch size of 200 it get's PHP memory exhaustion when PHP limit is set to 8 GB:

$ ./occ recognize:cluster-faces --batch-size=200
Clustering face detections for user cliff
ClusterDebug: Retrieving face detections for user cliff
ClusterDebug: Found 120 unclustered detections. Calculating clusters.
PHP Fatal error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 655360 bytes) in /opt/nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php on line 449

When raising the memory limit to 16GB it proceeds to run with batch size 200

There are about 300~350 thousand images that are being processed in total. At the moment there are around 230 named clusters and a few thousand unnamed clusters.

### Expected Behavior

Clustering faces

### To Reproduce

$ ./occ recognize:cluster-faces

**Comment by cliffalbert** [comment]
Currently testing the maximum batch size for 16G ram. It looks like it goes pretty ok when 16G ram is allocated to PHP. However when looking at the memory suggestions in recognize for clustering faces 8G should always be more then enough for a batch size of 200 (not that a batch size of 200 is that useful).

**Comment by marcelklehr** [comment]
> However when looking at the memory suggestions in recognize for clustering faces 8G should always be more then enough for a batch size of 200

Yes, 200 faces should be no problem with 8GB RAM.

One issue that I see is the amount of existing clusters: Recognize will sample ~40 faces from each existing cluster to allow new faces to be added to existing clusters, which in your cases causes 9660 faces to be added to the clustering in addition to your 200.

**Comment by marcelklehr** [comment]
But even those 9800 faces should be no problem with 8GB

**Comment by cliffalbert** [comment]
Yeah but those 230 are the named clusters (with person names), there are probably a few thousand clusters with "unknown" people. So that would equate to some 80000 faces. And in that case I can understand that 8GB would not be enough. So it seems to be the case to find the sweet spot for batch size.

Maybe there could be some kind of auto-tuning mechanism that will pre-calculate the batch size that could be safely done with the current memory limit on PHP.

**Comment by marcelklehr** [comment]
> Maybe there could be some kind of auto-tuning mechanism that will pre-calculate the batch size that could be safely done with the current memory limit on PHP.

Yeah, we do have to do some tuning on this evidently. I agree.
