### ISSUE TITLE
CUDA Libraries not found

### ISSUE THREAD

**Issue by arch-user-france1** [nextcloud/recognize#864]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Object recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

27.0.0 beta 1

### Which Operating system do you have installed?

Fedora

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

40GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

It seems that tensorflow is missing some libraries, _even though pytorch works fine on my machine and runs as expected_:

```
Running array (
  0 => '/bin/node',
  1 => '/var/www/html/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: 2023-05-28 09:13:33.016381: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.016668: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Classifier process output: 2023-05-28 09:13:33.054740: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Classifier process output: 2023-05-28 09:13:33.452690: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero

Classifier process output: 2023-05-28 09:13:33.452938: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.452993: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.453044: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.453093: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.453143: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.453191: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.453240: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory

Classifier process output: 2023-05-28 09:13:33.453297: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory
2023-05-28 09:13:33.453308: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

### Expected Behavior

Libraries are shipped by.

### To Reproduce

1. Install
2. Use /bin/node because Selinux does not like executing the shipped file. It tells me it could not find the file, however, it appears with ls. Does not matter if root privileges are used.
3. Enable WASM Mode
4. Disable WASM Mode
5. Enable GPU Mode
6. Run via the CLI with recognize:classify
7. See error
8. Run without GPU Mode
9. Runs fine
10. Enable GPU Mode
11. See error

**Comment by arch-user-france1** [comment]
From the Tensorflow Documentation:
<img width="937" alt="grafik" src="https://github.com/nextcloud/recognize/assets/72965843/b4761b9a-664d-4d6b-8c7e-4aca24187548">


Since the problem may be a misconfiguration of my system, I will look into it if someone verifies it's worked on other machines.

**Comment by marcelklehr** [comment]
>  Libraries are shipped

No. This won't work.

> Enable GPU Mode

In addition to enabling GPU mode, you need [the following](https://github.com/nextcloud/recognize/wiki/GPU-mode)

**Comment by arch-user-france1** [comment]
I'm sorry, but I don't understand. How am I supposed to install the CUDA libraries with Python when you are using NodeJS?

**Comment by marcelklehr** [comment]
> How am I supposed to install the CUDA libraries with Python when you are using NodeJS?

You can install CUDA and cuDNN via pip. Since you are making them available systemwide anyway via LD_LIBRARY_PATH, Tensorflow running in Node.js can use them too.

**Comment by arch-user-france1** [comment]
As suspected, it did not do anything. These commands only set up CUDA and CUDNN in a conda environment, but not globally and system-wide. It'll install them to the environment called `base`, in case nothing else is activated.

**Comment by marcelklehr** [comment]
Well, you do need to do some additional steps to add the libraries to the system: https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux

**Comment by arch-user-france1** [comment]
> Well, you do need to do some additional steps to add the libraries to the system: https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux

I really don't think we're on the correct path. These libraries are pre-installed because I have the CUDA package on the system.

**Comment by marcelklehr** [comment]
> These libraries are pre-installed because I have the CUDA package on the system.

Which version of the CUDA toolkit did you install, then?

**Comment by arch-user-france1** [comment]
Here's what `nvidia-smi` tells me: `CUDA Version: 12.0`.

**Comment by marcelklehr** [comment]
You need 11

**Comment by arch-user-france1** [comment]
Could you update your libraries so version 12 is supported too?

**Comment by marcelklehr** [comment]
No

**Comment by arch-user-france1** [comment]
From what I have heard, the CUDA libraries are back-compatible. Is the `$LD_LIBRARY_PATH` modified by your environment or PHP? Typically it should be empty.

**Comment by marcelklehr** [comment]
LD_LIBRARY_PATH is just a way to make the library files available if you installed them via python as recommended by the tensorflow documentation. If you insist on not installing them via python, I cannot help you.

**Comment by GreyMamoN** [comment]
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
sudo dpkg -i cuda-keyring_1.0-1_all.deb
sudo apt update
sudo apt install nvidia-cuda-toolkit cuda-11-8 cuda-drivers cuda-toolkit libcudnn8 libcudnn8-dev

Якщо е ще якась cuda окрім 11 тоді:
echo 'export PATH=/usr/local/cuda-11.8/bin:$PATH' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH' >> ~/.bashrc
source ~/.bashrc
sudo ldconfig
