### ISSUE TITLE
New faces from new photos (since 3 month) aren't listed

### ISSUE THREAD

**Issue by sebthesun** [nextcloud/recognize#871]
### Which version of recognize are you using?

3.8.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.7

### Which Operating system do you have installed?

ubuntu server 20.04

### Which Docker container are you using to run Nextcloud? (if applicable)

not using docker

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Since February, none of faces on new photos are listed and classify with no new or actual listed people.
Despite that fact, new photo are tagged with those tags:
recognize v3.0.0
Portrait
People
I'd launch occ recognize:recrawl but nothing changed.

### Expected Behavior

Faces on new photos get classified and associated with existing people or new people are created.

### To Reproduce

There are no step to reproduce, it always isn't working

**Comment by marcelklehr** [comment]
Can you post the contents of your oc_jobs database table?

**Comment by marcelklehr** [comment]
Also, can you run the following SQL query: `SELECT COUNT(*) from oc_recognize_face_detections where cluster_id IS NULL;`

**Comment by drhirn** [comment]
Same here using NC26 and Recognize 4.2.0 on bare metal.
Recognize tells me `Face recognition: 100 Queued files, Last classification: 3 days ago` and this doesn't change. In these last three days, I made manual classifies and started recrawls. Didn't change anything. New photos are still not tagged or faces recognized.

oc_jobs:
```
| 85332 | OCA\Recognize\BackgroundJobs\ClassifyImagenetJob                | {"storageId":1,"rootId":1}                                                                                                          | 1687339202 |   1687339202 |           0 |                193 | 127f6d3080643c511e99c2b74a5ebfb5 |              0 |
| 85353 | OCA\Recognize\BackgroundJobs\ClassifyFacesJob                   | {"storageId":1,"rootId":1}                                                                                                          |          0 |   1687340719 |           0 |                  0 | 127f6d3080643c511e99c2b74a5ebfb5 |              1 |
| 85354 | OCA\Recognize\BackgroundJobs\StorageCrawlJob                    | {"storage_id":1,"root_id":1,"override_root":2,"last_file_id":2044650,"models":["faces","imagenet","landmarks","movinet","musicnn"]} |          0 |   1687340720 |           0 |                  0 | 2dfee55f260f6a05fb6c9acc4f3e3dc0 |              1 |
| 85355 | OCA\Recognize\BackgroundJobs\StorageCrawlJob                    | {"storage_id":1,"root_id":1,"override_root":2,"last_file_id":1944698,"models":["imagenet"]}                                         |          0 |   1687340720 |           0 |                  0 | f5a55456e7114964dcdb6516fcd3b127 |              1 |
```

SELECT statement:
```
SELECT COUNT(*) from oc_recognize_face_detections where cluster_id IS NULL;
+----------+
| COUNT(*) |
+----------+
|     1424 |
+----------+
1 row in set (0.001 sec)
```

If you need more information, just ask.

**Comment by marcelklehr** [comment]
@drhirn Thank you for chiming in an providing data :) 

So, from the jobs table it seems ClassifyFacesJob on storage 1 is still waiting to be run for some reason. Triggering recrawls will probably not help with this as it just reduces the time available for other jobs.

> 1424 faces with cluster_id IS NULL

This would indicate that a face clustering run is pending for some reason. It should have been scheduled in the background automatically, but you can also run it manually using `occ recognize:cluster-faces -b 10000`

**Comment by drhirn** [comment]
```
$ myocc recognize:cluster-faces
Clustering face detections for user stefan
ClusterDebug: Retrieving face detections for user stefan
ClusterDebug: Found 6 fresh detections. Adding 1 old detections and 3042 sampled detections from already existing clusters. Calculating clusters on 3049 detections.
ClusterDebug: Clustering complete. Total num of clustered detections: 0

$ myocc recognize:cluster-faces -b 10000
Clustering face detections for user stefan
ClusterDebug: Retrieving face detections for user stefan
ClusterDebug: Not enough face detections found
```

Checked some faces I'm missing photos from but no change.

```
| 85332 | OCA\Recognize\BackgroundJobs\ClassifyImagenetJob                | {"storageId":1,"rootId":1}                                                                                                          | 1687339202 |   1687339202 |           0 |                193 | 127f6d3080643c511e99c2b74a5ebfb5 |              0 |
| 85447 | OCA\Recognize\BackgroundJobs\ClassifyFacesJob                   | {"storageId":1,"rootId":1}                                                                                                          |          0 |   1687350017 |           0 |                  0 | 127f6d3080643c511e99c2b74a5ebfb5 |              1 |
| 85448 | OCA\Recognize\BackgroundJobs\StorageCrawlJob                    | {"storage_id":1,"root_id":1,"override_root":2,"last_file_id":2174824,"models":["faces","imagenet","landmarks","movinet","musicnn"]} |          0 |   1687350018 |           0 |                  0 | 0d1fa6ee2ed633f837f8e28aa0f0f6b3 |              1 |
| 85449 | OCA\Recognize\BackgroundJobs\StorageCrawlJob                    | {"storage_id":1,"root_id":1,"override_root":2,"last_file_id":1978471,"models":["imagenet"]}                                         |          0 |   1687350018 |           0 |                  0 | fb0bec5fbc9400d66523af6d7377a5d1 |              1 |
```

```
SELECT COUNT(*) from oc_recognize_face_detections where cluster_id IS NULL;
+----------+
| COUNT(*) |
+----------+
|     1418 |
+----------+
1 row in set (0.001 sec)
```

**Comment by marcelklehr** [comment]
> Found 6 fresh detections.

Ah, then those 1400 faces are too small, never mind then.

**Comment by drhirn** [comment]
Done that already. Multiple times. Last one was yesterday.

Is there a difference between `classify` and `recrawl`. Besides a recrawl is done in the background?

**Comment by drhirn** [comment]
Btw. the faces I'm missing are from portraits I took a week ago. Large faces (2268x4032) ;)

**Comment by marcelklehr** [comment]
> Done that already.

Did you also clear all background jobs or only triggered recrawl? In v4.2.0 the latter doesn't entail the former, yet.

**Comment by drhirn** [comment]
I cleared the background jobs, than triggered a recrawl.

**Comment by marcelklehr** [comment]
> I cleared the background jobs, than triggered a recrawl.

Good. Then you need to wait until all StorageCrawlJobs are done. From your oc_jobs table it looks like you simply need to wait. Do you have a maintenance window set in your config?

**Comment by marcelklehr** [comment]
Object detection is currently running, right?

**Comment by drhirn** [comment]
> Recognize will use the preview mechanism of nextcloud to resize them, maybe there's something going wrong there :/
Hmm. Using imaginary in a docker container. Just checked it's logs. Seems working perfectly.

> Good. Then you need to wait until all StorageCrawlJobs are done. From your oc_jobs table it looks like you simply need to wait.
Well. It's not the first day I'm having problems with this. I just waited a long time to answer to this issue because nothing I tried worked out ;). But I'll wait.

> Object detection is currently running, right?
Yes. But enabled it just some hours before posting here. Before I had only face-detection enabled. Which explains the missing tags. But tags are not my problem.

**Comment by drhirn** [comment]
Sorry, missed that one

> Do you have a maintenance window set in your config?

Yes.
`'maintenance_window_start' => 1,`

**Comment by marcelklehr** [comment]
Then the recognize jobs will only run between 1am to 5am I believe

**Comment by drhirn** [comment]
Doesn't seem so. But would make sense.

Actual nextcloud-log:
```
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Face results for 2179554 are in","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Face is not straight. continuing with next face.","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Face score too low. continuing with next face.","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Result for /stefan/files/Photos/2021/01_20210724_Grillage-Wolfi/Sophie/IMG_3776.JPG(oc_tmp_audh1k-.jpg) = [{\"angle\":{\"roll\":-15,\"pitch\":-3,\"yaw\":-7},\"vector\":{\"0\":-0.14899221062660217,\"1\":0.07755135744810104,\"2\":0.026331476867198944,\"3\":-0.02233174629509449,\"4\":-0.1986481100320816,\"5\":-0.07165426015853882,\"6\":-0.08249407261610031,\"7\":-0.06146266683936119,\"8\":0.09157034754753113,\"9\":-0.14351923763751984,\"10\":0.17978926002979279,\"11\":[...]\"y\":0.03419299920399983,\"height\":0.19631810983022052,\"width\":0.09990006685256958,\"score\":0.6094170808792114}]","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Face results for 2179562 are in","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Face score too low. continuing with next face.","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"face classifier end","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
{"reqId":"xMBac6S8YiqYrkbdZ1o8","level":0,"time":"2023-06-21T15:00:12+02:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Removing OCA\\Recognize\\BackgroundJobs\\ClassifyFacesJob with argument array (\n  'storageId' => 1,\n  'rootId' => 1,\n)from oc_jobs","userAgent":"--","version":"26.0.2.1","data":{"app":"recognize"}}
```

**Comment by marcelklehr** [comment]
Huh, but that means the classify faces jobs is currently running :tada:

**Comment by drhirn** [comment]
Yes. We'll wait and see.

**Comment by drhirn** [comment]
To clarify: The classify-job was always running when I did a recrawl. Still, new faces weren't recognized.

**Comment by marcelklehr** [comment]
> Still, new faces weren't recognized.

ah. Are they different in any way from your other pictures? Other file type, etc.?

**Comment by drhirn** [comment]
Nope. Same camera, same file type, same image-size, mostly the same time of day.

**Comment by drhirn** [comment]
I'm still testing. Unfortunately I've too many pictures.
What I found out in the meantime is, that face-clusters are found. But the faces don't get added to a person. My "people"-pages in Memories- and Photos App don't change. But I'm not sure, who's responsible for that.
So, don't close anything here github-bot! ;)

**Comment by marcelklehr** [comment]
> But I'm not sure, who's responsible for that.

That would be recognize, so you're at the right place.

> face-clusters are found

What do you mean by this? Do you mean the faces are found?

> But the faces don't get added to a person.

Could you check your oc_jobs table for a ClusterFacesJob entry? There should be one. If not, then the short-term fix is to run `occ recognize:cluster-faces -b 10000` on the terminal.

**Comment by drhirn** [comment]
No ClusterFacesJob entry there. In fact, there's no recognize job at all.

The admin page of recognize tells me:
```
Face recognition is working.
Face recognition: 0 Queued files, Last classification: 18 hours ago
Object recognition is working.
Object recognition: 0 Queued files, Last classification: 18 hours ago
```

```
$ occ recognize:cluster-faces -b 10000
Clustering face detections for user stefan
ClusterDebug: Retrieving face detections for user <user>
ClusterDebug: Not enough face detections found
```

There is a picture with `file_id` 2390580 i uploaded some days ago. It's a selfie of me taken with my smartphone camera. It got two labels `Portrait` and `People`.
There are a lot of pictures with my face on it. So there should be enough to compare ;).

```
select * from oc_recognize_face_detections where file_id = 2390580;

| id     | user_id | file_id | x                | y                | height           | width            | vector     | cluster_id | threshold |
| 131424 | <user>  | 2390580 | 0.28528247939216 | 0.31062376499176 | 0.25408840179443 | 0.31395358509488 | [0.011561490595340729,0.18862468004226685,-0.0038468390703201294,-0.04326195269823074,-0.09638723731040955,0.08351553231477737,-0.027579467743635178,-0.04057746380567551,0.11857769638299942,-0.03036070615053177,0.25163617730140686,0.024825014173984528,-0.24293997883796692,-0.017363525927066803,0.06359069794416428,0.13358648121356964,-0.12483237683773041,-0.09204477071762085,-0.221342995762825,-0.0823478251695633,-0.020820800215005875,0.005868848413228989,-0.043898217380046844,-0.018112000077962875,-0.13603875041007996,-0.2780260443687439,-0.03868131339550018,-0.08877197653055191,0.12915050983428955,-0.1738690435886383,0.006392450071871281,0.048223596066236496,-0.1071489080786705,0.005451483651995659,0.04314971715211868,0.06986530125141144,-0.05686134099960327,-0.10812565684318542,0.18047811090946198,-0.03442879766225815,-0.13736920058727264,0.09530927240848541,0.022663608193397522,0.2371889054775238,0.21582520008087158,-0.07282834500074387,0.14008361101150513,-0.08316551148891449,0.06610985845327377,-0.23887616395950317,0.061553359031677246,0.1377319097518921,0.08635497093200684,0.12672212719917297,0.039664044976234436,-0.14453822374343872,-0.012425348162651062,0.17044252157211304,-0.16156315803527832,0.1202918067574501,0.1387498378753662,-0.08879061043262482,-0.16727060079574585,-0.06579336524009705,0.14304517209529877,0.11275041103363037,-0.1565682739019394,-0.20591455698013306,0.11591998487710953,-0.15105871856212616,-0.07903770357370377,0.03612319380044937,-0.1354876309633255,-0.1809712052345276,-0.22804869711399078,0.13898035883903503,0.3945017158985138,0.17389869689941406,-0.25185614824295044,0.032173264771699905,-0.012240875512361526,-0.029338538646697998,0.05899978429079056,0.095299631357193,-0.0502854660153389,-0.11985619366168976,-0.06493431329727173,0.10749168694019318,0.24645867943763733,-0.0351320318877697,0.02422909066081047,0.19462168216705322,0.010693080723285675,-0.02437691017985344,-0.03917979449033737,0.07077176123857498,-0.0591789111495018,-0.03286752849817276,-0.0615287646651268,0.005382753908634186,0.06365925818681717,-0.13744324445724487,-0.04220755398273468,0.0993952676653862,-0.13174203038215637,0.23353491723537445,-0.01946486532688141,0.029456019401550293,0.06822749972343445,-0.013183433562517166,-0.03698522597551346,-0.0024272501468658447,0.24601732194423676,-0.21181201934814453,0.21449261903762817,0.22466401755809784,0.05978941172361374,0.05461137741804123,0.10664193332195282,0.1304517239332199,0.09496520459651947,0.01971163973212242,-0.23529388010501862,-0.07726307958364487,-0.020171716809272766,-0.048966869711875916,-0.06659244000911713,0.0018502632156014442] |         -1 |         0 |
```

If I get this right, cluster_id is -1.
Same with to other pictures of me I took a day later.

**Comment by marcelklehr** [comment]
> If I get this right, cluster_id is -1.

Are you still on v3.8.0? cluster_id = -1 should only be a thing in v4.2+, I think.

Can you try

```
SELECT COUNT(*) from oc_recognize_face_detections where cluster_id IS NULL;
```

```
SELECT COUNT(*) from oc_recognize_face_detections where cluster_id = -1;
```

**Comment by marcelklehr** [comment]
-1 would indicate that they were already run through clustering (at least if your on v4.2)

**Comment by marcelklehr** [comment]
Let's try resetting face clusters and rerunning them perhaps:

```
occ recognize:reset-face-clusters
occ recognize:cluster-faces -b 10000
```

**Comment by marcelklehr** [comment]
> It's just a little bit confusing how, when and why faces are recognized (or not).

Ah. So, recognize filters out faces it deems too problematic, either because they are too small in relation to the picture size, or the faces are taken from an angle or are rotated somehow or the classifier is otherwise unsure whether it's really a face. There may be room for improvement here.

**Comment by drhirn** [comment]
While searching through all unassigned faces I found pictures of monkeys and stuffed animal. And a really, really small face in the company logo on a beer bottle. And sometimes there are faces recognized I personally can hardly see. So I would say, face recognition is working very good.

It's just the thing with assigning to persons.

Does the model learn? I mean, does assigning faces to persons work better, the more pictures of this face are there?

**Comment by marcelklehr** [comment]
> Does the model learn? I mean, does assigning faces to persons work better, the more pictures of this face are there?

Yes

> While searching through all unassigned faces I found pictures of monkeys and stuffed animal. And a really, really small face in the company logo on a beer bottle. And sometimes there are faces recognized I personally can hardly see. So I would say, face recognition is working very good.

Are all these detections from v4.2.0, though, or are they remnants from older versions of recognize?

> It's just the thing with assigning to persons.

Assigning to persons relies on a face description vector which allows identifying similar faces, but if the vector is off for a face it's hard for the clustering to do good work, this is why we filter out detections. The detections may be good, but the descriptor may be off. This is currently a bit of a gamble, though, as we are not certain which aspects of a face confuse the face descriptor...

**Comment by drhirn** [comment]
> Are all these detections from v4.2.0, though, or are they remnants from older versions of recognize?

I can't say. I'm on holiday the next two weeks and I'm sure I'll find some time to remove all clusters and start from the beginning. Then we'll know for sure.

> Assigning to persons relies on a face description vector which allows identifying similar faces, but if the vector is off for a face it's hard for the clustering to do good work, this is why we filter out detections, where we have reason to believe the descriptor is off. The detections may be good, but the descriptor may be off. This is currently a bit of a gamble, though, as we are not certain which aspects of a face confuse the model that generates the face descriptor...

I see.

Thanks a lot for your time and patience! I'm happy with the possibility to view all unassigned faces for now.
I'll come back here when I have some answers to your first question.

**Comment by drhirn** [comment]
Did a rescan with 4.2.0
```
occ recognize:reset-face-clusters
occ recognize:cluster-faces
```

```
SELECT COUNT(*) from oc_recognize_face_detections where cluster_id = -1;
+----------+
| COUNT(*) |
+----------+
|     9514 |
+----------+
```

```
SELECT COUNT(*) from oc_recognize_face_detections where cluster_id > 0;
+----------+
| COUNT(*) |
+----------+
|     4127 |
+----------+
```

Monkey still there (the one on the right): https://cloud.jft.at/s/wftGpoYLY7B3YSX
Stuffed animal too: https://cloud.jft.at/s/JPsmjMCECRMAag6

And I'm really sad about the fact, that of all faces mine wasn't assigned to a cluster 😁

**Comment by marcelklehr** [comment]
Are your new photos on external storage?

**Comment by marcelklehr** [comment]
So, basically the question is do these faces not appear in your people view because the photos were never picked up by recognize, or because the faces were never assigned to a cluster.

**Comment by johnhelt** [comment]
I have the same issue. Since I installed recognise, and all the initial face recognition took place, no new faces are being added to either persons or unassigned persons. Only garbage like random reflections (not of faces) are detected and put into the "unassigned persons" category. ![bad detection](https://github.com/nextcloud/recognize/assets/43775572/b68909be-41ee-436c-950e-dbf7897b45de)

I can see that recognise is running from the nextcloud logs, and that images are skipped because of "too low score", even though I am sure they're shot face forward.
