### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by joelra** [nextcloud/recognize#872]
### Which version of recognize are you using?

4.1.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.2

### Which Operating system do you have installed?

Unraid

### Which Docker container are you using to run Nextcloud? (if applicable)

linuxserver/nextcloud:latest

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

I'm receiving an error repeatedly in the Nextcloud logs:

`Using ${var} in strings is deprecated, use {$var} instead at /config/www/nextcloud/apps/recognize/vendor/voku/portable-utf8/src/voku/helper/UTF8.php#13409`

When looking at Recognize settings, under the **Image Tagging** section I have a warning of ` An error occurred during face recognition, please check the Nextcloud logs. `. The only error in the logs I'm experiencing is above.

The error is logged when I click on a photo or video.

### Expected Behavior

That no error messages are thrown.

### To Reproduce

Click on an image or video.

**Comment by joelra** [comment]
Seems that this is an issue within Voku: https://github.com/voku/portable-utf8/issues/191

**Comment by EVOTk** [comment]
Same issue for me :(

**Comment by marcelklehr** [comment]
v4.2.0 should fix this
