### ISSUE TITLE
Clean installation - no face recognition

### ISSUE THREAD

**Issue by Hainer1** [nextcloud/recognize#880]
### Which version of recognize are you using?

4.1.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

26.0.2

### Which Operating system do you have installed?

Ubuntu 22.04.2

### Which Docker container are you using to run Nextcloud? (if applicable)

no Docker but proxmox with VM 

### How much RAM does your server have?

7,81GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Clean installation on Ubuntu NextCloud and Recognize and occ recognize:download-models.
I uploaded about 50 photos with faces for testing.
The first time I installed I got no feedback in the Nextcloud.log after 15 minutes and no search results after a few hours. So I tried a bit and started the manual remove and install process with:
occ app:remove recognize
occ app:install recognize
occ recognize:download-models

After 24 hours no faces are recognised, but the message is "Face recognition is working".
For objects, recognition seems to work and I get the correct message "Object recognition is working.

### Expected Behavior

In the Photos / People folder, I expect to see pictures sorted by faces.

### To Reproduce

I am now installing Ubuntu, NextCloud, Recognize and the occ:download-models for the 3rd time and I continue get this behavior. 

### Debug log

Unfortunately I do not see any logs in nextcloud.log. Only logs from the mail application, but that is a different issue. So the log is running. Is there a way to get a more detailed log somewhere else?

**Comment by marcelklehr** [comment]
Hey @Hainer1 

You will likely need more photos for clustering to kick in. It starts once more than 120 faces have been detected in a user's photos.

**Comment by Hainer1** [comment]
Yes, that solves the problem. Thank you very much.
