### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by eohlde** [nextcloud/recognize#893]
### Which version of recognize are you using?

4.2.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

Nextcloud Hub 4 (26.0.2)

### Which Operating system do you have installed?

Debian 10

### Which Docker container are you using to run Nextcloud? (if applicable)

NA

### How much RAM does your server have?

4 GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Classification is not working, If I try to execute it manually I get this:
`www-data@nextcloud:~/nextcloud$ php occ recognize:classify      
Processing storage 1 with root ID 2
generating preview of 16 with dimension 1024
Copying 16 preview to tempfolder
generating preview of 19 with dimension 1024
Copying 19 preview to tempfolder
generating preview of 20 with dimension 1024
Copying 20 preview to tempfolder
generating preview of 21 with dimension 1024
Copying 21 preview to tempfolder
generating preview of 22 with dimension 1024
Copying 22 preview to tempfolder
generating preview of 23 with dimension 1024
Copying 23 preview to tempfolder
generating preview of 24 with dimension 1024
Copying 24 preview to tempfolder
generating preview of 25 with dimension 1024
Copying 25 preview to tempfolder
generating preview of 26 with dimension 1024
Copying 26 preview to tempfolder
Classifying array (
  0 => '/tmp/oc_tmp_z4O2Mi-.jpg',
  1 => '/tmp/oc_tmp_IgIWzL-.jpg',
  2 => '/tmp/oc_tmp_3ONone-.jpg',
  3 => '/tmp/oc_tmp_UdmobH-.jpg',
  4 => '/tmp/oc_tmp_xlxOZ9-.jpg',
  5 => '/tmp/oc_tmp_Y0kEOC-.jpg',
  6 => '/tmp/oc_tmp_9rZSD5-.jpg',
  7 => '/tmp/oc_tmp_aSXAty-.jpg',
  8 => '/tmp/oc_tmp_3znPj1-.jpg',
)
Running array (
  0 => '/var/www/nextcloud/apps/recognize/bin/node',
  1 => '/var/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  2 => '-',
)
Classifier process output: 2023-06-22 02:51:49.485398: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Classifier process output: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at NodeFileSystem.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:227:40)
    at step (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:49:23)
    at Object.next (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:30:53)
    at fulfilled (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:21:58)

Classifier process output: 2023-06-22 02:51:49.485398: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at NodeFileSystem.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:227:40)
    at step (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:49:23)
    at Object.next (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:30:53)
    at fulfilled (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:21:58)

In Classifier.php line 208:
                            
  Classifier process error  
                            

recognize:classify`

The logs are showing this:

`
[core] Error: RuntimeException: Classifier process error at <<closure>>

0. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ImagenetClassifier.php line 47
   OCA\Recognize\Classifiers\Classifier->classifyFiles()
1. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 41
   OCA\Recognize\Classifiers\Images\ImagenetClassifier->classify()
2. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
   OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->classify()
3. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyImagenetJob.php line 33
   OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
4. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 78
   OCA\Recognize\BackgroundJobs\ClassifyImagenetJob->run()
5. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
6. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
7. /var/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2023-06-22T02:50:13+00:00
`

AND

`
[recognize] Warning: Classifier process output: 2023-06-22 02:50:13.530158: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at NodeFileSystem.<anonymous> (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:227:40)
    at step (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:49:23)
    at Object.next (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:30:53)
    at fulfilled (/var/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:21:58)

at 2023-06-22T02:50:13+00:00
`

I don't know if both problems are related? (classification not working AND the AVX2/FMA warning)

I do have a processor that supports AVX2/FMA though:

`
cat /proc/cpuinfo 
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD Ryzen 5 1600 Six-Core Processor
stepping        : 1
microcode       : 0x8001138
cpu MHz         : 3311.359
cache size      : 512 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips        : 6387.82
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD Ryzen 5 1600 Six-Core Processor
stepping        : 1
microcode       : 0x8001138
cpu MHz         : 3234.224
cache size      : 512 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 6
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed
bogomips        : 6387.82
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 43 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]
`

### Expected Behavior

classification to succeed

### To Reproduce

Install LXC template of nextcloud
Update to latest version
Install Recognize
Attempt to run classification

**Comment by eohlde** [comment]
I ran a 
`
php occ recognize:download-models
php occ recognize:classify
`
It looks to be running correctly now.

However I still get this warning:

```
Classifier process output: 2023-06-22 17:51:47.400224: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
```
I do have a CPU with those supported flags, Should I open a new github issue?

**Comment by marcelklehr** [comment]
> It looks to be running correctly now.

Nice. The warning can be disregarded.
