### ISSUE TITLE
Cron jobs create numerous warnings from libpng

### ISSUE THREAD

**Issue by stweil** [nextcloud/recognize#899]
### Which version of recognize are you using?

4.2.0

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

Nextcloud 26.0.3

### Which Operating system do you have installed?

Debian 12

### Which Docker container are you using to run Nextcloud? (if applicable)

none

### How much RAM does your server have?

8 GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

If the recognize app is enabled we get many e-mails from the Cron daemon with the subject `Cron <www-data@cloud> /usr/bin/php -f /var/www/nextcloud/cron.php`. These e-mails report different libpng warnings, all from the following list:

- `libpng warning: Interlace handling should be turned on when using png_read_image`
- `libpng warning: iCCP: known incorrect sRGB profile`
- `libpng warning: iCCP: profile 'icc': 'desc': ICC profile tag start not a multiple of 4`

Possibly related issue: https://github.com/nextcloud/server/issues/27290.

Those e-mails are nagging, but of course we don't want to disable e-mails from cron (nor do I want to disable the recognize app). Suppressing them might be a possible solution.

Maybe some warnings can be fixed (turn on interlace handling).

If there are problems with certain images, it would help to get the name of the image which causes the warning.

### Expected Behavior

No warnings, or at least warnings with the name of the image which caused the warning.

### To Reproduce

Unknown, because the images which cause the warnings are not known.

**Comment by marcelklehr** [comment]
> Possibly related issue: https://github.com/nextcloud/server/issues/27290.

Yep, that's a problem with the preview generator in nextcloud. Nothing I can do about this here in recognize.

**Comment by stweil** [comment]
@marcelklehr, why does the recognize app generate preview images during the recognition process?

Wouldn't it be sufficient to create preview images when needed (like in the photo app)? That would save huge amounts of disk storage, processing time and also avoid the libpng warnings from the cron jobs.

**Comment by marcelklehr** [comment]
> why does the recognize app generate preview images during the recognition process?

Because large pictures would otherwise blow up RAM consumption and processing time in the classification step.

**Comment by stweil** [comment]
So those preview images are not for end users, but only used for the classification? Then I wonder why they are not created as temporary files which are deleted after the classification step.

**Comment by marcelklehr** [comment]
> Then I wonder why they are not created as temporary files

They are :)

**Comment by stweil** [comment]
Hm. We had to disable the recognize app after it had used more than 250 GiB for preview images in our Nextcloud instance, causing a disk full error (the disk size is about 500 GiB). The classification step was still unfinished and would have written hundreds of more GiB for such images.

**Comment by marcelklehr** [comment]
This is an artifact of the way the preview generation works. I guess, it stores all generated previews in a cache on disk. Recognize cannot remove those. Recognize could avoid requesting a preview for images that are already small enough, but I doubt this would really fix this, as most actual photos are larger these days. Recognize could also avoid using the preview generator mechanism, but then we'd be duplicating code and I'm not sure what edge cases are waiting for us there, so probably not trivial.

**Comment by marcelklehr** [comment]
Can you share the path where these previews reside just to make sure where they come from?

**Comment by marcelklehr** [comment]
This may help alleviate the storage size issues: https://github.com/nextcloud/server/issues/5717#issuecomment-357605516

**Comment by stweil** [comment]
The preview images were in subdirectories of `data/appdata_*/preview`

**Comment by marcelklehr** [comment]
:+1: Did the comment above help?

**Comment by stweil** [comment]
I had already read that issue before. And yes, I could fix the "disk full" by removing the content of the `preview` folder and running `occ files:scan-app-data`. But as soon as the recognize app is activated again, new preview images are created, and the disk will run out of storage once more. My system administrator now even decided to ban any preview images by disabling them.

**Comment by marcelklehr** [comment]
I see. I'm currently trying to figure out what I can do to prevent preview image proliferation in recognize.
