### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by relink2013** [nextcloud/recognize#901]
### Which version of recognize are you using?

4.2.0

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

GPU mode

### Which Nextcloud version do you have installed?

27.0.0

### Which Operating system do you have installed?

Ubuntu 22.04 (LXC Container on Unraid 6.12.2 Host)

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

80GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Recognize is working, I am seeing faces populating in the Photos app. Using nvtop I can clearly see my GPU being pushed very hard. GPU usage fluctuates between 97% - 100%, and vRAM is between 1.781GiB - 1.977GiB out of 2GiB. 

However in the admin settings I constantly see the following error:

`An error occurred during face recognition, please check the Nextcloud logs.`

I am also noticing the following message, despite the classification running non-stop for over 12hr so far:

`Face recognition: 512 Queued files, Last classification: 4 hours ago`

Below are the 2 errors I see repeating on the Logging page of Nextcloud. 

```php
[core] Error: RuntimeException: Classifier process error at <<closure>>

0. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/LandmarksClassifier.php line 45
   OCA\Recognize\Classifiers\Classifier->classifyFiles()
1. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php line 41
   OCA\Recognize\Classifiers\Images\LandmarksClassifier->classify()
2. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifierJob.php line 70
   OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob->classify()
3. /var/www/nextcloud/apps/recognize/lib/BackgroundJobs/ClassifyLandmarksJob.php line 33
   OCA\Recognize\BackgroundJobs\ClassifierJob->runClassifier()
4. /var/www/nextcloud/lib/public/BackgroundJob/Job.php line 86
   OCA\Recognize\BackgroundJobs\ClassifyLandmarksJob->run()
5. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start()
6. /var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start()
7. /var/www/nextcloud/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute()

at 2023-07-01T01:30:03+00:00
``` 

```php
[recognize] Warning: Classifier process output: 2023-07-01 01:30:02.770005: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-01 01:30:02.821933: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-07-01 01:30:02.830031: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-07-01 01:30:02.830256: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-07-01 01:30:03.140048: W tensorflow/stream_executor/cuda/cuda_driver.cc:374] A non-primary context 0x5b4d740 for device 0 exists before initializing the StreamExecutor. The primary context is now 0x151a00000000. We haven't verified StreamExecutor works with that.
2023-07-01 01:30:03.140171: F tensorflow/core/platform/statusor.cc:33] Attempting to fetch value instead of handling error INTERNAL: failed initializing StreamExecutor for CUDA device ordinal 0: INTERNAL: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY: out of memory; total memory reported: 2092957696


at 2023-07-01T01:30:03+00:00
``` 

### Expected Behavior

To not see a perpetual error message in settings, Out of memory errors in the logs, along with seeing that the last classification was several hours ago despite seeing large amounts of activity on my GPU. 

### To Reproduce

Im not sure how to reproduce this bug, but I can say that this exact same behavior happened before when running Recognize in a VM on the same hardware. 

If it helps heres the details of my installation. 

```
Host_OS:    Unraid 6.12.2
LXC_OS:     Ubuntu 22.04
CPU:        Ryzen 5 2600+
RAM:        80GB DDR4
GPU:        Nvidia Quadro P400 (2GB)
NV_Driver:  535.54.03 (Matches Host version)
CUDA:       11.2.0
cuDNN:      8.1.0.77
NodeJS:     14.21.3 (Using System version)
NPM:        6.14.18
NGINX:      1.18.0
PHP:        8.1.2
``` 

I have also tried to modify;

`/var/www/nextcloud/apps/recognize/lib/Classifiers/Classifier.php`

Based [this](https://github.com/nextcloud/recognize/issues/550#issuecomment-1346432775) comment made by @marcelklehr  on issue #550. Issue 550 has been closed but either it hasn't been resolved, or a new issue has been introduced since then.

**Comment by arch-user-france1** [comment]
That means your graphics card does not have enough video RAM to load the model. Disable `gpu mode` as there is no solution other than buying better components.

**Comment by relink2013** [comment]
I was afraid the vram was going to be the issue. From what I have seen everything works fine in CPU mode.

It's a bit older of a card, but could a 980Ti run the needed code? It has 6GB of Vram vs the 2GB on the P400. The 980Ti is Maxwell and supports CUDA 5.2, the P400 is Pascal and supports CUDA 6.1...I mean I have 3 of them doing nothing, if I can put one to good use I'd be thrilled.

**Comment by marcelklehr** [comment]
You should try to see if it works. I don't know how backward compatible CUDA is.

**Comment by arch-user-france1** [comment]
As long the code re-tries with the CPU if the model could not be evaluated on the GPU you could try with the stronger GPU that has less VRAM, but I do not have any information about how often the OOM occurs and whether recognize actually does use the CPU instead. @marcelklehr, you do have more information about that part?

**Comment by relink2013** [comment]
I had several hundred OOM CUDA errors, but considering it has scanned over 300,000 pictures at that point thats not a bad ratio to have fall back on the CPU. Unfortunately I don't think it falls back like that, at-least I saw nothing indicating it did in the logs...

I did disable everything except facial recognition which seems to be a bit less intense on the GPU, besides most of the object recognition just created tags that made absolutely no sense anyway.

**Comment by arch-user-france1** [comment]
Still waiting for @marcelklehr's answer. I know it falls back to the CPU if libraries were not found, so it might as well do that in OOM situations.

**Comment by marcelklehr** [comment]
It does not fall back to CPU in case of OOM.
