### ISSUE TITLE
[perf] vector is fetched for all queries

### ISSUE THREAD

**Issue by pulsejet** [nextcloud/recognize#903]
### Which version of recognize are you using?

4.2.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

28

### Which Operating system do you have installed?

N/A

### Which Docker container are you using to run Nextcloud? (if applicable)

N/A

### How much RAM does your server have?

N/A

### What processor Architecture does your CPU have?

N/A

### Describe the Bug

The query builders use `FaceDetection::$columns` which fetches the vector for the DAV queries (huge and unnecessary)

### Expected Behavior

Don't fetch the vector.

### To Reproduce

N/A

**Comment by pulsejet** [comment]
Yeah, ideally it could be a lazy field in the FaceDetection object. I wouldn't say it'd be a premature optimization since the DAV API gets called a lot in many user-facing operations.

Anyway, feel free to close this if there's no plan in the near future.

**Comment by marcelklehr** [comment]
Fixed in the next release.
