### ISSUE TITLE
Blank people, can't manage

### ISSUE THREAD

**Issue by YFrendo** [nextcloud/recognize#910]
### Which version of recognize are you using?

Recognize 4.2.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

Nextcloud 27.0.3

### Which Operating system do you have installed?

Docker

### Which Docker container are you using to run Nextcloud? (if applicable)

v 27

### How much RAM does your server have?

32GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Some people have a blank face and we can't manage their photos.

During the classification phase the head is correctly displayed but at some point (I don't know when) the error appears.

This does not happen for all people.

Here the UI:

<img width="561" alt="Capture d’écran 2023-07-09 à 10 48 23" src="https://github.com/nextcloud/recognize/assets/66957426/73cdac5f-9fdf-4177-801e-bdb41852749c">

### Expected Behavior

Display the face for everyone and manage everyone

### To Reproduce

I don't know why some people work and other don't so I can't tell how to reproduce this issue maybee some type of file ?

### Debug log

[webdav] Erreur: TypeError: json_decode(): Argument #1 ($json) must be of type string, null given at <<closure>>

 0. /var/www/html/lib/private/Metadata/FileMetadata.php line 45
    json_decode(null, true)
 1. /var/www/html/custom_apps/recognize/lib/Dav/Faces/FacePhoto.php line 142
    OC\Metadata\FileMetadata->getDecodedValue()
 2. /var/www/html/custom_apps/recognize/lib/Dav/Faces/PropFindPlugin.php line 59
    OCA\Recognize\Dav\Faces\FacePhoto->getMetadata()
 3. /var/www/html/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\Recognize\Dav\Faces\PropFindPlugin->OCA\Recognize\Dav\Faces\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/custom_apps/recognize/lib/Dav/Faces/PropFindPlugin.php line 59
    Sabre\DAV\PropFind->handle("{http://nextclo ... e", ["Closure"])
 5. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\Recognize\Dav\Faces\PropFindPlugin->propFind(["Sabre\\DAV\\PropFind"], ["OCA\\Recognize\\Dav\\Faces\\FacePhoto"])
 6. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit("propFind", [["Sabre\\DAV\\P ... ]])
 7. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode(["Sabre\\DAV\\PropFind"], ["OCA\\Recognize\\Dav\\Faces\\FacePhoto"])
 8. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath("rrecognize/{user}/faces/{Name of people face}/", ["{DAV:}getconte ... "], 
 9. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus(["Sabre\\Xml\\Wr ... ]], ["Generator"], false)
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus(["Generator"], false)
11. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
12. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:PROPFIND", [["Sabre\\HTTP\\ ... ]])
13. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(["Sabre\\HTTP\\Request"], ["Sabre\\HTTP\\Response"])
14. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
15. /var/www/html/apps/dav/lib/Server.php line 364
    Sabre\DAV\Server->exec()
16. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
17. /var/www/html/remote.php line 172
    require_once("/var/www/html/a ... p")

PROPFIND /remote.php/dav/recognize/{user}/faces/{Name of people face}/

**Comment by usernamehyphen** [comment]
please check your database, if you open your non-working 'faces' then its url ends with an ID (number) use that number to get amount of matches, I am having same issue currently with face id 178

```sql
mysql> select count(*) from oc_recognize_face_detections where cluster_id = '178';
```
```
+----------+
| count(*) |
+----------+
|     1171 |
+----------+
1 row in set (0.01 sec)
```
second one, id 156 contains _only_ 854 images and still works ...for a while.
I think this is due to some tiny timeout and happens every time when count grows above about 1000 images.

**Comment by usernamehyphen** [comment]
this seemingly stopped to be an issue with release 4.3.0, the above face with id 178 now works - it takes a little while to load, but it works.

**Comment by marcelklehr** [comment]
Yay! Than this was an instance of #904
