### ISSUE TITLE
There are queued files in the face recognition queue but no background job is scheduled to process them

### ISSUE THREAD

**Issue by ralfi** [nextcloud/recognize#912]
### Which version of recognize are you using?

4.3

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

27.0.0

### Which Operating system do you have installed?

Debian 12

### Which Docker container are you using to run Nextcloud? (if applicable)

20.10.24+dfsg1-1+b3

### How much RAM does your server have?

32

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Face recognize does work this error appears ...

![image](https://github.com/nextcloud/recognize/assets/294423/47fb802a-0ba5-43d2-8d62-8ca13f8eab67)

Many faces shown in groups but no progress.
Object detection and ladmark recignition works, see here ...

![image](https://github.com/nextcloud/recognize/assets/294423/8048d3df-1796-469f-979a-f73801622813)

### Expected Behavior

Backdround job for face detection works ...

### To Reproduce

Do not how ...
How can i debug these behavior or how can i do a complete reset of face recognize?

**Comment by ralfi** [comment]
Yeah, reset-faces, wait a little bit and now it works ...

**Comment by backupandforkacc** [comment]
@ralfi : How did you reset faces?

**Comment by ralfi** [comment]
occ recognize:reset-faces

But the behavior comes again ...

**Comment by backupandforkacc** [comment]
Is your cronjob working correctly? I sometimes have problems with mine, but do not how to resolve them. 
So your face recognition does not work correctly, I assume?

**Comment by marcelklehr** [comment]
It does seem that sometimes the background jobs fail and then recognize just drops the ball on the queued files completely. Will have to think about how to remedy this.

**Comment by marcelklehr** [comment]
Can you identify any errors from the background jobs? When you enable debug logging it should spit out some stuff.

Interesting would be a debug log similar to `Removing *** with argument ***from oc_jobs` or any error thrown by recognize.

**Comment by ralfi** [comment]
Hi @marcelklehr,

atm i have delete the app but i will install again and tell you asap, please be a little patient. How do i enable debug logging?

**Comment by ralfi** [comment]
BTW most of behaviors like this are that pics are on externer devices with nfs or smb connection and i have a collection of 34k pics...

**Comment by marcelklehr** [comment]
> How do i enable debug logging?

You can add `'debug' => true` in config.php

**Comment by Haui1112** [comment]
> BTW most of behaviors like this are that pics are on external devices with nfs or smb connection and i have a collection of 34k pics...

Oop! This could be it! I have my 14k pictures on an smb share (allthough nc is on the host where the drive is attached). Could it be that Recognize bashes with samba?

**Comment by Ra72xx** [comment]
Same with local storage as external storage in NC, so not only a SMB thing.

**Comment by marcelklehr** [comment]
Anyone up for checking the debug logs whats happening to those jobs?

**Comment by ralfi** [comment]
I am clearing all face related settings and started a new recognize session - as different to other settings i only setup face detection. ATM no errors, will have a look on this. I mean, external related could be related to extended time range for detection because heavy i/o traffic will be generated.

**Comment by xsiviso** [comment]
I have the same issue as described above. In the Nextcloud logs I have a bunch of those errors. 
![Uploading IMG_7675.jpeg…]()

**Comment by ralfi** [comment]
ATM exactly the same here, no issues but not ready working yet. For me it seem so this could be a solution. But i will send a message later... later... later...

**Comment by ralfi** [comment]
Seems to be fixed with the last release...

**Comment by marcelklehr** [comment]
Thanks everyone for your feedback! Much appreciated :)

**Comment by marianionut** [comment]
I have the same issue with Nextcloud version 27.1 6 and Recognize version 5.0.3, a lot of pictures in my case 133228.

Nextcloud is installed in a VM with 16 GB RAM, OS Ubuntu, kernel, Linux 5.11.0-49-generic x86_64

CPU: Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz (8 cores)

The pictures are mounted from a second internal drive NVMe 4 TB with NTFS and external drive plugin.

I already reset faces ones and re-run the classify job, but it takes a few days to proces all my pictures which are added in the queue. The issue is  the background jobs don't pick up the new faces.
If I manually run the  command occ recognize:cluster-faces =>

Clustering face detections for user x
ClusterDebug: Retrieving face detections for user x
ClusterDebug: Not enough face detections found
Clustering face detections for user y
ClusterDebug: Retrieving face detections for user y
ClusterDebug: Not enough face detections found
root@nextcloud:/home/nextcloud#

It started fine for a few hours and after that just dropped the queue.
