### ISSUE TITLE
Nice binary not properly recognized

### ISSUE THREAD

**Issue by oddstr13** [nextcloud/recognize#922]
### Which version of recognize are you using?

4.3.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

27.0.1

### Which Operating system do you have installed?

QTS 5

### Which Docker container are you using to run Nextcloud? (if applicable)

linuxserver/nextcloud:27.0.1

### How much RAM does your server have?

8GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

`occ recognize:classify` errors with the following due to not properly auto-detecting nice;
```javascript
Running array (
  0 => '""',
  1 => '-0',
  2 => '/config/www/nextcloud/apps/recognize/bin/node',
  3 => '/config/www/nextcloud/apps/recognize/src/classifier_imagenet.js',
  4 => '-',
)
Classifier process output: sh: exec: line 0: "": not found

Classifier process output: sh: exec: line 0: "": not found


In Classifier.php line 216:
                            
  Classifier process error  
                            
recognize:classify
```

### Expected Behavior

nice is at `/bin/nice`, but the setting defaulted to an empty double quote (literally `""`, not an empty string)

**Workaround**:
Manually set *«Nice binary path»* to `/bin/nice` in the Recognize settings.

### To Reproduce

This was a fresh install of the addon.

**Comment by oddstr13** [comment]
Likely related to a748a900038ff227bcc14f3b670a294b9c464fd4 (#906)

**Comment by phil-lipp** [comment]
The fix has been commited two weeks ago...when can we expect a new release containing this fix, @marcelklehr?

**Comment by marcelklehr** [comment]
Soon-ish (in the next two weeks). Sorry for the delay

**Comment by marcelklehr** [comment]
Say hello to https://github.com/nextcloud/recognize/releases/tag/v4.3.1

**Comment by phil-lipp** [comment]
> Say hello to https://github.com/nextcloud/recognize/releases/tag/v4.3.1 👋 ♥️

I'm still getting an error, even though using `sudo -u www-data whereis nice` returns `/usr/bin/nice`.

```
Classifier process output: sh: 1: exec: "/usr/bin/nice": not found
```

**Comment by DonPicciotto** [comment]
Hi, I still have this problem, I tried setting "Nice binary path" to /bin/nice, as well as leaving it blank, but nothing changed
