### ISSUE TITLE
Face Recognition stopped working, queue empty, system cron active

### ISSUE THREAD

**Issue by Haui1112** [nextcloud/recognize#924]
### Which version of recognize are you using?

4.3.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

27.0.1.2

### Which Operating system do you have installed?

Ubuntu 22.04.2

### Which Docker container are you using to run Nextcloud? (if applicable)

Nextcloud:latest

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

After installing recognize and limiting it to 2 CPU cores, it did it's job, new faces were added, pictures were added to them. CPU utliziation spiked to 50% (quad core processor without hyperthreading) as expected every 5 Minutes (cron schedule) for about two days. There are roughly 10.000 Photos in the library. I then started naming some faces and merged some recognized faces since they actually were the same person. I then left it alone.

Opening faces again, it had re added the faces it had already found (I ran deduplication before installing recognize) which is odd. The named faces are still there as well.

It has added some new tags for the landscape and object recognition but is not doing much anymore. The pictures are mostly people, architecture, cars and text (like screenshots) so it should be able to recognize a lot of them.

Looking through the logs I didnt see one error mentioning faces or recognize. The log has 20.000 entries from it through. Also, I don't know where Nextcloud puts old logs as it moves them once they reach 100MB in size.

I put a log, cleaned of anything else as attachment.

### Expected Behavior

It should still be using quite a bit of cpu power and have a couple thousand photos recognized by now.

### To Reproduce

Maybe my mistake was starting to move pictures and deleting faces I was not interested in having.

### Debug log

[nextcloud-recognize.log](https://github.com/nextcloud/recognize/files/12207017/nextcloud-recognize.log)

**Comment by Byter3** [comment]
Bump!

I just started using Nextcloud-AIO with recognize a couple of weeks ago. Labelled all my images, but I never got a single person or a landmark to get recognized.

**Comment by Haui1112** [comment]
Quick update on the initial issue:
Recognize is still scanning through pictures but new ones only. It has recognized approximately 1180 faces, 119 Tags out of 16.000+ Photos

Is there anything I can do to make it scan all the old files further?

**Comment by Neon-44** [comment]
> Is there anything I can do to make it scan all the old files further?

isn't that what ``` occ recognize:recrawl ``` is for?

**Comment by Byter3** [comment]
My Issue is not that recognize didn't scan. Recognized labelled all my images, BUT for some reason, no faces clustered.
`
Face recognition: 0 Queued files, Last classification: 12 hours ago, Scheduled background jobs: 0, Last background job execution: never
Face clustering: 6586 faces left to cluster, Last clustering run: 1969. 12. 31., Scheduled background jobs: 0, Last background job execution: never
A minimum of 120 faces per user is necessary for clustering to kick in
`
What should I configure for face recognition to finally kick in?

**Comment by Byter3** [comment]
It is also true for landmarks:
`

Object recognition is working.
Object recognition: 0 Queued files, Last classification: 2 hours ago, Scheduled background jobs: 0, Last background job execution: never
Landmark recognition is working.
Landmark recognition: 0 Queued files, Last classification: 4 days ago, Scheduled background jobs: 0, Last background job execution: never
`

**Comment by Byter3** [comment]
Also, when trying to run occ recognize:cluster-faces, I get back this:

`
Clustering face detections for user AG
ClusterDebug: Retrieving face detections for user AG
ClusterDebug: Found 4513 fresh detections. Adding 0 old detections and 0 sampled detections from already existing clusters. Calculating clusters on 4513 detections.
An unhandled exception has been thrown:
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features() in /var/www/html/custom_apps/recognize/lib/Clustering/DualTreeBall.php:107
Stack trace:
#0 /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php(632): OCA\Recognize\Clustering\DualTreeBall::split(Object(Rubix\ML\Datasets\Labeled), Object(OCA\Recognize\Clustering\SquaredDistance))
#1 /var/www/html/custom_apps/recognize/lib/Clustering/MstSolver.php(22): OCA\Recognize\Clustering\MrdBallTree->grow(Object(Rubix\ML\Datasets\Labeled))
#2 /var/www/html/custom_apps/recognize/lib/Clustering/HDBSCAN.php(89): OCA\Recognize\Clustering\MstSolver->__construct(Object(Rubix\ML\Datasets\Labeled), 20, 4, Object(OCA\Recognize\Clustering\SquaredDistance), Array, true)
#3 /var/www/html/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php(91): OCA\Recognize\Clustering\HDBSCAN->__construct(Object(Rubix\ML\Datasets\Labeled), 5, 4)
#4 /var/www/html/custom_apps/recognize/lib/Command/ClusterFaces.php(67): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters('AG', 0)
#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\Recognize\Command\ClusterFaces->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Recognize\Command\ClusterFaces), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/console.php(100): OC\Console\Application->run()
#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
#12 {main}
`

**Comment by Neon-44** [comment]
oh yeah, had that same Problem as well.
don't ask why, but: disable the "suspicious login" app and it should work.

**Comment by marcelklehr** [comment]
Yes, `Error: Call to undefined method Rubix\ML\Datasets\Labeled::features()` is #677 which sadly is not fixable atm.

**Comment by marcelklehr** [comment]
For the other recognition queues it seems that sometimes classification errors and then recognize drops the ball completely on those queues and doesn't continue. I'm investigating over here: #912
