### ISSUE TITLE
[doc] Face recognition onboarding path for clustering

### ISSUE THREAD

**Issue by ohthehugemanatee** [nextcloud/recognize#925]
### Describe the feature you'd like to request

Doco that walks through setting up your face clusters for good results.

e.g. I let it run through my entire photo library before assigning names to clusters. I found some people were consistently confused, like my 3 kids. Now I have clusters with thousands of images that are all mixed together, and the only way to resolve is to manually disambiguate the kids for every. single. photo. I get the impression that if I had started with a sample of, say 100 photos, I could have set up those initial face clusters to give the algo something to work with and gotten a better result. Or maybe not? Since there's no clear "how we expect you to use this on an existing library" I can't tell.

### Describe the solution you'd like

Documentation that walks through the first steps with an existing media library. Do I crawl the whole library first? Just a subset? Is there a way to help the algorithm separate similar looking people? etc

### Describe alternatives you've considered

An OCC command to drop all the automatic cluster assignments, leaving manual assignments, so the cronjob can re-run.

**Comment by marcelklehr** [comment]
> I get the impression that if I had started with a sample of, say 100 photos, I could have set up those initial face clusters to give the algo something to work with and gotten a better result. Or maybe not? Since there's no clear "how we expect you to use this on an existing library" I can't tell.

This is a good question. Generally, my expectation would be that the more photos the clustering algorithm has available, the better. At this stage, I believe the clustering algorithm to be as good as it can get, any remaining problems are probably due to the face descriptor model, which is known to be biased against children sadly.

**Comment by marcelklehr** [comment]
You can try running the clustering on a small set of photos first, then correct the mistakes and run it on a larger sample, but I personally doubt, that the results are going to be better than with the "massive attack" approach :D

**Comment by marcelklehr** [comment]
I've created a wiki page. Feel free to add more questions that you want answered :) https://github.com/nextcloud/recognize/wiki/FAQ-on-Face-recognition
