### ISSUE TITLE
"An error occurred" show in screen, when open tags in app Photos

### ISSUE THREAD

**Issue by jerry-ch-issue** [nextcloud/recognize#926]
### Which version of recognize are you using?

3.8.0

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.9

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

no.

### How much RAM does your server have?

4GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

![屏幕截图(49)](https://github.com/nextcloud/recognize/assets/65878337/3ff01b11-9bad-49a8-ac64-4f27186eb528)
I don't know this problem should belong here. I tried to restart nginx mariadb php, and reset recognize. but didn't solve my problem.

### Expected Behavior

Show tagged photos in tags.

### To Reproduce

When opening tags in Photos.

**Comment by backupandforkacc** [comment]
Can you show a screenshot from the files? There should be tags of jpg files:

![grafik](https://github.com/nextcloud/recognize/assets/1709199/f61d1ab5-ae81-4a7e-976f-bf82ac307d3f)

**Comment by backupandforkacc** [comment]
And what about the "People" ? Are there faces showing up?

**Comment by marcelklehr** [comment]
Hi @jerry-ch-issue

This seems like a photos app issue. Please file this over there.
