### ISSUE TITLE
New files are not queued for recognition

### ISSUE THREAD

**Issue by jacksbox** [nextcloud/recognize#947]
### Which version of recognize are you using?

4.3.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.0.2

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

Postgres

### Which Docker container are you using to run Nextcloud? (if applicable)

aio

### How much RAM does your server have?

8

### What processor Architecture does your CPU have?

arm64

### Describe the Bug

The initial run of recognition went as it should (I triggered it manually via the occ command).
After that I copied over a bunch (10000) images in my nextcloud user data dir and added the files to nextcloud via the `scan` occ. 
All went well, the files show up in nextcloud, the preview generator app pics them up for generating previews...
But not recognize:
The Queue is empty since 8 hours (cron runs), last run was before scanning for the new files. `recrawl` has no impact.

Do I need to run the `classify` command again?
Shouldn't the new files be picked up, or are they just added to the queue when uploaded traditionally (not found via `scan`)?

### Expected Behavior

If nextcloud detects new files, be it via a normal upload or a scan of the user folders, this files should be added to the recognize queue

### To Reproduce

Copy some files in the nextcloud data dir, `scan` to add them to nextcloud, wait for recognize to pick them up (will not happen)

**Update**
I just read the change log of 3.4.1 and the external storage topics sounds like it addresses this issue (👍)... but what can I do if the scan already happened before I upgraded to 3.4.1?

**Comment by marcelklehr** [comment]
This issue fixed in v4.3.1 which was released today. With the new release files:scan should now trigger recognize

**Comment by marcelklehr** [comment]
> but what can I do if the scan already happened before I upgraded to 3.4.1?

Then you will need to run classify again.

**Comment by jacksbox** [comment]
> > but what can I do if the scan already happened before I upgraded to 3.4.1?
> 
> Then you will need to run classify again.

Ok, will do. Thank you.
And also thanks a lot for the great work with this app - I really love how well it sorts the pictures 🙏
