### ISSUE TITLE
Search for tags

### ISSUE THREAD

**Issue by markuman** [nextcloud/recognize#95]
E.g., I got several Images that were tagged with "elephant".  
However, when I search for "elephant" I would expect that they appears in the results. But the won't.

![elephanttag](https://user-images.githubusercontent.com/3920157/135134647-efcee4da-6f3d-484a-bbcd-23297d1ab164.jpg)

**Comment by marcelklehr** [comment]
We're aware of that problem. See https://github.com/nextcloud/server/pull/26813

**Comment by bonswouar** [comment]
Should we keep this issue open although it's a nextcloud server's feature?

**Comment by markuman** [comment]
> Should we keep this issue open although it's a nextcloud server's issue?

In case people search before open a new issue, it would prevent duplicates...  
But I don't mind... when you like to close, feel free to do it.

**Comment by marcelklehr** [comment]
Update: This has been postponed to Nextcloud 24

**Comment by fuzxi** [comment]
This seems to have been delayed again, to Nextcloud 25.

**Comment by marcelklehr** [comment]
This feature has been merged into current master on track for Nextcloud 25 :tada:
