### ISSUE TITLE
Rerun cluster assignment for unassigned Faces

### ISSUE THREAD

**Issue by jacksbox** [nextcloud/recognize#951]
### Describe the feature you'd like to request

I have a lot of unassigned faces and it is really cumbersome to assign all of them manually.
As I add more photos, merge clusters which show the same person, I think the system should get better in assigning the unassigned faces.

_Without any concrete idea how recognise currently works:_

It would be nice to rerun the cluster assignment for unassigned faces. 
I imagine, that after some manual merging of persons, moving around of Images and especially after new images are uploaded (classified and clustered), there should be a possibility for unassigned faces to now match a certain cluster?
(Maybe that will not work because the cluster ?vectors? are static?)

### Describe the solution you'd like

Dynamically adjust the vectors (or however cluster affiliation is decided) and retry unclustered faces

### Describe alternatives you've considered

None

**Comment by marcelklehr** [comment]
This is already implemented. Recognize adds a small-ish percentage of rejected face detections to each batch of faces to be clustered, see https://github.com/nextcloud/recognize/blob/main/lib/Service/FaceClusterAnalyzer.php#L83

**Comment by ChapterSevenSeeds** [comment]
@marcelklehr What if you are not actively adding new faces but instead are manually assigning some unassigned faces? Will clustering rejected faces still occur?
