### ISSUE TITLE
Recognize: 4.3.2 occ recognize:cluster-faces -b 100 is broken

### ISSUE THREAD

**Issue by umarkashmiri** [nextcloud/recognize#957]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.0.2

### Which Operating system do you have installed?

Truenas Scale

### Which database are you running Nextcloud on?

Postgres

### How much RAM does your server have?

32Gib

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

occ recognize:cluster-faces -b 100 is broken, background job stopped working after the version update.

ClusterDebug: Found 500 fresh detections. Adding 125 old detections and 2606 sampled detections from already existing clusters. Calculating clusters on 3231 detections.

An unhandled exception has been thrown:

Error: Call to undefined method Rubix\ML\Datasets\Labeled::features() in /var/www/html/custom_apps/recognize/lib/Clustering/DualTreeBall.php:107

Stack trace:

#0 /var/www/html/custom_apps/recognize/lib/Clustering/MrdBallTree.php(632): OCA\Recognize\Clustering\DualTreeBall::split(Object(Rubix\ML\Datasets\Labeled), Object(OCA\Recognize\Clustering\SquaredDistance))

#1 /var/www/html/custom_apps/recognize/lib/Clustering/MstSolver.php(22): OCA\Recognize\Clustering\MrdBallTree->grow(Object(Rubix\ML\Datasets\Labeled))

#2 /var/www/html/custom_apps/recognize/lib/Clustering/HDBSCAN.php(89): OCA\Recognize\Clustering\MstSolver->__construct(Object(Rubix\ML\Datasets\Labeled), 20, 4, Object(OCA\Recognize\Clustering\SquaredDistance), Array, true)

#3 /var/www/html/custom_apps/recognize/lib/Service/FaceClusterAnalyzer.php(91): OCA\Recognize\Clustering\HDBSCAN->__construct(Object(Rubix\ML\Datasets\Labeled), 5, 4)

#4 /var/www/html/custom_apps/recognize/lib/Command/ClusterFaces.php(67): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters('admin', 500)

#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(298): OCA\Recognize\Command\ClusterFaces->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#6 /var/www/html/3rdparty/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#7 /var/www/html/3rdparty/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Recognize\Command\ClusterFaces), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#8 /var/www/html/3rdparty/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#9 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#10 /var/www/html/console.php(100): OC\Console\Application->run()

#11 /var/www/html/occ(11): require_once('/var/www/html/c...')

### Expected Behavior

occ recognize:cluster-faces -b 100 should work

### To Reproduce

update the recognize app to 4.3.2 and run this command manually. 
occ recognize:cluster-faces -b 100

**Comment by marcelklehr** [comment]
see #677
