### ISSUE TITLE
error while updating

### ISSUE THREAD

**Issue by nonofr91** [nextcloud/recognize#958]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

Nextcloud Hub 5 (27.0.2)

### Which Operating system do you have installed?

VM Debian 11

### Which database are you running Nextcloud on?

MariaDB Linuxserver.io version:- 10.11.4-r0-ls110

### How much RAM does your server have?

16Go

### What processor Architecture does your CPU have?

amd64

### Describe the Bug

An error occurs during the update and I'm still stuck in update even after occ maintenance:mode --off .
I did an occ upgrade in a bash console of the container and here are the logs:

root@f9447b31e88b:/# occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <recognize> ...
Repair error: Downloading of node binary failed
Updated <recognize> to 4.3.2
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
root@f9447b31e88b:/# 

The Nextcloud resumes normal operation.
Twice I have the problem.

### Expected Behavior

This is not a blocking problem

### To Reproduce

Upgrade to 4.3.1 --> 4.3.2

**Comment by nonofr91** [comment]
In addition I have just seen that the loading of node.js is not correct.

**Comment by mipro98** [comment]
I have the same problem after upgrading NC from 27.0.1 to 27.0.2 and upgrading recognize alongside it. Also, when I try to reinstall the app via Admin center, it says `App "recognize" cannot be installed because appinfo file cannot be read`.

**Comment by marcelklehr** [comment]
Can you manually download `https://nodejs.org/dist/v14.18.2/node-v14.18.2-linux-x64.tar.gz` from your nextcloud machine? Something might be off with the node.js download server or with your internet connection.

**Comment by mipro98** [comment]
> Can you manually download `https://nodejs.org/dist/v14.18.2/node-v14.18.2-linux-x64.tar.gz` from your nextcloud machine? Something might be off with the node.js download server or with your internet connection.

Yes, this is perfectly possible with `curl` or `wget`. The problem was back then the `tar.gz` did not get extracted and after manually extracting, the node binary got a segfault when running (perhaps due to currupted download). After manually downloading the node binary v14 and placing it in the folder and running it, complaints about libtensorflow not being installed arose so this didn't work out either.

I will try again fixing this in the weekend when I will update my Nextcloud instance from 27.0.2 to 27.1.1.

**Comment by marcelklehr** [comment]
> complaints about libtensorflow not being installed arose

This can be fixed with a run of `occ maintenance:repair`

**Comment by Tangado-Haid** [comment]
i have the same issue
couldnt update and after removal i can't install
`Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_GsFvnO-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3}`

**Comment by felixzieger** [comment]
> After manually deleting the folder `/var/www/html/custom_apps/recognize` and running `app:install recognize` again, it installed (after a very long time)

This fixed it for me. I don't see any other errors.
