### ISSUE TITLE
Enabling recognize app gives PostgreSQL unique constraint violation errors

### ISSUE THREAD

**Issue by Ra72xx** [nextcloud/recognize#960]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Object recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.0.1

### Which Operating system do you have installed?

Ubuntu 23.04

### Which database are you running Nextcloud on?

PostgreSQL 15

### How much RAM does your server have?

16GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

As soon as I enable "recognize", my PostgreSQL log throws out errors like:
`postgresql[526618]: 2023-08-23 04:01:05.002 CEST [326287] ERROR:  duplicate key value violates unique constraint "oc_systemtag_object_mapping_pkey"
postgresql[526618]: 2023-08-23 04:01:05.002 CEST [326287] DETAIL:  Key (objecttype, objectid, systemtagid)=(files, 11813756, 4) already exists.`

- Nextcloud log does not give any errors.
- I also do not discern any problems in Nextcloud UI. However, with several thousand pictures to scan and the classification job taking days to finish, I would probably not really notice any malfunction.
- This is with a picture database on an external storage shared by several users. I tried both "local storage" and "SFTP" as external storage. 
- I also removed and added this external storage, removed and reinstalled "recognize", re-indexed Nextcloud files, restarted the recognize jobs. 
- The above error always re-occurs as soon as I enable "recognize" and disappears when the app is deactivated.
- It looks like https://github.com/nextcloud/recognize/issues/562, but I don't know how this error was resolved.

### Expected Behavior

No PostgreSQL errors.

### To Reproduce

Enable "recognize"

**Comment by marcelklehr** [comment]
I believe you can ignore the unique constraint violation if it doesn't surface in the nextcloud. Nextcloud sometimes produces these and the gracefully recovers, by using an UPDATE query instead of a INSERT, so everything should be ok.

**Comment by warlordattack** [comment]
Everything is not OK at all, because this error repeats every second and fills database logs, and slows all the nextcloud in the process. A have wallpapers collection, few thousand files, and this error is a problem for me. It makes nextcloud database log unusable.

[nextcloud-aio-database-2024-04-18T15-05-49.log](https://github.com/nextcloud/recognize/files/15026796/nextcloud-aio-database-2024-04-18T15-05-49.log)
