### ISSUE TITLE
Interesting bug

### ISSUE THREAD

**Issue by mattish91** [nextcloud/recognize#961]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Music recognition

### TensorFlow mode

Normal mode

### Downstream App

Audioplayer App

### Which Nextcloud version do you have installed?

26.0.4snap1

### Which Operating system do you have installed?

Ubuntu 22.04.3

### Which database are you running Nextcloud on?

MySQL 8

### Which Docker container are you using to run Nextcloud? (if applicable)

not applicable

### How much RAM does your server have?

8 GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Well, i think it all goes here: [my paste](https://pastes.io/vdagkefiyp)

### Expected Behavior

Atleast not maintenance mode atleast as this took me by surprise

### To Reproduce

1. Install the latest stable nextcloud snap, as of current 26.0.4snap1 
2. install recognize app 
3. get this surprise at the next server reboot.

### Debug log

[my redacted paste](https://pastes.io/vdagkefiyp)
[my initial github thread about this, and the solution](https://github.com/nextcloud-snap/nextcloud-snap/issues/2506)

**Comment by marcelklehr** [comment]
Looks like recognize doesn't have enough permissions to write and make files executable inside the recognize app directory.
