### ISSUE TITLE
Tensorflow WASM-Modus error in CPU recognition

### ISSUE THREAD

**Issue by bschuele** [nextcloud/recognize#964]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.0.2

### Which Operating system do you have installed?

unkown

### Which database are you running Nextcloud on?

unkown

### How much RAM does your server have?

unkown

### What processor Architecture does your CPU have?

unkown

### Describe the Bug

On my hosting instance of nextcloud, I'm not allowed to read "/proc/cpuinfo". This causes some errors in the log.

### Expected Behavior

There should be no error in the log ;-)

### To Reproduce

Just install the addon and download the model.

### Debug log

[PHP] Fehler: file_get_contents(): open_basedir restriction in effect. File(/proc/cpuinfo) is not within the allowed path(s): (/var/www/vhosts/**nextcloud**/:/tmp/:/var/lib/php/sessions) at /var/www/vhosts/hosting136496.a2e43.netcup.net/httpdocs/nxtc.schuele.ch/apps/recognize/lib/Controller/AdminController.php#150

GET /index.php/apps/recognize/admin/avx
from 147.161.246.108 by benjamin at 2023-08-28T07:47:51+00:00

---------------------------------------------------
[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150

---------------------------------------------------
GET /index.php/apps/recognize/admin/avx
from 147.161.246.108 by benjamin at 2023-08-28T07:47:51+00:00

[index] Fehler: Exception: strpos(): Argument #1 ($haystack) must be of type string, bool given in file '/var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/apps/recognize/lib/Controller/AdminController.php' line 154 at <<closure>>

0. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Recognize ... "], "avx")
1. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\Recognize\ ... r", "avx", ["OC\\AppFramewo ... "], ["recognize.admin.avx"])
2. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/base.php line 1071
   OC\Route\Router->match("/apps/recognize/admin/avx")
3. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: strpos(): Argument #1 ($haystack) must be of type string, bool given at <<closure>>

0. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/apps/recognize/lib/Controller/AdminController.php line 154
   strpos(false, "avx")
1. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Recognize\Controller\AdminController->avx()
2. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController(["OCA\\Recognize ... "], "avx")
3. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch(["OCA\\Recognize ... "], "avx")
4. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\Recognize\ ... r", "avx", ["OC\\AppFramewo ... "], ["recognize.admin.avx"])
5. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/lib/base.php line 1071
   OC\Route\Router->match("/apps/recognize/admin/avx")
6. /var/www/vhosts/[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /var/www/vhosts/**nextcloud**/apps/recognize/lib/Controller/AdminController.php#150/index.php line 36
   OC::handleRequest()

GET /index.php/apps/recognize/admin/avx
from 147.161.246.108 by benjamin at 2023-08-28T07:47:51+00:00

**Comment by Megachip** [comment]
```
[PHP] Fehler: file_get_contents(/proc/cpuinfo): Failed to open stream: Operation not permitted at /.../apps/recognize/lib/Controller/AdminController.php#150

GET /index.php/apps/recognize/admin/avx
from xxx by admin at 2024-01-24T16:27:41+00:00
```
Still have this issue in 5.0.3 spamming the whole log :(
