### ISSUE TITLE
Generate also previews

### ISSUE THREAD

**Issue by markuman** [nextcloud/recognize#97]
There is already a previewgenerator app. But it looks like it is orphaned/unmaintained: https://github.com/nextcloud/previewgenerator/issues/243

I wonder if it is possible if `recognize` is also (_optional_) able to create previews for every image, because it is already open/analyzing every single image. What do you think @marcelklehr?

**Comment by bonswouar** [comment]
> It's integrated and works

In Recognize? You might be mistaken, OP is looking for a way to pre-generate all previews from one command (they're currently generated on the fly I believe)

**Comment by debian-user-france1** [comment]
I mean the photos app

**Comment by marcelklehr** [comment]
Sorry for the delay. I think preview generation is out of scope for this app. I do hope to be able to help improve the overall photo experience in nextcloud a bit, but it's early days. I have a lot on my plate as it is.

**Comment by bdrewery** [comment]
https://github.com/nextcloud/previewgenerator is just an addon to _pre generate_ previews. The preview generator itself is builtin to Nextcloud.
`preview:pre-generate` is part of the addon.
