### ISSUE TITLE
Downloading new models times out

### ISSUE THREAD

**Issue by a-0-dev** [nextcloud/recognize#970]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

27.0.2

### Which Operating system do you have installed?

Debian 11

### Which database are you running Nextcloud on?

Postgres

### How much RAM does your server have?

16GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

After updating recognize, running `sudo -u www-data php /var/www/nextcloud/occ recognize:download-models` times out with the following error, instead of terminating after some seconds as it did for previous updates.

`cURL error 18: transfer closed with outstanding read data remaining (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://codeload.github.com/nextcloud/recognize/tar.gz/refs/tags/v4.3.2`

I can't say how long exactly it takes until timeout, but I'm pretty sure it's >30sec

### Expected Behavior

Download the models, terminate after few seconds. Actually, I would expect performing the app update already downloads the models, but since it seems like doing this manually is explicitly wanted, I would assume the command above works.

### To Reproduce

Update to the current version of recognize, run the command above

**Comment by marcelklehr** [comment]
There is no timeout set for that download. If it fails, something with your network or with the download server may be wrong.

**Comment by a-0-dev** [comment]
Well, just tried again and it worked. Maybe something happened with the GitHub server during the time I wanted to download the models, maybe something else...

I'll report back if it appears again, but for now I think it's ok to close the issue.

**Comment by martadinata666** [comment]
Sorry for bumping an old thread, as I keep getting time out, not the best internet in the world, can we somehow manually download `models.tar.gz` without `occ recognize:download-models`?

**Comment by lefebsy** [comment]
Hello,
Same problem.. and very good internet connection ; but this github alias link prefixed with "codeload" seems very slow very very often... even in browser he download take a while. The classic link in github ui relase download seems far more faster...

**Comment by marcelklehr** [comment]
You can also download the models folder from this repo and put it in the recognize app folder at your-nextcloud/apps/recognize

**Comment by Piefje01** [comment]
Can you also download other models ? Recognize plants or insects?

**Comment by marcelklehr** [comment]
> @Piefje01 Can you also download other models ? Recognize plants or insects?

Sadly it's not that easy :) You can add a feature request for models you'd like to see, though, maybe we'll add them at some point :)
