### ISSUE TITLE
ErrorException: Classifier process error

### ISSUE THREAD

**Issue by SaschaMuehl** [nextcloud/recognize#974]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

Nextcloud Hub 5 (27.0.2)

### Which Operating system do you have installed?

ubuntu - Linux 5.4.0-162-generic x86_64

### Which database are you running Nextcloud on?

mysql 10.6.15

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

47GIB

### What processor Architecture does your CPU have?

Intel(R) Atom(TM) CPU C3558 @ 2.20GHz (4 cores)

### Describe the Bug

[recognize] Information: ErrorException: Classifier process error at <<closure>>

0. /var/www/nextcloud/apps/recognize/lib/Classifiers/Images/ClusteringFaceClassifier.php line 84
   OCA\Recognize\Classifiers\Classifier->classifyFiles()
1. /var/www/nextcloud/apps/recognize/lib/Command/Classify.php line 134
   OCA\Recognize\Classifiers\Images\ClusteringFaceClassifier->classify()
2. /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php line 298
   OCA\Recognize\Command\Classify->execute()
3. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 1040
   Symfony\Component\Console\Command\Command->run()
4. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 301
   Symfony\Component\Console\Application->doRunCommand()
5. /var/www/nextcloud/3rdparty/symfony/console/Application.php line 171
   Symfony\Component\Console\Application->doRun()
6. /var/www/nextcloud/lib/private/Console/Application.php line 211
   Symfony\Component\Console\Application->run()
7. /var/www/nextcloud/console.php line 100
   OC\Console\Application->run()
8. /var/www/nextcloud/occ line 11
   require_once("/var/www/nextcloud/console.php")

at 2023-09-10T17:33:20+02:00

### Expected Behavior

willing to start a full (re)Clustering and (re)Classification process (Face+Landmark) 

### To Reproduce

1. stopped all background jobs
2. removed all tags
3. Starting Clustering and Classification process (Face+Landmark) via admin mode

**Comment by xloypaypa** [comment]
hi. I'm facing similar issue with you. may I check if you got the same logs as below?
![image](https://github.com/nextcloud/recognize/assets/10886456/a9d83383-5180-49db-a39b-f5ceb28b1a2b)

if so, it should be the same issue with: https://github.com/nextcloud/recognize/issues/966

**Comment by marcelklehr** [comment]
Indeed recognize should log more details about the problem
