### ISSUE TITLE
Error when running for the first time

### ISSUE THREAD

**Issue by moritz453** [nextcloud/recognize#975]
### Which version of recognize are you using?

latest

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

Latest

### Which Operating system do you have installed?

Docker

### Which database are you running Nextcloud on?

MariaDB

### How much RAM does your server have?

64GB

### What processor Architecture does your CPU have?

AMD - x86_64

### Describe the Bug

When trying to start up the facial recognition. (Or any other) I get an error, that FFmpeg is not installed and that some file does not exist.

I am sure, that it is a silly mistake, so forgive me if the answer is obvious. I have spent 3 hours trying to figure this out, and I am unfortunately just not able to.

Please let me know if you need any more information. 

### Expected Behavior

The scan should start.

### To Reproduce

I don't think this applies in this case, and I am sure I have some error in my setup-up that I can not figure out.
All I did, was installed the app, download the model and even tried to install FFmpeg via the command line, but with no success.

### Debug log

ntext | Exception: Failed to install ffmpeg: os.js:68 throw new ERR_SYSTEM_ERROR(ctx); ^ SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory) at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/env-paths/index.js:5:20) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) at Module.load (internal/modules/cjs/loader.js:950:32) at Function.Module._load (internal/modules/cjs/loader.js:790:12) at Module.require (internal/modules/cjs/loader.js:974:19) at require (internal/modules/cjs/helpers.js:93:18) at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/ffmpeg-static/install.js:7:18) at Module._compile (internal/modules/cjs/loader.js:1085:14) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) { code: 'ERR_SYSTEM_ERROR', info: { errno: -2, code: 'ENOENT', message: 'no such file or directory', syscall: 'uv_os_homedir' }, errno: [Getter/Setter], syscall: [Getter/Setter] }
-- | --

**Comment by marcelklehr** [comment]
> Which Operating system do you have installed?
> 
> Docker

Docker is not an Operating system. Which docker container are you using?

**Comment by eibex** [comment]
> > Which Operating system do you have installed?
> > Docker
> 
> Docker is not an Operating system. Which docker container are you using?

I can replicated this issue on Docker too. Currently running this [container](https://hub.docker.com/_/nextcloud) on latest tag (28.0.2). The ffmpeg errors are shown upon installation of Recognize.

I already have ffmpeg installed within the docker if that matters (for preview generation).
