### ISSUE TITLE
required nodejs version is EOL

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/recognize#985]
### Describe the feature you'd like to request

Right now the admin ui states: ``Currently supported is Node v14.17 and newer v14 releases.``
Nodejs 14 is EOL, see https://endoflife.date/nodejs .

### Describe the solution you'd like

It should be upgraded to a newer version like 18.

### Describe alternatives you've considered

🤷🏼

**Comment by SuperSandro2000** [comment]
I think this is still a problem with 6.0.0. The PHP code still wants to install nodejs 14 https://github.com/nextcloud/recognize/blob/main/lib/Migration/InstallDeps.php#L42-L44 despite the nodejs part already using nodejs 16 https://github.com/nextcloud/recognize/blob/main/package.json#L66.

My distribution removed nodejs 14 and 16 for the next stable release. I have no problem with reverting both and getting them back but I'd imagine other distros will soon have a similar problems were reverting is not always as easy and might demand adding 3rd party sources like nodesource.com which already removed nodejs 14.

**Comment by marcelklehr** [comment]
Yes, it still needs to be fixed.

**Comment by espressodriven** [comment]
@marcelklehr I just wanted to ask about this, and fix it myself, but it seems to be fixed in commit a0ae4ac already? Thx you for your work!

**Comment by SuperSandro2000** [comment]
That's in no release yet according to git.

**Comment by espressodriven** [comment]
Yes I know that, but what I meant is that I can't help by creating a fix and a pull request for that issue myself, since it is already fixed upstream.
@marcelklehr Could you share a preliminary release date for a version which includes this fix?

**Comment by marcelklehr** [comment]
This will be fixed with v7
