### ISSUE TITLE
5.0.0 fails to upgrade or install.

### ISSUE THREAD

**Issue by Aquilum** [nextcloud/recognize#990]
### Which version of recognize are you using?

5.0.0

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Downstream App

other, please specify below

### Which Nextcloud version do you have installed?

27.1.2

### Which Operating system do you have installed?

Ubuntu 20.04.6

### Which database are you running Nextcloud on?

mySQL 8.0.4

### How much RAM does your server have?

128GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Unable to upgrade or install afresh Recognize 5.0. It appears the installer is trying to modify the system Python install.

`An error occurred during the request. Unable to proceed.
Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_s0gWZL-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3}`

### Expected Behavior

Install and upgrade paths operational.

### To Reproduce

1. Attempt to upgrade or install Recognize 5.0

**Comment by ThesiiNCey** [comment]
i got the same error

'Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_sviIrQ-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3}'

**Comment by ralfbgithub** [comment]
Same on Raspberry Pi 4 with Alpine-Linux Container
Nextcloud 27.1.2
Recognize 4.3.2

Exception: Could not extract app recognize: Out-of-path file extraction {/data/nextcloudtemp/oc_tmp_JBOmiD-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3}

**Comment by RedKage** [comment]
Same, with trying to upgrade, then I disabled and deleted recognize, and upon installation it is doing the same thing

```
{
    "reqId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "level": 3,
    "time": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
    "remoteAddr": "XXXXXXXXXXXXXXXXXXX",
    "user": "XXXXXXXXXXXXXXXX",
    "app": "settings",
    "method": "POST",
    "url": "/settings/apps/enable",
    "message": "could not enable apps",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "version": "27.0.2.1",
    "exception": {
        "Exception": "Exception",
        "Message": "Could not extract app recognize: Out-of-path file extraction {/$$$$$$$$$$$$$$$$/tmp/oc_tmp_LQ36Bv-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3}",
        "Code": 0,
        "Trace": [
            {
                "file": "/##################/nextcloud/apps/settings/lib/Controller/AppSettingsController.php",
                "line": 448,
                "function": "downloadApp",
                "class": "OC\\Installer",
                "type": "->",
                "args": [
                    "recognize"
                ]
            },
            {
                "file": "/##################/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 230,
                "function": "enableApps",
                "class": "OCA\\Settings\\Controller\\AppSettingsController",
                "type": "->",
                "args": [
                    [
                        "recognize"
                    ],
                    []
                ]
            },
            {
                "file": "/##################/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 137,
                "function": "executeController",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    [
                        "OCA\\Settings\\Controller\\AppSettingsController"
                    ],
                    "enableApps"
                ]
            },
            {
                "file": "/##################/nextcloud/lib/private/AppFramework/App.php",
                "line": 183,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    [
                        "OCA\\Settings\\Controller\\AppSettingsController"
                    ],
                    "enableApps"
                ]
            },
            {
                "file": "/##################/nextcloud/lib/private/Route/Router.php",
                "line": 315,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "OCA\\Settings\\Controller\\AppSettingsController",
                    "enableApps",
                    [
                        "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    ],
                    [
                        "settings.AppSettings.enableApps"
                    ]
                ]
            },
            {
                "file": "/##################/nextcloud/lib/base.php",
                "line": 1071,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/settings/apps/enable"
                ]
            },
            {
                "file": "/##################/nextcloud/index.php",
                "line": 36,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
        ],
        "File": "/##################/nextcloud/lib/private/Installer.php",
        "Line": 318,
        "message": "could not enable apps",
        "exception": {},
        "CustomMessage": "could not enable apps"
    }
}
```

The path `/$$$$$$$$$$$$$$$$` (where it is looking for `tmp/oc_tmp_LQ36Bv-folder/recognize`) is inside my local user space. It's the PREFIX path.
The path `/##################` is the nextcloud install containing the phps.

**Comment by ThesiiNCey** [comment]
> Same on Raspberry Pi 4 with Alpine-Linux Container Nextcloud 27.1.2 Recognize 4.3.2
> 
> Exception: Could not extract app recognize: Out-of-path file extraction {/data/nextcloudtemp/oc_tmp_JBOmiD-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3}

Recognize 4.3.2 was the latest working version on my case only 5.0.0 make problems

**Comment by oswaldo-be** [comment]
same here on ubuntu LTS
Linux 5.15.60-1-pve x86_64
PHP Version: 8.1.2
nextcloud 27.12
[no app in context] Fehler: Exception: Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_1ju6LC-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3} at <<closure>>

**Comment by maxnatt** [comment]
`nextcloud:27.1.1-apache` Docker [image](https://hub.docker.com/_/nextcloud) is affected as well.

**Comment by ralfi** [comment]
same here with Docker 27.1.1

**Comment by killerb77** [comment]
same here.

**Comment by Termikkazan** [comment]
I have the same as everyone else.   Debian (proxmox container)

**Comment by DenuxPlays** [comment]
Nextcloud AIO is also affected (at least v7.4.0 Beta) 
Link to my comment [here](https://github.com/nextcloud/recognize/discussions/989#discussioncomment-7222964)

**Comment by Haidafraid** [comment]
Same here. Fresh install.
Ubuntu 20.04 Nextcloud 27.1.2 php8.2.
Trying to install via Web Admin and cli

Error given:
`Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_ahUkwR-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3} `

**Comment by bendschs** [comment]
same here

**Comment by MrLoverLoverMMMM** [comment]
fresh install also does not work:

App "recognize" cannot be installed because appinfo file cannot be read.

**Comment by MikeDuncan1** [comment]
#metoo

**Comment by HenkVirtual** [comment]
I am getting this;
`sudo -u nginx php occ app:update recognize
recognize new version available: 5.0.0
recognize couldn't be updated
`

**Comment by Jaime-GP** [comment]
Same error with cocker nextcloud:stable

Could not extract app recognize: Out-of-path file extraction {/tmp/oc_tmp_ahUkwR-folder/recognize/node_modules/@tensorflow/tfjs-node/build-tmp-napi-v8/node_gyp_bins/python3 --> /bin/python3}

**Comment by Radiicall** [comment]
Manual install seems to work in-case anyone here wants to get it working asap

**Comment by marcelklehr** [comment]
Hello everyone! Sorry for the problems and thanks for the feedback! I'll churn out a fix asap.

**Comment by marcelklehr** [comment]
v5.0.1 is out now, but it might take a while (up to an hour) before your nextcloud instance picks it up.

**Comment by maxnatt** [comment]
Thank you!

**Comment by delabat** [comment]
v5.0.1 solved the issue... Thank you for the really fast fix guys!
