### ISSUE TITLE
Classify hung/blocked probably because of empty file.

### ISSUE THREAD

**Issue by tdltdl** [nextcloud/recognize#992]
### Which version of recognize are you using?

5.0.1

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

Normal mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.1.2

### Which Operating system do you have installed?

Debian - Docker official

### Which database are you running Nextcloud on?

MariaDB

### How much RAM does your server have?

12G

### What processor Architecture does your CPU have?

X86_64

### Describe the Bug

Recognize was hanging (always at the same point when running occ recognize:classify:
generating preview of 1325 with dimension 1024
Copying 1325 preview to tempfolder

Note this error message did not told me which file was causing the issue - which would be a nice addition)

I looked at my source file system (it is an external storage SMB). I did a find for files of file 0 and deleted them.

After I did that deletion, and re-run the classify, it reported
generating preview of 1325 with dimension 1024
Copying 1325 preview to tempfolder
Could not find file

but continued happily after.

### Expected Behavior

Recognize should ignore corrupted/empty files

### To Reproduce

Upload a 0 byte jpg image and try to classify

**Comment by geez0x1** [comment]
Let me help this thread along by posting a bit of output from `cat nextcloud.log | grep -i recognize`:
```
{"reqId":"somestring","level":3,"time":"2023-11-01T16:37:25+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"filesize(): stat failed for /nextcloud_data/user/files/somedirectory/somefile.png at /var/www/html/apps/recognize/lib/Classifiers/Classifier.php#92","userAgent":"--","version":"27.1.3.2","data":{"app":"PHP"}}
```
I'm not sure it actually causes the classification itself to be stopped - I get those errors repeatedly if there are multiple zero-byte files during a run (suggesting files are otherwise processed fine).
