### ISSUE TITLE
Extremely buggy app

### ISSUE THREAD

**Issue by dillfrescott** [nextcloud/recognize#993]
### Which version of recognize are you using?

5.0.1

### Enabled Modes

Object recognition, Face recognition, Music recognition

### TensorFlow mode

WASM mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.1.0

### Which Operating system do you have installed?

Arch Linux

### Which database are you running Nextcloud on?

Arch Linux

### Which Docker container are you using to run Nextcloud? (if applicable)

AIO latest container

### How much RAM does your server have?

8 GB with like 4 Gb of swap

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

930 images are queued and never ever actually get recognized. The models are downloaded, its running in WASM mode with default recommended amounts and the modules are flipped on but it does nothing.

### Expected Behavior

Identify and classify music, and images (including faces)

### To Reproduce

Install Nextcloud AIO and recognize plugin

**Comment by dillfrescott** [comment]
Please help

**Comment by dillfrescott** [comment]
I noticed that enabling audio recognition causes the libtensorflow check to spin forever. as soon as i disable it it loads

**Comment by dillfrescott** [comment]
I managed to jerryrig it by running a classify cronjob regularly once a day. This solution I guess works for me...

**Comment by Dav-Git** [comment]
Had the same experience and for now have disabled audio classification. I do not think that this issue is solved however (since it requires a workaround) so this issue should probably stay open.

**Comment by dillfrescott** [comment]
Gotcha

**Comment by marcelklehr** [comment]
> Extremely buggy app

Cannot reproduce.
