### ISSUE TITLE
Search doesn't show tags added from the recognize app

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/recognize#994]
### Which version of recognize are you using?

4.3.2

### Enabled Modes

Object recognition

### TensorFlow mode

Normal mode

### Downstream App

Files App

### Which Nextcloud version do you have installed?

26.0.7

### Which Operating system do you have installed?

Ubuntu 22.04

### Which database are you running Nextcloud on?

PostgreSQL 14.9

### How much RAM does your server have?

16 GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

If you use the unified search to find files with a specific tag, those files don't show up in the search results if the tag was created from the recognize app. 
They only show up if you type only the first 2 characters of the tag. 
If you type 3 or more characters of the tag, they don't show up. 

### Expected Behavior

Those files should be listed in the search results like any other manually tagged files. 

### To Reproduce

1. Give a random file a tag that was created by the recognize app. e.g. "backpack" (Select a file, click on details , 3-dot-menu, tags)
2. reload the page and see, that the tag was applied to that file (shows up in activity)
3. Use the unified search:
a. type in "back" --> no results
b. type in "backpack" --> no results
c. type in "ba" --> get all results (including files with the tag "backpak")

**Comment by marcelklehr** [comment]
Hi @hartsberger 

Is this specific to tags created by recognize? Could you try creating a tag yourself and doing the same steps?

**Comment by marcelklehr** [comment]
Also, I notice the tag you mentioned `"backpack"` is spelled lowercase. In recent versions recognize tags are always uppercase :thinking: Maybe this is a legacy tag from an old version of recognize? Have you tried `"Backpack"`?

**Comment by hartsberger** [comment]
Hi @marcelklehr 
you were right. My fault was to type the tag in lowercase. As soon as I typed in "Backpack" the search results are as expected. 

I would then ask if it is possible to change the current tag search from case sensitive to case insesnitive. 

Every other search type (at least I tested files, apps, talk messages, deck cards) is not case sensitive. And no user would expect the requirement to type the first character in upper case. 
This would greatly enhance the UX. 

Thank you.

**Comment by marcelklehr** [comment]
> I would then ask if it is possible to change the current tag search from case sensitive to case insesnitive.

Agreed. This is not an issue for this repo, though, but rather for nextcloud/server -- if you are a Nextcloud customer, you may file this as a support ticket to get it fixed faster.
